/**
 * This file was generated by the Objective Systems ASN1C Compiler
 * (http://www.obj-sys.com).  Version: 7.8.2.5, Date: 12-Sep-2025.
 *
 * Command:  asn1c asn1files/E2SM-KPM-v05.00.asn asn1files/asn_flexric/e2sm_rc_v1_03_modified.asn asn1files/asn_flexric/e42ap_v2_03.asn -genTest -per -json -w32 -server -depends -events -genPrtToStr -list -reader -trace -c++ -print -prtfmt details -srcdir src -make Makefile -w32 -table-unions -stream -pdu all
 */
#include <new>
#include "E2AP-CommonDataTypes.h"
#include "rtxsrc/rtxDiag.h"

/* ASN1T_ProcedureCode */

ASN1T_ProcedureCode* new_ASN1T_ProcedureCode (ASN1CType& ccobj)
{
   void* pdata = ccobj.memAlloc (sizeof(ASN1T_ProcedureCode));
   if (0 == pdata) return 0;
   else return new (pdata) ASN1T_ProcedureCode;
}

ASN1C_ProcedureCode::ASN1C_ProcedureCode (ASN1T_ProcedureCode& data) : 
   ASN1CType(), msgData(data)
{
   setRunTimeKey (_rtkey, sizeof(_rtkey));
}

ASN1C_ProcedureCode::ASN1C_ProcedureCode (OSRTMessageBufferIF& msgBuf
   , ASN1T_ProcedureCode& data) : ASN1CType(msgBuf), msgData(data)
{
   setRunTimeKey (_rtkey, sizeof(_rtkey));
}
ASN1C_ProcedureCode::ASN1C_ProcedureCode (OSRTContext &context
   , ASN1T_ProcedureCode& data) : ASN1CType(context), msgData(data)
{
   setRunTimeKey (_rtkey, sizeof(_rtkey));
}


int ASN1C_ProcedureCode::EncodeTo (OSRTMessageBufferIF& msgBuf)
{
   int stat = setMsgBuf (msgBuf, TRUE);
   if (stat != 0) return (stat);

   if (msgBuf.isA (OSRTMessageBufferIF::PEREncode)) {
      stat= asn1PE_ProcedureCode (msgBuf.getCtxtPtr(), msgData);
      ((ASN1PEREncodeBuffer&)msgBuf).byteAlign();
      return stat;
   }
   else if (msgBuf.isA (OSRTMessageBufferIF::JSONEncode)) {
      return asn1JsonEnc_ProcedureCode (msgBuf.getCtxtPtr(), &msgData);
   }
   return RTERR_NOTSUPP;
}

int ASN1C_ProcedureCode::DecodeFrom (OSRTMessageBufferIF& msgBuf, OSBOOL free)
{
   int stat = setMsgBuf (msgBuf, TRUE);
   if (stat != 0) return (stat);

   if (msgBuf.isA (OSRTMessageBufferIF::PERDecode)) {
      stat = asn1PD_ProcedureCode (msgBuf.getCtxtPtr(), &msgData);
      ((ASN1PERDecodeBuffer&)msgBuf).byteAlign();
      return stat;
   }
   else if (msgBuf.isA (OSRTMessageBufferIF::JSONDecode)) {
      return asn1JsonDec_ProcedureCode (msgBuf.getCtxtPtr(), &msgData);
   }
   return RTERR_NOTSUPP;
}

/* ASN1T_Criticality */

const OSEnumItem ASN1T_Criticality_ENUMTAB[] = {
   { OSUTF8("ignore"), 1, 6, 2 },
   { OSUTF8("notify"), 2, 6, 0 },
   { OSUTF8("reject"), 0, 6, 1 }
} ;

const OSUTF8CHAR* ASN1T_Criticality_ToString (OSINT32 value)
{
   OSINT32 idx = value;

   if (idx >= 0 && idx < ASN1T_Criticality_ENUMTABSIZE) {
      return ASN1T_Criticality_ENUMTAB
         [ASN1T_Criticality_ENUMTAB[idx].transidx].name;
   }
   else
      return OSUTF8("_UNKNOWN_");
}

int ASN1T_Criticality_ToEnum (OSCTXT* pctxt,
   const OSUTF8CHAR* value, ASN1T_Criticality* pvalue)
{
   OSSIZE valueLen = rtxUTF8LenBytes (value);
   return ASN1T_Criticality_ToEnum2 (pctxt, value, valueLen, pvalue);
}

int ASN1T_Criticality_ToEnum2 (OSCTXT* pctxt,
   const OSUTF8CHAR* value, OSSIZE valueLen, ASN1T_Criticality* pvalue)
{
   OSINT32 idx = rtxLookupEnum (value, valueLen, ASN1T_Criticality_ENUMTAB, 
      ASN1T_Criticality_ENUMTABSIZE);

   if (idx >= 0) {
      *pvalue = (ASN1T_Criticality)ASN1T_Criticality_ENUMTAB[idx].value;
      return 0;
   }
   else {
      rtxErrAddStrParm (pctxt, (const char*)value);
      return LOG_RTERR (pctxt, RTERR_INVENUM);
   }
}

ASN1T_Criticality* new_ASN1T_Criticality (ASN1CType& ccobj)
{
   void* pdata = ccobj.memAlloc (sizeof(ASN1T_Criticality));
   if (0 == pdata) return 0;
   else return new (pdata) ASN1T_Criticality;
}

ASN1C_Criticality::ASN1C_Criticality (ASN1T_Criticality& data) : 
   ASN1CType(), msgData(data)
{
   setRunTimeKey (_rtkey, sizeof(_rtkey));
}

ASN1C_Criticality::ASN1C_Criticality (OSRTMessageBufferIF& msgBuf
   , ASN1T_Criticality& data) : ASN1CType(msgBuf), msgData(data)
{
   setRunTimeKey (_rtkey, sizeof(_rtkey));
}
ASN1C_Criticality::ASN1C_Criticality (OSRTContext &context
   , ASN1T_Criticality& data) : ASN1CType(context), msgData(data)
{
   setRunTimeKey (_rtkey, sizeof(_rtkey));
}


int ASN1C_Criticality::EncodeTo (OSRTMessageBufferIF& msgBuf)
{
   int stat = setMsgBuf (msgBuf, TRUE);
   if (stat != 0) return (stat);

   if (msgBuf.isA (OSRTMessageBufferIF::PEREncode)) {
      stat= asn1PE_Criticality (msgBuf.getCtxtPtr(), msgData);
      ((ASN1PEREncodeBuffer&)msgBuf).byteAlign();
      return stat;
   }
   else if (msgBuf.isA (OSRTMessageBufferIF::JSONEncode)) {
      return asn1JsonEnc_Criticality (msgBuf.getCtxtPtr(), &msgData);
   }
   return RTERR_NOTSUPP;
}

int ASN1C_Criticality::DecodeFrom (OSRTMessageBufferIF& msgBuf, OSBOOL free)
{
   int stat = setMsgBuf (msgBuf, TRUE);
   if (stat != 0) return (stat);

   if (msgBuf.isA (OSRTMessageBufferIF::PERDecode)) {
      stat = asn1PD_Criticality (msgBuf.getCtxtPtr(), &msgData);
      ((ASN1PERDecodeBuffer&)msgBuf).byteAlign();
      return stat;
   }
   else if (msgBuf.isA (OSRTMessageBufferIF::JSONDecode)) {
      return asn1JsonDec_Criticality (msgBuf.getCtxtPtr(), &msgData);
   }
   return RTERR_NOTSUPP;
}

/* ASN1T_ProtocolIE_ID */

ASN1T_ProtocolIE_ID* new_ASN1T_ProtocolIE_ID (ASN1CType& ccobj)
{
   void* pdata = ccobj.memAlloc (sizeof(ASN1T_ProtocolIE_ID));
   if (0 == pdata) return 0;
   else return new (pdata) ASN1T_ProtocolIE_ID;
}

ASN1C_ProtocolIE_ID::ASN1C_ProtocolIE_ID (ASN1T_ProtocolIE_ID& data) : 
   ASN1CType(), msgData(data)
{
   setRunTimeKey (_rtkey, sizeof(_rtkey));
}

ASN1C_ProtocolIE_ID::ASN1C_ProtocolIE_ID (OSRTMessageBufferIF& msgBuf
   , ASN1T_ProtocolIE_ID& data) : ASN1CType(msgBuf), msgData(data)
{
   setRunTimeKey (_rtkey, sizeof(_rtkey));
}
ASN1C_ProtocolIE_ID::ASN1C_ProtocolIE_ID (OSRTContext &context
   , ASN1T_ProtocolIE_ID& data) : ASN1CType(context), msgData(data)
{
   setRunTimeKey (_rtkey, sizeof(_rtkey));
}


int ASN1C_ProtocolIE_ID::EncodeTo (OSRTMessageBufferIF& msgBuf)
{
   int stat = setMsgBuf (msgBuf, TRUE);
   if (stat != 0) return (stat);

   if (msgBuf.isA (OSRTMessageBufferIF::PEREncode)) {
      stat= asn1PE_ProtocolIE_ID (msgBuf.getCtxtPtr(), msgData);
      ((ASN1PEREncodeBuffer&)msgBuf).byteAlign();
      return stat;
   }
   else if (msgBuf.isA (OSRTMessageBufferIF::JSONEncode)) {
      return asn1JsonEnc_ProtocolIE_ID (msgBuf.getCtxtPtr(), &msgData);
   }
   return RTERR_NOTSUPP;
}

int ASN1C_ProtocolIE_ID::DecodeFrom (OSRTMessageBufferIF& msgBuf, OSBOOL free)
{
   int stat = setMsgBuf (msgBuf, TRUE);
   if (stat != 0) return (stat);

   if (msgBuf.isA (OSRTMessageBufferIF::PERDecode)) {
      stat = asn1PD_ProtocolIE_ID (msgBuf.getCtxtPtr(), &msgData);
      ((ASN1PERDecodeBuffer&)msgBuf).byteAlign();
      return stat;
   }
   else if (msgBuf.isA (OSRTMessageBufferIF::JSONDecode)) {
      return asn1JsonDec_ProtocolIE_ID (msgBuf.getCtxtPtr(), &msgData);
   }
   return RTERR_NOTSUPP;
}

/* ASN1T_TriggeringMessage */

const OSEnumItem ASN1T_TriggeringMessage_ENUMTAB[] = {
   { OSUTF8("initiating-message"), 0, 18, 0 },
   { OSUTF8("successful-outcome"), 1, 18, 1 },
   { OSUTF8("unsuccessfull-outcome"), 2, 21, 2 }
} ;

const OSUTF8CHAR* ASN1T_TriggeringMessage_ToString (OSINT32 value)
{
   OSINT32 idx = value;

   if (idx >= 0 && idx < ASN1T_TriggeringMessage_ENUMTABSIZE) {
      return ASN1T_TriggeringMessage_ENUMTAB
         [ASN1T_TriggeringMessage_ENUMTAB[idx].transidx].name;
   }
   else
      return OSUTF8("_UNKNOWN_");
}

int ASN1T_TriggeringMessage_ToEnum (OSCTXT* pctxt,
   const OSUTF8CHAR* value, ASN1T_TriggeringMessage* pvalue)
{
   OSSIZE valueLen = rtxUTF8LenBytes (value);
   return ASN1T_TriggeringMessage_ToEnum2 (pctxt, value, valueLen, pvalue);
}

int ASN1T_TriggeringMessage_ToEnum2 (OSCTXT* pctxt,
   const OSUTF8CHAR* value, OSSIZE valueLen, ASN1T_TriggeringMessage* pvalue)
{
   OSINT32 idx = rtxLookupEnum (value, valueLen, 
      ASN1T_TriggeringMessage_ENUMTAB, ASN1T_TriggeringMessage_ENUMTABSIZE);

   if (idx >= 0) {
      *pvalue = (ASN1T_TriggeringMessage)
         ASN1T_TriggeringMessage_ENUMTAB[idx].value;
      return 0;
   }
   else {
      rtxErrAddStrParm (pctxt, (const char*)value);
      return LOG_RTERR (pctxt, RTERR_INVENUM);
   }
}

ASN1T_TriggeringMessage* new_ASN1T_TriggeringMessage (ASN1CType& ccobj)
{
   void* pdata = ccobj.memAlloc (sizeof(ASN1T_TriggeringMessage));
   if (0 == pdata) return 0;
   else return new (pdata) ASN1T_TriggeringMessage;
}

ASN1C_TriggeringMessage::ASN1C_TriggeringMessage
    (ASN1T_TriggeringMessage& data) : ASN1CType(), msgData(data)
{
   setRunTimeKey (_rtkey, sizeof(_rtkey));
}

ASN1C_TriggeringMessage::ASN1C_TriggeringMessage (OSRTMessageBufferIF& msgBuf
   , ASN1T_TriggeringMessage& data) : ASN1CType(msgBuf), msgData(data)
{
   setRunTimeKey (_rtkey, sizeof(_rtkey));
}
ASN1C_TriggeringMessage::ASN1C_TriggeringMessage (OSRTContext &context
   , ASN1T_TriggeringMessage& data) : ASN1CType(context), msgData(data)
{
   setRunTimeKey (_rtkey, sizeof(_rtkey));
}


int ASN1C_TriggeringMessage::EncodeTo (OSRTMessageBufferIF& msgBuf)
{
   int stat = setMsgBuf (msgBuf, TRUE);
   if (stat != 0) return (stat);

   if (msgBuf.isA (OSRTMessageBufferIF::PEREncode)) {
      stat= asn1PE_TriggeringMessage (msgBuf.getCtxtPtr(), msgData);
      ((ASN1PEREncodeBuffer&)msgBuf).byteAlign();
      return stat;
   }
   else if (msgBuf.isA (OSRTMessageBufferIF::JSONEncode)) {
      return asn1JsonEnc_TriggeringMessage (msgBuf.getCtxtPtr(), &msgData);
   }
   return RTERR_NOTSUPP;
}

int ASN1C_TriggeringMessage::DecodeFrom (OSRTMessageBufferIF& msgBuf, OSBOOL free)
{
   int stat = setMsgBuf (msgBuf, TRUE);
   if (stat != 0) return (stat);

   if (msgBuf.isA (OSRTMessageBufferIF::PERDecode)) {
      stat = asn1PD_TriggeringMessage (msgBuf.getCtxtPtr(), &msgData);
      ((ASN1PERDecodeBuffer&)msgBuf).byteAlign();
      return stat;
   }
   else if (msgBuf.isA (OSRTMessageBufferIF::JSONDecode)) {
      return asn1JsonDec_TriggeringMessage (msgBuf.getCtxtPtr(), &msgData);
   }
   return RTERR_NOTSUPP;
}

/* ASN1T_Presence */

const OSEnumItem ASN1T_Presence_ENUMTAB[] = {
   { OSUTF8("conditional"), 1, 11, 2 },
   { OSUTF8("mandatory"), 2, 9, 0 },
   { OSUTF8("optional"), 0, 8, 1 }
} ;

const OSUTF8CHAR* ASN1T_Presence_ToString (OSINT32 value)
{
   OSINT32 idx = value;

   if (idx >= 0 && idx < ASN1T_Presence_ENUMTABSIZE) {
      return ASN1T_Presence_ENUMTAB
         [ASN1T_Presence_ENUMTAB[idx].transidx].name;
   }
   else
      return OSUTF8("_UNKNOWN_");
}

int ASN1T_Presence_ToEnum (OSCTXT* pctxt,
   const OSUTF8CHAR* value, ASN1T_Presence* pvalue)
{
   OSSIZE valueLen = rtxUTF8LenBytes (value);
   return ASN1T_Presence_ToEnum2 (pctxt, value, valueLen, pvalue);
}

int ASN1T_Presence_ToEnum2 (OSCTXT* pctxt,
   const OSUTF8CHAR* value, OSSIZE valueLen, ASN1T_Presence* pvalue)
{
   OSINT32 idx = rtxLookupEnum (value, valueLen, ASN1T_Presence_ENUMTAB, 
      ASN1T_Presence_ENUMTABSIZE);

   if (idx >= 0) {
      *pvalue = (ASN1T_Presence)ASN1T_Presence_ENUMTAB[idx].value;
      return 0;
   }
   else {
      rtxErrAddStrParm (pctxt, (const char*)value);
      return LOG_RTERR (pctxt, RTERR_INVENUM);
   }
}

ASN1T_Presence* new_ASN1T_Presence (ASN1CType& ccobj)
{
   void* pdata = ccobj.memAlloc (sizeof(ASN1T_Presence));
   if (0 == pdata) return 0;
   else return new (pdata) ASN1T_Presence;
}

ASN1C_Presence::ASN1C_Presence (ASN1T_Presence& data) : 
   ASN1CType(), msgData(data)
{
   setRunTimeKey (_rtkey, sizeof(_rtkey));
}

ASN1C_Presence::ASN1C_Presence (OSRTMessageBufferIF& msgBuf
   , ASN1T_Presence& data) : ASN1CType(msgBuf), msgData(data)
{
   setRunTimeKey (_rtkey, sizeof(_rtkey));
}
ASN1C_Presence::ASN1C_Presence (OSRTContext &context, ASN1T_Presence& data) : 
   ASN1CType(context), msgData(data)
{
   setRunTimeKey (_rtkey, sizeof(_rtkey));
}


int ASN1C_Presence::EncodeTo (OSRTMessageBufferIF& msgBuf)
{
   int stat = setMsgBuf (msgBuf, TRUE);
   if (stat != 0) return (stat);

   if (msgBuf.isA (OSRTMessageBufferIF::PEREncode)) {
      stat= asn1PE_Presence (msgBuf.getCtxtPtr(), msgData);
      ((ASN1PEREncodeBuffer&)msgBuf).byteAlign();
      return stat;
   }
   else if (msgBuf.isA (OSRTMessageBufferIF::JSONEncode)) {
      return asn1JsonEnc_Presence (msgBuf.getCtxtPtr(), &msgData);
   }
   return RTERR_NOTSUPP;
}

int ASN1C_Presence::DecodeFrom (OSRTMessageBufferIF& msgBuf, OSBOOL free)
{
   int stat = setMsgBuf (msgBuf, TRUE);
   if (stat != 0) return (stat);

   if (msgBuf.isA (OSRTMessageBufferIF::PERDecode)) {
      stat = asn1PD_Presence (msgBuf.getCtxtPtr(), &msgData);
      ((ASN1PERDecodeBuffer&)msgBuf).byteAlign();
      return stat;
   }
   else if (msgBuf.isA (OSRTMessageBufferIF::JSONDecode)) {
      return asn1JsonDec_Presence (msgBuf.getCtxtPtr(), &msgData);
   }
   return RTERR_NOTSUPP;
}

