/**
 * This file was generated by the Objective Systems ASN1C Compiler
 * (http://www.obj-sys.com).  Version: 7.8.2.5, Date: 12-Sep-2025.
 *
 * Command:  asn1c asn1files/E2SM-KPM-v05.00.asn asn1files/asn_flexric/e2sm_rc_v1_03_modified.asn asn1files/asn_flexric/e42ap_v2_03.asn -genTest -per -json -w32 -server -depends -events -genPrtToStr -list -reader -trace -c++ -print -prtfmt details -srcdir src -make Makefile -w32 -table-unions -stream -pdu all
 */
#include "E2AP-IEs.h"
#include "E2AP-CommonDataTypes.h"
#include "E2AP-Constants.h"
#include "rtxsrc/rtxCharStr.h"
#include "rtxsrc/rtxDiag.h"

/*
 * Randomly generated test file: seed = 1757655164
 */
ASN1T_RICrequestID* ASN1C_RICrequestID::genTestInstance(OSCTXT *pctxt, OSBOOL free)

{
   if (0 == pctxt) pctxt = getCtxtPtr();
   ASN1T_RICrequestID* pvalue = (ASN1T_RICrequestID*)&msgData;
   asn1Init_RICrequestID (pvalue, free, pctxt);

   pvalue->ricRequestorID = 26994;

   pvalue->ricInstanceID = 49863;
   return (pvalue);
}

ASN1T_RANfunctionID* ASN1C_RANfunctionID::genTestInstance(OSCTXT *pctxt, OSBOOL free)

{
   if (0 == pctxt) pctxt = getCtxtPtr();
   ASN1T_RANfunctionID* pvalue = (ASN1T_RANfunctionID*)&msgData;

   *pvalue = 1934;
   return (pvalue);
}

ASN1T_RICeventTriggerDefinition* ASN1C_RICeventTriggerDefinition::genTestInstance(OSCTXT *pctxt, OSBOOL free)

{
   if (0 == pctxt) pctxt = getCtxtPtr();
   ASN1T_RICeventTriggerDefinition* pvalue = (ASN1T_RICeventTriggerDefinition*)&msgData;
   new (pvalue) ASN1TDynOctStr();

   pvalue->numocts = 5;
   pvalue->data = (OSOCTET*) rtxMemAlloc (pctxt, 5);
   {
      static const OSOCTET testdata[] = {
      0xe1, 0x81, 0xa1, 0x77, 0x01 };
      OSCRTLSAFEMEMCPY ((void*)pvalue->data, 5, testdata, 5);
   }
   return (pvalue);
}

ASN1T_RICactionID* ASN1C_RICactionID::genTestInstance(OSCTXT *pctxt, OSBOOL free)

{
   if (0 == pctxt) pctxt = getCtxtPtr();
   ASN1T_RICactionID* pvalue = (ASN1T_RICactionID*)&msgData;

   *pvalue = 69;
   return (pvalue);
}

ASN1T_RICactionType* ASN1C_RICactionType::genTestInstance(OSCTXT *pctxt, OSBOOL free)

{
   if (0 == pctxt) pctxt = getCtxtPtr();
   ASN1T_RICactionType* pvalue = (ASN1T_RICactionType*)&msgData;

   *pvalue = RICactionType::report;
   return (pvalue);
}

ASN1T_RICactionDefinition* ASN1C_RICactionDefinition::genTestInstance(OSCTXT *pctxt, OSBOOL free)

{
   if (0 == pctxt) pctxt = getCtxtPtr();
   ASN1T_RICactionDefinition* pvalue = (ASN1T_RICactionDefinition*)&msgData;
   new (pvalue) ASN1TDynOctStr();

   pvalue->numocts = 20;
   pvalue->data = (OSOCTET*) rtxMemAlloc (pctxt, 20);
   {
      static const OSOCTET testdata[] = {
      0x23, 0xfd, 0xba, 0x54, 0x84, 0xa0, 0xc6, 0x2a, 
      0x3d, 0xc8, 0xb6, 0x49, 0x4b, 0x8a, 0x06, 0x54, 
      0x55, 0x47, 0xe4, 0xb0 };
      OSCRTLSAFEMEMCPY ((void*)pvalue->data, 20, testdata, 20);
   }
   return (pvalue);
}

ASN1T_RICsubsequentActionType* ASN1C_RICsubsequentActionType::genTestInstance(OSCTXT *pctxt, OSBOOL free)

{
   if (0 == pctxt) pctxt = getCtxtPtr();
   ASN1T_RICsubsequentActionType* pvalue = (ASN1T_RICsubsequentActionType*)&msgData;

   *pvalue = RICsubsequentActionType::continue_;
   return (pvalue);
}

ASN1T_RICtimeToWait* ASN1C_RICtimeToWait::genTestInstance(OSCTXT *pctxt, OSBOOL free)

{
   if (0 == pctxt) pctxt = getCtxtPtr();
   ASN1T_RICtimeToWait* pvalue = (ASN1T_RICtimeToWait*)&msgData;

   *pvalue = RICtimeToWait::w30ms;
   return (pvalue);
}

ASN1T_RICsubsequentAction* ASN1C_RICsubsequentAction::genTestInstance(OSCTXT *pctxt, OSBOOL free)

{
   if (0 == pctxt) pctxt = getCtxtPtr();
   ASN1T_RICsubsequentAction* pvalue = (ASN1T_RICsubsequentAction*)&msgData;
   asn1Init_RICsubsequentAction (pvalue, free, pctxt);

   pvalue->ricSubsequentActionType = RICsubsequentActionType::continue_;

   pvalue->ricTimeToWait = RICtimeToWait::w100ms;
   return (pvalue);
}

ASN1T_TransactionID* ASN1C_TransactionID::genTestInstance(OSCTXT *pctxt, OSBOOL free)

{
   if (0 == pctxt) pctxt = getCtxtPtr();
   ASN1T_TransactionID* pvalue = (ASN1T_TransactionID*)&msgData;

   *pvalue = 109;
   return (pvalue);
}

ASN1T_RANfunctionDefinition* ASN1C_RANfunctionDefinition::genTestInstance(OSCTXT *pctxt, OSBOOL free)

{
   if (0 == pctxt) pctxt = getCtxtPtr();
   ASN1T_RANfunctionDefinition* pvalue = (ASN1T_RANfunctionDefinition*)&msgData;
   new (pvalue) ASN1TDynOctStr();

   pvalue->numocts = 14;
   pvalue->data = (OSOCTET*) rtxMemAlloc (pctxt, 14);
   {
      static const OSOCTET testdata[] = {
      0xaa, 0xed, 0x18, 0xc5, 0xf8, 0x3b, 0x43, 0xb3, 
      0x8f, 0x47, 0x54, 0xd6, 0x71, 0x11 };
      OSCRTLSAFEMEMCPY ((void*)pvalue->data, 14, testdata, 14);
   }
   return (pvalue);
}

ASN1T_RANfunctionRevision* ASN1C_RANfunctionRevision::genTestInstance(OSCTXT *pctxt, OSBOOL free)

{
   if (0 == pctxt) pctxt = getCtxtPtr();
   ASN1T_RANfunctionRevision* pvalue = (ASN1T_RANfunctionRevision*)&msgData;

   *pvalue = 2656;
   return (pvalue);
}

ASN1T_RANfunctionOID ASN1C_RANfunctionOID::genTestInstance(OSCTXT *pctxt, OSBOOL free)

{
   if (0 == pctxt) pctxt = getCtxtPtr();

   msgData = "+XW8w2qt2Rn8N(7gE KJf?T/N(Z1NG88dRMZG)SRUGM)/cONGuWl73tHsTRFvMWCdjx,mQAGsi0e1X4QSO'MavTS5.un:7";
   return (msgData);
}

ASN1T_RICcallProcessID* ASN1C_RICcallProcessID::genTestInstance(OSCTXT *pctxt, OSBOOL free)

{
   if (0 == pctxt) pctxt = getCtxtPtr();
   ASN1T_RICcallProcessID* pvalue = (ASN1T_RICcallProcessID*)&msgData;
   new (pvalue) ASN1TDynOctStr();

   pvalue->numocts = 16;
   pvalue->data = (OSOCTET*) rtxMemAlloc (pctxt, 16);
   {
      static const OSOCTET testdata[] = {
      0x05, 0x6f, 0x8c, 0x4c, 0x24, 0x9d, 0x48, 0xb2, 
      0xa4, 0xdf, 0xc8, 0x20, 0x52, 0xbb, 0x79, 0x71 };
      OSCRTLSAFEMEMCPY ((void*)pvalue->data, 16, testdata, 16);
   }
   return (pvalue);
}

ASN1T_RICcontrolHeader* ASN1C_RICcontrolHeader::genTestInstance(OSCTXT *pctxt, OSBOOL free)

{
   if (0 == pctxt) pctxt = getCtxtPtr();
   ASN1T_RICcontrolHeader* pvalue = (ASN1T_RICcontrolHeader*)&msgData;
   new (pvalue) ASN1TDynOctStr();

   pvalue->numocts = 7;
   pvalue->data = (OSOCTET*) rtxMemAlloc (pctxt, 7);
   {
      static const OSOCTET testdata[] = {
      0x96, 0x4f, 0xef, 0x0e, 0x0a, 0x37, 0xcc };
      OSCRTLSAFEMEMCPY ((void*)pvalue->data, 7, testdata, 7);
   }
   return (pvalue);
}

ASN1T_RICcontrolMessage* ASN1C_RICcontrolMessage::genTestInstance(OSCTXT *pctxt, OSBOOL free)

{
   if (0 == pctxt) pctxt = getCtxtPtr();
   ASN1T_RICcontrolMessage* pvalue = (ASN1T_RICcontrolMessage*)&msgData;
   new (pvalue) ASN1TDynOctStr();

   pvalue->numocts = 10;
   pvalue->data = (OSOCTET*) rtxMemAlloc (pctxt, 10);
   {
      static const OSOCTET testdata[] = {
      0x16, 0xcd, 0x8f, 0xcd, 0xe8, 0x71, 0x52, 0x59, 
      0x7d, 0x1f };
      OSCRTLSAFEMEMCPY ((void*)pvalue->data, 10, testdata, 10);
   }
   return (pvalue);
}

ASN1T_RICcontrolAckRequest* ASN1C_RICcontrolAckRequest::genTestInstance(OSCTXT *pctxt, OSBOOL free)

{
   if (0 == pctxt) pctxt = getCtxtPtr();
   ASN1T_RICcontrolAckRequest* pvalue = (ASN1T_RICcontrolAckRequest*)&msgData;

   *pvalue = RICcontrolAckRequest::noAck;
   return (pvalue);
}

ASN1T_PLMN_Identity* ASN1C_PLMN_Identity::genTestInstance(OSCTXT *pctxt, OSBOOL free)

{
   if (0 == pctxt) pctxt = getCtxtPtr();
   ASN1T_PLMN_Identity* pvalue = (ASN1T_PLMN_Identity*)&msgData;
   asn1Init_PLMN_Identity (pvalue, free, pctxt);

   pvalue->numocts = 3;
   {
      static const OSOCTET testdata[] = {
      0x9b, 0x67, 0x30 };
      OSCRTLSAFEMEMCPY ((void*)pvalue->data, 3, testdata, 3);
   }
   return (pvalue);
}

ASN1T_GNB_ID_Choice* ASN1C_GNB_ID_Choice::genTestInstance(OSCTXT *pctxt, OSBOOL free)

{
   if (0 == pctxt) pctxt = getCtxtPtr();
   ASN1T_GNB_ID_Choice* pvalue = (ASN1T_GNB_ID_Choice*)&msgData;
   asn1Init_GNB_ID_Choice (pvalue, free, pctxt);

   pvalue->t =  1;
   pvalue->u.gnb_ID = rtxMemAllocTypeZ (pctxt, ASN1TBitStr32);
   pvalue->u.gnb_ID->numbits = 28;
   pvalue->u.gnb_ID->data[0] = 0x51;
   pvalue->u.gnb_ID->data[1] = 0x41;
   pvalue->u.gnb_ID->data[2] = 0x61;
   pvalue->u.gnb_ID->data[3] = 0x5c;
   return (pvalue);
}

ASN1T_GlobalgNB_ID* ASN1C_GlobalgNB_ID::genTestInstance(OSCTXT *pctxt, OSBOOL free)

{
   if (0 == pctxt) pctxt = getCtxtPtr();
   ASN1T_GlobalgNB_ID* pvalue = (ASN1T_GlobalgNB_ID*)&msgData;
   asn1Init_GlobalgNB_ID (pvalue, free, pctxt);

   pvalue->plmn_id.numocts = 3;
   {
      static const OSOCTET testdata[] = {
      0xda, 0xcd, 0xfe };
      OSCRTLSAFEMEMCPY ((void*)pvalue->plmn_id.data, 3, testdata, 3);
   }

   pvalue->gnb_id.t =  1;
   pvalue->gnb_id.u.gnb_ID = rtxMemAllocTypeZ (pctxt, ASN1TBitStr32);
   pvalue->gnb_id.u.gnb_ID->numbits = 22;
   pvalue->gnb_id.u.gnb_ID->data[0] = 0x43;
   pvalue->gnb_id.u.gnb_ID->data[1] = 0x5d;
   pvalue->gnb_id.u.gnb_ID->data[2] = 0x44;
   return (pvalue);
}

ASN1T_ENGNB_ID* ASN1C_ENGNB_ID::genTestInstance(OSCTXT *pctxt, OSBOOL free)

{
   if (0 == pctxt) pctxt = getCtxtPtr();
   ASN1T_ENGNB_ID* pvalue = (ASN1T_ENGNB_ID*)&msgData;
   asn1Init_ENGNB_ID (pvalue, free, pctxt);

   pvalue->t =  1;
   pvalue->u.gNB_ID = rtxMemAllocTypeZ (pctxt, ASN1TBitStr32);
   pvalue->u.gNB_ID->numbits = 24;
   pvalue->u.gNB_ID->data[0] = 0x47;
   pvalue->u.gNB_ID->data[1] = 0x67;
   pvalue->u.gNB_ID->data[2] = 0x55;
   pvalue->u.gNB_ID->data[3] = 0x4a;
   return (pvalue);
}

ASN1T_E2AP_IEs_GlobalenGNB_ID* ASN1C_E2AP_IEs_GlobalenGNB_ID::genTestInstance(OSCTXT *pctxt, OSBOOL free)

{
   if (0 == pctxt) pctxt = getCtxtPtr();
   ASN1T_E2AP_IEs_GlobalenGNB_ID* pvalue = (ASN1T_E2AP_IEs_GlobalenGNB_ID*)&msgData;
   asn1Init_E2AP_IEs_GlobalenGNB_ID (pvalue, free, pctxt);

   pvalue->pLMN_Identity.numocts = 3;
   {
      static const OSOCTET testdata[] = {
      0xd6, 0x09, 0x81 };
      OSCRTLSAFEMEMCPY ((void*)pvalue->pLMN_Identity.data, 3, testdata, 3);
   }

   pvalue->gNB_ID.t =  1;
   pvalue->gNB_ID.u.gNB_ID = rtxMemAllocTypeZ (pctxt, ASN1TBitStr32);
   pvalue->gNB_ID.u.gNB_ID->numbits = 31;
   pvalue->gNB_ID.u.gNB_ID->data[0] = 0x63;
   pvalue->gNB_ID.u.gNB_ID->data[1] = 0x64;
   pvalue->gNB_ID.u.gNB_ID->data[2] = 0x33;
   pvalue->gNB_ID.u.gNB_ID->data[3] = 0x69;
   return (pvalue);
}

ASN1T_E2AP_IEs_GNB_CU_UP_ID* ASN1C_E2AP_IEs_GNB_CU_UP_ID::genTestInstance(OSCTXT *pctxt, OSBOOL free)

{
   if (0 == pctxt) pctxt = getCtxtPtr();
   ASN1T_E2AP_IEs_GNB_CU_UP_ID* pvalue = (ASN1T_E2AP_IEs_GNB_CU_UP_ID*)&msgData;

   *pvalue = OSUI64CONST(54042439072);
   return (pvalue);
}

ASN1T_E2AP_IEs_GNB_DU_ID* ASN1C_E2AP_IEs_GNB_DU_ID::genTestInstance(OSCTXT *pctxt, OSBOOL free)

{
   if (0 == pctxt) pctxt = getCtxtPtr();
   ASN1T_E2AP_IEs_GNB_DU_ID* pvalue = (ASN1T_E2AP_IEs_GNB_DU_ID*)&msgData;

   *pvalue = OSUI64CONST(49109115040);
   return (pvalue);
}

ASN1T_GlobalE2node_gNB_ID* ASN1C_GlobalE2node_gNB_ID::genTestInstance(OSCTXT *pctxt, OSBOOL free)

{
   if (0 == pctxt) pctxt = getCtxtPtr();
   ASN1T_GlobalE2node_gNB_ID* pvalue = (ASN1T_GlobalE2node_gNB_ID*)&msgData;
   asn1Init_GlobalE2node_gNB_ID (pvalue, free, pctxt);

   pvalue->global_gNB_ID.plmn_id.numocts = 3;
   {
      static const OSOCTET testdata[] = {
      0xca, 0xe8, 0x82 };
      OSCRTLSAFEMEMCPY ((void*)pvalue->global_gNB_ID.plmn_id.data, 3, testdata, 3);
   }

   pvalue->global_gNB_ID.gnb_id.t =  1;
   pvalue->global_gNB_ID.gnb_id.u.gnb_ID = rtxMemAllocTypeZ (pctxt, ASN1TBitStr32);
   pvalue->global_gNB_ID.gnb_id.u.gnb_ID->numbits = 31;
   pvalue->global_gNB_ID.gnb_id.u.gnb_ID->data[0] = 0x60;
   pvalue->global_gNB_ID.gnb_id.u.gnb_ID->data[1] = 0x42;
   pvalue->global_gNB_ID.gnb_id.u.gnb_ID->data[2] = 0x6f;
   pvalue->global_gNB_ID.gnb_id.u.gnb_ID->data[3] = 0x46;

   return (pvalue);
}

ASN1T_GlobalE2node_en_gNB_ID* ASN1C_GlobalE2node_en_gNB_ID::genTestInstance(OSCTXT *pctxt, OSBOOL free)

{
   if (0 == pctxt) pctxt = getCtxtPtr();
   ASN1T_GlobalE2node_en_gNB_ID* pvalue = (ASN1T_GlobalE2node_en_gNB_ID*)&msgData;
   asn1Init_GlobalE2node_en_gNB_ID (pvalue, free, pctxt);

   pvalue->global_en_gNB_ID.pLMN_Identity.numocts = 3;
   {
      static const OSOCTET testdata[] = {
      0x02, 0xc1, 0x21 };
      OSCRTLSAFEMEMCPY ((void*)pvalue->global_en_gNB_ID.pLMN_Identity.data, 3, testdata, 3);
   }

   pvalue->global_en_gNB_ID.gNB_ID.t =  1;
   pvalue->global_en_gNB_ID.gNB_ID.u.gNB_ID = rtxMemAllocTypeZ (pctxt, ASN1TBitStr32);
   pvalue->global_en_gNB_ID.gNB_ID.u.gNB_ID->numbits = 29;
   pvalue->global_en_gNB_ID.gNB_ID.u.gNB_ID->data[0] = 0x54;
   pvalue->global_en_gNB_ID.gNB_ID.u.gNB_ID->data[1] = 0x41;
   pvalue->global_en_gNB_ID.gNB_ID.u.gNB_ID->data[2] = 0x75;
   pvalue->global_en_gNB_ID.gNB_ID.u.gNB_ID->data[3] = 0x73;

   return (pvalue);
}

ASN1T_ENB_ID_Choice* ASN1C_ENB_ID_Choice::genTestInstance(OSCTXT *pctxt, OSBOOL free)

{
   if (0 == pctxt) pctxt = getCtxtPtr();
   ASN1T_ENB_ID_Choice* pvalue = (ASN1T_ENB_ID_Choice*)&msgData;
   asn1Init_ENB_ID_Choice (pvalue, free, pctxt);

   pvalue->t =  2;
   pvalue->u.enb_ID_shortmacro = rtxMemAllocTypeZ (pctxt, ASN1TBitStr32);
   pvalue->u.enb_ID_shortmacro->numbits = 18;
   pvalue->u.enb_ID_shortmacro->data[0] = 0x66;
   pvalue->u.enb_ID_shortmacro->data[1] = 0x32;
   pvalue->u.enb_ID_shortmacro->data[2] = 0x4d;
   return (pvalue);
}

ASN1T_GlobalngeNB_ID* ASN1C_GlobalngeNB_ID::genTestInstance(OSCTXT *pctxt, OSBOOL free)

{
   if (0 == pctxt) pctxt = getCtxtPtr();
   ASN1T_GlobalngeNB_ID* pvalue = (ASN1T_GlobalngeNB_ID*)&msgData;
   asn1Init_GlobalngeNB_ID (pvalue, free, pctxt);

   pvalue->plmn_id.numocts = 3;
   {
      static const OSOCTET testdata[] = {
      0x36, 0x4d, 0x6e };
      OSCRTLSAFEMEMCPY ((void*)pvalue->plmn_id.data, 3, testdata, 3);
   }

   pvalue->enb_id.t =  1;
   pvalue->enb_id.u.enb_ID_macro = rtxMemAllocTypeZ (pctxt, ASN1TBitStr32);
   pvalue->enb_id.u.enb_ID_macro->numbits = 20;
   pvalue->enb_id.u.enb_ID_macro->data[0] = 0x52;
   pvalue->enb_id.u.enb_ID_macro->data[1] = 0x30;
   pvalue->enb_id.u.enb_ID_macro->data[2] = 0x67;
   return (pvalue);
}

ASN1T_E2AP_IEs_ENB_ID* ASN1C_E2AP_IEs_ENB_ID::genTestInstance(OSCTXT *pctxt, OSBOOL free)

{
   if (0 == pctxt) pctxt = getCtxtPtr();
   ASN1T_E2AP_IEs_ENB_ID* pvalue = (ASN1T_E2AP_IEs_ENB_ID*)&msgData;
   asn1Init_E2AP_IEs_ENB_ID (pvalue, free, pctxt);

   pvalue->t =  1;
   pvalue->u.macro_eNB_ID = rtxMemAllocTypeZ (pctxt, ASN1TBitStr32);
   pvalue->u.macro_eNB_ID->numbits = 20;
   pvalue->u.macro_eNB_ID->data[0] = 0x5b;
   pvalue->u.macro_eNB_ID->data[1] = 0x4c;
   pvalue->u.macro_eNB_ID->data[2] = 0x31;
   return (pvalue);
}

ASN1T_E2AP_IEs_GlobalENB_ID* ASN1C_E2AP_IEs_GlobalENB_ID::genTestInstance(OSCTXT *pctxt, OSBOOL free)

{
   if (0 == pctxt) pctxt = getCtxtPtr();
   ASN1T_E2AP_IEs_GlobalENB_ID* pvalue = (ASN1T_E2AP_IEs_GlobalENB_ID*)&msgData;
   asn1Init_E2AP_IEs_GlobalENB_ID (pvalue, free, pctxt);

   pvalue->pLMN_Identity.numocts = 3;
   {
      static const OSOCTET testdata[] = {
      0x38, 0x43, 0x26 };
      OSCRTLSAFEMEMCPY ((void*)pvalue->pLMN_Identity.data, 3, testdata, 3);
   }

   pvalue->eNB_ID.t =  2;
   pvalue->eNB_ID.u.home_eNB_ID = rtxMemAllocTypeZ (pctxt, ASN1TBitStr32);
   pvalue->eNB_ID.u.home_eNB_ID->numbits = 28;
   pvalue->eNB_ID.u.home_eNB_ID->data[0] = 0x4e;
   pvalue->eNB_ID.u.home_eNB_ID->data[1] = 0x36;
   pvalue->eNB_ID.u.home_eNB_ID->data[2] = 0x59;
   pvalue->eNB_ID.u.home_eNB_ID->data[3] = 0x5a;
   return (pvalue);
}

ASN1T_E2AP_IEs_NGENB_DU_ID* ASN1C_E2AP_IEs_NGENB_DU_ID::genTestInstance(OSCTXT *pctxt, OSBOOL free)

{
   if (0 == pctxt) pctxt = getCtxtPtr();
   ASN1T_E2AP_IEs_NGENB_DU_ID* pvalue = (ASN1T_E2AP_IEs_NGENB_DU_ID*)&msgData;

   *pvalue = OSUI64CONST(66717184160);
   return (pvalue);
}

ASN1T_GlobalE2node_ng_eNB_ID* ASN1C_GlobalE2node_ng_eNB_ID::genTestInstance(OSCTXT *pctxt, OSBOOL free)

{
   if (0 == pctxt) pctxt = getCtxtPtr();
   ASN1T_GlobalE2node_ng_eNB_ID* pvalue = (ASN1T_GlobalE2node_ng_eNB_ID*)&msgData;
   asn1Init_GlobalE2node_ng_eNB_ID (pvalue, free, pctxt);

   pvalue->global_ng_eNB_ID.plmn_id.numocts = 3;
   {
      static const OSOCTET testdata[] = {
      0x0c, 0xc9, 0x4f };
      OSCRTLSAFEMEMCPY ((void*)pvalue->global_ng_eNB_ID.plmn_id.data, 3, testdata, 3);
   }

   pvalue->global_ng_eNB_ID.enb_id.t =  1;
   pvalue->global_ng_eNB_ID.enb_id.u.enb_ID_macro = rtxMemAllocTypeZ (pctxt, ASN1TBitStr32);
   pvalue->global_ng_eNB_ID.enb_id.u.enb_ID_macro->numbits = 20;
   pvalue->global_ng_eNB_ID.enb_id.u.enb_ID_macro->data[0] = 0x50;
   pvalue->global_ng_eNB_ID.enb_id.u.enb_ID_macro->data[1] = 0x39;
   pvalue->global_ng_eNB_ID.enb_id.u.enb_ID_macro->data[2] = 0x37;

   return (pvalue);
}

ASN1T_GlobalE2node_eNB_ID* ASN1C_GlobalE2node_eNB_ID::genTestInstance(OSCTXT *pctxt, OSBOOL free)

{
   if (0 == pctxt) pctxt = getCtxtPtr();
   ASN1T_GlobalE2node_eNB_ID* pvalue = (ASN1T_GlobalE2node_eNB_ID*)&msgData;
   asn1Init_GlobalE2node_eNB_ID (pvalue, free, pctxt);

   pvalue->global_eNB_ID.pLMN_Identity.numocts = 3;
   {
      static const OSOCTET testdata[] = {
      0x7c, 0x80, 0xf6 };
      OSCRTLSAFEMEMCPY ((void*)pvalue->global_eNB_ID.pLMN_Identity.data, 3, testdata, 3);
   }

   pvalue->global_eNB_ID.eNB_ID.t =  2;
   pvalue->global_eNB_ID.eNB_ID.u.home_eNB_ID = rtxMemAllocTypeZ (pctxt, ASN1TBitStr32);
   pvalue->global_eNB_ID.eNB_ID.u.home_eNB_ID->numbits = 28;
   pvalue->global_eNB_ID.eNB_ID.u.home_eNB_ID->data[0] = 0x6b;
   pvalue->global_eNB_ID.eNB_ID.u.home_eNB_ID->data[1] = 0x45;
   pvalue->global_eNB_ID.eNB_ID.u.home_eNB_ID->data[2] = 0x48;
   pvalue->global_eNB_ID.eNB_ID.u.home_eNB_ID->data[3] = 0x66;
   return (pvalue);
}

ASN1T_GlobalE2node_ID* ASN1C_GlobalE2node_ID::genTestInstance(OSCTXT *pctxt, OSBOOL free)

{
   if (0 == pctxt) pctxt = getCtxtPtr();
   ASN1T_GlobalE2node_ID* pvalue = (ASN1T_GlobalE2node_ID*)&msgData;
   asn1Init_GlobalE2node_ID (pvalue, free, pctxt);

   pvalue->t =  3;
   pvalue->u.ng_eNB = rtxMemAllocTypeZ (pctxt, ASN1T_GlobalE2node_ng_eNB_ID);
   new (pvalue->u.ng_eNB) ASN1T_GlobalE2node_ng_eNB_ID();

   pvalue->u.ng_eNB->global_ng_eNB_ID.plmn_id.numocts = 3;
   {
      static const OSOCTET testdata[] = {
      0xb4, 0xa6, 0x7e };
      OSCRTLSAFEMEMCPY ((void*)pvalue->u.ng_eNB->global_ng_eNB_ID.plmn_id.data, 3, testdata, 3);
   }

   pvalue->u.ng_eNB->global_ng_eNB_ID.enb_id.t =  3;
   pvalue->u.ng_eNB->global_ng_eNB_ID.enb_id.u.enb_ID_longmacro = rtxMemAllocTypeZ (pctxt, ASN1TBitStr32);
   pvalue->u.ng_eNB->global_ng_eNB_ID.enb_id.u.enb_ID_longmacro->numbits = 21;
   pvalue->u.ng_eNB->global_ng_eNB_ID.enb_id.u.enb_ID_longmacro->data[0] = 0x6b;
   pvalue->u.ng_eNB->global_ng_eNB_ID.enb_id.u.enb_ID_longmacro->data[1] = 0x58;
   pvalue->u.ng_eNB->global_ng_eNB_ID.enb_id.u.enb_ID_longmacro->data[2] = 0x67;

   return (pvalue);
}

ASN1T_E2nodeComponentInterfaceType* ASN1C_E2nodeComponentInterfaceType::genTestInstance(OSCTXT *pctxt, OSBOOL free)

{
   if (0 == pctxt) pctxt = getCtxtPtr();
   ASN1T_E2nodeComponentInterfaceType* pvalue = (ASN1T_E2nodeComponentInterfaceType*)&msgData;

   *pvalue = E2nodeComponentInterfaceType::e1;
   return (pvalue);
}

ASN1T_AMFName ASN1C_AMFName::genTestInstance(OSCTXT *pctxt, OSBOOL free)

{
   if (0 == pctxt) pctxt = getCtxtPtr();

   msgData = "jjmelgoIJa3/eKBHqJb/V6eA.KUWo=9Bh,g:lUb7un(ZxDgnM.whAa).lBIDAaEhf- 7bb1V6qu3tE GLanM rTlsbo5C6wh?wy";
   return (msgData);
}

ASN1T_E2nodeComponentInterfaceNG* ASN1C_E2nodeComponentInterfaceNG::genTestInstance(OSCTXT *pctxt, OSBOOL free)

{
   if (0 == pctxt) pctxt = getCtxtPtr();
   ASN1T_E2nodeComponentInterfaceNG* pvalue = (ASN1T_E2nodeComponentInterfaceNG*)&msgData;
   asn1Init_E2nodeComponentInterfaceNG (pvalue, free, pctxt);

   pvalue->amf_name = "CmwRdUHAv.c-h";
   return (pvalue);
}

ASN1T_GlobalNG_RANNode_ID* ASN1C_GlobalNG_RANNode_ID::genTestInstance(OSCTXT *pctxt, OSBOOL free)

{
   if (0 == pctxt) pctxt = getCtxtPtr();
   ASN1T_GlobalNG_RANNode_ID* pvalue = (ASN1T_GlobalNG_RANNode_ID*)&msgData;
   asn1Init_GlobalNG_RANNode_ID (pvalue, free, pctxt);

   pvalue->t =  1;
   pvalue->u.gNB = rtxMemAllocTypeZ (pctxt, ASN1T_GlobalgNB_ID);
   new (pvalue->u.gNB) ASN1T_GlobalgNB_ID();

   pvalue->u.gNB->plmn_id.numocts = 3;
   {
      static const OSOCTET testdata[] = {
      0x3a, 0xe0, 0x8f };
      OSCRTLSAFEMEMCPY ((void*)pvalue->u.gNB->plmn_id.data, 3, testdata, 3);
   }

   pvalue->u.gNB->gnb_id.t =  1;
   pvalue->u.gNB->gnb_id.u.gnb_ID = rtxMemAllocTypeZ (pctxt, ASN1TBitStr32);
   pvalue->u.gNB->gnb_id.u.gnb_ID->numbits = 27;
   pvalue->u.gNB->gnb_id.u.gnb_ID->data[0] = 0x35;
   pvalue->u.gNB->gnb_id.u.gnb_ID->data[1] = 0x46;
   pvalue->u.gNB->gnb_id.u.gnb_ID->data[2] = 0x5d;
   pvalue->u.gNB->gnb_id.u.gnb_ID->data[3] = 0x4f;
   return (pvalue);
}

ASN1T_E2nodeComponentInterfaceXn* ASN1C_E2nodeComponentInterfaceXn::genTestInstance(OSCTXT *pctxt, OSBOOL free)

{
   if (0 == pctxt) pctxt = getCtxtPtr();
   ASN1T_E2nodeComponentInterfaceXn* pvalue = (ASN1T_E2nodeComponentInterfaceXn*)&msgData;
   asn1Init_E2nodeComponentInterfaceXn (pvalue, free, pctxt);

   pvalue->global_NG_RAN_Node_ID.t =  1;
   pvalue->global_NG_RAN_Node_ID.u.gNB = rtxMemAllocTypeZ (pctxt, ASN1T_GlobalgNB_ID);
   new (pvalue->global_NG_RAN_Node_ID.u.gNB) ASN1T_GlobalgNB_ID();

   pvalue->global_NG_RAN_Node_ID.u.gNB->plmn_id.numocts = 3;
   {
      static const OSOCTET testdata[] = {
      0x26, 0x1c, 0xd6 };
      OSCRTLSAFEMEMCPY ((void*)pvalue->global_NG_RAN_Node_ID.u.gNB->plmn_id.data, 3, testdata, 3);
   }

   pvalue->global_NG_RAN_Node_ID.u.gNB->gnb_id.t =  1;
   pvalue->global_NG_RAN_Node_ID.u.gNB->gnb_id.u.gnb_ID = rtxMemAllocTypeZ (pctxt, ASN1TBitStr32);
   pvalue->global_NG_RAN_Node_ID.u.gNB->gnb_id.u.gnb_ID->numbits = 25;
   pvalue->global_NG_RAN_Node_ID.u.gNB->gnb_id.u.gnb_ID->data[0] = 0x4b;
   pvalue->global_NG_RAN_Node_ID.u.gNB->gnb_id.u.gnb_ID->data[1] = 0x65;
   pvalue->global_NG_RAN_Node_ID.u.gNB->gnb_id.u.gnb_ID->data[2] = 0x63;
   pvalue->global_NG_RAN_Node_ID.u.gNB->gnb_id.u.gnb_ID->data[3] = 0x46;
   return (pvalue);
}

ASN1T_E2nodeComponentInterfaceE1* ASN1C_E2nodeComponentInterfaceE1::genTestInstance(OSCTXT *pctxt, OSBOOL free)

{
   if (0 == pctxt) pctxt = getCtxtPtr();
   ASN1T_E2nodeComponentInterfaceE1* pvalue = (ASN1T_E2nodeComponentInterfaceE1*)&msgData;
   asn1Init_E2nodeComponentInterfaceE1 (pvalue, free, pctxt);

   pvalue->gNB_CU_CP_ID = OSUI64CONST(22300986976);
   return (pvalue);
}

ASN1T_E2nodeComponentInterfaceF1* ASN1C_E2nodeComponentInterfaceF1::genTestInstance(OSCTXT *pctxt, OSBOOL free)

{
   if (0 == pctxt) pctxt = getCtxtPtr();
   ASN1T_E2nodeComponentInterfaceF1* pvalue = (ASN1T_E2nodeComponentInterfaceF1*)&msgData;
   asn1Init_E2nodeComponentInterfaceF1 (pvalue, free, pctxt);

   pvalue->gNB_DU_ID = OSUI64CONST(29008051168);
   return (pvalue);
}

ASN1T_E2nodeComponentInterfaceW1* ASN1C_E2nodeComponentInterfaceW1::genTestInstance(OSCTXT *pctxt, OSBOOL free)

{
   if (0 == pctxt) pctxt = getCtxtPtr();
   ASN1T_E2nodeComponentInterfaceW1* pvalue = (ASN1T_E2nodeComponentInterfaceW1*)&msgData;
   asn1Init_E2nodeComponentInterfaceW1 (pvalue, free, pctxt);

   pvalue->ng_eNB_DU_ID = OSUI64CONST(66117324160);
   return (pvalue);
}

ASN1T_MMEname ASN1C_MMEname::genTestInstance(OSCTXT *pctxt, OSBOOL free)

{
   if (0 == pctxt) pctxt = getCtxtPtr();

   msgData = "piS,'9:01M1cJLq+";
   return (msgData);
}

ASN1T_E2nodeComponentInterfaceS1* ASN1C_E2nodeComponentInterfaceS1::genTestInstance(OSCTXT *pctxt, OSBOOL free)

{
   if (0 == pctxt) pctxt = getCtxtPtr();
   ASN1T_E2nodeComponentInterfaceS1* pvalue = (ASN1T_E2nodeComponentInterfaceS1*)&msgData;
   asn1Init_E2nodeComponentInterfaceS1 (pvalue, free, pctxt);

   pvalue->mme_name = "d7fK+Wr601Lg15?sLFXdChRkVt7(jyo35TX:q53d(X03Q/ixN-EPRrA/k";
   return (pvalue);
}

ASN1T_E2nodeComponentInterfaceX2* ASN1C_E2nodeComponentInterfaceX2::genTestInstance(OSCTXT *pctxt, OSBOOL free)

{
   if (0 == pctxt) pctxt = getCtxtPtr();
   ASN1T_E2nodeComponentInterfaceX2* pvalue = (ASN1T_E2nodeComponentInterfaceX2*)&msgData;
   asn1Init_E2nodeComponentInterfaceX2 (pvalue, free, pctxt);

   return (pvalue);
}

ASN1T_E2nodeComponentID* ASN1C_E2nodeComponentID::genTestInstance(OSCTXT *pctxt, OSBOOL free)

{
   if (0 == pctxt) pctxt = getCtxtPtr();
   ASN1T_E2nodeComponentID* pvalue = (ASN1T_E2nodeComponentID*)&msgData;
   asn1Init_E2nodeComponentID (pvalue, free, pctxt);

   pvalue->t =  3;
   pvalue->u.e2nodeComponentInterfaceTypeE1 = rtxMemAllocTypeZ (pctxt, ASN1T_E2nodeComponentInterfaceE1);
   new (pvalue->u.e2nodeComponentInterfaceTypeE1) ASN1T_E2nodeComponentInterfaceE1();

   pvalue->u.e2nodeComponentInterfaceTypeE1->gNB_CU_CP_ID = OSUI64CONST(50717220512);
   return (pvalue);
}

ASN1T_E2nodeComponentConfiguration* ASN1C_E2nodeComponentConfiguration::genTestInstance(OSCTXT *pctxt, OSBOOL free)

{
   if (0 == pctxt) pctxt = getCtxtPtr();
   ASN1T_E2nodeComponentConfiguration* pvalue = (ASN1T_E2nodeComponentConfiguration*)&msgData;
   asn1Init_E2nodeComponentConfiguration (pvalue, free, pctxt);

   pvalue->e2nodeComponentRequestPart.numocts = 16;
   pvalue->e2nodeComponentRequestPart.data = (OSOCTET*) rtxMemAlloc (pctxt, 16);
   {
      static const OSOCTET testdata[] = {
      0x4b, 0x9a, 0xc0, 0xe2, 0x80, 0xb4, 0x66, 0x20, 
      0xef, 0x63, 0xc5, 0x6f, 0x73, 0x2c, 0x71, 0x0f };
      OSCRTLSAFEMEMCPY ((void*)pvalue->e2nodeComponentRequestPart.data, 16, testdata, 16);
   }

   pvalue->e2nodeComponentResponsePart.numocts = 18;
   pvalue->e2nodeComponentResponsePart.data = (OSOCTET*) rtxMemAlloc (pctxt, 18);
   {
      static const OSOCTET testdata[] = {
      0x1a, 0x42, 0x11, 0xc2, 0x7f, 0xf2, 0x51, 0x98, 
      0xd2, 0x10, 0x50, 0xcc, 0xb6, 0x0f, 0x98, 0xd1, 
      0xcf, 0xfa };
      OSCRTLSAFEMEMCPY ((void*)pvalue->e2nodeComponentResponsePart.data, 18, testdata, 18);
   }
   return (pvalue);
}

ASN1T_TNLinformation* ASN1C_TNLinformation::genTestInstance(OSCTXT *pctxt, OSBOOL free)

{
   if (0 == pctxt) pctxt = getCtxtPtr();
   ASN1T_TNLinformation* pvalue = (ASN1T_TNLinformation*)&msgData;
   asn1Init_TNLinformation (pvalue, free, pctxt);

   pvalue->tnlAddress.numbits = 95;
   {
      OSOCTET* bitData = (OSOCTET*) rtxMemAlloc (pctxt, 12);
      bitData[0] = 0x6e;
      bitData[1] = 0x4f;
      bitData[2] = 0x5c;
      bitData[3] = 0x38;
      bitData[4] = 0x5d;
      bitData[5] = 0x4e;
      bitData[6] = 0x38;
      bitData[7] = 0x36;
      bitData[8] = 0x6a;
      bitData[9] = 0x58;
      bitData[10] = 0x3f;
      bitData[11] = 0x4f;
      pvalue->tnlAddress.data = (const OSOCTET*)bitData;
   }

   return (pvalue);
}

ASN1T_TNLusage* ASN1C_TNLusage::genTestInstance(OSCTXT *pctxt, OSBOOL free)

{
   if (0 == pctxt) pctxt = getCtxtPtr();
   ASN1T_TNLusage* pvalue = (ASN1T_TNLusage*)&msgData;

   *pvalue = TNLusage::support_function;
   return (pvalue);
}

ASN1T_CauseRICrequest* ASN1C_CauseRICrequest::genTestInstance(OSCTXT *pctxt, OSBOOL free)

{
   if (0 == pctxt) pctxt = getCtxtPtr();
   ASN1T_CauseRICrequest* pvalue = (ASN1T_CauseRICrequest*)&msgData;

   *pvalue = CauseRICrequest::control_message_invalid;
   return (pvalue);
}

ASN1T_CauseRICservice* ASN1C_CauseRICservice::genTestInstance(OSCTXT *pctxt, OSBOOL free)

{
   if (0 == pctxt) pctxt = getCtxtPtr();
   ASN1T_CauseRICservice* pvalue = (ASN1T_CauseRICservice*)&msgData;

   *pvalue = CauseRICservice::ran_function_not_supported;
   return (pvalue);
}

ASN1T_CauseE2node* ASN1C_CauseE2node::genTestInstance(OSCTXT *pctxt, OSBOOL free)

{
   if (0 == pctxt) pctxt = getCtxtPtr();
   ASN1T_CauseE2node* pvalue = (ASN1T_CauseE2node*)&msgData;

   *pvalue = CauseE2node::e2node_component_unknown;
   return (pvalue);
}

ASN1T_CauseTransport* ASN1C_CauseTransport::genTestInstance(OSCTXT *pctxt, OSBOOL free)

{
   if (0 == pctxt) pctxt = getCtxtPtr();
   ASN1T_CauseTransport* pvalue = (ASN1T_CauseTransport*)&msgData;

   *pvalue = CauseTransport::transport_resource_unavailable;
   return (pvalue);
}

ASN1T_CauseProtocol* ASN1C_CauseProtocol::genTestInstance(OSCTXT *pctxt, OSBOOL free)

{
   if (0 == pctxt) pctxt = getCtxtPtr();
   ASN1T_CauseProtocol* pvalue = (ASN1T_CauseProtocol*)&msgData;

   *pvalue = CauseProtocol::abstract_syntax_error_falsely_constructed_message;
   return (pvalue);
}

ASN1T_CauseMisc* ASN1C_CauseMisc::genTestInstance(OSCTXT *pctxt, OSBOOL free)

{
   if (0 == pctxt) pctxt = getCtxtPtr();
   ASN1T_CauseMisc* pvalue = (ASN1T_CauseMisc*)&msgData;

   *pvalue = CauseMisc::om_intervention;
   return (pvalue);
}

ASN1T_Cause* ASN1C_Cause::genTestInstance(OSCTXT *pctxt, OSBOOL free)

{
   if (0 == pctxt) pctxt = getCtxtPtr();
   ASN1T_Cause* pvalue = (ASN1T_Cause*)&msgData;
   asn1Init_Cause (pvalue, free, pctxt);

   pvalue->t =  4;
   pvalue->u.transport = CauseTransport::transport_resource_unavailable;
   return (pvalue);
}

ASN1T_XAPP_ID* ASN1C_XAPP_ID::genTestInstance(OSCTXT *pctxt, OSBOOL free)

{
   if (0 == pctxt) pctxt = getCtxtPtr();
   ASN1T_XAPP_ID* pvalue = (ASN1T_XAPP_ID*)&msgData;

   *pvalue = 53024;
   return (pvalue);
}

ASN1T_RICindicationSN* ASN1C_RICindicationSN::genTestInstance(OSCTXT *pctxt, OSBOOL free)

{
   if (0 == pctxt) pctxt = getCtxtPtr();
   ASN1T_RICindicationSN* pvalue = (ASN1T_RICindicationSN*)&msgData;

   *pvalue = 4286;
   return (pvalue);
}

ASN1T_RICindicationType* ASN1C_RICindicationType::genTestInstance(OSCTXT *pctxt, OSBOOL free)

{
   if (0 == pctxt) pctxt = getCtxtPtr();
   ASN1T_RICindicationType* pvalue = (ASN1T_RICindicationType*)&msgData;

   *pvalue = RICindicationType::report;
   return (pvalue);
}

ASN1T_RICindicationHeader* ASN1C_RICindicationHeader::genTestInstance(OSCTXT *pctxt, OSBOOL free)

{
   if (0 == pctxt) pctxt = getCtxtPtr();
   ASN1T_RICindicationHeader* pvalue = (ASN1T_RICindicationHeader*)&msgData;
   new (pvalue) ASN1TDynOctStr();

   pvalue->numocts = 11;
   pvalue->data = (OSOCTET*) rtxMemAlloc (pctxt, 11);
   {
      static const OSOCTET testdata[] = {
      0x67, 0x9b, 0x4f, 0x62, 0x6d, 0x54, 0x43, 0xde, 
      0x49, 0x87, 0x16 };
      OSCRTLSAFEMEMCPY ((void*)pvalue->data, 11, testdata, 11);
   }
   return (pvalue);
}

ASN1T_RICindicationMessage* ASN1C_RICindicationMessage::genTestInstance(OSCTXT *pctxt, OSBOOL free)

{
   if (0 == pctxt) pctxt = getCtxtPtr();
   ASN1T_RICindicationMessage* pvalue = (ASN1T_RICindicationMessage*)&msgData;
   new (pvalue) ASN1TDynOctStr();

   pvalue->numocts = 1;
   pvalue->data = (OSOCTET*) rtxMemAlloc (pctxt, 1);
   {
      static const OSOCTET testdata[] = {
      0xbf };
      OSCRTLSAFEMEMCPY ((void*)pvalue->data, 1, testdata, 1);
   }
   return (pvalue);
}

ASN1T_TypeOfError* ASN1C_TypeOfError::genTestInstance(OSCTXT *pctxt, OSBOOL free)

{
   if (0 == pctxt) pctxt = getCtxtPtr();
   ASN1T_TypeOfError* pvalue = (ASN1T_TypeOfError*)&msgData;

   *pvalue = TypeOfError::missing;
   return (pvalue);
}

ASN1T_CriticalityDiagnostics_IE_Item* ASN1C_CriticalityDiagnostics_IE_Item::genTestInstance(OSCTXT *pctxt, OSBOOL free)

{
   if (0 == pctxt) pctxt = getCtxtPtr();
   ASN1T_CriticalityDiagnostics_IE_Item* pvalue = (ASN1T_CriticalityDiagnostics_IE_Item*)&msgData;
   asn1Init_CriticalityDiagnostics_IE_Item (pvalue, free, pctxt);

   pvalue->iECriticality = Criticality::ignore;

   pvalue->iE_ID = 23976;

   pvalue->typeOfError = TypeOfError::missing;
   return (pvalue);
}

ASN1T_CriticalityDiagnostics_IE_List* ASN1C_CriticalityDiagnostics_IE_List::genTestInstance(OSCTXT *pctxt, OSBOOL free)

{
   if (0 == pctxt) pctxt = getCtxtPtr();
   ASN1T_CriticalityDiagnostics_IE_List* pvalue = (ASN1T_CriticalityDiagnostics_IE_List*)&msgData;
   asn1Init_CriticalityDiagnostics_IE_List (pvalue, free, pctxt);

   {
      ASN1C_CriticalityDiagnostics_IE_List llist1 (*this, *pvalue);
      llist1.init ();
      ASN1T_CriticalityDiagnostics_IE_Item* pdata1;

      pdata1 = llist1.NewElement ();

      pdata1->iECriticality = Criticality::reject;

      pdata1->iE_ID = 51525;

      pdata1->typeOfError = TypeOfError::missing;

      llist1.Append (pdata1);

   }
   return (pvalue);
}

ASN1T_CriticalityDiagnostics* ASN1C_CriticalityDiagnostics::genTestInstance(OSCTXT *pctxt, OSBOOL free)

{
   if (0 == pctxt) pctxt = getCtxtPtr();
   ASN1T_CriticalityDiagnostics* pvalue = (ASN1T_CriticalityDiagnostics*)&msgData;
   asn1Init_CriticalityDiagnostics (pvalue, free, pctxt);

   return (pvalue);
}

ASN1T_RICcontrolOutcome* ASN1C_RICcontrolOutcome::genTestInstance(OSCTXT *pctxt, OSBOOL free)

{
   if (0 == pctxt) pctxt = getCtxtPtr();
   ASN1T_RICcontrolOutcome* pvalue = (ASN1T_RICcontrolOutcome*)&msgData;
   new (pvalue) ASN1TDynOctStr();

   pvalue->numocts = 7;
   pvalue->data = (OSOCTET*) rtxMemAlloc (pctxt, 7);
   {
      static const OSOCTET testdata[] = {
      0x16, 0x0e, 0xa7, 0xb6, 0x10, 0x3b, 0x26 };
      OSCRTLSAFEMEMCPY ((void*)pvalue->data, 7, testdata, 7);
   }
   return (pvalue);
}

ASN1T_GlobalRIC_ID* ASN1C_GlobalRIC_ID::genTestInstance(OSCTXT *pctxt, OSBOOL free)

{
   if (0 == pctxt) pctxt = getCtxtPtr();
   ASN1T_GlobalRIC_ID* pvalue = (ASN1T_GlobalRIC_ID*)&msgData;
   asn1Init_GlobalRIC_ID (pvalue, free, pctxt);

   pvalue->pLMN_Identity.numocts = 3;
   {
      static const OSOCTET testdata[] = {
      0xde, 0x05, 0x26 };
      OSCRTLSAFEMEMCPY ((void*)pvalue->pLMN_Identity.data, 3, testdata, 3);
   }

   pvalue->ric_ID.numbits = 20;
   pvalue->ric_ID.data[0] = 0x36;
   pvalue->ric_ID.data[1] = 0x6c;
   pvalue->ric_ID.data[2] = 0x61;
   return (pvalue);
}

ASN1T_E2nodeComponentConfigurationAck* ASN1C_E2nodeComponentConfigurationAck::genTestInstance(OSCTXT *pctxt, OSBOOL free)

{
   if (0 == pctxt) pctxt = getCtxtPtr();
   ASN1T_E2nodeComponentConfigurationAck* pvalue = (ASN1T_E2nodeComponentConfigurationAck*)&msgData;
   asn1Init_E2nodeComponentConfigurationAck (pvalue, free, pctxt);

   pvalue->updateOutcome = E2nodeComponentConfigurationAck_updateOutcome::failure;

   return (pvalue);
}

ASN1T_TimeToWait* ASN1C_TimeToWait::genTestInstance(OSCTXT *pctxt, OSBOOL free)

{
   if (0 == pctxt) pctxt = getCtxtPtr();
   ASN1T_TimeToWait* pvalue = (ASN1T_TimeToWait*)&msgData;

   *pvalue = TimeToWait::v1s;
   return (pvalue);
}

