/**
 * This file was generated by the Objective Systems ASN1C Compiler
 * (http://www.obj-sys.com).  Version: 7.8.2.5, Date: 12-Sep-2025.
 *
 * Command:  asn1c asn1files/E2SM-KPM-v05.00.asn asn1files/asn_flexric/e2sm_rc_v1_03_modified.asn asn1files/asn_flexric/e42ap_v2_03.asn -genTest -per -json -w32 -server -depends -events -genPrtToStr -list -reader -trace -c++ -print -prtfmt details -srcdir src -make Makefile -w32 -table-unions -stream -pdu all
 */
#include "E2AP-CommonDataTypes.h"
#include "rtxsrc/rtxCharStr.h"
#include "rtsrc/rtPrint.h"
#include "rtsrc/rtBCD.h"
#include "rtxsrc/rtxDiag.h"

void asn1Print_ProcedureCode 
   (const char* name, const ASN1T_ProcedureCode* pvalue)
{
   rtxPrintUnsigned (name, *pvalue);
}

void ASN1C_ProcedureCode::Print (const char* name)
{
   asn1Print_ProcedureCode (name, &msgData);
}

void asn1Print_Criticality (const char* name, const ASN1T_Criticality* pvalue)
{
   printf ("%s = ", name);
   switch (*pvalue) {
      case 0: printf ("reject\n"); break;
      case 1: printf ("ignore\n"); break;
      case 2: printf ("notify\n"); break;
      default: printf ("???\n");
   }
}

void ASN1C_Criticality::Print (const char* name)
{
   asn1Print_Criticality (name, &msgData);
}

void asn1Print_ProtocolIE_ID 
   (const char* name, const ASN1T_ProtocolIE_ID* pvalue)
{
   rtxPrintUnsigned (name, *pvalue);
}

void ASN1C_ProtocolIE_ID::Print (const char* name)
{
   asn1Print_ProtocolIE_ID (name, &msgData);
}

void asn1Print_TriggeringMessage 
   (const char* name, const ASN1T_TriggeringMessage* pvalue)
{
   printf ("%s = ", name);
   switch (*pvalue) {
      case 0: printf ("initiating-message\n"); break;
      case 1: printf ("successful-outcome\n"); break;
      case 2: printf ("unsuccessfull-outcome\n"); break;
      default: printf ("???\n");
   }
}

void ASN1C_TriggeringMessage::Print (const char* name)
{
   asn1Print_TriggeringMessage (name, &msgData);
}

void asn1Print_Presence (const char* name, const ASN1T_Presence* pvalue)
{
   printf ("%s = ", name);
   switch (*pvalue) {
      case 0: printf ("optional\n"); break;
      case 1: printf ("conditional\n"); break;
      case 2: printf ("mandatory\n"); break;
      default: printf ("???\n");
   }
}

void ASN1C_Presence::Print (const char* name)
{
   asn1Print_Presence (name, &msgData);
}

