/**
 * This file was generated by the Objective Systems ASN1C Compiler
 * (http://www.obj-sys.com).  Version: 7.8.2.5, Date: 27-Jun-2025.
 *
 * Command:  asn1c ./asn1files/E2SM-KPM-v05.00.asn ./asn1files/asn_flexric/e2sm_rc_v1_03_modified.asn ./asn1files/asn_flexric/e42ap_v2_03.asn -cpp -json -per -depends -events -oh ./src -i asn1files -i asn1files/asn_flexric -o ./src -genprint -printformat details -genprttostr -printformat details -stream -table-unions -gentest -trace
 */
#include "E2AP-CommonDataTypes.h"
#include "rtxsrc/rtxCharStr.h"
#include "rtsrc/rtPrintToString.h"
#include "rtsrc/rtBCD.h"
#include "rtxsrc/rtxDiag.h"

int asn1PrtToStr_ProcedureCode (const char* name, ASN1T_ProcedureCode* pvalue, 
   char* buffer, OSSIZE bufSize)
{
   if (rtPrintToStringUnsigned (name, *pvalue, buffer, bufSize) < 0)
   {
      return -1;
   }
   return 0;
}

int asn1PrtToStr_Criticality (const char* name, ASN1T_Criticality* pvalue, 
   char* buffer, OSSIZE bufSize)
{
   int stat;
   if(rtPrintToString (name, buffer, bufSize) < 0)
   {
      return -1;
   }
   switch (*pvalue) {
      case 0:
         stat = rtPrintToString (" = reject\n", buffer, bufSize);
         break;

      case 1:
         stat = rtPrintToString (" = ignore\n", buffer, bufSize);
         break;

      case 2:
         stat = rtPrintToString (" = notify\n", buffer, bufSize);
         break;

      default:
      stat = rtPrintToString (" = ???\n", buffer, bufSize);
   }

   if(stat < 0) return -1;
   return 0;
}

int asn1PrtToStr_ProtocolIE_ID (const char* name, ASN1T_ProtocolIE_ID* pvalue, 
   char* buffer, OSSIZE bufSize)
{
   if (rtPrintToStringUnsigned (name, *pvalue, buffer, bufSize) < 0)
   {
      return -1;
   }
   return 0;
}

int asn1PrtToStr_TriggeringMessage (const char* name, 
   ASN1T_TriggeringMessage* pvalue, char* buffer, OSSIZE bufSize)
{
   int stat;
   if(rtPrintToString (name, buffer, bufSize) < 0)
   {
      return -1;
   }
   switch (*pvalue) {
      case 0:
         stat = rtPrintToString (" = initiating-message\n", buffer, bufSize);
         break;

      case 1:
         stat = rtPrintToString (" = successful-outcome\n", buffer, bufSize);
         break;

      case 2:
         stat = rtPrintToString (" = unsuccessfull-outcome\n", buffer, bufSize);
         break;

      default:
      stat = rtPrintToString (" = ???\n", buffer, bufSize);
   }

   if(stat < 0) return -1;
   return 0;
}

int asn1PrtToStr_Presence (const char* name, ASN1T_Presence* pvalue, 
   char* buffer, OSSIZE bufSize)
{
   int stat;
   if(rtPrintToString (name, buffer, bufSize) < 0)
   {
      return -1;
   }
   switch (*pvalue) {
      case 0:
         stat = rtPrintToString (" = optional\n", buffer, bufSize);
         break;

      case 1:
         stat = rtPrintToString (" = conditional\n", buffer, bufSize);
         break;

      case 2:
         stat = rtPrintToString (" = mandatory\n", buffer, bufSize);
         break;

      default:
      stat = rtPrintToString (" = ???\n", buffer, bufSize);
   }

   if(stat < 0) return -1;
   return 0;
}

