/**
 * This file was generated by the Objective Systems ASN1C Compiler
 * (http://www.obj-sys.com).  Version: 7.8.2.5, Date: 12-Sep-2025.
 *
 * Command:  asn1c asn1files/E2SM-KPM-v05.00.asn asn1files/asn_flexric/e2sm_rc_v1_03_modified.asn asn1files/asn_flexric/e42ap_v2_03.asn -genTest -per -json -w32 -server -depends -events -genPrtToStr -list -reader -trace -c++ -print -prtfmt details -srcdir src -make Makefile -w32 -table-unions -stream -pdu all
 */
#ifndef E2AP_CONSTANTS_H
#define E2AP_CONSTANTS_H

#include "rtkey.h"
#include "rtpersrc/asn1PerCppTypes.h"
#include "rtsrc/asn1type.h"
#include "rtjsonsrc/asn1json.h"
#include "rtjsonsrc/rtJsonCppMsgBuf.h"

#include "E2AP-CommonDataTypes.h"

/**
 * Header file for ASN.1 module E2AP-Constants
 */
/* Value definitions */

#define ASN1V_id_E2setup 1
#define ASN1V_id_ErrorIndication 2
#define ASN1V_id_Reset 3
#define ASN1V_id_RICcontrol 4
#define ASN1V_id_RICindication 5
#define ASN1V_id_RICserviceQuery 6
#define ASN1V_id_RICserviceUpdate 7
#define ASN1V_id_RICsubscription 8
#define ASN1V_id_RICsubscriptionDelete 9
#define ASN1V_id_E2nodeConfigurationUpdate 10
#define ASN1V_id_E2connectionUpdate 11
#define ASN1V_id_RICsubscriptionDeleteRequired 12
#define ASN1V_id_E2removal 13
#define ASN1V_id_E42setup 14
#define ASN1V_id_E42RICsubscription 15
#define ASN1V_id_E42RICsubscriptionDelete 16
#define ASN1V_id_E42RICcontrol 17
#define ASN1V_maxProtocolIEs 65535
#define ASN1V_maxnoofErrors 256
#define ASN1V_maxofE2nodeComponents 1024
#define ASN1V_maxofRANfunctionID 256
#define ASN1V_maxofRICactionID 16
#define ASN1V_maxofTNLA 32
#define ASN1V_maxofRICrequestID 1024
#define ASN1V_id_Cause 1
#define ASN1V_id_CriticalityDiagnostics 2
#define ASN1V_id_GlobalE2node_ID 3
#define ASN1V_id_GlobalRIC_ID 4
#define ASN1V_id_RANfunctionID 5
#define ASN1V_id_RANfunctionID_Item 6
#define ASN1V_id_RANfunctionIEcause_Item 7
#define ASN1V_id_RANfunction_Item 8
#define ASN1V_id_RANfunctionsAccepted 9
#define ASN1V_id_RANfunctionsAdded 10
#define ASN1V_id_RANfunctionsDeleted 11
#define ASN1V_id_RANfunctionsModified 12
#define ASN1V_id_RANfunctionsRejected 13
#define ASN1V_id_RICaction_Admitted_Item 14
#define ASN1V_id_RICactionID 15
#define ASN1V_id_RICaction_NotAdmitted_Item 16
#define ASN1V_id_RICactions_Admitted 17
#define ASN1V_id_RICactions_NotAdmitted 18
#define ASN1V_id_RICaction_ToBeSetup_Item 19
#define ASN1V_id_RICcallProcessID 20
#define ASN1V_id_RICcontrolAckRequest 21
#define ASN1V_id_RICcontrolHeader 22
#define ASN1V_id_RICcontrolMessage 23
#define ASN1V_id_RICcontrolStatus 24
#define ASN1V_id_RICindicationHeader 25
#define ASN1V_id_RICindicationMessage 26
#define ASN1V_id_RICindicationSN 27
#define ASN1V_id_RICindicationType 28
#define ASN1V_id_RICrequestID 29
#define ASN1V_id_RICsubscriptionDetails 30
#define ASN1V_id_TimeToWait 31
#define ASN1V_id_RICcontrolOutcome 32
#define ASN1V_id_E2nodeComponentConfigUpdate 33
#define ASN1V_id_E2nodeComponentConfigUpdate_Item 34
#define ASN1V_id_E2nodeComponentConfigUpdateAck 35
#define ASN1V_id_E2nodeComponentConfigUpdateAck_Item 36
#define ASN1V_id_E2connectionSetup 39
#define ASN1V_id_E2connectionSetupFailed 40
#define ASN1V_id_E2connectionSetupFailed_Item 41
#define ASN1V_id_E2connectionFailed_Item 42
#define ASN1V_id_E2connectionUpdate_Item 43
#define ASN1V_id_E2connectionUpdateAdd 44
#define ASN1V_id_E2connectionUpdateModify 45
#define ASN1V_id_E2connectionUpdateRemove 46
#define ASN1V_id_E2connectionUpdateRemove_Item 47
#define ASN1V_id_TNLinformation 48
#define ASN1V_id_TransactionID 49
#define ASN1V_id_E2nodeComponentConfigAddition 50
#define ASN1V_id_E2nodeComponentConfigAddition_Item 51
#define ASN1V_id_E2nodeComponentConfigAdditionAck 52
#define ASN1V_id_E2nodeComponentConfigAdditionAck_Item 53
#define ASN1V_id_E2nodeComponentConfigRemoval 54
#define ASN1V_id_E2nodeComponentConfigRemoval_Item 55
#define ASN1V_id_E2nodeComponentConfigRemovalAck 56
#define ASN1V_id_E2nodeComponentConfigRemovalAck_Item 57
#define ASN1V_id_E2nodeTNLassociationRemoval 58
#define ASN1V_id_E2nodeTNLassociationRemoval_Item 59
#define ASN1V_id_RICsubscriptionToBeRemoved 60
#define ASN1V_id_RICsubscription_withCause_Item 61
#define ASN1V_id_XAPP_ID 62
#define ASN1V_id_E2nodesConnected 63
#define ASN1V_id_NODEfunctionID_Item 64

#endif
