/**
 * This file was generated by the Objective Systems ASN1C Compiler
 * (http://www.obj-sys.com).  Version: 7.8.2.5, Date: 12-Sep-2025.
 *
 * Command:  asn1c asn1files/E2SM-KPM-v05.00.asn asn1files/asn_flexric/e2sm_rc_v1_03_modified.asn asn1files/asn_flexric/e42ap_v2_03.asn -genTest -per -json -w32 -server -depends -events -genPrtToStr -list -reader -trace -c++ -print -prtfmt details -srcdir src -make Makefile -w32 -table-unions -stream -pdu all
 */
#include <new>
#include "E2AP-PDU-Descriptions.h"
#include "E2AP-Constants.h"
#include "rtxsrc/rtxDiag.h"

/* ASN1T_InitiatingMessage */

ASN1T_InitiatingMessage* new_ASN1T_InitiatingMessage (ASN1CType& ccobj)
{
   void* pdata = ccobj.memAlloc (sizeof(ASN1T_InitiatingMessage));
   if (0 == pdata) return 0;
   else return new (pdata) ASN1T_InitiatingMessage;
}

void asn1SetTC_InitiatingMessage_ricSubscription
   (OSCTXT* pctxt, ASN1T_InitiatingMessage* pElem, ASN1T_RICsubscriptionRequest *pvalue)
{
   pElem->procedureCode = 8;
   pElem->criticality = Criticality::reject;
   pElem->value.t = E2AP_ELEMENTARY_PROCEDURES::T_ricSubscription;
   pElem->value.u.ricSubscription = pvalue;
}

void asn1SetTC_InitiatingMessage_ricSubscriptionDelete
   (OSCTXT* pctxt, ASN1T_InitiatingMessage* pElem, ASN1T_RICsubscriptionDeleteRequest *pvalue)
{
   pElem->procedureCode = 9;
   pElem->criticality = Criticality::reject;
   pElem->value.t = E2AP_ELEMENTARY_PROCEDURES::T_ricSubscriptionDelete;
   pElem->value.u.ricSubscriptionDelete = pvalue;
}

void asn1SetTC_InitiatingMessage_ricServiceUpdate
   (OSCTXT* pctxt, ASN1T_InitiatingMessage* pElem, ASN1T_RICserviceUpdate *pvalue)
{
   pElem->procedureCode = 7;
   pElem->criticality = Criticality::reject;
   pElem->value.t = E2AP_ELEMENTARY_PROCEDURES::T_ricServiceUpdate;
   pElem->value.u.ricServiceUpdate = pvalue;
}

void asn1SetTC_InitiatingMessage_ricControl
   (OSCTXT* pctxt, ASN1T_InitiatingMessage* pElem, ASN1T_RICcontrolRequest *pvalue)
{
   pElem->procedureCode = 4;
   pElem->criticality = Criticality::reject;
   pElem->value.t = E2AP_ELEMENTARY_PROCEDURES::T_ricControl;
   pElem->value.u.ricControl = pvalue;
}

void asn1SetTC_InitiatingMessage_e2setup
   (OSCTXT* pctxt, ASN1T_InitiatingMessage* pElem, ASN1T_E2setupRequest *pvalue)
{
   pElem->procedureCode = 1;
   pElem->criticality = Criticality::reject;
   pElem->value.t = E2AP_ELEMENTARY_PROCEDURES::T_e2setup;
   pElem->value.u.e2setup = pvalue;
}

void asn1SetTC_InitiatingMessage_e2nodeConfigurationUpdate
   (OSCTXT* pctxt, ASN1T_InitiatingMessage* pElem, ASN1T_E2nodeConfigurationUpdate *pvalue)
{
   pElem->procedureCode = 10;
   pElem->criticality = Criticality::reject;
   pElem->value.t = E2AP_ELEMENTARY_PROCEDURES::T_e2nodeConfigurationUpdate;
   pElem->value.u.e2nodeConfigurationUpdate = pvalue;
}

void asn1SetTC_InitiatingMessage_e2connectionUpdate
   (OSCTXT* pctxt, ASN1T_InitiatingMessage* pElem, ASN1T_E2connectionUpdate *pvalue)
{
   pElem->procedureCode = 11;
   pElem->criticality = Criticality::reject;
   pElem->value.t = E2AP_ELEMENTARY_PROCEDURES::T_e2connectionUpdate;
   pElem->value.u.e2connectionUpdate = pvalue;
}

void asn1SetTC_InitiatingMessage_reset
   (OSCTXT* pctxt, ASN1T_InitiatingMessage* pElem, ASN1T_ResetRequest *pvalue)
{
   pElem->procedureCode = 3;
   pElem->criticality = Criticality::reject;
   pElem->value.t = E2AP_ELEMENTARY_PROCEDURES::T_reset;
   pElem->value.u.reset = pvalue;
}

void asn1SetTC_InitiatingMessage_e2removal
   (OSCTXT* pctxt, ASN1T_InitiatingMessage* pElem, ASN1T_E2RemovalRequest *pvalue)
{
   pElem->procedureCode = 13;
   pElem->criticality = Criticality::reject;
   pElem->value.t = E2AP_ELEMENTARY_PROCEDURES::T_e2removal;
   pElem->value.u.e2removal = pvalue;
}

void asn1SetTC_InitiatingMessage_e42setup
   (OSCTXT* pctxt, ASN1T_InitiatingMessage* pElem, ASN1T_E42setupRequest *pvalue)
{
   pElem->procedureCode = 14;
   pElem->criticality = Criticality::reject;
   pElem->value.t = E2AP_ELEMENTARY_PROCEDURES::T_e42setup;
   pElem->value.u.e42setup = pvalue;
}

void asn1SetTC_InitiatingMessage_e42ricSubscription
   (OSCTXT* pctxt, ASN1T_InitiatingMessage* pElem, ASN1T_E42RICsubscriptionRequest *pvalue)
{
   pElem->procedureCode = 15;
   pElem->criticality = Criticality::reject;
   pElem->value.t = E2AP_ELEMENTARY_PROCEDURES::T_e42ricSubscription;
   pElem->value.u.e42ricSubscription = pvalue;
}

void asn1SetTC_InitiatingMessage_e42ricSubscriptionDelete
   (OSCTXT* pctxt, ASN1T_InitiatingMessage* pElem, ASN1T_E42RICsubscriptionDeleteRequest *pvalue)
{
   pElem->procedureCode = 16;
   pElem->criticality = Criticality::reject;
   pElem->value.t = E2AP_ELEMENTARY_PROCEDURES::T_e42ricSubscriptionDelete;
   pElem->value.u.e42ricSubscriptionDelete = pvalue;
}

void asn1SetTC_InitiatingMessage_e42ricControl
   (OSCTXT* pctxt, ASN1T_InitiatingMessage* pElem, ASN1T_E42RICcontrolRequest *pvalue)
{
   pElem->procedureCode = 17;
   pElem->criticality = Criticality::reject;
   pElem->value.t = E2AP_ELEMENTARY_PROCEDURES::T_e42ricControl;
   pElem->value.u.e42ricControl = pvalue;
}

void asn1SetTC_InitiatingMessage_ricIndication
   (OSCTXT* pctxt, ASN1T_InitiatingMessage* pElem, ASN1T_RICindication *pvalue)
{
   pElem->procedureCode = 5;
   pElem->criticality = Criticality::ignore;
   pElem->value.t = E2AP_ELEMENTARY_PROCEDURES::T_ricIndication;
   pElem->value.u.ricIndication = pvalue;
}

void asn1SetTC_InitiatingMessage_ricServiceQuery
   (OSCTXT* pctxt, ASN1T_InitiatingMessage* pElem, ASN1T_RICserviceQuery *pvalue)
{
   pElem->procedureCode = 6;
   pElem->criticality = Criticality::ignore;
   pElem->value.t = E2AP_ELEMENTARY_PROCEDURES::T_ricServiceQuery;
   pElem->value.u.ricServiceQuery = pvalue;
}

void asn1SetTC_InitiatingMessage_errorIndication
   (OSCTXT* pctxt, ASN1T_InitiatingMessage* pElem, ASN1T_ErrorIndication *pvalue)
{
   pElem->procedureCode = 2;
   pElem->criticality = Criticality::ignore;
   pElem->value.t = E2AP_ELEMENTARY_PROCEDURES::T_errorIndication;
   pElem->value.u.errorIndication = pvalue;
}

void asn1SetTC_InitiatingMessage_ricSubscriptionDeleteRequired
   (OSCTXT* pctxt, ASN1T_InitiatingMessage* pElem, ASN1T_RICsubscriptionDeleteRequired *pvalue)
{
   pElem->procedureCode = 12;
   pElem->criticality = Criticality::ignore;
   pElem->value.t = E2AP_ELEMENTARY_PROCEDURES::T_ricSubscriptionDeleteRequired;
   pElem->value.u.ricSubscriptionDeleteRequired = pvalue;
}

ASN1C_InitiatingMessage::ASN1C_InitiatingMessage
    (ASN1T_InitiatingMessage& data) : ASN1CType(), msgData(data)
{
   setRunTimeKey (_rtkey, sizeof(_rtkey));
}

ASN1C_InitiatingMessage::ASN1C_InitiatingMessage (OSRTMessageBufferIF& msgBuf
   , ASN1T_InitiatingMessage& data) : ASN1CType(msgBuf), msgData(data)
{
   setRunTimeKey (_rtkey, sizeof(_rtkey));
}
ASN1C_InitiatingMessage::ASN1C_InitiatingMessage (OSRTContext &context
   , ASN1T_InitiatingMessage& data) : ASN1CType(context), msgData(data)
{
   setRunTimeKey (_rtkey, sizeof(_rtkey));
}


void ASN1C_InitiatingMessage::setTC_ricSubscription(
   ASN1T_RICsubscriptionRequest *pvalue)  {
   asn1SetTC_InitiatingMessage_ricSubscription(getCtxtPtr(), &msgData, pvalue
      );
}

void ASN1C_InitiatingMessage::setTC_ricSubscriptionDelete(
   ASN1T_RICsubscriptionDeleteRequest *pvalue)  {
   asn1SetTC_InitiatingMessage_ricSubscriptionDelete(getCtxtPtr(), &msgData, 
      pvalue);
}

void ASN1C_InitiatingMessage::setTC_ricServiceUpdate(ASN1T_RICserviceUpdate 
   *pvalue)  {
   asn1SetTC_InitiatingMessage_ricServiceUpdate(getCtxtPtr(), &msgData, pvalue
      );
}

void ASN1C_InitiatingMessage::setTC_ricControl(ASN1T_RICcontrolRequest *pvalue)
     {
   asn1SetTC_InitiatingMessage_ricControl(getCtxtPtr(), &msgData, pvalue);
}

void ASN1C_InitiatingMessage::setTC_e2setup(ASN1T_E2setupRequest *pvalue)  {
   asn1SetTC_InitiatingMessage_e2setup(getCtxtPtr(), &msgData, pvalue);
}

void ASN1C_InitiatingMessage::setTC_e2nodeConfigurationUpdate(
   ASN1T_E2nodeConfigurationUpdate *pvalue)  {
   asn1SetTC_InitiatingMessage_e2nodeConfigurationUpdate(getCtxtPtr(), &msgData
      , pvalue);
}

void ASN1C_InitiatingMessage::setTC_e2connectionUpdate(
   ASN1T_E2connectionUpdate *pvalue)  {
   asn1SetTC_InitiatingMessage_e2connectionUpdate(getCtxtPtr(), &msgData, 
      pvalue);
}

void ASN1C_InitiatingMessage::setTC_reset(ASN1T_ResetRequest *pvalue)  {
   asn1SetTC_InitiatingMessage_reset(getCtxtPtr(), &msgData, pvalue);
}

void ASN1C_InitiatingMessage::setTC_e2removal(ASN1T_E2RemovalRequest *pvalue)
     {
   asn1SetTC_InitiatingMessage_e2removal(getCtxtPtr(), &msgData, pvalue);
}

void ASN1C_InitiatingMessage::setTC_e42setup(ASN1T_E42setupRequest *pvalue)  {
   asn1SetTC_InitiatingMessage_e42setup(getCtxtPtr(), &msgData, pvalue);
}

void ASN1C_InitiatingMessage::setTC_e42ricSubscription(
   ASN1T_E42RICsubscriptionRequest *pvalue)  {
   asn1SetTC_InitiatingMessage_e42ricSubscription(getCtxtPtr(), &msgData, 
      pvalue);
}

void ASN1C_InitiatingMessage::setTC_e42ricSubscriptionDelete(
   ASN1T_E42RICsubscriptionDeleteRequest *pvalue)  {
   asn1SetTC_InitiatingMessage_e42ricSubscriptionDelete(getCtxtPtr(), &msgData
      , pvalue);
}

void ASN1C_InitiatingMessage::setTC_e42ricControl(ASN1T_E42RICcontrolRequest 
   *pvalue)  {
   asn1SetTC_InitiatingMessage_e42ricControl(getCtxtPtr(), &msgData, pvalue);
}

void ASN1C_InitiatingMessage::setTC_ricIndication(ASN1T_RICindication *pvalue)
     {
   asn1SetTC_InitiatingMessage_ricIndication(getCtxtPtr(), &msgData, pvalue);
}

void ASN1C_InitiatingMessage::setTC_ricServiceQuery(ASN1T_RICserviceQuery 
   *pvalue)  {
   asn1SetTC_InitiatingMessage_ricServiceQuery(getCtxtPtr(), &msgData, pvalue
      );
}

void ASN1C_InitiatingMessage::setTC_errorIndication(ASN1T_ErrorIndication 
   *pvalue)  {
   asn1SetTC_InitiatingMessage_errorIndication(getCtxtPtr(), &msgData, pvalue
      );
}

void ASN1C_InitiatingMessage::setTC_ricSubscriptionDeleteRequired(
   ASN1T_RICsubscriptionDeleteRequired *pvalue)  {
   asn1SetTC_InitiatingMessage_ricSubscriptionDeleteRequired(getCtxtPtr(), &msgData
      , pvalue);
}

ASN1T_InitiatingMessage::ASN1T_InitiatingMessage ()
{
   OSCRTLMEMSET (&value, 0, sizeof(value));
}

ASN1T_InitiatingMessage::~ASN1T_InitiatingMessage ()
{
   OSCTXT* pctxt = mpContext.getCtxtPtr();
   if (pctxt != 0 && !rtxMemHeapIsEmpty (pctxt)) {
      asn1Free_InitiatingMessage (pctxt, this);
   }
}

int ASN1C_InitiatingMessage::EncodeTo (OSRTMessageBufferIF& msgBuf)
{
   int stat = setMsgBuf (msgBuf, TRUE);
   if (stat != 0) return (stat);

   if (msgBuf.isA (OSRTMessageBufferIF::PEREncode)) {
      stat= asn1PE_InitiatingMessage (msgBuf.getCtxtPtr(), &msgData);
      ((ASN1PEREncodeBuffer&)msgBuf).byteAlign();
      return stat;
   }
   else if (msgBuf.isA (OSRTMessageBufferIF::JSONEncode)) {
      return asn1JsonEnc_InitiatingMessage (msgBuf.getCtxtPtr(), &msgData);
   }
   return RTERR_NOTSUPP;
}

int ASN1C_InitiatingMessage::DecodeFrom (OSRTMessageBufferIF& msgBuf, OSBOOL free)
{
   int stat = setMsgBuf (msgBuf, TRUE);
   if (stat != 0) return (stat);

   asn1Init_InitiatingMessage (&msgData, free, getCtxtPtr());
   msgData.setContext (msgBuf.getContext());
   if (msgBuf.isA (OSRTMessageBufferIF::PERDecode)) {
      stat = asn1PD_InitiatingMessage (msgBuf.getCtxtPtr(), &msgData);
      ((ASN1PERDecodeBuffer&)msgBuf).byteAlign();
      return stat;
   }
   else if (msgBuf.isA (OSRTMessageBufferIF::JSONDecode)) {
      return asn1JsonDec_InitiatingMessage (msgBuf.getCtxtPtr(), &msgData);
   }
   return RTERR_NOTSUPP;
}

int asn1Init_InitiatingMessage (ASN1T_InitiatingMessage* pvalue, 
   OSBOOL free, OSCTXT *pctxt)
{
   if (0 == pvalue) return RTERR_NULLPTR;
   OSCRTLMEMSET (&pvalue->value, 0, sizeof(pvalue->value));
   return 0;
}

void asn1Free_InitiatingMessage (OSCTXT *pctxt, 
   ASN1T_InitiatingMessage* pvalue)
{
   if (0 == pvalue) return;
   switch (pvalue->value.t) {
      case E2AP_ELEMENTARY_PROCEDURES::T_ricSubscription:
         if (0 != pvalue->value.u.ricSubscription) {
            asn1Free_RICsubscriptionRequest (pctxt, pvalue->value.u.ricSubscription);
            ((ASN1T_RICsubscriptionRequest*)pvalue->value.u.ricSubscription)->~ASN1T_RICsubscriptionRequest();
            rtxMemFreePtr (pctxt, (void*)pvalue->value.u.ricSubscription);
            pvalue->value.u.ricSubscription = 0;
         }
         break;

      case E2AP_ELEMENTARY_PROCEDURES::T_ricSubscriptionDelete:
         if (0 != pvalue->value.u.ricSubscriptionDelete) {
            asn1Free_RICsubscriptionDeleteRequest (pctxt, pvalue->value.u.ricSubscriptionDelete);
            ((ASN1T_RICsubscriptionDeleteRequest*)pvalue->value.u.ricSubscriptionDelete)->~ASN1T_RICsubscriptionDeleteRequest();
            rtxMemFreePtr (pctxt, (void*)pvalue->value.u.ricSubscriptionDelete);
            pvalue->value.u.ricSubscriptionDelete = 0;
         }
         break;

      case E2AP_ELEMENTARY_PROCEDURES::T_ricServiceUpdate:
         if (0 != pvalue->value.u.ricServiceUpdate) {
            asn1Free_RICserviceUpdate (pctxt, pvalue->value.u.ricServiceUpdate);
            ((ASN1T_RICserviceUpdate*)pvalue->value.u.ricServiceUpdate)->~ASN1T_RICserviceUpdate();
            rtxMemFreePtr (pctxt, (void*)pvalue->value.u.ricServiceUpdate);
            pvalue->value.u.ricServiceUpdate = 0;
         }
         break;

      case E2AP_ELEMENTARY_PROCEDURES::T_ricControl:
         if (0 != pvalue->value.u.ricControl) {
            asn1Free_RICcontrolRequest (pctxt, pvalue->value.u.ricControl);
            ((ASN1T_RICcontrolRequest*)pvalue->value.u.ricControl)->~ASN1T_RICcontrolRequest();
            rtxMemFreePtr (pctxt, (void*)pvalue->value.u.ricControl);
            pvalue->value.u.ricControl = 0;
         }
         break;

      case E2AP_ELEMENTARY_PROCEDURES::T_e2setup:
         if (0 != pvalue->value.u.e2setup) {
            asn1Free_E2setupRequest (pctxt, pvalue->value.u.e2setup);
            ((ASN1T_E2setupRequest*)pvalue->value.u.e2setup)->~ASN1T_E2setupRequest();
            rtxMemFreePtr (pctxt, (void*)pvalue->value.u.e2setup);
            pvalue->value.u.e2setup = 0;
         }
         break;

      case E2AP_ELEMENTARY_PROCEDURES::T_e2nodeConfigurationUpdate:
         if (0 != pvalue->value.u.e2nodeConfigurationUpdate) {
            asn1Free_E2nodeConfigurationUpdate (pctxt, pvalue->value.u.e2nodeConfigurationUpdate);
            ((ASN1T_E2nodeConfigurationUpdate*)pvalue->value.u.e2nodeConfigurationUpdate)->~ASN1T_E2nodeConfigurationUpdate();
            rtxMemFreePtr (pctxt, (void*)pvalue->value.u.e2nodeConfigurationUpdate);
            pvalue->value.u.e2nodeConfigurationUpdate = 0;
         }
         break;

      case E2AP_ELEMENTARY_PROCEDURES::T_e2connectionUpdate:
         if (0 != pvalue->value.u.e2connectionUpdate) {
            asn1Free_E2connectionUpdate (pctxt, pvalue->value.u.e2connectionUpdate);
            ((ASN1T_E2connectionUpdate*)pvalue->value.u.e2connectionUpdate)->~ASN1T_E2connectionUpdate();
            rtxMemFreePtr (pctxt, (void*)pvalue->value.u.e2connectionUpdate);
            pvalue->value.u.e2connectionUpdate = 0;
         }
         break;

      case E2AP_ELEMENTARY_PROCEDURES::T_reset:
         if (0 != pvalue->value.u.reset) {
            asn1Free_ResetRequest (pctxt, pvalue->value.u.reset);
            ((ASN1T_ResetRequest*)pvalue->value.u.reset)->~ASN1T_ResetRequest();
            rtxMemFreePtr (pctxt, (void*)pvalue->value.u.reset);
            pvalue->value.u.reset = 0;
         }
         break;

      case E2AP_ELEMENTARY_PROCEDURES::T_e2removal:
         if (0 != pvalue->value.u.e2removal) {
            asn1Free_E2RemovalRequest (pctxt, pvalue->value.u.e2removal);
            ((ASN1T_E2RemovalRequest*)pvalue->value.u.e2removal)->~ASN1T_E2RemovalRequest();
            rtxMemFreePtr (pctxt, (void*)pvalue->value.u.e2removal);
            pvalue->value.u.e2removal = 0;
         }
         break;

      case E2AP_ELEMENTARY_PROCEDURES::T_e42setup:
         if (0 != pvalue->value.u.e42setup) {
            asn1Free_E42setupRequest (pctxt, pvalue->value.u.e42setup);
            ((ASN1T_E42setupRequest*)pvalue->value.u.e42setup)->~ASN1T_E42setupRequest();
            rtxMemFreePtr (pctxt, (void*)pvalue->value.u.e42setup);
            pvalue->value.u.e42setup = 0;
         }
         break;

      case E2AP_ELEMENTARY_PROCEDURES::T_e42ricSubscription:
         if (0 != pvalue->value.u.e42ricSubscription) {
            asn1Free_E42RICsubscriptionRequest (pctxt, pvalue->value.u.e42ricSubscription);
            ((ASN1T_E42RICsubscriptionRequest*)pvalue->value.u.e42ricSubscription)->~ASN1T_E42RICsubscriptionRequest();
            rtxMemFreePtr (pctxt, (void*)pvalue->value.u.e42ricSubscription);
            pvalue->value.u.e42ricSubscription = 0;
         }
         break;

      case E2AP_ELEMENTARY_PROCEDURES::T_e42ricSubscriptionDelete:
         if (0 != pvalue->value.u.e42ricSubscriptionDelete) {
            asn1Free_E42RICsubscriptionDeleteRequest (pctxt, pvalue->value.u.e42ricSubscriptionDelete);
            ((ASN1T_E42RICsubscriptionDeleteRequest*)pvalue->value.u.e42ricSubscriptionDelete)->~ASN1T_E42RICsubscriptionDeleteRequest();
            rtxMemFreePtr (pctxt, (void*)pvalue->value.u.e42ricSubscriptionDelete);
            pvalue->value.u.e42ricSubscriptionDelete = 0;
         }
         break;

      case E2AP_ELEMENTARY_PROCEDURES::T_e42ricControl:
         if (0 != pvalue->value.u.e42ricControl) {
            asn1Free_E42RICcontrolRequest (pctxt, pvalue->value.u.e42ricControl);
            ((ASN1T_E42RICcontrolRequest*)pvalue->value.u.e42ricControl)->~ASN1T_E42RICcontrolRequest();
            rtxMemFreePtr (pctxt, (void*)pvalue->value.u.e42ricControl);
            pvalue->value.u.e42ricControl = 0;
         }
         break;

      case E2AP_ELEMENTARY_PROCEDURES::T_ricIndication:
         if (0 != pvalue->value.u.ricIndication) {
            asn1Free_RICindication (pctxt, pvalue->value.u.ricIndication);
            ((ASN1T_RICindication*)pvalue->value.u.ricIndication)->~ASN1T_RICindication();
            rtxMemFreePtr (pctxt, (void*)pvalue->value.u.ricIndication);
            pvalue->value.u.ricIndication = 0;
         }
         break;

      case E2AP_ELEMENTARY_PROCEDURES::T_ricServiceQuery:
         if (0 != pvalue->value.u.ricServiceQuery) {
            asn1Free_RICserviceQuery (pctxt, pvalue->value.u.ricServiceQuery);
            ((ASN1T_RICserviceQuery*)pvalue->value.u.ricServiceQuery)->~ASN1T_RICserviceQuery();
            rtxMemFreePtr (pctxt, (void*)pvalue->value.u.ricServiceQuery);
            pvalue->value.u.ricServiceQuery = 0;
         }
         break;

      case E2AP_ELEMENTARY_PROCEDURES::T_errorIndication:
         if (0 != pvalue->value.u.errorIndication) {
            asn1Free_ErrorIndication (pctxt, pvalue->value.u.errorIndication);
            ((ASN1T_ErrorIndication*)pvalue->value.u.errorIndication)->~ASN1T_ErrorIndication();
            rtxMemFreePtr (pctxt, (void*)pvalue->value.u.errorIndication);
            pvalue->value.u.errorIndication = 0;
         }
         break;

      case E2AP_ELEMENTARY_PROCEDURES::T_ricSubscriptionDeleteRequired:
         if (0 != pvalue->value.u.ricSubscriptionDeleteRequired) {
            asn1Free_RICsubscriptionDeleteRequired (pctxt, pvalue->value.u.ricSubscriptionDeleteRequired);
            ((ASN1T_RICsubscriptionDeleteRequired*)pvalue->value.u.ricSubscriptionDeleteRequired)->~ASN1T_RICsubscriptionDeleteRequired();
            rtxMemFreePtr (pctxt, (void*)pvalue->value.u.ricSubscriptionDeleteRequired);
            pvalue->value.u.ricSubscriptionDeleteRequired = 0;
         }
         break;

      default:;
   }
}

void ASN1C_InitiatingMessage::MemFree ()
{
   asn1Free_InitiatingMessage (getCtxtPtr(), &msgData);
}

/* ASN1T_SuccessfulOutcome */

ASN1T_SuccessfulOutcome* new_ASN1T_SuccessfulOutcome (ASN1CType& ccobj)
{
   void* pdata = ccobj.memAlloc (sizeof(ASN1T_SuccessfulOutcome));
   if (0 == pdata) return 0;
   else return new (pdata) ASN1T_SuccessfulOutcome;
}

void asn1SetTC_SuccessfulOutcome_ricSubscription
   (OSCTXT* pctxt, ASN1T_SuccessfulOutcome* pElem, ASN1T_RICsubscriptionResponse *pvalue)
{
   pElem->procedureCode = 8;
   pElem->criticality = Criticality::reject;
   pElem->value.t = E2AP_ELEMENTARY_PROCEDURES::T_ricSubscription;
   pElem->value.u.ricSubscription = pvalue;
}

void asn1SetTC_SuccessfulOutcome_ricSubscriptionDelete
   (OSCTXT* pctxt, ASN1T_SuccessfulOutcome* pElem, ASN1T_RICsubscriptionDeleteResponse *pvalue)
{
   pElem->procedureCode = 9;
   pElem->criticality = Criticality::reject;
   pElem->value.t = E2AP_ELEMENTARY_PROCEDURES::T_ricSubscriptionDelete;
   pElem->value.u.ricSubscriptionDelete = pvalue;
}

void asn1SetTC_SuccessfulOutcome_ricServiceUpdate
   (OSCTXT* pctxt, ASN1T_SuccessfulOutcome* pElem, ASN1T_RICserviceUpdateAcknowledge *pvalue)
{
   pElem->procedureCode = 7;
   pElem->criticality = Criticality::reject;
   pElem->value.t = E2AP_ELEMENTARY_PROCEDURES::T_ricServiceUpdate;
   pElem->value.u.ricServiceUpdate = pvalue;
}

void asn1SetTC_SuccessfulOutcome_ricControl
   (OSCTXT* pctxt, ASN1T_SuccessfulOutcome* pElem, ASN1T_RICcontrolAcknowledge *pvalue)
{
   pElem->procedureCode = 4;
   pElem->criticality = Criticality::reject;
   pElem->value.t = E2AP_ELEMENTARY_PROCEDURES::T_ricControl;
   pElem->value.u.ricControl = pvalue;
}

void asn1SetTC_SuccessfulOutcome_e2setup
   (OSCTXT* pctxt, ASN1T_SuccessfulOutcome* pElem, ASN1T_E2setupResponse *pvalue)
{
   pElem->procedureCode = 1;
   pElem->criticality = Criticality::reject;
   pElem->value.t = E2AP_ELEMENTARY_PROCEDURES::T_e2setup;
   pElem->value.u.e2setup = pvalue;
}

void asn1SetTC_SuccessfulOutcome_e2nodeConfigurationUpdate
   (OSCTXT* pctxt, ASN1T_SuccessfulOutcome* pElem, ASN1T_E2nodeConfigurationUpdateAcknowledge *pvalue)
{
   pElem->procedureCode = 10;
   pElem->criticality = Criticality::reject;
   pElem->value.t = E2AP_ELEMENTARY_PROCEDURES::T_e2nodeConfigurationUpdate;
   pElem->value.u.e2nodeConfigurationUpdate = pvalue;
}

void asn1SetTC_SuccessfulOutcome_e2connectionUpdate
   (OSCTXT* pctxt, ASN1T_SuccessfulOutcome* pElem, ASN1T_E2connectionUpdateAcknowledge *pvalue)
{
   pElem->procedureCode = 11;
   pElem->criticality = Criticality::reject;
   pElem->value.t = E2AP_ELEMENTARY_PROCEDURES::T_e2connectionUpdate;
   pElem->value.u.e2connectionUpdate = pvalue;
}

void asn1SetTC_SuccessfulOutcome_reset
   (OSCTXT* pctxt, ASN1T_SuccessfulOutcome* pElem, ASN1T_ResetResponse *pvalue)
{
   pElem->procedureCode = 3;
   pElem->criticality = Criticality::reject;
   pElem->value.t = E2AP_ELEMENTARY_PROCEDURES::T_reset;
   pElem->value.u.reset = pvalue;
}

void asn1SetTC_SuccessfulOutcome_e2removal
   (OSCTXT* pctxt, ASN1T_SuccessfulOutcome* pElem, ASN1T_E2RemovalResponse *pvalue)
{
   pElem->procedureCode = 13;
   pElem->criticality = Criticality::reject;
   pElem->value.t = E2AP_ELEMENTARY_PROCEDURES::T_e2removal;
   pElem->value.u.e2removal = pvalue;
}

void asn1SetTC_SuccessfulOutcome_e42setup
   (OSCTXT* pctxt, ASN1T_SuccessfulOutcome* pElem, ASN1T_E42setupResponse *pvalue)
{
   pElem->procedureCode = 14;
   pElem->criticality = Criticality::reject;
   pElem->value.t = E2AP_ELEMENTARY_PROCEDURES::T_e42setup;
   pElem->value.u.e42setup = pvalue;
}

void asn1SetTC_SuccessfulOutcome_e42ricSubscription
   (OSCTXT* pctxt, ASN1T_SuccessfulOutcome* pElem, ASN1T_RICsubscriptionResponse *pvalue)
{
   pElem->procedureCode = 15;
   pElem->criticality = Criticality::reject;
   pElem->value.t = E2AP_ELEMENTARY_PROCEDURES::T_e42ricSubscription;
   pElem->value.u.e42ricSubscription = pvalue;
}

void asn1SetTC_SuccessfulOutcome_e42ricSubscriptionDelete
   (OSCTXT* pctxt, ASN1T_SuccessfulOutcome* pElem, ASN1T_RICsubscriptionDeleteResponse *pvalue)
{
   pElem->procedureCode = 16;
   pElem->criticality = Criticality::reject;
   pElem->value.t = E2AP_ELEMENTARY_PROCEDURES::T_e42ricSubscriptionDelete;
   pElem->value.u.e42ricSubscriptionDelete = pvalue;
}

void asn1SetTC_SuccessfulOutcome_e42ricControl
   (OSCTXT* pctxt, ASN1T_SuccessfulOutcome* pElem, ASN1T_RICcontrolAcknowledge *pvalue)
{
   pElem->procedureCode = 17;
   pElem->criticality = Criticality::reject;
   pElem->value.t = E2AP_ELEMENTARY_PROCEDURES::T_e42ricControl;
   pElem->value.u.e42ricControl = pvalue;
}

ASN1C_SuccessfulOutcome::ASN1C_SuccessfulOutcome
    (ASN1T_SuccessfulOutcome& data) : ASN1CType(), msgData(data)
{
   setRunTimeKey (_rtkey, sizeof(_rtkey));
}

ASN1C_SuccessfulOutcome::ASN1C_SuccessfulOutcome (OSRTMessageBufferIF& msgBuf
   , ASN1T_SuccessfulOutcome& data) : ASN1CType(msgBuf), msgData(data)
{
   setRunTimeKey (_rtkey, sizeof(_rtkey));
}
ASN1C_SuccessfulOutcome::ASN1C_SuccessfulOutcome (OSRTContext &context
   , ASN1T_SuccessfulOutcome& data) : ASN1CType(context), msgData(data)
{
   setRunTimeKey (_rtkey, sizeof(_rtkey));
}


void ASN1C_SuccessfulOutcome::setTC_ricSubscription(
   ASN1T_RICsubscriptionResponse *pvalue)  {
   asn1SetTC_SuccessfulOutcome_ricSubscription(getCtxtPtr(), &msgData, pvalue
      );
}

void ASN1C_SuccessfulOutcome::setTC_ricSubscriptionDelete(
   ASN1T_RICsubscriptionDeleteResponse *pvalue)  {
   asn1SetTC_SuccessfulOutcome_ricSubscriptionDelete(getCtxtPtr(), &msgData, 
      pvalue);
}

void ASN1C_SuccessfulOutcome::setTC_ricServiceUpdate(
   ASN1T_RICserviceUpdateAcknowledge *pvalue)  {
   asn1SetTC_SuccessfulOutcome_ricServiceUpdate(getCtxtPtr(), &msgData, pvalue
      );
}

void ASN1C_SuccessfulOutcome::setTC_ricControl(ASN1T_RICcontrolAcknowledge 
   *pvalue)  {
   asn1SetTC_SuccessfulOutcome_ricControl(getCtxtPtr(), &msgData, pvalue);
}

void ASN1C_SuccessfulOutcome::setTC_e2setup(ASN1T_E2setupResponse *pvalue)  {
   asn1SetTC_SuccessfulOutcome_e2setup(getCtxtPtr(), &msgData, pvalue);
}

void ASN1C_SuccessfulOutcome::setTC_e2nodeConfigurationUpdate(
   ASN1T_E2nodeConfigurationUpdateAcknowledge *pvalue)  {
   asn1SetTC_SuccessfulOutcome_e2nodeConfigurationUpdate(getCtxtPtr(), &msgData
      , pvalue);
}

void ASN1C_SuccessfulOutcome::setTC_e2connectionUpdate(
   ASN1T_E2connectionUpdateAcknowledge *pvalue)  {
   asn1SetTC_SuccessfulOutcome_e2connectionUpdate(getCtxtPtr(), &msgData, 
      pvalue);
}

void ASN1C_SuccessfulOutcome::setTC_reset(ASN1T_ResetResponse *pvalue)  {
   asn1SetTC_SuccessfulOutcome_reset(getCtxtPtr(), &msgData, pvalue);
}

void ASN1C_SuccessfulOutcome::setTC_e2removal(ASN1T_E2RemovalResponse *pvalue)
     {
   asn1SetTC_SuccessfulOutcome_e2removal(getCtxtPtr(), &msgData, pvalue);
}

void ASN1C_SuccessfulOutcome::setTC_e42setup(ASN1T_E42setupResponse *pvalue)
     {
   asn1SetTC_SuccessfulOutcome_e42setup(getCtxtPtr(), &msgData, pvalue);
}

void ASN1C_SuccessfulOutcome::setTC_e42ricSubscription(
   ASN1T_RICsubscriptionResponse *pvalue)  {
   asn1SetTC_SuccessfulOutcome_e42ricSubscription(getCtxtPtr(), &msgData, 
      pvalue);
}

void ASN1C_SuccessfulOutcome::setTC_e42ricSubscriptionDelete(
   ASN1T_RICsubscriptionDeleteResponse *pvalue)  {
   asn1SetTC_SuccessfulOutcome_e42ricSubscriptionDelete(getCtxtPtr(), &msgData
      , pvalue);
}

void ASN1C_SuccessfulOutcome::setTC_e42ricControl(ASN1T_RICcontrolAcknowledge 
   *pvalue)  {
   asn1SetTC_SuccessfulOutcome_e42ricControl(getCtxtPtr(), &msgData, pvalue);
}

ASN1T_SuccessfulOutcome::ASN1T_SuccessfulOutcome ()
{
   OSCRTLMEMSET (&value, 0, sizeof(value));
}

ASN1T_SuccessfulOutcome::~ASN1T_SuccessfulOutcome ()
{
   OSCTXT* pctxt = mpContext.getCtxtPtr();
   if (pctxt != 0 && !rtxMemHeapIsEmpty (pctxt)) {
      asn1Free_SuccessfulOutcome (pctxt, this);
   }
}

int ASN1C_SuccessfulOutcome::EncodeTo (OSRTMessageBufferIF& msgBuf)
{
   int stat = setMsgBuf (msgBuf, TRUE);
   if (stat != 0) return (stat);

   if (msgBuf.isA (OSRTMessageBufferIF::PEREncode)) {
      stat= asn1PE_SuccessfulOutcome (msgBuf.getCtxtPtr(), &msgData);
      ((ASN1PEREncodeBuffer&)msgBuf).byteAlign();
      return stat;
   }
   else if (msgBuf.isA (OSRTMessageBufferIF::JSONEncode)) {
      return asn1JsonEnc_SuccessfulOutcome (msgBuf.getCtxtPtr(), &msgData);
   }
   return RTERR_NOTSUPP;
}

int ASN1C_SuccessfulOutcome::DecodeFrom (OSRTMessageBufferIF& msgBuf, OSBOOL free)
{
   int stat = setMsgBuf (msgBuf, TRUE);
   if (stat != 0) return (stat);

   asn1Init_SuccessfulOutcome (&msgData, free, getCtxtPtr());
   msgData.setContext (msgBuf.getContext());
   if (msgBuf.isA (OSRTMessageBufferIF::PERDecode)) {
      stat = asn1PD_SuccessfulOutcome (msgBuf.getCtxtPtr(), &msgData);
      ((ASN1PERDecodeBuffer&)msgBuf).byteAlign();
      return stat;
   }
   else if (msgBuf.isA (OSRTMessageBufferIF::JSONDecode)) {
      return asn1JsonDec_SuccessfulOutcome (msgBuf.getCtxtPtr(), &msgData);
   }
   return RTERR_NOTSUPP;
}

int asn1Init_SuccessfulOutcome (ASN1T_SuccessfulOutcome* pvalue, 
   OSBOOL free, OSCTXT *pctxt)
{
   if (0 == pvalue) return RTERR_NULLPTR;
   OSCRTLMEMSET (&pvalue->value, 0, sizeof(pvalue->value));
   return 0;
}

void asn1Free_SuccessfulOutcome (OSCTXT *pctxt, 
   ASN1T_SuccessfulOutcome* pvalue)
{
   if (0 == pvalue) return;
   switch (pvalue->value.t) {
      case E2AP_ELEMENTARY_PROCEDURES::T_ricSubscription:
         if (0 != pvalue->value.u.ricSubscription) {
            asn1Free_RICsubscriptionResponse (pctxt, pvalue->value.u.ricSubscription);
            ((ASN1T_RICsubscriptionResponse*)pvalue->value.u.ricSubscription)->~ASN1T_RICsubscriptionResponse();
            rtxMemFreePtr (pctxt, (void*)pvalue->value.u.ricSubscription);
            pvalue->value.u.ricSubscription = 0;
         }
         break;

      case E2AP_ELEMENTARY_PROCEDURES::T_ricSubscriptionDelete:
         if (0 != pvalue->value.u.ricSubscriptionDelete) {
            asn1Free_RICsubscriptionDeleteResponse (pctxt, pvalue->value.u.ricSubscriptionDelete);
            ((ASN1T_RICsubscriptionDeleteResponse*)pvalue->value.u.ricSubscriptionDelete)->~ASN1T_RICsubscriptionDeleteResponse();
            rtxMemFreePtr (pctxt, (void*)pvalue->value.u.ricSubscriptionDelete);
            pvalue->value.u.ricSubscriptionDelete = 0;
         }
         break;

      case E2AP_ELEMENTARY_PROCEDURES::T_ricServiceUpdate:
         if (0 != pvalue->value.u.ricServiceUpdate) {
            asn1Free_RICserviceUpdateAcknowledge (pctxt, pvalue->value.u.ricServiceUpdate);
            ((ASN1T_RICserviceUpdateAcknowledge*)pvalue->value.u.ricServiceUpdate)->~ASN1T_RICserviceUpdateAcknowledge();
            rtxMemFreePtr (pctxt, (void*)pvalue->value.u.ricServiceUpdate);
            pvalue->value.u.ricServiceUpdate = 0;
         }
         break;

      case E2AP_ELEMENTARY_PROCEDURES::T_ricControl:
         if (0 != pvalue->value.u.ricControl) {
            asn1Free_RICcontrolAcknowledge (pctxt, pvalue->value.u.ricControl);
            ((ASN1T_RICcontrolAcknowledge*)pvalue->value.u.ricControl)->~ASN1T_RICcontrolAcknowledge();
            rtxMemFreePtr (pctxt, (void*)pvalue->value.u.ricControl);
            pvalue->value.u.ricControl = 0;
         }
         break;

      case E2AP_ELEMENTARY_PROCEDURES::T_e2setup:
         if (0 != pvalue->value.u.e2setup) {
            asn1Free_E2setupResponse (pctxt, pvalue->value.u.e2setup);
            ((ASN1T_E2setupResponse*)pvalue->value.u.e2setup)->~ASN1T_E2setupResponse();
            rtxMemFreePtr (pctxt, (void*)pvalue->value.u.e2setup);
            pvalue->value.u.e2setup = 0;
         }
         break;

      case E2AP_ELEMENTARY_PROCEDURES::T_e2nodeConfigurationUpdate:
         if (0 != pvalue->value.u.e2nodeConfigurationUpdate) {
            asn1Free_E2nodeConfigurationUpdateAcknowledge (pctxt, pvalue->value.u.e2nodeConfigurationUpdate);
            ((ASN1T_E2nodeConfigurationUpdateAcknowledge*)pvalue->value.u.e2nodeConfigurationUpdate)->~ASN1T_E2nodeConfigurationUpdateAcknowledge();
            rtxMemFreePtr (pctxt, (void*)pvalue->value.u.e2nodeConfigurationUpdate);
            pvalue->value.u.e2nodeConfigurationUpdate = 0;
         }
         break;

      case E2AP_ELEMENTARY_PROCEDURES::T_e2connectionUpdate:
         if (0 != pvalue->value.u.e2connectionUpdate) {
            asn1Free_E2connectionUpdateAcknowledge (pctxt, pvalue->value.u.e2connectionUpdate);
            ((ASN1T_E2connectionUpdateAcknowledge*)pvalue->value.u.e2connectionUpdate)->~ASN1T_E2connectionUpdateAcknowledge();
            rtxMemFreePtr (pctxt, (void*)pvalue->value.u.e2connectionUpdate);
            pvalue->value.u.e2connectionUpdate = 0;
         }
         break;

      case E2AP_ELEMENTARY_PROCEDURES::T_reset:
         if (0 != pvalue->value.u.reset) {
            asn1Free_ResetResponse (pctxt, pvalue->value.u.reset);
            ((ASN1T_ResetResponse*)pvalue->value.u.reset)->~ASN1T_ResetResponse();
            rtxMemFreePtr (pctxt, (void*)pvalue->value.u.reset);
            pvalue->value.u.reset = 0;
         }
         break;

      case E2AP_ELEMENTARY_PROCEDURES::T_e2removal:
         if (0 != pvalue->value.u.e2removal) {
            asn1Free_E2RemovalResponse (pctxt, pvalue->value.u.e2removal);
            ((ASN1T_E2RemovalResponse*)pvalue->value.u.e2removal)->~ASN1T_E2RemovalResponse();
            rtxMemFreePtr (pctxt, (void*)pvalue->value.u.e2removal);
            pvalue->value.u.e2removal = 0;
         }
         break;

      case E2AP_ELEMENTARY_PROCEDURES::T_e42setup:
         if (0 != pvalue->value.u.e42setup) {
            asn1Free_E42setupResponse (pctxt, pvalue->value.u.e42setup);
            ((ASN1T_E42setupResponse*)pvalue->value.u.e42setup)->~ASN1T_E42setupResponse();
            rtxMemFreePtr (pctxt, (void*)pvalue->value.u.e42setup);
            pvalue->value.u.e42setup = 0;
         }
         break;

      case E2AP_ELEMENTARY_PROCEDURES::T_e42ricSubscription:
         if (0 != pvalue->value.u.e42ricSubscription) {
            asn1Free_RICsubscriptionResponse (pctxt, pvalue->value.u.e42ricSubscription);
            ((ASN1T_RICsubscriptionResponse*)pvalue->value.u.e42ricSubscription)->~ASN1T_RICsubscriptionResponse();
            rtxMemFreePtr (pctxt, (void*)pvalue->value.u.e42ricSubscription);
            pvalue->value.u.e42ricSubscription = 0;
         }
         break;

      case E2AP_ELEMENTARY_PROCEDURES::T_e42ricSubscriptionDelete:
         if (0 != pvalue->value.u.e42ricSubscriptionDelete) {
            asn1Free_RICsubscriptionDeleteResponse (pctxt, pvalue->value.u.e42ricSubscriptionDelete);
            ((ASN1T_RICsubscriptionDeleteResponse*)pvalue->value.u.e42ricSubscriptionDelete)->~ASN1T_RICsubscriptionDeleteResponse();
            rtxMemFreePtr (pctxt, (void*)pvalue->value.u.e42ricSubscriptionDelete);
            pvalue->value.u.e42ricSubscriptionDelete = 0;
         }
         break;

      case E2AP_ELEMENTARY_PROCEDURES::T_e42ricControl:
         if (0 != pvalue->value.u.e42ricControl) {
            asn1Free_RICcontrolAcknowledge (pctxt, pvalue->value.u.e42ricControl);
            ((ASN1T_RICcontrolAcknowledge*)pvalue->value.u.e42ricControl)->~ASN1T_RICcontrolAcknowledge();
            rtxMemFreePtr (pctxt, (void*)pvalue->value.u.e42ricControl);
            pvalue->value.u.e42ricControl = 0;
         }
         break;

      default:;
   }
}

void ASN1C_SuccessfulOutcome::MemFree ()
{
   asn1Free_SuccessfulOutcome (getCtxtPtr(), &msgData);
}

/* ASN1T_UnsuccessfulOutcome */

ASN1T_UnsuccessfulOutcome* new_ASN1T_UnsuccessfulOutcome (ASN1CType& ccobj)
{
   void* pdata = ccobj.memAlloc (sizeof(ASN1T_UnsuccessfulOutcome));
   if (0 == pdata) return 0;
   else return new (pdata) ASN1T_UnsuccessfulOutcome;
}

void asn1SetTC_UnsuccessfulOutcome_ricSubscription
   (OSCTXT* pctxt, ASN1T_UnsuccessfulOutcome* pElem, ASN1T_RICsubscriptionFailure *pvalue)
{
   pElem->procedureCode = 8;
   pElem->criticality = Criticality::reject;
   pElem->value.t = E2AP_ELEMENTARY_PROCEDURES::T_ricSubscription;
   pElem->value.u.ricSubscription = pvalue;
}

void asn1SetTC_UnsuccessfulOutcome_ricSubscriptionDelete
   (OSCTXT* pctxt, ASN1T_UnsuccessfulOutcome* pElem, ASN1T_RICsubscriptionDeleteFailure *pvalue)
{
   pElem->procedureCode = 9;
   pElem->criticality = Criticality::reject;
   pElem->value.t = E2AP_ELEMENTARY_PROCEDURES::T_ricSubscriptionDelete;
   pElem->value.u.ricSubscriptionDelete = pvalue;
}

void asn1SetTC_UnsuccessfulOutcome_ricServiceUpdate
   (OSCTXT* pctxt, ASN1T_UnsuccessfulOutcome* pElem, ASN1T_RICserviceUpdateFailure *pvalue)
{
   pElem->procedureCode = 7;
   pElem->criticality = Criticality::reject;
   pElem->value.t = E2AP_ELEMENTARY_PROCEDURES::T_ricServiceUpdate;
   pElem->value.u.ricServiceUpdate = pvalue;
}

void asn1SetTC_UnsuccessfulOutcome_ricControl
   (OSCTXT* pctxt, ASN1T_UnsuccessfulOutcome* pElem, ASN1T_RICcontrolFailure *pvalue)
{
   pElem->procedureCode = 4;
   pElem->criticality = Criticality::reject;
   pElem->value.t = E2AP_ELEMENTARY_PROCEDURES::T_ricControl;
   pElem->value.u.ricControl = pvalue;
}

void asn1SetTC_UnsuccessfulOutcome_e2setup
   (OSCTXT* pctxt, ASN1T_UnsuccessfulOutcome* pElem, ASN1T_E2setupFailure *pvalue)
{
   pElem->procedureCode = 1;
   pElem->criticality = Criticality::reject;
   pElem->value.t = E2AP_ELEMENTARY_PROCEDURES::T_e2setup;
   pElem->value.u.e2setup = pvalue;
}

void asn1SetTC_UnsuccessfulOutcome_e2nodeConfigurationUpdate
   (OSCTXT* pctxt, ASN1T_UnsuccessfulOutcome* pElem, ASN1T_E2nodeConfigurationUpdateFailure *pvalue)
{
   pElem->procedureCode = 10;
   pElem->criticality = Criticality::reject;
   pElem->value.t = E2AP_ELEMENTARY_PROCEDURES::T_e2nodeConfigurationUpdate;
   pElem->value.u.e2nodeConfigurationUpdate = pvalue;
}

void asn1SetTC_UnsuccessfulOutcome_e2connectionUpdate
   (OSCTXT* pctxt, ASN1T_UnsuccessfulOutcome* pElem, ASN1T_E2connectionUpdateFailure *pvalue)
{
   pElem->procedureCode = 11;
   pElem->criticality = Criticality::reject;
   pElem->value.t = E2AP_ELEMENTARY_PROCEDURES::T_e2connectionUpdate;
   pElem->value.u.e2connectionUpdate = pvalue;
}

void asn1SetTC_UnsuccessfulOutcome_e2removal
   (OSCTXT* pctxt, ASN1T_UnsuccessfulOutcome* pElem, ASN1T_E2RemovalFailure *pvalue)
{
   pElem->procedureCode = 13;
   pElem->criticality = Criticality::reject;
   pElem->value.t = E2AP_ELEMENTARY_PROCEDURES::T_e2removal;
   pElem->value.u.e2removal = pvalue;
}

void asn1SetTC_UnsuccessfulOutcome_e42setup
   (OSCTXT* pctxt, ASN1T_UnsuccessfulOutcome* pElem, ASN1T_E2setupFailure *pvalue)
{
   pElem->procedureCode = 14;
   pElem->criticality = Criticality::reject;
   pElem->value.t = E2AP_ELEMENTARY_PROCEDURES::T_e42setup;
   pElem->value.u.e42setup = pvalue;
}

void asn1SetTC_UnsuccessfulOutcome_e42ricSubscription
   (OSCTXT* pctxt, ASN1T_UnsuccessfulOutcome* pElem, ASN1T_RICsubscriptionFailure *pvalue)
{
   pElem->procedureCode = 15;
   pElem->criticality = Criticality::reject;
   pElem->value.t = E2AP_ELEMENTARY_PROCEDURES::T_e42ricSubscription;
   pElem->value.u.e42ricSubscription = pvalue;
}

void asn1SetTC_UnsuccessfulOutcome_e42ricSubscriptionDelete
   (OSCTXT* pctxt, ASN1T_UnsuccessfulOutcome* pElem, ASN1T_RICsubscriptionDeleteFailure *pvalue)
{
   pElem->procedureCode = 16;
   pElem->criticality = Criticality::reject;
   pElem->value.t = E2AP_ELEMENTARY_PROCEDURES::T_e42ricSubscriptionDelete;
   pElem->value.u.e42ricSubscriptionDelete = pvalue;
}

void asn1SetTC_UnsuccessfulOutcome_e42ricControl
   (OSCTXT* pctxt, ASN1T_UnsuccessfulOutcome* pElem, ASN1T_RICcontrolFailure *pvalue)
{
   pElem->procedureCode = 17;
   pElem->criticality = Criticality::reject;
   pElem->value.t = E2AP_ELEMENTARY_PROCEDURES::T_e42ricControl;
   pElem->value.u.e42ricControl = pvalue;
}

ASN1C_UnsuccessfulOutcome::ASN1C_UnsuccessfulOutcome
    (ASN1T_UnsuccessfulOutcome& data) : ASN1CType(), msgData(data)
{
   setRunTimeKey (_rtkey, sizeof(_rtkey));
}

ASN1C_UnsuccessfulOutcome::ASN1C_UnsuccessfulOutcome (
   OSRTMessageBufferIF& msgBuf, ASN1T_UnsuccessfulOutcome& data) : 
   ASN1CType(msgBuf), msgData(data)
{
   setRunTimeKey (_rtkey, sizeof(_rtkey));
}
ASN1C_UnsuccessfulOutcome::ASN1C_UnsuccessfulOutcome (OSRTContext &context
   , ASN1T_UnsuccessfulOutcome& data) : ASN1CType(context), msgData(data)
{
   setRunTimeKey (_rtkey, sizeof(_rtkey));
}


void ASN1C_UnsuccessfulOutcome::setTC_ricSubscription(
   ASN1T_RICsubscriptionFailure *pvalue)  {
   asn1SetTC_UnsuccessfulOutcome_ricSubscription(getCtxtPtr(), &msgData, pvalue
      );
}

void ASN1C_UnsuccessfulOutcome::setTC_ricSubscriptionDelete(
   ASN1T_RICsubscriptionDeleteFailure *pvalue)  {
   asn1SetTC_UnsuccessfulOutcome_ricSubscriptionDelete(getCtxtPtr(), &msgData, 
      pvalue);
}

void ASN1C_UnsuccessfulOutcome::setTC_ricServiceUpdate(
   ASN1T_RICserviceUpdateFailure *pvalue)  {
   asn1SetTC_UnsuccessfulOutcome_ricServiceUpdate(getCtxtPtr(), &msgData, 
      pvalue);
}

void ASN1C_UnsuccessfulOutcome::setTC_ricControl(ASN1T_RICcontrolFailure 
   *pvalue)  {
   asn1SetTC_UnsuccessfulOutcome_ricControl(getCtxtPtr(), &msgData, pvalue);
}

void ASN1C_UnsuccessfulOutcome::setTC_e2setup(ASN1T_E2setupFailure *pvalue)  {
   asn1SetTC_UnsuccessfulOutcome_e2setup(getCtxtPtr(), &msgData, pvalue);
}

void ASN1C_UnsuccessfulOutcome::setTC_e2nodeConfigurationUpdate(
   ASN1T_E2nodeConfigurationUpdateFailure *pvalue)  {
   asn1SetTC_UnsuccessfulOutcome_e2nodeConfigurationUpdate(getCtxtPtr(), &msgData
      , pvalue);
}

void ASN1C_UnsuccessfulOutcome::setTC_e2connectionUpdate(
   ASN1T_E2connectionUpdateFailure *pvalue)  {
   asn1SetTC_UnsuccessfulOutcome_e2connectionUpdate(getCtxtPtr(), &msgData, 
      pvalue);
}

void ASN1C_UnsuccessfulOutcome::setTC_e2removal(ASN1T_E2RemovalFailure *pvalue)
     {
   asn1SetTC_UnsuccessfulOutcome_e2removal(getCtxtPtr(), &msgData, pvalue);
}

void ASN1C_UnsuccessfulOutcome::setTC_e42setup(ASN1T_E2setupFailure *pvalue)
     {
   asn1SetTC_UnsuccessfulOutcome_e42setup(getCtxtPtr(), &msgData, pvalue);
}

void ASN1C_UnsuccessfulOutcome::setTC_e42ricSubscription(
   ASN1T_RICsubscriptionFailure *pvalue)  {
   asn1SetTC_UnsuccessfulOutcome_e42ricSubscription(getCtxtPtr(), &msgData, 
      pvalue);
}

void ASN1C_UnsuccessfulOutcome::setTC_e42ricSubscriptionDelete(
   ASN1T_RICsubscriptionDeleteFailure *pvalue)  {
   asn1SetTC_UnsuccessfulOutcome_e42ricSubscriptionDelete(getCtxtPtr(), &msgData
      , pvalue);
}

void ASN1C_UnsuccessfulOutcome::setTC_e42ricControl(ASN1T_RICcontrolFailure 
   *pvalue)  {
   asn1SetTC_UnsuccessfulOutcome_e42ricControl(getCtxtPtr(), &msgData, pvalue
      );
}

ASN1T_UnsuccessfulOutcome::ASN1T_UnsuccessfulOutcome ()
{
   OSCRTLMEMSET (&value, 0, sizeof(value));
}

ASN1T_UnsuccessfulOutcome::~ASN1T_UnsuccessfulOutcome ()
{
   OSCTXT* pctxt = mpContext.getCtxtPtr();
   if (pctxt != 0 && !rtxMemHeapIsEmpty (pctxt)) {
      asn1Free_UnsuccessfulOutcome (pctxt, this);
   }
}

int ASN1C_UnsuccessfulOutcome::EncodeTo (OSRTMessageBufferIF& msgBuf)
{
   int stat = setMsgBuf (msgBuf, TRUE);
   if (stat != 0) return (stat);

   if (msgBuf.isA (OSRTMessageBufferIF::PEREncode)) {
      stat= asn1PE_UnsuccessfulOutcome (msgBuf.getCtxtPtr(), &msgData);
      ((ASN1PEREncodeBuffer&)msgBuf).byteAlign();
      return stat;
   }
   else if (msgBuf.isA (OSRTMessageBufferIF::JSONEncode)) {
      return asn1JsonEnc_UnsuccessfulOutcome (msgBuf.getCtxtPtr(), &msgData);
   }
   return RTERR_NOTSUPP;
}

int ASN1C_UnsuccessfulOutcome::DecodeFrom (OSRTMessageBufferIF& msgBuf, OSBOOL free)
{
   int stat = setMsgBuf (msgBuf, TRUE);
   if (stat != 0) return (stat);

   asn1Init_UnsuccessfulOutcome (&msgData, free, getCtxtPtr());
   msgData.setContext (msgBuf.getContext());
   if (msgBuf.isA (OSRTMessageBufferIF::PERDecode)) {
      stat = asn1PD_UnsuccessfulOutcome (msgBuf.getCtxtPtr(), &msgData);
      ((ASN1PERDecodeBuffer&)msgBuf).byteAlign();
      return stat;
   }
   else if (msgBuf.isA (OSRTMessageBufferIF::JSONDecode)) {
      return asn1JsonDec_UnsuccessfulOutcome (msgBuf.getCtxtPtr(), &msgData);
   }
   return RTERR_NOTSUPP;
}

int asn1Init_UnsuccessfulOutcome (ASN1T_UnsuccessfulOutcome* pvalue, 
   OSBOOL free, OSCTXT *pctxt)
{
   if (0 == pvalue) return RTERR_NULLPTR;
   OSCRTLMEMSET (&pvalue->value, 0, sizeof(pvalue->value));
   return 0;
}

void asn1Free_UnsuccessfulOutcome (OSCTXT *pctxt, 
   ASN1T_UnsuccessfulOutcome* pvalue)
{
   if (0 == pvalue) return;
   switch (pvalue->value.t) {
      case E2AP_ELEMENTARY_PROCEDURES::T_ricSubscription:
         if (0 != pvalue->value.u.ricSubscription) {
            asn1Free_RICsubscriptionFailure (pctxt, pvalue->value.u.ricSubscription);
            ((ASN1T_RICsubscriptionFailure*)pvalue->value.u.ricSubscription)->~ASN1T_RICsubscriptionFailure();
            rtxMemFreePtr (pctxt, (void*)pvalue->value.u.ricSubscription);
            pvalue->value.u.ricSubscription = 0;
         }
         break;

      case E2AP_ELEMENTARY_PROCEDURES::T_ricSubscriptionDelete:
         if (0 != pvalue->value.u.ricSubscriptionDelete) {
            asn1Free_RICsubscriptionDeleteFailure (pctxt, pvalue->value.u.ricSubscriptionDelete);
            ((ASN1T_RICsubscriptionDeleteFailure*)pvalue->value.u.ricSubscriptionDelete)->~ASN1T_RICsubscriptionDeleteFailure();
            rtxMemFreePtr (pctxt, (void*)pvalue->value.u.ricSubscriptionDelete);
            pvalue->value.u.ricSubscriptionDelete = 0;
         }
         break;

      case E2AP_ELEMENTARY_PROCEDURES::T_ricServiceUpdate:
         if (0 != pvalue->value.u.ricServiceUpdate) {
            asn1Free_RICserviceUpdateFailure (pctxt, pvalue->value.u.ricServiceUpdate);
            ((ASN1T_RICserviceUpdateFailure*)pvalue->value.u.ricServiceUpdate)->~ASN1T_RICserviceUpdateFailure();
            rtxMemFreePtr (pctxt, (void*)pvalue->value.u.ricServiceUpdate);
            pvalue->value.u.ricServiceUpdate = 0;
         }
         break;

      case E2AP_ELEMENTARY_PROCEDURES::T_ricControl:
         if (0 != pvalue->value.u.ricControl) {
            asn1Free_RICcontrolFailure (pctxt, pvalue->value.u.ricControl);
            ((ASN1T_RICcontrolFailure*)pvalue->value.u.ricControl)->~ASN1T_RICcontrolFailure();
            rtxMemFreePtr (pctxt, (void*)pvalue->value.u.ricControl);
            pvalue->value.u.ricControl = 0;
         }
         break;

      case E2AP_ELEMENTARY_PROCEDURES::T_e2setup:
         if (0 != pvalue->value.u.e2setup) {
            asn1Free_E2setupFailure (pctxt, pvalue->value.u.e2setup);
            ((ASN1T_E2setupFailure*)pvalue->value.u.e2setup)->~ASN1T_E2setupFailure();
            rtxMemFreePtr (pctxt, (void*)pvalue->value.u.e2setup);
            pvalue->value.u.e2setup = 0;
         }
         break;

      case E2AP_ELEMENTARY_PROCEDURES::T_e2nodeConfigurationUpdate:
         if (0 != pvalue->value.u.e2nodeConfigurationUpdate) {
            asn1Free_E2nodeConfigurationUpdateFailure (pctxt, pvalue->value.u.e2nodeConfigurationUpdate);
            ((ASN1T_E2nodeConfigurationUpdateFailure*)pvalue->value.u.e2nodeConfigurationUpdate)->~ASN1T_E2nodeConfigurationUpdateFailure();
            rtxMemFreePtr (pctxt, (void*)pvalue->value.u.e2nodeConfigurationUpdate);
            pvalue->value.u.e2nodeConfigurationUpdate = 0;
         }
         break;

      case E2AP_ELEMENTARY_PROCEDURES::T_e2connectionUpdate:
         if (0 != pvalue->value.u.e2connectionUpdate) {
            asn1Free_E2connectionUpdateFailure (pctxt, pvalue->value.u.e2connectionUpdate);
            ((ASN1T_E2connectionUpdateFailure*)pvalue->value.u.e2connectionUpdate)->~ASN1T_E2connectionUpdateFailure();
            rtxMemFreePtr (pctxt, (void*)pvalue->value.u.e2connectionUpdate);
            pvalue->value.u.e2connectionUpdate = 0;
         }
         break;

      case E2AP_ELEMENTARY_PROCEDURES::T_e2removal:
         if (0 != pvalue->value.u.e2removal) {
            asn1Free_E2RemovalFailure (pctxt, pvalue->value.u.e2removal);
            ((ASN1T_E2RemovalFailure*)pvalue->value.u.e2removal)->~ASN1T_E2RemovalFailure();
            rtxMemFreePtr (pctxt, (void*)pvalue->value.u.e2removal);
            pvalue->value.u.e2removal = 0;
         }
         break;

      case E2AP_ELEMENTARY_PROCEDURES::T_e42setup:
         if (0 != pvalue->value.u.e42setup) {
            asn1Free_E2setupFailure (pctxt, pvalue->value.u.e42setup);
            ((ASN1T_E2setupFailure*)pvalue->value.u.e42setup)->~ASN1T_E2setupFailure();
            rtxMemFreePtr (pctxt, (void*)pvalue->value.u.e42setup);
            pvalue->value.u.e42setup = 0;
         }
         break;

      case E2AP_ELEMENTARY_PROCEDURES::T_e42ricSubscription:
         if (0 != pvalue->value.u.e42ricSubscription) {
            asn1Free_RICsubscriptionFailure (pctxt, pvalue->value.u.e42ricSubscription);
            ((ASN1T_RICsubscriptionFailure*)pvalue->value.u.e42ricSubscription)->~ASN1T_RICsubscriptionFailure();
            rtxMemFreePtr (pctxt, (void*)pvalue->value.u.e42ricSubscription);
            pvalue->value.u.e42ricSubscription = 0;
         }
         break;

      case E2AP_ELEMENTARY_PROCEDURES::T_e42ricSubscriptionDelete:
         if (0 != pvalue->value.u.e42ricSubscriptionDelete) {
            asn1Free_RICsubscriptionDeleteFailure (pctxt, pvalue->value.u.e42ricSubscriptionDelete);
            ((ASN1T_RICsubscriptionDeleteFailure*)pvalue->value.u.e42ricSubscriptionDelete)->~ASN1T_RICsubscriptionDeleteFailure();
            rtxMemFreePtr (pctxt, (void*)pvalue->value.u.e42ricSubscriptionDelete);
            pvalue->value.u.e42ricSubscriptionDelete = 0;
         }
         break;

      case E2AP_ELEMENTARY_PROCEDURES::T_e42ricControl:
         if (0 != pvalue->value.u.e42ricControl) {
            asn1Free_RICcontrolFailure (pctxt, pvalue->value.u.e42ricControl);
            ((ASN1T_RICcontrolFailure*)pvalue->value.u.e42ricControl)->~ASN1T_RICcontrolFailure();
            rtxMemFreePtr (pctxt, (void*)pvalue->value.u.e42ricControl);
            pvalue->value.u.e42ricControl = 0;
         }
         break;

      default:;
   }
}

void ASN1C_UnsuccessfulOutcome::MemFree ()
{
   asn1Free_UnsuccessfulOutcome (getCtxtPtr(), &msgData);
}

/* ASN1T_E2AP_PDU */

ASN1T_E2AP_PDU* new_ASN1T_E2AP_PDU (ASN1CType& ccobj)
{
   void* pdata = ccobj.memAlloc (sizeof(ASN1T_E2AP_PDU));
   if (0 == pdata) return 0;
   else return new (pdata) ASN1T_E2AP_PDU;
}

ASN1C_E2AP_PDU::ASN1C_E2AP_PDU (ASN1T_E2AP_PDU& data) : 
   ASN1CType(), msgData(data)
{
   setRunTimeKey (_rtkey, sizeof(_rtkey));
}

ASN1C_E2AP_PDU::ASN1C_E2AP_PDU (OSRTMessageBufferIF& msgBuf
   , ASN1T_E2AP_PDU& data) : ASN1CType(msgBuf), msgData(data)
{
   setRunTimeKey (_rtkey, sizeof(_rtkey));
}
ASN1C_E2AP_PDU::ASN1C_E2AP_PDU (OSRTContext &context, ASN1T_E2AP_PDU& data) : 
   ASN1CType(context), msgData(data)
{
   setRunTimeKey (_rtkey, sizeof(_rtkey));
}


ASN1T_E2AP_PDU::~ASN1T_E2AP_PDU ()
{
   OSCTXT* pctxt = mpContext.getCtxtPtr();
   if (pctxt != 0 && !rtxMemHeapIsEmpty (pctxt)) {
      asn1Free_E2AP_PDU (pctxt, this);
   }
}

int ASN1C_E2AP_PDU::EncodeTo (OSRTMessageBufferIF& msgBuf)
{
   int stat = setMsgBuf (msgBuf, TRUE);
   if (stat != 0) return (stat);

   if (msgBuf.isA (OSRTMessageBufferIF::PEREncode)) {
      stat= asn1PE_E2AP_PDU (msgBuf.getCtxtPtr(), &msgData);
      ((ASN1PEREncodeBuffer&)msgBuf).byteAlign();
      return stat;
   }
   else if (msgBuf.isA (OSRTMessageBufferIF::JSONEncode)) {
      return asn1JsonEnc_E2AP_PDU (msgBuf.getCtxtPtr(), &msgData);
   }
   return RTERR_NOTSUPP;
}

int ASN1C_E2AP_PDU::DecodeFrom (OSRTMessageBufferIF& msgBuf, OSBOOL free)
{
   int stat = setMsgBuf (msgBuf, TRUE);
   if (stat != 0) return (stat);

   asn1Init_E2AP_PDU (&msgData, free, getCtxtPtr());
   msgData.setContext (msgBuf.getContext());
   if (msgBuf.isA (OSRTMessageBufferIF::PERDecode)) {
      stat = asn1PD_E2AP_PDU (msgBuf.getCtxtPtr(), &msgData);
      ((ASN1PERDecodeBuffer&)msgBuf).byteAlign();
      return stat;
   }
   else if (msgBuf.isA (OSRTMessageBufferIF::JSONDecode)) {
      return asn1JsonDec_E2AP_PDU (msgBuf.getCtxtPtr(), &msgData);
   }
   return RTERR_NOTSUPP;
}

int asn1Init_E2AP_PDU (ASN1T_E2AP_PDU* pvalue, OSBOOL free, OSCTXT *pctxt)
{
   if (0 == pvalue) return RTERR_NULLPTR;
   if (free) {
      asn1Free_E2AP_PDU (pctxt, pvalue);
   }
   else {
      pvalue->t = 0;
      OSCRTLMEMSET (&pvalue->u, 0, sizeof(pvalue->u));
   }
   return 0;
}

void asn1Free_E2AP_PDU (OSCTXT *pctxt, ASN1T_E2AP_PDU* pvalue)
{
   if (0 == pvalue) return;
   switch (pvalue->t) {
      case 0: break; /* no choice; nothing to free */
      case 1:
         if (0 != pvalue->u.initiatingMessage) {
            asn1Free_InitiatingMessage (pctxt, pvalue->u.initiatingMessage);
            ((ASN1T_InitiatingMessage*)pvalue->u.initiatingMessage)->~ASN1T_InitiatingMessage();
            rtxMemFreePtr (pctxt, (void*)pvalue->u.initiatingMessage);
            pvalue->u.initiatingMessage = 0;
         }
         break;

      case 2:
         if (0 != pvalue->u.successfulOutcome) {
            asn1Free_SuccessfulOutcome (pctxt, pvalue->u.successfulOutcome);
            ((ASN1T_SuccessfulOutcome*)pvalue->u.successfulOutcome)->~ASN1T_SuccessfulOutcome();
            rtxMemFreePtr (pctxt, (void*)pvalue->u.successfulOutcome);
            pvalue->u.successfulOutcome = 0;
         }
         break;

      case 3:
         if (0 != pvalue->u.unsuccessfulOutcome) {
            asn1Free_UnsuccessfulOutcome (pctxt, pvalue->u.unsuccessfulOutcome);
            ((ASN1T_UnsuccessfulOutcome*)pvalue->u.unsuccessfulOutcome)->~ASN1T_UnsuccessfulOutcome();
            rtxMemFreePtr (pctxt, (void*)pvalue->u.unsuccessfulOutcome);
            pvalue->u.unsuccessfulOutcome = 0;
         }
         break;

      default:
         if (0 != pvalue->u.extElem1) {
            if (!rtxCtxtTestFlag (pctxt, ASN1FASTCOPY)) {
               rtxMemFreePtr (pctxt, (void*)pvalue->u.extElem1->data);
               pvalue->u.extElem1->data = 0;
            }
            rtxMemFreePtr (pctxt, (void*)pvalue->u.extElem1);
            pvalue->u.extElem1 = 0;
         }
   }
}

void ASN1C_E2AP_PDU::MemFree ()
{
   asn1Free_E2AP_PDU (getCtxtPtr(), &msgData);
}

