/**
 * This file was generated by the Objective Systems ASN1C Compiler
 * (http://www.obj-sys.com).  Version: 7.8.2.5, Date: 27-Jun-2025.
 *
 * Command:  asn1c ./asn1files/E2SM-KPM-v05.00.asn ./asn1files/asn_flexric/e2sm_rc_v1_03_modified.asn ./asn1files/asn_flexric/e42ap_v2_03.asn -cpp -json -per -depends -events -oh ./src -i asn1files -i asn1files/asn_flexric -o ./src -genprint -printformat details -genprttostr -printformat details -stream -table-unions -gentest -trace
 */
#include "E2AP-CommonDataTypes.h"
#include "rtxsrc/rtxCharStr.h"
#include "rtxsrc/rtxDiag.h"

EXTERN int asn1PE_ProcedureCode (OSCTXT* pctxt, ASN1T_ProcedureCode value)
{
   int stat = 0;

   RTXCTXTPUSHTYPENAME (pctxt, "ProcedureCode");

   RTDIAGSTRM2 (pctxt, "asn1PE_ProcedureCode: start\n");

   stat = pe_ConsUnsigned(pctxt, value,  0,  255);
   if (stat != 0) return LOG_RTERR (pctxt, stat);

   RTDIAGSTRM2 (pctxt, "asn1PE_ProcedureCode: end\n");

   RTXCTXTPOPTYPENAME (pctxt);

   return (stat);
}

EXTERN int asn1JsonEnc_ProcedureCode (OSCTXT *pctxt, ASN1T_ProcedureCode *pvalue)
{
   int stat = 0;

   stat = rtJsonEncUIntValue (pctxt, *pvalue);

   return stat;
}

EXTERN int asn1PE_Criticality (OSCTXT* pctxt, ASN1T_Criticality value)
{
   int stat = 0;

   RTXCTXTPUSHTYPENAME (pctxt, "Criticality");

   RTDIAGSTRM2 (pctxt, "asn1PE_Criticality: start\n");

   if (value >= 3) {
      {
         int lstat = Asn1ErrorHandler::invoke (pctxt, 0, RTERR_INVENUM);
         if (lstat != 0)  {
            return LOG_RTERR (pctxt, lstat);
         }
      }
   }
   PU_NEWFIELD(pctxt, "data");

   stat = rtxEncBits(pctxt, value, 2);
   if (stat != 0) return LOG_RTERR (pctxt, stat);

   PU_SETBITCOUNT(pctxt);

   RTDIAGSTRM2 (pctxt, "asn1PE_Criticality: end\n");

   RTXCTXTPOPTYPENAME (pctxt);

   return (stat);
}

EXTERN int asn1JsonEnc_Criticality (OSCTXT *pctxt, ASN1T_Criticality *pvalue)
{
   int stat = 0;

   if (*pvalue >= 3) {
      int lstat = Asn1ErrorHandler::invoke (pctxt, 0, RTERR_INVENUM);
      if (lstat != 0)  {
         return LOG_RTERR (pctxt, lstat);
      }
   }
   {
      OSINT32 enumVarIdx_;
      const OSUTF8CHAR* enumIdString_;
      enumVarIdx_ = *pvalue;

      if (enumVarIdx_ >= 0 && enumVarIdx_ < ASN1T_Criticality_ENUMTABSIZE) {
         enumIdString_ = ASN1T_Criticality_ENUMTAB[ASN1T_Criticality_ENUMTAB[enumVarIdx_].transidx].name;
      }
      else
         return LOG_RTERRNEW(pctxt, RTERR_INVENUM);
      stat = rtJsonEncStringValue (pctxt, enumIdString_);
      if ( stat < 0 ) return LOG_RTERR(pctxt, stat);
   }

   return stat;
}

EXTERN int asn1PE_ProtocolIE_ID (OSCTXT* pctxt, ASN1T_ProtocolIE_ID value)
{
   int stat = 0;

   RTXCTXTPUSHTYPENAME (pctxt, "ProtocolIE-ID");

   RTDIAGSTRM2 (pctxt, "asn1PE_ProtocolIE_ID: start\n");

   stat = pe_ConsUnsigned(pctxt, value,  0,  65535);
   if (stat != 0) return LOG_RTERR (pctxt, stat);

   RTDIAGSTRM2 (pctxt, "asn1PE_ProtocolIE_ID: end\n");

   RTXCTXTPOPTYPENAME (pctxt);

   return (stat);
}

EXTERN int asn1JsonEnc_ProtocolIE_ID (OSCTXT *pctxt, ASN1T_ProtocolIE_ID *pvalue)
{
   int stat = 0;

   stat = rtJsonEncUIntValue (pctxt, *pvalue);

   return stat;
}

EXTERN int asn1PE_TriggeringMessage (OSCTXT* pctxt, ASN1T_TriggeringMessage value)
{
   int stat = 0;

   RTXCTXTPUSHTYPENAME (pctxt, "TriggeringMessage");

   RTDIAGSTRM2 (pctxt, "asn1PE_TriggeringMessage: start\n");

   if (value >= 3) {
      {
         int lstat = Asn1ErrorHandler::invoke (pctxt, 0, RTERR_INVENUM);
         if (lstat != 0)  {
            return LOG_RTERR (pctxt, lstat);
         }
      }
   }
   PU_NEWFIELD(pctxt, "data");

   stat = rtxEncBits(pctxt, value, 2);
   if (stat != 0) return LOG_RTERR (pctxt, stat);

   PU_SETBITCOUNT(pctxt);

   RTDIAGSTRM2 (pctxt, "asn1PE_TriggeringMessage: end\n");

   RTXCTXTPOPTYPENAME (pctxt);

   return (stat);
}

EXTERN int asn1JsonEnc_TriggeringMessage (OSCTXT *pctxt, ASN1T_TriggeringMessage *pvalue)
{
   int stat = 0;

   if (*pvalue >= 3) {
      int lstat = Asn1ErrorHandler::invoke (pctxt, 0, RTERR_INVENUM);
      if (lstat != 0)  {
         return LOG_RTERR (pctxt, lstat);
      }
   }
   {
      OSINT32 enumVarIdx_;
      const OSUTF8CHAR* enumIdString_;
      enumVarIdx_ = *pvalue;

      if (enumVarIdx_ >= 0 && enumVarIdx_ < ASN1T_TriggeringMessage_ENUMTABSIZE) {
         enumIdString_ = ASN1T_TriggeringMessage_ENUMTAB[ASN1T_TriggeringMessage_ENUMTAB[enumVarIdx_].transidx].name;
      }
      else
         return LOG_RTERRNEW(pctxt, RTERR_INVENUM);
      stat = rtJsonEncStringValue (pctxt, enumIdString_);
      if ( stat < 0 ) return LOG_RTERR(pctxt, stat);
   }

   return stat;
}

EXTERN int asn1PE_Presence (OSCTXT* pctxt, ASN1T_Presence value)
{
   int stat = 0;

   RTXCTXTPUSHTYPENAME (pctxt, "Presence");

   RTDIAGSTRM2 (pctxt, "asn1PE_Presence: start\n");

   if (value >= 3) {
      {
         int lstat = Asn1ErrorHandler::invoke (pctxt, 0, RTERR_INVENUM);
         if (lstat != 0)  {
            return LOG_RTERR (pctxt, lstat);
         }
      }
   }
   PU_NEWFIELD(pctxt, "data");

   stat = rtxEncBits(pctxt, value, 2);
   if (stat != 0) return LOG_RTERR (pctxt, stat);

   PU_SETBITCOUNT(pctxt);

   RTDIAGSTRM2 (pctxt, "asn1PE_Presence: end\n");

   RTXCTXTPOPTYPENAME (pctxt);

   return (stat);
}

EXTERN int asn1JsonEnc_Presence (OSCTXT *pctxt, ASN1T_Presence *pvalue)
{
   int stat = 0;

   if (*pvalue >= 3) {
      int lstat = Asn1ErrorHandler::invoke (pctxt, 0, RTERR_INVENUM);
      if (lstat != 0)  {
         return LOG_RTERR (pctxt, lstat);
      }
   }
   {
      OSINT32 enumVarIdx_;
      const OSUTF8CHAR* enumIdString_;
      enumVarIdx_ = *pvalue;

      if (enumVarIdx_ >= 0 && enumVarIdx_ < ASN1T_Presence_ENUMTABSIZE) {
         enumIdString_ = ASN1T_Presence_ENUMTAB[ASN1T_Presence_ENUMTAB[enumVarIdx_].transidx].name;
      }
      else
         return LOG_RTERRNEW(pctxt, RTERR_INVENUM);
      stat = rtJsonEncStringValue (pctxt, enumIdString_);
      if ( stat < 0 ) return LOG_RTERR(pctxt, stat);
   }

   return stat;
}

