/**
 * This file was generated by the Objective Systems ASN1C Compiler
 * (http://www.obj-sys.com).  Version: 7.8.2.5, Date: 27-Jun-2025.
 *
 * Command:  asn1c ./asn1files/E2SM-KPM-v05.00.asn ./asn1files/asn_flexric/e2sm_rc_v1_03_modified.asn ./asn1files/asn_flexric/e42ap_v2_03.asn -cpp -json -per -depends -events -oh ./src -i asn1files -i asn1files/asn_flexric -o ./src -genprint -printformat details -genprttostr -printformat details -stream -table-unions -gentest -trace
 */
#include <new>
#include "E2AP-IEs.h"
#include "E2AP-Constants.h"
#include "rtxsrc/rtxDiag.h"

/* ASN1T_RICrequestID */

ASN1T_RICrequestID* new_ASN1T_RICrequestID (ASN1CType& ccobj)
{
   void* pdata = ccobj.memAlloc (sizeof(ASN1T_RICrequestID));
   if (0 == pdata) return 0;
   else return new (pdata) ASN1T_RICrequestID;
}

int asn1Init_RICrequestID (ASN1T_RICrequestID* pvalue, 
   OSBOOL free, OSCTXT *pctxt)
{
   if (0 == pvalue) return RTERR_NULLPTR;
   rtxDListFastInit (&pvalue->extElem1);
   return 0;
}

void asn1Free_RICrequestID (OSCTXT *pctxt, ASN1T_RICrequestID* pvalue)
{
   if (0 == pvalue) return;
   rtxMemFreeOpenSeqExt (pctxt, &pvalue->extElem1);
}

/* ASN1T_RANfunctionID */

ASN1T_RANfunctionID* new_ASN1T_RANfunctionID (ASN1CType& ccobj)
{
   void* pdata = ccobj.memAlloc (sizeof(ASN1T_RANfunctionID));
   if (0 == pdata) return 0;
   else return new (pdata) ASN1T_RANfunctionID;
}

/* ASN1T_RICeventTriggerDefinition */

ASN1T_RICeventTriggerDefinition* 
   new_ASN1T_RICeventTriggerDefinition (ASN1CType& ccobj)
{
   void* pdata = ccobj.memAlloc (sizeof(ASN1T_RICeventTriggerDefinition));
   if (0 == pdata) return 0;
   else return new (pdata) ASN1T_RICeventTriggerDefinition;
}

int asn1Init_RICeventTriggerDefinition (
   ASN1T_RICeventTriggerDefinition* pvalue, OSBOOL free, OSCTXT *pctxt)
{
   if (0 == pvalue) return RTERR_NULLPTR;
   pvalue->numocts = 0;
   pvalue->data = 0;
   return 0;
}

void asn1Free_RICeventTriggerDefinition (OSCTXT *pctxt, 
   ASN1T_RICeventTriggerDefinition* pvalue)
{
   if (0 == pvalue) return;
   if (pvalue->numocts > 0) {
      rtxMemFreePtr (pctxt, (void*)pvalue->data);
      pvalue->numocts = 0;
      pvalue->data = 0;
   }
}

/* ASN1T_RICactionID */

ASN1T_RICactionID* new_ASN1T_RICactionID (ASN1CType& ccobj)
{
   void* pdata = ccobj.memAlloc (sizeof(ASN1T_RICactionID));
   if (0 == pdata) return 0;
   else return new (pdata) ASN1T_RICactionID;
}

/* ASN1T_RICactionType */

const OSEnumItem ASN1T_RICactionType_ENUMTAB[] = {
   { OSUTF8("insert"), 1, 6, 2 },
   { OSUTF8("policy"), 2, 6, 0 },
   { OSUTF8("report"), 0, 6, 1 }
} ;

const OSUTF8CHAR* ASN1T_RICactionType_ToString (OSINT32 value)
{
   OSINT32 idx = value;

   if (idx >= 0 && idx < ASN1T_RICactionType_ENUMTABSIZE) {
      return ASN1T_RICactionType_ENUMTAB
         [ASN1T_RICactionType_ENUMTAB[idx].transidx].name;
   }
   else
      return OSUTF8("_UNKNOWN_");
}

int ASN1T_RICactionType_ToEnum (OSCTXT* pctxt,
   const OSUTF8CHAR* value, ASN1T_RICactionType* pvalue)
{
   OSSIZE valueLen = rtxUTF8LenBytes (value);
   return ASN1T_RICactionType_ToEnum2 (pctxt, value, valueLen, pvalue);
}

int ASN1T_RICactionType_ToEnum2 (OSCTXT* pctxt,
   const OSUTF8CHAR* value, OSSIZE valueLen, ASN1T_RICactionType* pvalue)
{
   OSINT32 idx = rtxLookupEnum (value, valueLen, ASN1T_RICactionType_ENUMTAB, 
      ASN1T_RICactionType_ENUMTABSIZE);

   if (idx >= 0) {
      *pvalue = (ASN1T_RICactionType)ASN1T_RICactionType_ENUMTAB[idx].value;
      return 0;
   }
   else {
      rtxErrAddStrParm (pctxt, (const char*)value);
      return LOG_RTERR (pctxt, RTERR_INVENUM);
   }
}

ASN1T_RICactionType* new_ASN1T_RICactionType (ASN1CType& ccobj)
{
   void* pdata = ccobj.memAlloc (sizeof(ASN1T_RICactionType));
   if (0 == pdata) return 0;
   else return new (pdata) ASN1T_RICactionType;
}

/* ASN1T_RICactionDefinition */

ASN1T_RICactionDefinition* new_ASN1T_RICactionDefinition (ASN1CType& ccobj)
{
   void* pdata = ccobj.memAlloc (sizeof(ASN1T_RICactionDefinition));
   if (0 == pdata) return 0;
   else return new (pdata) ASN1T_RICactionDefinition;
}

int asn1Init_RICactionDefinition (ASN1T_RICactionDefinition* pvalue, 
   OSBOOL free, OSCTXT *pctxt)
{
   if (0 == pvalue) return RTERR_NULLPTR;
   pvalue->numocts = 0;
   pvalue->data = 0;
   return 0;
}

void asn1Free_RICactionDefinition (OSCTXT *pctxt, 
   ASN1T_RICactionDefinition* pvalue)
{
   if (0 == pvalue) return;
   if (pvalue->numocts > 0) {
      rtxMemFreePtr (pctxt, (void*)pvalue->data);
      pvalue->numocts = 0;
      pvalue->data = 0;
   }
}

/* ASN1T_RICsubsequentActionType */

const OSEnumItem ASN1T_RICsubsequentActionType_ENUMTAB[] = {
   { OSUTF8("continue"), 0, 8, 0 },
   { OSUTF8("wait"), 1, 4, 1 }
} ;

const OSUTF8CHAR* ASN1T_RICsubsequentActionType_ToString (OSINT32 value)
{
   OSINT32 idx = value;

   if (idx >= 0 && idx < ASN1T_RICsubsequentActionType_ENUMTABSIZE) {
      return ASN1T_RICsubsequentActionType_ENUMTAB
         [ASN1T_RICsubsequentActionType_ENUMTAB[idx].transidx].name;
   }
   else
      return OSUTF8("_UNKNOWN_");
}

int ASN1T_RICsubsequentActionType_ToEnum (OSCTXT* pctxt,
   const OSUTF8CHAR* value, ASN1T_RICsubsequentActionType* pvalue)
{
   OSSIZE valueLen = rtxUTF8LenBytes (value);
   return ASN1T_RICsubsequentActionType_ToEnum2 (pctxt, value, valueLen, pvalue);
}

int ASN1T_RICsubsequentActionType_ToEnum2 (OSCTXT* pctxt,
   const OSUTF8CHAR* value, OSSIZE valueLen, 
      ASN1T_RICsubsequentActionType* pvalue)
{
   OSINT32 idx = rtxLookupEnum (value, valueLen, 
      ASN1T_RICsubsequentActionType_ENUMTAB, 
      ASN1T_RICsubsequentActionType_ENUMTABSIZE);

   if (idx >= 0) {
      *pvalue = (ASN1T_RICsubsequentActionType)
         ASN1T_RICsubsequentActionType_ENUMTAB[idx].value;
      return 0;
   }
   else {
      rtxErrAddStrParm (pctxt, (const char*)value);
      return LOG_RTERR (pctxt, RTERR_INVENUM);
   }
}

ASN1T_RICsubsequentActionType* 
   new_ASN1T_RICsubsequentActionType (ASN1CType& ccobj)
{
   void* pdata = ccobj.memAlloc (sizeof(ASN1T_RICsubsequentActionType));
   if (0 == pdata) return 0;
   else return new (pdata) ASN1T_RICsubsequentActionType;
}

/* ASN1T_RICtimeToWait */

const OSEnumItem ASN1T_RICtimeToWait_ENUMTAB[] = {
   { OSUTF8("w100ms"), 8, 6, 3 },
   { OSUTF8("w10ms"), 3, 5, 8 },
   { OSUTF8("w10s"), 14, 4, 14 },
   { OSUTF8("w1ms"), 0, 4, 1 },
   { OSUTF8("w1s"), 11, 3, 6 },
   { OSUTF8("w200ms"), 9, 6, 10 },
   { OSUTF8("w20ms"), 4, 5, 11 },
   { OSUTF8("w20s"), 15, 4, 13 },
   { OSUTF8("w2ms"), 1, 4, 0 },
   { OSUTF8("w2s"), 12, 3, 5 },
   { OSUTF8("w30ms"), 5, 5, 12 },
   { OSUTF8("w40ms"), 6, 5, 4 },
   { OSUTF8("w500ms"), 10, 6, 9 },
   { OSUTF8("w50ms"), 7, 5, 15 },
   { OSUTF8("w5ms"), 2, 4, 2 },
   { OSUTF8("w5s"), 13, 3, 7 },
   { OSUTF8("w60s"), 16, 4, 16 }
} ;

const OSUTF8CHAR* ASN1T_RICtimeToWait_ToString (OSINT32 value)
{
   OSINT32 idx = value;

   if (idx >= 0 && idx < ASN1T_RICtimeToWait_ENUMTABSIZE) {
      return ASN1T_RICtimeToWait_ENUMTAB
         [ASN1T_RICtimeToWait_ENUMTAB[idx].transidx].name;
   }
   else
      return OSUTF8("_UNKNOWN_");
}

int ASN1T_RICtimeToWait_ToEnum (OSCTXT* pctxt,
   const OSUTF8CHAR* value, ASN1T_RICtimeToWait* pvalue)
{
   OSSIZE valueLen = rtxUTF8LenBytes (value);
   return ASN1T_RICtimeToWait_ToEnum2 (pctxt, value, valueLen, pvalue);
}

int ASN1T_RICtimeToWait_ToEnum2 (OSCTXT* pctxt,
   const OSUTF8CHAR* value, OSSIZE valueLen, ASN1T_RICtimeToWait* pvalue)
{
   OSINT32 idx = rtxLookupEnum (value, valueLen, ASN1T_RICtimeToWait_ENUMTAB, 
      ASN1T_RICtimeToWait_ENUMTABSIZE);

   if (idx >= 0) {
      *pvalue = (ASN1T_RICtimeToWait)ASN1T_RICtimeToWait_ENUMTAB[idx].value;
      return 0;
   }
   else {
      rtxErrAddStrParm (pctxt, (const char*)value);
      return LOG_RTERR (pctxt, RTERR_INVENUM);
   }
}

ASN1T_RICtimeToWait* new_ASN1T_RICtimeToWait (ASN1CType& ccobj)
{
   void* pdata = ccobj.memAlloc (sizeof(ASN1T_RICtimeToWait));
   if (0 == pdata) return 0;
   else return new (pdata) ASN1T_RICtimeToWait;
}

/* ASN1T_RICsubsequentAction */

ASN1T_RICsubsequentAction* new_ASN1T_RICsubsequentAction (ASN1CType& ccobj)
{
   void* pdata = ccobj.memAlloc (sizeof(ASN1T_RICsubsequentAction));
   if (0 == pdata) return 0;
   else return new (pdata) ASN1T_RICsubsequentAction;
}

int asn1Init_RICsubsequentAction (ASN1T_RICsubsequentAction* pvalue, 
   OSBOOL free, OSCTXT *pctxt)
{
   if (0 == pvalue) return RTERR_NULLPTR;
   rtxDListFastInit (&pvalue->extElem1);
   return 0;
}

void asn1Free_RICsubsequentAction (OSCTXT *pctxt, 
   ASN1T_RICsubsequentAction* pvalue)
{
   if (0 == pvalue) return;
   rtxMemFreeOpenSeqExt (pctxt, &pvalue->extElem1);
}

/* ASN1T_TransactionID */

ASN1T_TransactionID* new_ASN1T_TransactionID (ASN1CType& ccobj)
{
   void* pdata = ccobj.memAlloc (sizeof(ASN1T_TransactionID));
   if (0 == pdata) return 0;
   else return new (pdata) ASN1T_TransactionID;
}

/* ASN1T_RANfunctionDefinition */

ASN1T_RANfunctionDefinition* new_ASN1T_RANfunctionDefinition (ASN1CType& ccobj)
{
   void* pdata = ccobj.memAlloc (sizeof(ASN1T_RANfunctionDefinition));
   if (0 == pdata) return 0;
   else return new (pdata) ASN1T_RANfunctionDefinition;
}

int asn1Init_RANfunctionDefinition (ASN1T_RANfunctionDefinition* pvalue, 
   OSBOOL free, OSCTXT *pctxt)
{
   if (0 == pvalue) return RTERR_NULLPTR;
   pvalue->numocts = 0;
   pvalue->data = 0;
   return 0;
}

void asn1Free_RANfunctionDefinition (OSCTXT *pctxt, 
   ASN1T_RANfunctionDefinition* pvalue)
{
   if (0 == pvalue) return;
   if (pvalue->numocts > 0) {
      rtxMemFreePtr (pctxt, (void*)pvalue->data);
      pvalue->numocts = 0;
      pvalue->data = 0;
   }
}

/* ASN1T_RANfunctionRevision */

ASN1T_RANfunctionRevision* new_ASN1T_RANfunctionRevision (ASN1CType& ccobj)
{
   void* pdata = ccobj.memAlloc (sizeof(ASN1T_RANfunctionRevision));
   if (0 == pdata) return 0;
   else return new (pdata) ASN1T_RANfunctionRevision;
}

/* ASN1T_RANfunctionOID */

void asn1Free_RANfunctionOID (OSCTXT *pctxt, ASN1T_RANfunctionOID pvalue)
{
   if (0 == pvalue) return;
   rtxMemFreePtr (pctxt, (void*)pvalue);
   pvalue = 0;
}

/* ASN1T_RICcallProcessID */

ASN1T_RICcallProcessID* new_ASN1T_RICcallProcessID (ASN1CType& ccobj)
{
   void* pdata = ccobj.memAlloc (sizeof(ASN1T_RICcallProcessID));
   if (0 == pdata) return 0;
   else return new (pdata) ASN1T_RICcallProcessID;
}

int asn1Init_RICcallProcessID (ASN1T_RICcallProcessID* pvalue, 
   OSBOOL free, OSCTXT *pctxt)
{
   if (0 == pvalue) return RTERR_NULLPTR;
   pvalue->numocts = 0;
   pvalue->data = 0;
   return 0;
}

void asn1Free_RICcallProcessID (OSCTXT *pctxt, ASN1T_RICcallProcessID* pvalue)
{
   if (0 == pvalue) return;
   if (pvalue->numocts > 0) {
      rtxMemFreePtr (pctxt, (void*)pvalue->data);
      pvalue->numocts = 0;
      pvalue->data = 0;
   }
}

/* ASN1T_RICcontrolHeader */

ASN1T_RICcontrolHeader* new_ASN1T_RICcontrolHeader (ASN1CType& ccobj)
{
   void* pdata = ccobj.memAlloc (sizeof(ASN1T_RICcontrolHeader));
   if (0 == pdata) return 0;
   else return new (pdata) ASN1T_RICcontrolHeader;
}

int asn1Init_RICcontrolHeader (ASN1T_RICcontrolHeader* pvalue, 
   OSBOOL free, OSCTXT *pctxt)
{
   if (0 == pvalue) return RTERR_NULLPTR;
   pvalue->numocts = 0;
   pvalue->data = 0;
   return 0;
}

void asn1Free_RICcontrolHeader (OSCTXT *pctxt, ASN1T_RICcontrolHeader* pvalue)
{
   if (0 == pvalue) return;
   if (pvalue->numocts > 0) {
      rtxMemFreePtr (pctxt, (void*)pvalue->data);
      pvalue->numocts = 0;
      pvalue->data = 0;
   }
}

/* ASN1T_RICcontrolMessage */

ASN1T_RICcontrolMessage* new_ASN1T_RICcontrolMessage (ASN1CType& ccobj)
{
   void* pdata = ccobj.memAlloc (sizeof(ASN1T_RICcontrolMessage));
   if (0 == pdata) return 0;
   else return new (pdata) ASN1T_RICcontrolMessage;
}

int asn1Init_RICcontrolMessage (ASN1T_RICcontrolMessage* pvalue, 
   OSBOOL free, OSCTXT *pctxt)
{
   if (0 == pvalue) return RTERR_NULLPTR;
   pvalue->numocts = 0;
   pvalue->data = 0;
   return 0;
}

void asn1Free_RICcontrolMessage (OSCTXT *pctxt, 
   ASN1T_RICcontrolMessage* pvalue)
{
   if (0 == pvalue) return;
   if (pvalue->numocts > 0) {
      rtxMemFreePtr (pctxt, (void*)pvalue->data);
      pvalue->numocts = 0;
      pvalue->data = 0;
   }
}

/* ASN1T_RICcontrolAckRequest */

const OSEnumItem ASN1T_RICcontrolAckRequest_ENUMTAB[] = {
   { OSUTF8("ack"), 1, 3, 1 },
   { OSUTF8("noAck"), 0, 5, 0 }
} ;

const OSUTF8CHAR* ASN1T_RICcontrolAckRequest_ToString (OSINT32 value)
{
   OSINT32 idx = value;

   if (idx >= 0 && idx < ASN1T_RICcontrolAckRequest_ENUMTABSIZE) {
      return ASN1T_RICcontrolAckRequest_ENUMTAB
         [ASN1T_RICcontrolAckRequest_ENUMTAB[idx].transidx].name;
   }
   else
      return OSUTF8("_UNKNOWN_");
}

int ASN1T_RICcontrolAckRequest_ToEnum (OSCTXT* pctxt,
   const OSUTF8CHAR* value, ASN1T_RICcontrolAckRequest* pvalue)
{
   OSSIZE valueLen = rtxUTF8LenBytes (value);
   return ASN1T_RICcontrolAckRequest_ToEnum2 (pctxt, value, valueLen, pvalue);
}

int ASN1T_RICcontrolAckRequest_ToEnum2 (OSCTXT* pctxt,
   const OSUTF8CHAR* value, OSSIZE valueLen, 
      ASN1T_RICcontrolAckRequest* pvalue)
{
   OSINT32 idx = rtxLookupEnum (value, valueLen, 
      ASN1T_RICcontrolAckRequest_ENUMTAB, 
      ASN1T_RICcontrolAckRequest_ENUMTABSIZE);

   if (idx >= 0) {
      *pvalue = (ASN1T_RICcontrolAckRequest)
         ASN1T_RICcontrolAckRequest_ENUMTAB[idx].value;
      return 0;
   }
   else {
      rtxErrAddStrParm (pctxt, (const char*)value);
      return LOG_RTERR (pctxt, RTERR_INVENUM);
   }
}

ASN1T_RICcontrolAckRequest* new_ASN1T_RICcontrolAckRequest (ASN1CType& ccobj)
{
   void* pdata = ccobj.memAlloc (sizeof(ASN1T_RICcontrolAckRequest));
   if (0 == pdata) return 0;
   else return new (pdata) ASN1T_RICcontrolAckRequest;
}

/* ASN1T_PLMN_Identity */

ASN1T_PLMN_Identity* new_ASN1T_PLMN_Identity (ASN1CType& ccobj)
{
   void* pdata = ccobj.memAlloc (sizeof(ASN1T_PLMN_Identity));
   if (0 == pdata) return 0;
   else return new (pdata) ASN1T_PLMN_Identity;
}

int asn1Init_PLMN_Identity (ASN1T_PLMN_Identity* pvalue, 
   OSBOOL free, OSCTXT *pctxt)
{
   if (0 == pvalue) return RTERR_NULLPTR;
   pvalue->numocts = 0;
   return 0;
}

/* ASN1T_GNB_ID_Choice */

ASN1T_GNB_ID_Choice* new_ASN1T_GNB_ID_Choice (ASN1CType& ccobj)
{
   void* pdata = ccobj.memAlloc (sizeof(ASN1T_GNB_ID_Choice));
   if (0 == pdata) return 0;
   else return new (pdata) ASN1T_GNB_ID_Choice;
}

int asn1Init_GNB_ID_Choice (ASN1T_GNB_ID_Choice* pvalue, 
   OSBOOL free, OSCTXT *pctxt)
{
   if (0 == pvalue) return RTERR_NULLPTR;
   if (free) {
      asn1Free_GNB_ID_Choice (pctxt, pvalue);
   }
   else {
      pvalue->t = 0;
      OSCRTLMEMSET (&pvalue->u, 0, sizeof(pvalue->u));
   }
   return 0;
}

void asn1Free_GNB_ID_Choice (OSCTXT *pctxt, ASN1T_GNB_ID_Choice* pvalue)
{
   if (0 == pvalue) return;
   switch (pvalue->t) {
      case 0: break; /* no choice; nothing to free */
      case 1:
         if (0 != pvalue->u.gnb_ID) {
            rtxMemFreePtr (pctxt, (void*)pvalue->u.gnb_ID);
            pvalue->u.gnb_ID = 0;
         }
         break;

      default:
         if (0 != pvalue->u.extElem1) {
            if (!rtxCtxtTestFlag (pctxt, ASN1FASTCOPY)) {
               rtxMemFreePtr (pctxt, (void*)pvalue->u.extElem1->data);
               pvalue->u.extElem1->data = 0;
            }
            rtxMemFreePtr (pctxt, (void*)pvalue->u.extElem1);
            pvalue->u.extElem1 = 0;
         }
   }
}

/* ASN1T_GlobalgNB_ID */

ASN1T_GlobalgNB_ID* new_ASN1T_GlobalgNB_ID (ASN1CType& ccobj)
{
   void* pdata = ccobj.memAlloc (sizeof(ASN1T_GlobalgNB_ID));
   if (0 == pdata) return 0;
   else return new (pdata) ASN1T_GlobalgNB_ID;
}

int asn1Init_GlobalgNB_ID (ASN1T_GlobalgNB_ID* pvalue, 
   OSBOOL free, OSCTXT *pctxt)
{
   if (0 == pvalue) return RTERR_NULLPTR;
   asn1Init_PLMN_Identity (&pvalue->plmn_id, free, pctxt);
   asn1Init_GNB_ID_Choice (&pvalue->gnb_id, free, pctxt);
   rtxDListFastInit (&pvalue->extElem1);
   return 0;
}

void asn1Free_GlobalgNB_ID (OSCTXT *pctxt, ASN1T_GlobalgNB_ID* pvalue)
{
   if (0 == pvalue) return;
   asn1Free_GNB_ID_Choice (pctxt, &pvalue->gnb_id);
   rtxMemFreeOpenSeqExt (pctxt, &pvalue->extElem1);
}

/* ASN1T_ENGNB_ID */

ASN1T_ENGNB_ID* new_ASN1T_ENGNB_ID (ASN1CType& ccobj)
{
   void* pdata = ccobj.memAlloc (sizeof(ASN1T_ENGNB_ID));
   if (0 == pdata) return 0;
   else return new (pdata) ASN1T_ENGNB_ID;
}

int asn1Init_ENGNB_ID (ASN1T_ENGNB_ID* pvalue, OSBOOL free, OSCTXT *pctxt)
{
   if (0 == pvalue) return RTERR_NULLPTR;
   if (free) {
      asn1Free_ENGNB_ID (pctxt, pvalue);
   }
   else {
      pvalue->t = 0;
      OSCRTLMEMSET (&pvalue->u, 0, sizeof(pvalue->u));
   }
   return 0;
}

void asn1Free_ENGNB_ID (OSCTXT *pctxt, ASN1T_ENGNB_ID* pvalue)
{
   if (0 == pvalue) return;
   switch (pvalue->t) {
      case 0: break; /* no choice; nothing to free */
      case 1:
         if (0 != pvalue->u.gNB_ID) {
            rtxMemFreePtr (pctxt, (void*)pvalue->u.gNB_ID);
            pvalue->u.gNB_ID = 0;
         }
         break;

      default:
         if (0 != pvalue->u.extElem1) {
            if (!rtxCtxtTestFlag (pctxt, ASN1FASTCOPY)) {
               rtxMemFreePtr (pctxt, (void*)pvalue->u.extElem1->data);
               pvalue->u.extElem1->data = 0;
            }
            rtxMemFreePtr (pctxt, (void*)pvalue->u.extElem1);
            pvalue->u.extElem1 = 0;
         }
   }
}

/* ASN1T_E2AP_IEs_GlobalenGNB_ID */

ASN1T_E2AP_IEs_GlobalenGNB_ID* 
   new_ASN1T_E2AP_IEs_GlobalenGNB_ID (ASN1CType& ccobj)
{
   void* pdata = ccobj.memAlloc (sizeof(ASN1T_E2AP_IEs_GlobalenGNB_ID));
   if (0 == pdata) return 0;
   else return new (pdata) ASN1T_E2AP_IEs_GlobalenGNB_ID;
}

int asn1Init_E2AP_IEs_GlobalenGNB_ID (ASN1T_E2AP_IEs_GlobalenGNB_ID* pvalue, 
   OSBOOL free, OSCTXT *pctxt)
{
   if (0 == pvalue) return RTERR_NULLPTR;
   asn1Init_PLMN_Identity (&pvalue->pLMN_Identity, free, pctxt);
   asn1Init_ENGNB_ID (&pvalue->gNB_ID, free, pctxt);
   rtxDListFastInit (&pvalue->extElem1);
   return 0;
}

void asn1Free_E2AP_IEs_GlobalenGNB_ID (OSCTXT *pctxt, 
   ASN1T_E2AP_IEs_GlobalenGNB_ID* pvalue)
{
   if (0 == pvalue) return;
   asn1Free_ENGNB_ID (pctxt, &pvalue->gNB_ID);
   rtxMemFreeOpenSeqExt (pctxt, &pvalue->extElem1);
}

/* ASN1T_E2AP_IEs_GNB_CU_UP_ID */

ASN1T_E2AP_IEs_GNB_CU_UP_ID* new_ASN1T_E2AP_IEs_GNB_CU_UP_ID (ASN1CType& ccobj)
{
   void* pdata = ccobj.memAlloc (sizeof(ASN1T_E2AP_IEs_GNB_CU_UP_ID));
   if (0 == pdata) return 0;
   else return new (pdata) ASN1T_E2AP_IEs_GNB_CU_UP_ID;
}

/* ASN1T_E2AP_IEs_GNB_DU_ID */

ASN1T_E2AP_IEs_GNB_DU_ID* new_ASN1T_E2AP_IEs_GNB_DU_ID (ASN1CType& ccobj)
{
   void* pdata = ccobj.memAlloc (sizeof(ASN1T_E2AP_IEs_GNB_DU_ID));
   if (0 == pdata) return 0;
   else return new (pdata) ASN1T_E2AP_IEs_GNB_DU_ID;
}

/* ASN1T_GlobalE2node_gNB_ID */

ASN1T_GlobalE2node_gNB_ID* new_ASN1T_GlobalE2node_gNB_ID (ASN1CType& ccobj)
{
   void* pdata = ccobj.memAlloc (sizeof(ASN1T_GlobalE2node_gNB_ID));
   if (0 == pdata) return 0;
   else return new (pdata) ASN1T_GlobalE2node_gNB_ID;
}

ASN1T_GlobalE2node_gNB_ID::ASN1T_GlobalE2node_gNB_ID ()
{
   m.global_en_gNB_IDPresent = 0;
   m.gNB_CU_UP_IDPresent = 0;
   m.gNB_DU_IDPresent = 0;
}

int asn1Init_GlobalE2node_gNB_ID (ASN1T_GlobalE2node_gNB_ID* pvalue, 
   OSBOOL free, OSCTXT *pctxt)
{
   if (0 == pvalue) return RTERR_NULLPTR;
   OSCRTLMEMSET (&pvalue->m, 0, sizeof (pvalue->m));
   asn1Init_GlobalgNB_ID (&pvalue->global_gNB_ID, free, pctxt);
   asn1Init_E2AP_IEs_GlobalenGNB_ID (&pvalue->global_en_gNB_ID, free, pctxt);
   rtxDListFastInit (&pvalue->extElem1);
   return 0;
}

void asn1Free_GlobalE2node_gNB_ID (OSCTXT *pctxt, 
   ASN1T_GlobalE2node_gNB_ID* pvalue)
{
   if (0 == pvalue) return;
   asn1Free_GlobalgNB_ID (pctxt, &pvalue->global_gNB_ID);
   if (pvalue->m.global_en_gNB_IDPresent) {
      asn1Free_E2AP_IEs_GlobalenGNB_ID (pctxt, &pvalue->global_en_gNB_ID);
   }
   rtxMemFreeOpenSeqExt (pctxt, &pvalue->extElem1);
}

/* ASN1T_GlobalE2node_en_gNB_ID */

ASN1T_GlobalE2node_en_gNB_ID* 
   new_ASN1T_GlobalE2node_en_gNB_ID (ASN1CType& ccobj)
{
   void* pdata = ccobj.memAlloc (sizeof(ASN1T_GlobalE2node_en_gNB_ID));
   if (0 == pdata) return 0;
   else return new (pdata) ASN1T_GlobalE2node_en_gNB_ID;
}

ASN1T_GlobalE2node_en_gNB_ID::ASN1T_GlobalE2node_en_gNB_ID ()
{
   m.en_gNB_CU_UP_IDPresent = 0;
   m.en_gNB_DU_IDPresent = 0;
}

int asn1Init_GlobalE2node_en_gNB_ID (ASN1T_GlobalE2node_en_gNB_ID* pvalue, 
   OSBOOL free, OSCTXT *pctxt)
{
   if (0 == pvalue) return RTERR_NULLPTR;
   OSCRTLMEMSET (&pvalue->m, 0, sizeof (pvalue->m));
   asn1Init_E2AP_IEs_GlobalenGNB_ID (&pvalue->global_en_gNB_ID, free, pctxt);
   rtxDListFastInit (&pvalue->extElem1);
   return 0;
}

void asn1Free_GlobalE2node_en_gNB_ID (OSCTXT *pctxt, 
   ASN1T_GlobalE2node_en_gNB_ID* pvalue)
{
   if (0 == pvalue) return;
   asn1Free_E2AP_IEs_GlobalenGNB_ID (pctxt, &pvalue->global_en_gNB_ID);
   rtxMemFreeOpenSeqExt (pctxt, &pvalue->extElem1);
}

/* ASN1T_ENB_ID_Choice */

ASN1T_ENB_ID_Choice* new_ASN1T_ENB_ID_Choice (ASN1CType& ccobj)
{
   void* pdata = ccobj.memAlloc (sizeof(ASN1T_ENB_ID_Choice));
   if (0 == pdata) return 0;
   else return new (pdata) ASN1T_ENB_ID_Choice;
}

int asn1Init_ENB_ID_Choice (ASN1T_ENB_ID_Choice* pvalue, 
   OSBOOL free, OSCTXT *pctxt)
{
   if (0 == pvalue) return RTERR_NULLPTR;
   if (free) {
      asn1Free_ENB_ID_Choice (pctxt, pvalue);
   }
   else {
      pvalue->t = 0;
      OSCRTLMEMSET (&pvalue->u, 0, sizeof(pvalue->u));
   }
   return 0;
}

void asn1Free_ENB_ID_Choice (OSCTXT *pctxt, ASN1T_ENB_ID_Choice* pvalue)
{
   if (0 == pvalue) return;
   switch (pvalue->t) {
      case 0: break; /* no choice; nothing to free */
      case 1:
         if (0 != pvalue->u.enb_ID_macro) {
            rtxMemFreePtr (pctxt, (void*)pvalue->u.enb_ID_macro);
            pvalue->u.enb_ID_macro = 0;
         }
         break;

      case 2:
         if (0 != pvalue->u.enb_ID_shortmacro) {
            rtxMemFreePtr (pctxt, (void*)pvalue->u.enb_ID_shortmacro);
            pvalue->u.enb_ID_shortmacro = 0;
         }
         break;

      case 3:
         if (0 != pvalue->u.enb_ID_longmacro) {
            rtxMemFreePtr (pctxt, (void*)pvalue->u.enb_ID_longmacro);
            pvalue->u.enb_ID_longmacro = 0;
         }
         break;

      default:
         if (0 != pvalue->u.extElem1) {
            if (!rtxCtxtTestFlag (pctxt, ASN1FASTCOPY)) {
               rtxMemFreePtr (pctxt, (void*)pvalue->u.extElem1->data);
               pvalue->u.extElem1->data = 0;
            }
            rtxMemFreePtr (pctxt, (void*)pvalue->u.extElem1);
            pvalue->u.extElem1 = 0;
         }
   }
}

/* ASN1T_GlobalngeNB_ID */

ASN1T_GlobalngeNB_ID* new_ASN1T_GlobalngeNB_ID (ASN1CType& ccobj)
{
   void* pdata = ccobj.memAlloc (sizeof(ASN1T_GlobalngeNB_ID));
   if (0 == pdata) return 0;
   else return new (pdata) ASN1T_GlobalngeNB_ID;
}

int asn1Init_GlobalngeNB_ID (ASN1T_GlobalngeNB_ID* pvalue, 
   OSBOOL free, OSCTXT *pctxt)
{
   if (0 == pvalue) return RTERR_NULLPTR;
   asn1Init_PLMN_Identity (&pvalue->plmn_id, free, pctxt);
   asn1Init_ENB_ID_Choice (&pvalue->enb_id, free, pctxt);
   rtxDListFastInit (&pvalue->extElem1);
   return 0;
}

void asn1Free_GlobalngeNB_ID (OSCTXT *pctxt, ASN1T_GlobalngeNB_ID* pvalue)
{
   if (0 == pvalue) return;
   asn1Free_ENB_ID_Choice (pctxt, &pvalue->enb_id);
   rtxMemFreeOpenSeqExt (pctxt, &pvalue->extElem1);
}

/* ASN1T_E2AP_IEs_ENB_ID */

ASN1T_E2AP_IEs_ENB_ID* new_ASN1T_E2AP_IEs_ENB_ID (ASN1CType& ccobj)
{
   void* pdata = ccobj.memAlloc (sizeof(ASN1T_E2AP_IEs_ENB_ID));
   if (0 == pdata) return 0;
   else return new (pdata) ASN1T_E2AP_IEs_ENB_ID;
}

int asn1Init_E2AP_IEs_ENB_ID (ASN1T_E2AP_IEs_ENB_ID* pvalue, 
   OSBOOL free, OSCTXT *pctxt)
{
   if (0 == pvalue) return RTERR_NULLPTR;
   if (free) {
      asn1Free_E2AP_IEs_ENB_ID (pctxt, pvalue);
   }
   else {
      pvalue->t = 0;
      OSCRTLMEMSET (&pvalue->u, 0, sizeof(pvalue->u));
   }
   return 0;
}

void asn1Free_E2AP_IEs_ENB_ID (OSCTXT *pctxt, ASN1T_E2AP_IEs_ENB_ID* pvalue)
{
   if (0 == pvalue) return;
   switch (pvalue->t) {
      case 0: break; /* no choice; nothing to free */
      case 1:
         if (0 != pvalue->u.macro_eNB_ID) {
            rtxMemFreePtr (pctxt, (void*)pvalue->u.macro_eNB_ID);
            pvalue->u.macro_eNB_ID = 0;
         }
         break;

      case 2:
         if (0 != pvalue->u.home_eNB_ID) {
            rtxMemFreePtr (pctxt, (void*)pvalue->u.home_eNB_ID);
            pvalue->u.home_eNB_ID = 0;
         }
         break;

      case 3:
         if (0 != pvalue->u.short_Macro_eNB_ID) {
            rtxMemFreePtr (pctxt, (void*)pvalue->u.short_Macro_eNB_ID);
            pvalue->u.short_Macro_eNB_ID = 0;
         }
         break;

      case 4:
         if (0 != pvalue->u.long_Macro_eNB_ID) {
            rtxMemFreePtr (pctxt, (void*)pvalue->u.long_Macro_eNB_ID);
            pvalue->u.long_Macro_eNB_ID = 0;
         }
         break;

      default:
         if (0 != pvalue->u.extElem1) {
            if (!rtxCtxtTestFlag (pctxt, ASN1FASTCOPY)) {
               rtxMemFreePtr (pctxt, (void*)pvalue->u.extElem1->data);
               pvalue->u.extElem1->data = 0;
            }
            rtxMemFreePtr (pctxt, (void*)pvalue->u.extElem1);
            pvalue->u.extElem1 = 0;
         }
   }
}

/* ASN1T_E2AP_IEs_GlobalENB_ID */

ASN1T_E2AP_IEs_GlobalENB_ID* new_ASN1T_E2AP_IEs_GlobalENB_ID (ASN1CType& ccobj)
{
   void* pdata = ccobj.memAlloc (sizeof(ASN1T_E2AP_IEs_GlobalENB_ID));
   if (0 == pdata) return 0;
   else return new (pdata) ASN1T_E2AP_IEs_GlobalENB_ID;
}

int asn1Init_E2AP_IEs_GlobalENB_ID (ASN1T_E2AP_IEs_GlobalENB_ID* pvalue, 
   OSBOOL free, OSCTXT *pctxt)
{
   if (0 == pvalue) return RTERR_NULLPTR;
   asn1Init_PLMN_Identity (&pvalue->pLMN_Identity, free, pctxt);
   asn1Init_E2AP_IEs_ENB_ID (&pvalue->eNB_ID, free, pctxt);
   rtxDListFastInit (&pvalue->extElem1);
   return 0;
}

void asn1Free_E2AP_IEs_GlobalENB_ID (OSCTXT *pctxt, 
   ASN1T_E2AP_IEs_GlobalENB_ID* pvalue)
{
   if (0 == pvalue) return;
   asn1Free_E2AP_IEs_ENB_ID (pctxt, &pvalue->eNB_ID);
   rtxMemFreeOpenSeqExt (pctxt, &pvalue->extElem1);
}

/* ASN1T_E2AP_IEs_NGENB_DU_ID */

ASN1T_E2AP_IEs_NGENB_DU_ID* new_ASN1T_E2AP_IEs_NGENB_DU_ID (ASN1CType& ccobj)
{
   void* pdata = ccobj.memAlloc (sizeof(ASN1T_E2AP_IEs_NGENB_DU_ID));
   if (0 == pdata) return 0;
   else return new (pdata) ASN1T_E2AP_IEs_NGENB_DU_ID;
}

/* ASN1T_GlobalE2node_ng_eNB_ID */

ASN1T_GlobalE2node_ng_eNB_ID* 
   new_ASN1T_GlobalE2node_ng_eNB_ID (ASN1CType& ccobj)
{
   void* pdata = ccobj.memAlloc (sizeof(ASN1T_GlobalE2node_ng_eNB_ID));
   if (0 == pdata) return 0;
   else return new (pdata) ASN1T_GlobalE2node_ng_eNB_ID;
}

ASN1T_GlobalE2node_ng_eNB_ID::ASN1T_GlobalE2node_ng_eNB_ID ()
{
   m.global_eNB_IDPresent = 0;
   m.ngENB_DU_IDPresent = 0;
}

int asn1Init_GlobalE2node_ng_eNB_ID (ASN1T_GlobalE2node_ng_eNB_ID* pvalue, 
   OSBOOL free, OSCTXT *pctxt)
{
   if (0 == pvalue) return RTERR_NULLPTR;
   OSCRTLMEMSET (&pvalue->m, 0, sizeof (pvalue->m));
   asn1Init_GlobalngeNB_ID (&pvalue->global_ng_eNB_ID, free, pctxt);
   asn1Init_E2AP_IEs_GlobalENB_ID (&pvalue->global_eNB_ID, free, pctxt);
   rtxDListFastInit (&pvalue->extElem1);
   return 0;
}

void asn1Free_GlobalE2node_ng_eNB_ID (OSCTXT *pctxt, 
   ASN1T_GlobalE2node_ng_eNB_ID* pvalue)
{
   if (0 == pvalue) return;
   asn1Free_GlobalngeNB_ID (pctxt, &pvalue->global_ng_eNB_ID);
   if (pvalue->m.global_eNB_IDPresent) {
      asn1Free_E2AP_IEs_GlobalENB_ID (pctxt, &pvalue->global_eNB_ID);
   }
   rtxMemFreeOpenSeqExt (pctxt, &pvalue->extElem1);
}

/* ASN1T_GlobalE2node_eNB_ID */

ASN1T_GlobalE2node_eNB_ID* new_ASN1T_GlobalE2node_eNB_ID (ASN1CType& ccobj)
{
   void* pdata = ccobj.memAlloc (sizeof(ASN1T_GlobalE2node_eNB_ID));
   if (0 == pdata) return 0;
   else return new (pdata) ASN1T_GlobalE2node_eNB_ID;
}

int asn1Init_GlobalE2node_eNB_ID (ASN1T_GlobalE2node_eNB_ID* pvalue, 
   OSBOOL free, OSCTXT *pctxt)
{
   if (0 == pvalue) return RTERR_NULLPTR;
   asn1Init_E2AP_IEs_GlobalENB_ID (&pvalue->global_eNB_ID, free, pctxt);
   rtxDListFastInit (&pvalue->extElem1);
   return 0;
}

void asn1Free_GlobalE2node_eNB_ID (OSCTXT *pctxt, 
   ASN1T_GlobalE2node_eNB_ID* pvalue)
{
   if (0 == pvalue) return;
   asn1Free_E2AP_IEs_GlobalENB_ID (pctxt, &pvalue->global_eNB_ID);
   rtxMemFreeOpenSeqExt (pctxt, &pvalue->extElem1);
}

/* ASN1T_GlobalE2node_ID */

ASN1T_GlobalE2node_ID* new_ASN1T_GlobalE2node_ID (ASN1CType& ccobj)
{
   void* pdata = ccobj.memAlloc (sizeof(ASN1T_GlobalE2node_ID));
   if (0 == pdata) return 0;
   else return new (pdata) ASN1T_GlobalE2node_ID;
}

int asn1Init_GlobalE2node_ID (ASN1T_GlobalE2node_ID* pvalue, 
   OSBOOL free, OSCTXT *pctxt)
{
   if (0 == pvalue) return RTERR_NULLPTR;
   if (free) {
      asn1Free_GlobalE2node_ID (pctxt, pvalue);
   }
   else {
      pvalue->t = 0;
      OSCRTLMEMSET (&pvalue->u, 0, sizeof(pvalue->u));
   }
   return 0;
}

void asn1Free_GlobalE2node_ID (OSCTXT *pctxt, ASN1T_GlobalE2node_ID* pvalue)
{
   if (0 == pvalue) return;
   switch (pvalue->t) {
      case 0: break; /* no choice; nothing to free */
      case 1:
         if (0 != pvalue->u.gNB) {
            asn1Free_GlobalE2node_gNB_ID (pctxt, pvalue->u.gNB);
            rtxMemFreePtr (pctxt, (void*)pvalue->u.gNB);
            pvalue->u.gNB = 0;
         }
         break;

      case 2:
         if (0 != pvalue->u.en_gNB) {
            asn1Free_GlobalE2node_en_gNB_ID (pctxt, pvalue->u.en_gNB);
            rtxMemFreePtr (pctxt, (void*)pvalue->u.en_gNB);
            pvalue->u.en_gNB = 0;
         }
         break;

      case 3:
         if (0 != pvalue->u.ng_eNB) {
            asn1Free_GlobalE2node_ng_eNB_ID (pctxt, pvalue->u.ng_eNB);
            rtxMemFreePtr (pctxt, (void*)pvalue->u.ng_eNB);
            pvalue->u.ng_eNB = 0;
         }
         break;

      case 4:
         if (0 != pvalue->u.eNB) {
            asn1Free_GlobalE2node_eNB_ID (pctxt, pvalue->u.eNB);
            rtxMemFreePtr (pctxt, (void*)pvalue->u.eNB);
            pvalue->u.eNB = 0;
         }
         break;

      default:
         if (0 != pvalue->u.extElem1) {
            if (!rtxCtxtTestFlag (pctxt, ASN1FASTCOPY)) {
               rtxMemFreePtr (pctxt, (void*)pvalue->u.extElem1->data);
               pvalue->u.extElem1->data = 0;
            }
            rtxMemFreePtr (pctxt, (void*)pvalue->u.extElem1);
            pvalue->u.extElem1 = 0;
         }
   }
}

/* ASN1T_E2nodeComponentInterfaceType */

const OSEnumItem ASN1T_E2nodeComponentInterfaceType_ENUMTAB[] = {
   { OSUTF8("e1"), 2, 2, 2 },
   { OSUTF8("f1"), 3, 2, 6 },
   { OSUTF8("ng"), 0, 2, 0 },
   { OSUTF8("s1"), 5, 2, 1 },
   { OSUTF8("w1"), 4, 2, 4 },
   { OSUTF8("x2"), 6, 2, 3 },
   { OSUTF8("xn"), 1, 2, 5 }
} ;

const OSUTF8CHAR* ASN1T_E2nodeComponentInterfaceType_ToString (OSINT32 value)
{
   OSINT32 idx = value;

   if (idx >= 0 && idx < ASN1T_E2nodeComponentInterfaceType_ENUMTABSIZE) {
      return ASN1T_E2nodeComponentInterfaceType_ENUMTAB
         [ASN1T_E2nodeComponentInterfaceType_ENUMTAB[idx].transidx].name;
   }
   else
      return OSUTF8("_UNKNOWN_");
}

int ASN1T_E2nodeComponentInterfaceType_ToEnum (OSCTXT* pctxt,
   const OSUTF8CHAR* value, ASN1T_E2nodeComponentInterfaceType* pvalue)
{
   OSSIZE valueLen = rtxUTF8LenBytes (value);
   return ASN1T_E2nodeComponentInterfaceType_ToEnum2 (pctxt, value, valueLen, pvalue);
}

int ASN1T_E2nodeComponentInterfaceType_ToEnum2 (OSCTXT* pctxt,
   const OSUTF8CHAR* value, OSSIZE valueLen, 
      ASN1T_E2nodeComponentInterfaceType* pvalue)
{
   OSINT32 idx = rtxLookupEnum (value, valueLen, 
      ASN1T_E2nodeComponentInterfaceType_ENUMTAB, 
      ASN1T_E2nodeComponentInterfaceType_ENUMTABSIZE);

   if (idx >= 0) {
      *pvalue = (ASN1T_E2nodeComponentInterfaceType)
         ASN1T_E2nodeComponentInterfaceType_ENUMTAB[idx].value;
      return 0;
   }
   else {
      rtxErrAddStrParm (pctxt, (const char*)value);
      return LOG_RTERR (pctxt, RTERR_INVENUM);
   }
}

ASN1T_E2nodeComponentInterfaceType* 
   new_ASN1T_E2nodeComponentInterfaceType (ASN1CType& ccobj)
{
   void* pdata = ccobj.memAlloc (sizeof(ASN1T_E2nodeComponentInterfaceType));
   if (0 == pdata) return 0;
   else return new (pdata) ASN1T_E2nodeComponentInterfaceType;
}

/* ASN1T_AMFName */

void asn1Free_AMFName (OSCTXT *pctxt, ASN1T_AMFName pvalue)
{
   if (0 == pvalue) return;
   rtxMemFreePtr (pctxt, (void*)pvalue);
   pvalue = 0;
}

/* ASN1T_E2nodeComponentInterfaceNG */

ASN1T_E2nodeComponentInterfaceNG* 
   new_ASN1T_E2nodeComponentInterfaceNG (ASN1CType& ccobj)
{
   void* pdata = ccobj.memAlloc (sizeof(ASN1T_E2nodeComponentInterfaceNG));
   if (0 == pdata) return 0;
   else return new (pdata) ASN1T_E2nodeComponentInterfaceNG;
}

ASN1T_E2nodeComponentInterfaceNG::ASN1T_E2nodeComponentInterfaceNG ()
{
   amf_name = 0;
}

int asn1Init_E2nodeComponentInterfaceNG (
   ASN1T_E2nodeComponentInterfaceNG* pvalue, OSBOOL free, OSCTXT *pctxt)
{
   if (0 == pvalue) return RTERR_NULLPTR;
   pvalue->amf_name = 0;
   rtxDListFastInit (&pvalue->extElem1);
   return 0;
}

void asn1Free_E2nodeComponentInterfaceNG (OSCTXT *pctxt, 
   ASN1T_E2nodeComponentInterfaceNG* pvalue)
{
   if (0 == pvalue) return;
   rtxMemFreePtr (pctxt, (void*)pvalue->amf_name);
   pvalue->amf_name = 0;
   rtxMemFreeOpenSeqExt (pctxt, &pvalue->extElem1);
}

/* ASN1T_GlobalNG_RANNode_ID */

ASN1T_GlobalNG_RANNode_ID* new_ASN1T_GlobalNG_RANNode_ID (ASN1CType& ccobj)
{
   void* pdata = ccobj.memAlloc (sizeof(ASN1T_GlobalNG_RANNode_ID));
   if (0 == pdata) return 0;
   else return new (pdata) ASN1T_GlobalNG_RANNode_ID;
}

int asn1Init_GlobalNG_RANNode_ID (ASN1T_GlobalNG_RANNode_ID* pvalue, 
   OSBOOL free, OSCTXT *pctxt)
{
   if (0 == pvalue) return RTERR_NULLPTR;
   if (free) {
      asn1Free_GlobalNG_RANNode_ID (pctxt, pvalue);
   }
   else {
      pvalue->t = 0;
      OSCRTLMEMSET (&pvalue->u, 0, sizeof(pvalue->u));
   }
   return 0;
}

void asn1Free_GlobalNG_RANNode_ID (OSCTXT *pctxt, 
   ASN1T_GlobalNG_RANNode_ID* pvalue)
{
   if (0 == pvalue) return;
   switch (pvalue->t) {
      case 0: break; /* no choice; nothing to free */
      case 1:
         if (0 != pvalue->u.gNB) {
            asn1Free_GlobalgNB_ID (pctxt, pvalue->u.gNB);
            rtxMemFreePtr (pctxt, (void*)pvalue->u.gNB);
            pvalue->u.gNB = 0;
         }
         break;

      case 2:
         if (0 != pvalue->u.ng_eNB) {
            asn1Free_GlobalngeNB_ID (pctxt, pvalue->u.ng_eNB);
            rtxMemFreePtr (pctxt, (void*)pvalue->u.ng_eNB);
            pvalue->u.ng_eNB = 0;
         }
         break;

      default:
         if (0 != pvalue->u.extElem1) {
            if (!rtxCtxtTestFlag (pctxt, ASN1FASTCOPY)) {
               rtxMemFreePtr (pctxt, (void*)pvalue->u.extElem1->data);
               pvalue->u.extElem1->data = 0;
            }
            rtxMemFreePtr (pctxt, (void*)pvalue->u.extElem1);
            pvalue->u.extElem1 = 0;
         }
   }
}

/* ASN1T_E2nodeComponentInterfaceXn */

ASN1T_E2nodeComponentInterfaceXn* 
   new_ASN1T_E2nodeComponentInterfaceXn (ASN1CType& ccobj)
{
   void* pdata = ccobj.memAlloc (sizeof(ASN1T_E2nodeComponentInterfaceXn));
   if (0 == pdata) return 0;
   else return new (pdata) ASN1T_E2nodeComponentInterfaceXn;
}

int asn1Init_E2nodeComponentInterfaceXn (
   ASN1T_E2nodeComponentInterfaceXn* pvalue, OSBOOL free, OSCTXT *pctxt)
{
   if (0 == pvalue) return RTERR_NULLPTR;
   asn1Init_GlobalNG_RANNode_ID (&pvalue->global_NG_RAN_Node_ID, free, pctxt);
   rtxDListFastInit (&pvalue->extElem1);
   return 0;
}

void asn1Free_E2nodeComponentInterfaceXn (OSCTXT *pctxt, 
   ASN1T_E2nodeComponentInterfaceXn* pvalue)
{
   if (0 == pvalue) return;
   asn1Free_GlobalNG_RANNode_ID (pctxt, &pvalue->global_NG_RAN_Node_ID);
   rtxMemFreeOpenSeqExt (pctxt, &pvalue->extElem1);
}

/* ASN1T_E2nodeComponentInterfaceE1 */

ASN1T_E2nodeComponentInterfaceE1* 
   new_ASN1T_E2nodeComponentInterfaceE1 (ASN1CType& ccobj)
{
   void* pdata = ccobj.memAlloc (sizeof(ASN1T_E2nodeComponentInterfaceE1));
   if (0 == pdata) return 0;
   else return new (pdata) ASN1T_E2nodeComponentInterfaceE1;
}

int asn1Init_E2nodeComponentInterfaceE1 (
   ASN1T_E2nodeComponentInterfaceE1* pvalue, OSBOOL free, OSCTXT *pctxt)
{
   if (0 == pvalue) return RTERR_NULLPTR;
   rtxDListFastInit (&pvalue->extElem1);
   return 0;
}

void asn1Free_E2nodeComponentInterfaceE1 (OSCTXT *pctxt, 
   ASN1T_E2nodeComponentInterfaceE1* pvalue)
{
   if (0 == pvalue) return;
   rtxMemFreeOpenSeqExt (pctxt, &pvalue->extElem1);
}

/* ASN1T_E2nodeComponentInterfaceF1 */

ASN1T_E2nodeComponentInterfaceF1* 
   new_ASN1T_E2nodeComponentInterfaceF1 (ASN1CType& ccobj)
{
   void* pdata = ccobj.memAlloc (sizeof(ASN1T_E2nodeComponentInterfaceF1));
   if (0 == pdata) return 0;
   else return new (pdata) ASN1T_E2nodeComponentInterfaceF1;
}

int asn1Init_E2nodeComponentInterfaceF1 (
   ASN1T_E2nodeComponentInterfaceF1* pvalue, OSBOOL free, OSCTXT *pctxt)
{
   if (0 == pvalue) return RTERR_NULLPTR;
   rtxDListFastInit (&pvalue->extElem1);
   return 0;
}

void asn1Free_E2nodeComponentInterfaceF1 (OSCTXT *pctxt, 
   ASN1T_E2nodeComponentInterfaceF1* pvalue)
{
   if (0 == pvalue) return;
   rtxMemFreeOpenSeqExt (pctxt, &pvalue->extElem1);
}

/* ASN1T_E2nodeComponentInterfaceW1 */

ASN1T_E2nodeComponentInterfaceW1* 
   new_ASN1T_E2nodeComponentInterfaceW1 (ASN1CType& ccobj)
{
   void* pdata = ccobj.memAlloc (sizeof(ASN1T_E2nodeComponentInterfaceW1));
   if (0 == pdata) return 0;
   else return new (pdata) ASN1T_E2nodeComponentInterfaceW1;
}

int asn1Init_E2nodeComponentInterfaceW1 (
   ASN1T_E2nodeComponentInterfaceW1* pvalue, OSBOOL free, OSCTXT *pctxt)
{
   if (0 == pvalue) return RTERR_NULLPTR;
   rtxDListFastInit (&pvalue->extElem1);
   return 0;
}

void asn1Free_E2nodeComponentInterfaceW1 (OSCTXT *pctxt, 
   ASN1T_E2nodeComponentInterfaceW1* pvalue)
{
   if (0 == pvalue) return;
   rtxMemFreeOpenSeqExt (pctxt, &pvalue->extElem1);
}

/* ASN1T_MMEname */

void asn1Free_MMEname (OSCTXT *pctxt, ASN1T_MMEname pvalue)
{
   if (0 == pvalue) return;
   rtxMemFreePtr (pctxt, (void*)pvalue);
   pvalue = 0;
}

/* ASN1T_E2nodeComponentInterfaceS1 */

ASN1T_E2nodeComponentInterfaceS1* 
   new_ASN1T_E2nodeComponentInterfaceS1 (ASN1CType& ccobj)
{
   void* pdata = ccobj.memAlloc (sizeof(ASN1T_E2nodeComponentInterfaceS1));
   if (0 == pdata) return 0;
   else return new (pdata) ASN1T_E2nodeComponentInterfaceS1;
}

ASN1T_E2nodeComponentInterfaceS1::ASN1T_E2nodeComponentInterfaceS1 ()
{
   mme_name = 0;
}

int asn1Init_E2nodeComponentInterfaceS1 (
   ASN1T_E2nodeComponentInterfaceS1* pvalue, OSBOOL free, OSCTXT *pctxt)
{
   if (0 == pvalue) return RTERR_NULLPTR;
   pvalue->mme_name = 0;
   rtxDListFastInit (&pvalue->extElem1);
   return 0;
}

void asn1Free_E2nodeComponentInterfaceS1 (OSCTXT *pctxt, 
   ASN1T_E2nodeComponentInterfaceS1* pvalue)
{
   if (0 == pvalue) return;
   rtxMemFreePtr (pctxt, (void*)pvalue->mme_name);
   pvalue->mme_name = 0;
   rtxMemFreeOpenSeqExt (pctxt, &pvalue->extElem1);
}

/* ASN1T_E2nodeComponentInterfaceX2 */

ASN1T_E2nodeComponentInterfaceX2* 
   new_ASN1T_E2nodeComponentInterfaceX2 (ASN1CType& ccobj)
{
   void* pdata = ccobj.memAlloc (sizeof(ASN1T_E2nodeComponentInterfaceX2));
   if (0 == pdata) return 0;
   else return new (pdata) ASN1T_E2nodeComponentInterfaceX2;
}

ASN1T_E2nodeComponentInterfaceX2::ASN1T_E2nodeComponentInterfaceX2 ()
{
   m.global_eNB_IDPresent = 0;
   m.global_en_gNB_IDPresent = 0;
}

int asn1Init_E2nodeComponentInterfaceX2 (
   ASN1T_E2nodeComponentInterfaceX2* pvalue, OSBOOL free, OSCTXT *pctxt)
{
   if (0 == pvalue) return RTERR_NULLPTR;
   OSCRTLMEMSET (&pvalue->m, 0, sizeof (pvalue->m));
   asn1Init_E2AP_IEs_GlobalENB_ID (&pvalue->global_eNB_ID, free, pctxt);
   asn1Init_E2AP_IEs_GlobalenGNB_ID (&pvalue->global_en_gNB_ID, free, pctxt);
   rtxDListFastInit (&pvalue->extElem1);
   return 0;
}

void asn1Free_E2nodeComponentInterfaceX2 (OSCTXT *pctxt, 
   ASN1T_E2nodeComponentInterfaceX2* pvalue)
{
   if (0 == pvalue) return;
   if (pvalue->m.global_eNB_IDPresent) {
      asn1Free_E2AP_IEs_GlobalENB_ID (pctxt, &pvalue->global_eNB_ID);
   }
   if (pvalue->m.global_en_gNB_IDPresent) {
      asn1Free_E2AP_IEs_GlobalenGNB_ID (pctxt, &pvalue->global_en_gNB_ID);
   }
   rtxMemFreeOpenSeqExt (pctxt, &pvalue->extElem1);
}

/* ASN1T_E2nodeComponentID */

ASN1T_E2nodeComponentID* new_ASN1T_E2nodeComponentID (ASN1CType& ccobj)
{
   void* pdata = ccobj.memAlloc (sizeof(ASN1T_E2nodeComponentID));
   if (0 == pdata) return 0;
   else return new (pdata) ASN1T_E2nodeComponentID;
}

int asn1Init_E2nodeComponentID (ASN1T_E2nodeComponentID* pvalue, 
   OSBOOL free, OSCTXT *pctxt)
{
   if (0 == pvalue) return RTERR_NULLPTR;
   if (free) {
      asn1Free_E2nodeComponentID (pctxt, pvalue);
   }
   else {
      pvalue->t = 0;
      OSCRTLMEMSET (&pvalue->u, 0, sizeof(pvalue->u));
   }
   return 0;
}

void asn1Free_E2nodeComponentID (OSCTXT *pctxt, 
   ASN1T_E2nodeComponentID* pvalue)
{
   if (0 == pvalue) return;
   switch (pvalue->t) {
      case 0: break; /* no choice; nothing to free */
      case 1:
         if (0 != pvalue->u.e2nodeComponentInterfaceTypeNG) {
            asn1Free_E2nodeComponentInterfaceNG (pctxt, pvalue->u.e2nodeComponentInterfaceTypeNG);
            rtxMemFreePtr (pctxt, (void*)pvalue->u.e2nodeComponentInterfaceTypeNG);
            pvalue->u.e2nodeComponentInterfaceTypeNG = 0;
         }
         break;

      case 2:
         if (0 != pvalue->u.e2nodeComponentInterfaceTypeXn) {
            asn1Free_E2nodeComponentInterfaceXn (pctxt, pvalue->u.e2nodeComponentInterfaceTypeXn);
            rtxMemFreePtr (pctxt, (void*)pvalue->u.e2nodeComponentInterfaceTypeXn);
            pvalue->u.e2nodeComponentInterfaceTypeXn = 0;
         }
         break;

      case 3:
         if (0 != pvalue->u.e2nodeComponentInterfaceTypeE1) {
            asn1Free_E2nodeComponentInterfaceE1 (pctxt, pvalue->u.e2nodeComponentInterfaceTypeE1);
            rtxMemFreePtr (pctxt, (void*)pvalue->u.e2nodeComponentInterfaceTypeE1);
            pvalue->u.e2nodeComponentInterfaceTypeE1 = 0;
         }
         break;

      case 4:
         if (0 != pvalue->u.e2nodeComponentInterfaceTypeF1) {
            asn1Free_E2nodeComponentInterfaceF1 (pctxt, pvalue->u.e2nodeComponentInterfaceTypeF1);
            rtxMemFreePtr (pctxt, (void*)pvalue->u.e2nodeComponentInterfaceTypeF1);
            pvalue->u.e2nodeComponentInterfaceTypeF1 = 0;
         }
         break;

      case 5:
         if (0 != pvalue->u.e2nodeComponentInterfaceTypeW1) {
            asn1Free_E2nodeComponentInterfaceW1 (pctxt, pvalue->u.e2nodeComponentInterfaceTypeW1);
            rtxMemFreePtr (pctxt, (void*)pvalue->u.e2nodeComponentInterfaceTypeW1);
            pvalue->u.e2nodeComponentInterfaceTypeW1 = 0;
         }
         break;

      case 6:
         if (0 != pvalue->u.e2nodeComponentInterfaceTypeS1) {
            asn1Free_E2nodeComponentInterfaceS1 (pctxt, pvalue->u.e2nodeComponentInterfaceTypeS1);
            rtxMemFreePtr (pctxt, (void*)pvalue->u.e2nodeComponentInterfaceTypeS1);
            pvalue->u.e2nodeComponentInterfaceTypeS1 = 0;
         }
         break;

      case 7:
         if (0 != pvalue->u.e2nodeComponentInterfaceTypeX2) {
            asn1Free_E2nodeComponentInterfaceX2 (pctxt, pvalue->u.e2nodeComponentInterfaceTypeX2);
            rtxMemFreePtr (pctxt, (void*)pvalue->u.e2nodeComponentInterfaceTypeX2);
            pvalue->u.e2nodeComponentInterfaceTypeX2 = 0;
         }
         break;

      default:
         if (0 != pvalue->u.extElem1) {
            if (!rtxCtxtTestFlag (pctxt, ASN1FASTCOPY)) {
               rtxMemFreePtr (pctxt, (void*)pvalue->u.extElem1->data);
               pvalue->u.extElem1->data = 0;
            }
            rtxMemFreePtr (pctxt, (void*)pvalue->u.extElem1);
            pvalue->u.extElem1 = 0;
         }
   }
}

/* ASN1T_E2nodeComponentConfiguration */

ASN1T_E2nodeComponentConfiguration* 
   new_ASN1T_E2nodeComponentConfiguration (ASN1CType& ccobj)
{
   void* pdata = ccobj.memAlloc (sizeof(ASN1T_E2nodeComponentConfiguration));
   if (0 == pdata) return 0;
   else return new (pdata) ASN1T_E2nodeComponentConfiguration;
}

int asn1Init_E2nodeComponentConfiguration (
   ASN1T_E2nodeComponentConfiguration* pvalue, OSBOOL free, OSCTXT *pctxt)
{
   if (0 == pvalue) return RTERR_NULLPTR;
   pvalue->e2nodeComponentRequestPart.numocts = 0;
   pvalue->e2nodeComponentRequestPart.data = 0;
   pvalue->e2nodeComponentResponsePart.numocts = 0;
   pvalue->e2nodeComponentResponsePart.data = 0;
   rtxDListFastInit (&pvalue->extElem1);
   return 0;
}

void asn1Free_E2nodeComponentConfiguration (OSCTXT *pctxt, 
   ASN1T_E2nodeComponentConfiguration* pvalue)
{
   if (0 == pvalue) return;
   if (pvalue->e2nodeComponentRequestPart.numocts > 0) {
      rtxMemFreePtr (pctxt, (void*)pvalue->e2nodeComponentRequestPart.data);
      pvalue->e2nodeComponentRequestPart.numocts = 0;
      pvalue->e2nodeComponentRequestPart.data = 0;
   }
   if (pvalue->e2nodeComponentResponsePart.numocts > 0) {
      rtxMemFreePtr (pctxt, (void*)pvalue->e2nodeComponentResponsePart.data);
      pvalue->e2nodeComponentResponsePart.numocts = 0;
      pvalue->e2nodeComponentResponsePart.data = 0;
   }
   rtxMemFreeOpenSeqExt (pctxt, &pvalue->extElem1);
}

/* ASN1T_TNLinformation */

ASN1T_TNLinformation* new_ASN1T_TNLinformation (ASN1CType& ccobj)
{
   void* pdata = ccobj.memAlloc (sizeof(ASN1T_TNLinformation));
   if (0 == pdata) return 0;
   else return new (pdata) ASN1T_TNLinformation;
}

ASN1T_TNLinformation::ASN1T_TNLinformation ()
{
   m.tnlPortPresent = 0;
}

int asn1Init_TNLinformation (ASN1T_TNLinformation* pvalue, 
   OSBOOL free, OSCTXT *pctxt)
{
   if (0 == pvalue) return RTERR_NULLPTR;
   OSCRTLMEMSET (&pvalue->m, 0, sizeof (pvalue->m));
   pvalue->tnlAddress.numbits = 0;
   pvalue->tnlAddress.data = 0;
   pvalue->tnlPort.numbits = 0;
   rtxDListFastInit (&pvalue->extElem1);
   return 0;
}

void asn1Free_TNLinformation (OSCTXT *pctxt, ASN1T_TNLinformation* pvalue)
{
   if (0 == pvalue) return;
   if (pvalue->tnlAddress.numbits > 0) {
      rtxMemFreePtr (pctxt, (void*)pvalue->tnlAddress.data);
      pvalue->tnlAddress.numbits = 0;
      pvalue->tnlAddress.data = 0;
   }
   rtxMemFreeOpenSeqExt (pctxt, &pvalue->extElem1);
}

/* ASN1T_TNLusage */

const OSEnumItem ASN1T_TNLusage_ENUMTAB[] = {
   { OSUTF8("both"), 2, 4, 1 },
   { OSUTF8("ric-service"), 0, 11, 2 },
   { OSUTF8("support-function"), 1, 16, 0 }
} ;

const OSUTF8CHAR* ASN1T_TNLusage_ToString (OSINT32 value)
{
   OSINT32 idx = value;

   if (idx >= 0 && idx < ASN1T_TNLusage_ENUMTABSIZE) {
      return ASN1T_TNLusage_ENUMTAB
         [ASN1T_TNLusage_ENUMTAB[idx].transidx].name;
   }
   else
      return OSUTF8("_UNKNOWN_");
}

int ASN1T_TNLusage_ToEnum (OSCTXT* pctxt,
   const OSUTF8CHAR* value, ASN1T_TNLusage* pvalue)
{
   OSSIZE valueLen = rtxUTF8LenBytes (value);
   return ASN1T_TNLusage_ToEnum2 (pctxt, value, valueLen, pvalue);
}

int ASN1T_TNLusage_ToEnum2 (OSCTXT* pctxt,
   const OSUTF8CHAR* value, OSSIZE valueLen, ASN1T_TNLusage* pvalue)
{
   OSINT32 idx = rtxLookupEnum (value, valueLen, ASN1T_TNLusage_ENUMTAB, 
      ASN1T_TNLusage_ENUMTABSIZE);

   if (idx >= 0) {
      *pvalue = (ASN1T_TNLusage)ASN1T_TNLusage_ENUMTAB[idx].value;
      return 0;
   }
   else {
      rtxErrAddStrParm (pctxt, (const char*)value);
      return LOG_RTERR (pctxt, RTERR_INVENUM);
   }
}

ASN1T_TNLusage* new_ASN1T_TNLusage (ASN1CType& ccobj)
{
   void* pdata = ccobj.memAlloc (sizeof(ASN1T_TNLusage));
   if (0 == pdata) return 0;
   else return new (pdata) ASN1T_TNLusage;
}

/* ASN1T_CauseRICrequest */

const OSEnumItem ASN1T_CauseRICrequest_ENUMTAB[] = {
   { OSUTF8("action-not-supported"), 1, 20, 9 },
   { OSUTF8("control-failed-to-execute"), 11, 25, 0 },
   { OSUTF8("control-message-invalid"), 8, 23, 6 },
   { OSUTF8("control-timer-expired"), 10, 21, 4 },
   { OSUTF8("duplicate-action"), 3, 16, 5 },
   { OSUTF8("duplicate-event-trigger"), 4, 23, 7 },
   { OSUTF8("excessive-actions"), 2, 17, 10 },
   { OSUTF8("function-resource-limit"), 5, 23, 8 },
   { OSUTF8("inconsistent-action-subsequent-action-sequence"), 7, 46, 2 },
   { OSUTF8("ran-function-id-invalid"), 0, 23, 11 },
   { OSUTF8("request-id-unknown"), 6, 18, 3 },
   { OSUTF8("ric-call-process-id-invalid"), 9, 27, 1 },
   { OSUTF8("system-not-ready"), 12, 16, 12 },
   { OSUTF8("unspecified"), 13, 11, 13 }
} ;

const OSUTF8CHAR* ASN1T_CauseRICrequest_ToString (OSINT32 value)
{
   OSINT32 idx = value;

   if (idx >= 0 && idx < ASN1T_CauseRICrequest_ENUMTABSIZE) {
      return ASN1T_CauseRICrequest_ENUMTAB
         [ASN1T_CauseRICrequest_ENUMTAB[idx].transidx].name;
   }
   else
      return OSUTF8("_UNKNOWN_");
}

int ASN1T_CauseRICrequest_ToEnum (OSCTXT* pctxt,
   const OSUTF8CHAR* value, ASN1T_CauseRICrequest* pvalue)
{
   OSSIZE valueLen = rtxUTF8LenBytes (value);
   return ASN1T_CauseRICrequest_ToEnum2 (pctxt, value, valueLen, pvalue);
}

int ASN1T_CauseRICrequest_ToEnum2 (OSCTXT* pctxt,
   const OSUTF8CHAR* value, OSSIZE valueLen, ASN1T_CauseRICrequest* pvalue)
{
   OSINT32 idx = rtxLookupEnum (value, valueLen, 
      ASN1T_CauseRICrequest_ENUMTAB, ASN1T_CauseRICrequest_ENUMTABSIZE);

   if (idx >= 0) {
      *pvalue = (ASN1T_CauseRICrequest)
         ASN1T_CauseRICrequest_ENUMTAB[idx].value;
      return 0;
   }
   else {
      rtxErrAddStrParm (pctxt, (const char*)value);
      return LOG_RTERR (pctxt, RTERR_INVENUM);
   }
}

ASN1T_CauseRICrequest* new_ASN1T_CauseRICrequest (ASN1CType& ccobj)
{
   void* pdata = ccobj.memAlloc (sizeof(ASN1T_CauseRICrequest));
   if (0 == pdata) return 0;
   else return new (pdata) ASN1T_CauseRICrequest;
}

/* ASN1T_CauseRICservice */

const OSEnumItem ASN1T_CauseRICservice_ENUMTAB[] = {
   { OSUTF8("excessive-functions"), 1, 19, 1 },
   { OSUTF8("ran-function-not-supported"), 0, 26, 0 },
   { OSUTF8("ric-resource-limit"), 2, 18, 2 }
} ;

const OSUTF8CHAR* ASN1T_CauseRICservice_ToString (OSINT32 value)
{
   OSINT32 idx = value;

   if (idx >= 0 && idx < ASN1T_CauseRICservice_ENUMTABSIZE) {
      return ASN1T_CauseRICservice_ENUMTAB
         [ASN1T_CauseRICservice_ENUMTAB[idx].transidx].name;
   }
   else
      return OSUTF8("_UNKNOWN_");
}

int ASN1T_CauseRICservice_ToEnum (OSCTXT* pctxt,
   const OSUTF8CHAR* value, ASN1T_CauseRICservice* pvalue)
{
   OSSIZE valueLen = rtxUTF8LenBytes (value);
   return ASN1T_CauseRICservice_ToEnum2 (pctxt, value, valueLen, pvalue);
}

int ASN1T_CauseRICservice_ToEnum2 (OSCTXT* pctxt,
   const OSUTF8CHAR* value, OSSIZE valueLen, ASN1T_CauseRICservice* pvalue)
{
   OSINT32 idx = rtxLookupEnum (value, valueLen, 
      ASN1T_CauseRICservice_ENUMTAB, ASN1T_CauseRICservice_ENUMTABSIZE);

   if (idx >= 0) {
      *pvalue = (ASN1T_CauseRICservice)
         ASN1T_CauseRICservice_ENUMTAB[idx].value;
      return 0;
   }
   else {
      rtxErrAddStrParm (pctxt, (const char*)value);
      return LOG_RTERR (pctxt, RTERR_INVENUM);
   }
}

ASN1T_CauseRICservice* new_ASN1T_CauseRICservice (ASN1CType& ccobj)
{
   void* pdata = ccobj.memAlloc (sizeof(ASN1T_CauseRICservice));
   if (0 == pdata) return 0;
   else return new (pdata) ASN1T_CauseRICservice;
}

/* ASN1T_CauseE2node */

const OSEnumItem ASN1T_CauseE2node_ENUMTAB[] = {
   { OSUTF8("e2node-component-unknown"), 0, 24, 0 }
} ;

const OSUTF8CHAR* ASN1T_CauseE2node_ToString (OSINT32 value)
{
   OSINT32 idx = rtxLookupEnumByValue (value, ASN1T_CauseE2node_ENUMTAB, 
      ASN1T_CauseE2node_ENUMTABSIZE);

   if (idx >= 0 && idx < ASN1T_CauseE2node_ENUMTABSIZE) {
      return ASN1T_CauseE2node_ENUMTAB[idx].name;
   }
   else
      return OSUTF8("_UNKNOWN_");
}

int ASN1T_CauseE2node_ToEnum (OSCTXT* pctxt,
   const OSUTF8CHAR* value, ASN1T_CauseE2node* pvalue)
{
   OSSIZE valueLen = rtxUTF8LenBytes (value);
   return ASN1T_CauseE2node_ToEnum2 (pctxt, value, valueLen, pvalue);
}

int ASN1T_CauseE2node_ToEnum2 (OSCTXT* pctxt,
   const OSUTF8CHAR* value, OSSIZE valueLen, ASN1T_CauseE2node* pvalue)
{
   OSINT32 idx = rtxLookupEnum (value, valueLen, ASN1T_CauseE2node_ENUMTAB, 
      ASN1T_CauseE2node_ENUMTABSIZE);

   if (idx >= 0) {
      *pvalue = (ASN1T_CauseE2node)ASN1T_CauseE2node_ENUMTAB[idx].value;
      return 0;
   }
   else {
      rtxErrAddStrParm (pctxt, (const char*)value);
      return LOG_RTERR (pctxt, RTERR_INVENUM);
   }
}

ASN1T_CauseE2node* new_ASN1T_CauseE2node (ASN1CType& ccobj)
{
   void* pdata = ccobj.memAlloc (sizeof(ASN1T_CauseE2node));
   if (0 == pdata) return 0;
   else return new (pdata) ASN1T_CauseE2node;
}

/* ASN1T_CauseTransport */

const OSEnumItem ASN1T_CauseTransport_ENUMTAB[] = {
   { OSUTF8("transport-resource-unavailable"), 1, 30, 1 },
   { OSUTF8("unspecified"), 0, 11, 0 }
} ;

const OSUTF8CHAR* ASN1T_CauseTransport_ToString (OSINT32 value)
{
   OSINT32 idx = value;

   if (idx >= 0 && idx < ASN1T_CauseTransport_ENUMTABSIZE) {
      return ASN1T_CauseTransport_ENUMTAB
         [ASN1T_CauseTransport_ENUMTAB[idx].transidx].name;
   }
   else
      return OSUTF8("_UNKNOWN_");
}

int ASN1T_CauseTransport_ToEnum (OSCTXT* pctxt,
   const OSUTF8CHAR* value, ASN1T_CauseTransport* pvalue)
{
   OSSIZE valueLen = rtxUTF8LenBytes (value);
   return ASN1T_CauseTransport_ToEnum2 (pctxt, value, valueLen, pvalue);
}

int ASN1T_CauseTransport_ToEnum2 (OSCTXT* pctxt,
   const OSUTF8CHAR* value, OSSIZE valueLen, ASN1T_CauseTransport* pvalue)
{
   OSINT32 idx = rtxLookupEnum (value, valueLen, ASN1T_CauseTransport_ENUMTAB, 
      ASN1T_CauseTransport_ENUMTABSIZE);

   if (idx >= 0) {
      *pvalue = (ASN1T_CauseTransport)ASN1T_CauseTransport_ENUMTAB[idx].value;
      return 0;
   }
   else {
      rtxErrAddStrParm (pctxt, (const char*)value);
      return LOG_RTERR (pctxt, RTERR_INVENUM);
   }
}

ASN1T_CauseTransport* new_ASN1T_CauseTransport (ASN1CType& ccobj)
{
   void* pdata = ccobj.memAlloc (sizeof(ASN1T_CauseTransport));
   if (0 == pdata) return 0;
   else return new (pdata) ASN1T_CauseTransport;
}

/* ASN1T_CauseProtocol */

const OSEnumItem ASN1T_CauseProtocol_ENUMTAB[] = {
   { OSUTF8("abstract-syntax-error-falsely-constructed-message"), 5, 49, 5 },
   { OSUTF8("abstract-syntax-error-ignore-and-notify"), 2, 39, 2 },
   { OSUTF8("abstract-syntax-error-reject"), 1, 28, 1 },
   { OSUTF8("message-not-compatible-with-receiver-state"), 3, 42, 3 },
   { OSUTF8("semantic-error"), 4, 14, 4 },
   { OSUTF8("transfer-syntax-error"), 0, 21, 0 },
   { OSUTF8("unspecified"), 6, 11, 6 }
} ;

const OSUTF8CHAR* ASN1T_CauseProtocol_ToString (OSINT32 value)
{
   OSINT32 idx = value;

   if (idx >= 0 && idx < ASN1T_CauseProtocol_ENUMTABSIZE) {
      return ASN1T_CauseProtocol_ENUMTAB
         [ASN1T_CauseProtocol_ENUMTAB[idx].transidx].name;
   }
   else
      return OSUTF8("_UNKNOWN_");
}

int ASN1T_CauseProtocol_ToEnum (OSCTXT* pctxt,
   const OSUTF8CHAR* value, ASN1T_CauseProtocol* pvalue)
{
   OSSIZE valueLen = rtxUTF8LenBytes (value);
   return ASN1T_CauseProtocol_ToEnum2 (pctxt, value, valueLen, pvalue);
}

int ASN1T_CauseProtocol_ToEnum2 (OSCTXT* pctxt,
   const OSUTF8CHAR* value, OSSIZE valueLen, ASN1T_CauseProtocol* pvalue)
{
   OSINT32 idx = rtxLookupEnum (value, valueLen, ASN1T_CauseProtocol_ENUMTAB, 
      ASN1T_CauseProtocol_ENUMTABSIZE);

   if (idx >= 0) {
      *pvalue = (ASN1T_CauseProtocol)ASN1T_CauseProtocol_ENUMTAB[idx].value;
      return 0;
   }
   else {
      rtxErrAddStrParm (pctxt, (const char*)value);
      return LOG_RTERR (pctxt, RTERR_INVENUM);
   }
}

ASN1T_CauseProtocol* new_ASN1T_CauseProtocol (ASN1CType& ccobj)
{
   void* pdata = ccobj.memAlloc (sizeof(ASN1T_CauseProtocol));
   if (0 == pdata) return 0;
   else return new (pdata) ASN1T_CauseProtocol;
}

/* ASN1T_CauseMisc */

const OSEnumItem ASN1T_CauseMisc_ENUMTAB[] = {
   { OSUTF8("control-processing-overload"), 0, 27, 0 },
   { OSUTF8("hardware-failure"), 1, 16, 1 },
   { OSUTF8("om-intervention"), 2, 15, 2 },
   { OSUTF8("unspecified"), 3, 11, 3 }
} ;

const OSUTF8CHAR* ASN1T_CauseMisc_ToString (OSINT32 value)
{
   OSINT32 idx = value;

   if (idx >= 0 && idx < ASN1T_CauseMisc_ENUMTABSIZE) {
      return ASN1T_CauseMisc_ENUMTAB
         [ASN1T_CauseMisc_ENUMTAB[idx].transidx].name;
   }
   else
      return OSUTF8("_UNKNOWN_");
}

int ASN1T_CauseMisc_ToEnum (OSCTXT* pctxt,
   const OSUTF8CHAR* value, ASN1T_CauseMisc* pvalue)
{
   OSSIZE valueLen = rtxUTF8LenBytes (value);
   return ASN1T_CauseMisc_ToEnum2 (pctxt, value, valueLen, pvalue);
}

int ASN1T_CauseMisc_ToEnum2 (OSCTXT* pctxt,
   const OSUTF8CHAR* value, OSSIZE valueLen, ASN1T_CauseMisc* pvalue)
{
   OSINT32 idx = rtxLookupEnum (value, valueLen, ASN1T_CauseMisc_ENUMTAB, 
      ASN1T_CauseMisc_ENUMTABSIZE);

   if (idx >= 0) {
      *pvalue = (ASN1T_CauseMisc)ASN1T_CauseMisc_ENUMTAB[idx].value;
      return 0;
   }
   else {
      rtxErrAddStrParm (pctxt, (const char*)value);
      return LOG_RTERR (pctxt, RTERR_INVENUM);
   }
}

ASN1T_CauseMisc* new_ASN1T_CauseMisc (ASN1CType& ccobj)
{
   void* pdata = ccobj.memAlloc (sizeof(ASN1T_CauseMisc));
   if (0 == pdata) return 0;
   else return new (pdata) ASN1T_CauseMisc;
}

/* ASN1T_Cause */

ASN1T_Cause* new_ASN1T_Cause (ASN1CType& ccobj)
{
   void* pdata = ccobj.memAlloc (sizeof(ASN1T_Cause));
   if (0 == pdata) return 0;
   else return new (pdata) ASN1T_Cause;
}

int asn1Init_Cause (ASN1T_Cause* pvalue, OSBOOL free, OSCTXT *pctxt)
{
   if (0 == pvalue) return RTERR_NULLPTR;
   if (free) {
      asn1Free_Cause (pctxt, pvalue);
   }
   else {
      pvalue->t = 0;
      OSCRTLMEMSET (&pvalue->u, 0, sizeof(pvalue->u));
   }
   return 0;
}

void asn1Free_Cause (OSCTXT *pctxt, ASN1T_Cause* pvalue)
{
   if (0 == pvalue) return;
   switch (pvalue->t) {
      case 0: break; /* no choice; nothing to free */
      case 1:
         break;

      case 2:
         break;

      case 3:
         break;

      case 4:
         break;

      case 5:
         break;

      case 6:
         break;

      default:
         if (0 != pvalue->u.extElem1) {
            if (!rtxCtxtTestFlag (pctxt, ASN1FASTCOPY)) {
               rtxMemFreePtr (pctxt, (void*)pvalue->u.extElem1->data);
               pvalue->u.extElem1->data = 0;
            }
            rtxMemFreePtr (pctxt, (void*)pvalue->u.extElem1);
            pvalue->u.extElem1 = 0;
         }
   }
}

/* ASN1T_XAPP_ID */

ASN1T_XAPP_ID* new_ASN1T_XAPP_ID (ASN1CType& ccobj)
{
   void* pdata = ccobj.memAlloc (sizeof(ASN1T_XAPP_ID));
   if (0 == pdata) return 0;
   else return new (pdata) ASN1T_XAPP_ID;
}

/* ASN1T_RICindicationSN */

ASN1T_RICindicationSN* new_ASN1T_RICindicationSN (ASN1CType& ccobj)
{
   void* pdata = ccobj.memAlloc (sizeof(ASN1T_RICindicationSN));
   if (0 == pdata) return 0;
   else return new (pdata) ASN1T_RICindicationSN;
}

/* ASN1T_RICindicationType */

const OSEnumItem ASN1T_RICindicationType_ENUMTAB[] = {
   { OSUTF8("insert"), 1, 6, 1 },
   { OSUTF8("report"), 0, 6, 0 }
} ;

const OSUTF8CHAR* ASN1T_RICindicationType_ToString (OSINT32 value)
{
   OSINT32 idx = value;

   if (idx >= 0 && idx < ASN1T_RICindicationType_ENUMTABSIZE) {
      return ASN1T_RICindicationType_ENUMTAB
         [ASN1T_RICindicationType_ENUMTAB[idx].transidx].name;
   }
   else
      return OSUTF8("_UNKNOWN_");
}

int ASN1T_RICindicationType_ToEnum (OSCTXT* pctxt,
   const OSUTF8CHAR* value, ASN1T_RICindicationType* pvalue)
{
   OSSIZE valueLen = rtxUTF8LenBytes (value);
   return ASN1T_RICindicationType_ToEnum2 (pctxt, value, valueLen, pvalue);
}

int ASN1T_RICindicationType_ToEnum2 (OSCTXT* pctxt,
   const OSUTF8CHAR* value, OSSIZE valueLen, ASN1T_RICindicationType* pvalue)
{
   OSINT32 idx = rtxLookupEnum (value, valueLen, 
      ASN1T_RICindicationType_ENUMTAB, ASN1T_RICindicationType_ENUMTABSIZE);

   if (idx >= 0) {
      *pvalue = (ASN1T_RICindicationType)
         ASN1T_RICindicationType_ENUMTAB[idx].value;
      return 0;
   }
   else {
      rtxErrAddStrParm (pctxt, (const char*)value);
      return LOG_RTERR (pctxt, RTERR_INVENUM);
   }
}

ASN1T_RICindicationType* new_ASN1T_RICindicationType (ASN1CType& ccobj)
{
   void* pdata = ccobj.memAlloc (sizeof(ASN1T_RICindicationType));
   if (0 == pdata) return 0;
   else return new (pdata) ASN1T_RICindicationType;
}

/* ASN1T_RICindicationHeader */

ASN1T_RICindicationHeader* new_ASN1T_RICindicationHeader (ASN1CType& ccobj)
{
   void* pdata = ccobj.memAlloc (sizeof(ASN1T_RICindicationHeader));
   if (0 == pdata) return 0;
   else return new (pdata) ASN1T_RICindicationHeader;
}

int asn1Init_RICindicationHeader (ASN1T_RICindicationHeader* pvalue, 
   OSBOOL free, OSCTXT *pctxt)
{
   if (0 == pvalue) return RTERR_NULLPTR;
   pvalue->numocts = 0;
   pvalue->data = 0;
   return 0;
}

void asn1Free_RICindicationHeader (OSCTXT *pctxt, 
   ASN1T_RICindicationHeader* pvalue)
{
   if (0 == pvalue) return;
   if (pvalue->numocts > 0) {
      rtxMemFreePtr (pctxt, (void*)pvalue->data);
      pvalue->numocts = 0;
      pvalue->data = 0;
   }
}

/* ASN1T_RICindicationMessage */

ASN1T_RICindicationMessage* new_ASN1T_RICindicationMessage (ASN1CType& ccobj)
{
   void* pdata = ccobj.memAlloc (sizeof(ASN1T_RICindicationMessage));
   if (0 == pdata) return 0;
   else return new (pdata) ASN1T_RICindicationMessage;
}

int asn1Init_RICindicationMessage (ASN1T_RICindicationMessage* pvalue, 
   OSBOOL free, OSCTXT *pctxt)
{
   if (0 == pvalue) return RTERR_NULLPTR;
   pvalue->numocts = 0;
   pvalue->data = 0;
   return 0;
}

void asn1Free_RICindicationMessage (OSCTXT *pctxt, 
   ASN1T_RICindicationMessage* pvalue)
{
   if (0 == pvalue) return;
   if (pvalue->numocts > 0) {
      rtxMemFreePtr (pctxt, (void*)pvalue->data);
      pvalue->numocts = 0;
      pvalue->data = 0;
   }
}

/* ASN1T_TypeOfError */

const OSEnumItem ASN1T_TypeOfError_ENUMTAB[] = {
   { OSUTF8("missing"), 1, 7, 1 },
   { OSUTF8("not-understood"), 0, 14, 0 }
} ;

const OSUTF8CHAR* ASN1T_TypeOfError_ToString (OSINT32 value)
{
   OSINT32 idx = value;

   if (idx >= 0 && idx < ASN1T_TypeOfError_ENUMTABSIZE) {
      return ASN1T_TypeOfError_ENUMTAB
         [ASN1T_TypeOfError_ENUMTAB[idx].transidx].name;
   }
   else
      return OSUTF8("_UNKNOWN_");
}

int ASN1T_TypeOfError_ToEnum (OSCTXT* pctxt,
   const OSUTF8CHAR* value, ASN1T_TypeOfError* pvalue)
{
   OSSIZE valueLen = rtxUTF8LenBytes (value);
   return ASN1T_TypeOfError_ToEnum2 (pctxt, value, valueLen, pvalue);
}

int ASN1T_TypeOfError_ToEnum2 (OSCTXT* pctxt,
   const OSUTF8CHAR* value, OSSIZE valueLen, ASN1T_TypeOfError* pvalue)
{
   OSINT32 idx = rtxLookupEnum (value, valueLen, ASN1T_TypeOfError_ENUMTAB, 
      ASN1T_TypeOfError_ENUMTABSIZE);

   if (idx >= 0) {
      *pvalue = (ASN1T_TypeOfError)ASN1T_TypeOfError_ENUMTAB[idx].value;
      return 0;
   }
   else {
      rtxErrAddStrParm (pctxt, (const char*)value);
      return LOG_RTERR (pctxt, RTERR_INVENUM);
   }
}

ASN1T_TypeOfError* new_ASN1T_TypeOfError (ASN1CType& ccobj)
{
   void* pdata = ccobj.memAlloc (sizeof(ASN1T_TypeOfError));
   if (0 == pdata) return 0;
   else return new (pdata) ASN1T_TypeOfError;
}

/* ASN1T_CriticalityDiagnostics_IE_Item */

ASN1T_CriticalityDiagnostics_IE_Item* 
   new_ASN1T_CriticalityDiagnostics_IE_Item (ASN1CType& ccobj)
{
   void* pdata = ccobj.memAlloc (sizeof(ASN1T_CriticalityDiagnostics_IE_Item));
   if (0 == pdata) return 0;
   else return new (pdata) ASN1T_CriticalityDiagnostics_IE_Item;
}

int asn1Init_CriticalityDiagnostics_IE_Item (
   ASN1T_CriticalityDiagnostics_IE_Item* pvalue, OSBOOL free, OSCTXT *pctxt)
{
   if (0 == pvalue) return RTERR_NULLPTR;
   rtxDListFastInit (&pvalue->extElem1);
   return 0;
}

void asn1Free_CriticalityDiagnostics_IE_Item (OSCTXT *pctxt, 
   ASN1T_CriticalityDiagnostics_IE_Item* pvalue)
{
   if (0 == pvalue) return;
   rtxMemFreeOpenSeqExt (pctxt, &pvalue->extElem1);
}

/* ASN1T_CriticalityDiagnostics_IE_List */

ASN1T_CriticalityDiagnostics_IE_List* 
   new_ASN1T_CriticalityDiagnostics_IE_List (ASN1CType& ccobj)
{
   void* pdata = ccobj.memAlloc (sizeof(ASN1T_CriticalityDiagnostics_IE_List));
   if (0 == pdata) return 0;
   else return new (pdata) ASN1T_CriticalityDiagnostics_IE_List;
}

ASN1C_CriticalityDiagnostics_IE_List::ASN1C_CriticalityDiagnostics_IE_List
    (ASN1T_CriticalityDiagnostics_IE_List& data) : ASN1CSeqOfList(data)
   , msgData(data)
{
   setRunTimeKey (_rtkey, sizeof(_rtkey));
}

ASN1C_CriticalityDiagnostics_IE_List::ASN1C_CriticalityDiagnostics_IE_List (
   OSRTMessageBufferIF& msgBuf, ASN1T_CriticalityDiagnostics_IE_List& data) : 
   ASN1CSeqOfList(msgBuf, data), msgData(data)
{
   setRunTimeKey (_rtkey, sizeof(_rtkey));
}
ASN1C_CriticalityDiagnostics_IE_List::ASN1C_CriticalityDiagnostics_IE_List (
   OSRTContext &context, ASN1T_CriticalityDiagnostics_IE_List& data) : 
   ASN1CSeqOfList(context, data), msgData(data)
{
   setRunTimeKey (_rtkey, sizeof(_rtkey));
}


ASN1C_CriticalityDiagnostics_IE_List::
   ASN1C_CriticalityDiagnostics_IE_List (ASN1CType& ccobj
   , ASN1T_CriticalityDiagnostics_IE_List& data) :
   ASN1CSeqOfList(ccobj, data), msgData(data)
{
   setRunTimeKey (_rtkey, sizeof(_rtkey));
}

void ASN1C_CriticalityDiagnostics_IE_List::Append (ASN1T_CriticalityDiagnostics_IE_Item* elem)
{
   append ((void*)elem);
}

void ASN1C_CriticalityDiagnostics_IE_List::freeMemory() { asn1Free_CriticalityDiagnostics_IE_List(getCtxtPtr(), &msgData); }
ASN1T_CriticalityDiagnostics_IE_Item* ASN1C_CriticalityDiagnostics_IE_List::NewElement ()
{
   void* pdata = memAlloc (sizeof(ASN1T_CriticalityDiagnostics_IE_Item));

   if (0 == pdata) return 0;
   else return new (pdata) ASN1T_CriticalityDiagnostics_IE_Item;
}

ASN1T_CriticalityDiagnostics_IE_Item* ASN1C_CriticalityDiagnostics_IE_List::AppendNewElement ()
{
   ASN1T_CriticalityDiagnostics_IE_Item* pdata = NewElement();
   if (0 != pdata) {
      Append (pdata);
   }
   return pdata;
}

int asn1Init_CriticalityDiagnostics_IE_List (
   ASN1T_CriticalityDiagnostics_IE_List* pvalue, OSBOOL free, OSCTXT *pctxt)
{
   if (0 == pvalue) return RTERR_NULLPTR;
   rtxDListFastInit (pvalue);
   return 0;
}

void asn1Free_CriticalityDiagnostics_IE_List (OSCTXT *pctxt, 
   ASN1T_CriticalityDiagnostics_IE_List* pvalue)
{
   if (0 == pvalue) return;
   { ASN1T_CriticalityDiagnostics_IE_Item* pdata;
   OSRTDListNode* pnode = pvalue->head;
   while (0 != pnode) {
      pdata = (ASN1T_CriticalityDiagnostics_IE_Item*)pnode->data;
      asn1Free_CriticalityDiagnostics_IE_Item (pctxt, pdata);
      pnode = pnode->next;
   }
   rtxDListFreeAll (pctxt, pvalue);
   }
}

/* ASN1T_CriticalityDiagnostics */

ASN1T_CriticalityDiagnostics* 
   new_ASN1T_CriticalityDiagnostics (ASN1CType& ccobj)
{
   void* pdata = ccobj.memAlloc (sizeof(ASN1T_CriticalityDiagnostics));
   if (0 == pdata) return 0;
   else return new (pdata) ASN1T_CriticalityDiagnostics;
}

ASN1T_CriticalityDiagnostics::ASN1T_CriticalityDiagnostics ()
{
   m.procedureCodePresent = 0;
   m.triggeringMessagePresent = 0;
   m.procedureCriticalityPresent = 0;
   m.ricRequestorIDPresent = 0;
   m.iEsCriticalityDiagnosticsPresent = 0;
}

int asn1Init_CriticalityDiagnostics (ASN1T_CriticalityDiagnostics* pvalue, 
   OSBOOL free, OSCTXT *pctxt)
{
   if (0 == pvalue) return RTERR_NULLPTR;
   OSCRTLMEMSET (&pvalue->m, 0, sizeof (pvalue->m));
   asn1Init_RICrequestID (&pvalue->ricRequestorID, free, pctxt);
   asn1Init_CriticalityDiagnostics_IE_List (&pvalue->iEsCriticalityDiagnostics, free, pctxt);
   rtxDListFastInit (&pvalue->extElem1);
   return 0;
}

void asn1Free_CriticalityDiagnostics (OSCTXT *pctxt, 
   ASN1T_CriticalityDiagnostics* pvalue)
{
   if (0 == pvalue) return;
   if (pvalue->m.ricRequestorIDPresent) {
      asn1Free_RICrequestID (pctxt, &pvalue->ricRequestorID);
   }
   if (pvalue->m.iEsCriticalityDiagnosticsPresent) {
      asn1Free_CriticalityDiagnostics_IE_List (pctxt, &pvalue->iEsCriticalityDiagnostics);
   }
   rtxMemFreeOpenSeqExt (pctxt, &pvalue->extElem1);
}

/* ASN1T_RICcontrolOutcome */

ASN1T_RICcontrolOutcome* new_ASN1T_RICcontrolOutcome (ASN1CType& ccobj)
{
   void* pdata = ccobj.memAlloc (sizeof(ASN1T_RICcontrolOutcome));
   if (0 == pdata) return 0;
   else return new (pdata) ASN1T_RICcontrolOutcome;
}

int asn1Init_RICcontrolOutcome (ASN1T_RICcontrolOutcome* pvalue, 
   OSBOOL free, OSCTXT *pctxt)
{
   if (0 == pvalue) return RTERR_NULLPTR;
   pvalue->numocts = 0;
   pvalue->data = 0;
   return 0;
}

void asn1Free_RICcontrolOutcome (OSCTXT *pctxt, 
   ASN1T_RICcontrolOutcome* pvalue)
{
   if (0 == pvalue) return;
   if (pvalue->numocts > 0) {
      rtxMemFreePtr (pctxt, (void*)pvalue->data);
      pvalue->numocts = 0;
      pvalue->data = 0;
   }
}

/* ASN1T_GlobalRIC_ID */

ASN1T_GlobalRIC_ID* new_ASN1T_GlobalRIC_ID (ASN1CType& ccobj)
{
   void* pdata = ccobj.memAlloc (sizeof(ASN1T_GlobalRIC_ID));
   if (0 == pdata) return 0;
   else return new (pdata) ASN1T_GlobalRIC_ID;
}

int asn1Init_GlobalRIC_ID (ASN1T_GlobalRIC_ID* pvalue, 
   OSBOOL free, OSCTXT *pctxt)
{
   if (0 == pvalue) return RTERR_NULLPTR;
   asn1Init_PLMN_Identity (&pvalue->pLMN_Identity, free, pctxt);
   pvalue->ric_ID.numbits = 0;
   rtxDListFastInit (&pvalue->extElem1);
   return 0;
}

void asn1Free_GlobalRIC_ID (OSCTXT *pctxt, ASN1T_GlobalRIC_ID* pvalue)
{
   if (0 == pvalue) return;
   rtxMemFreeOpenSeqExt (pctxt, &pvalue->extElem1);
}

/* ASN1T_E2nodeComponentConfigurationAck_updateOutcome */

const OSEnumItem ASN1T_E2nodeComponentConfigurationAck_updateOutcome_ENUMTAB[] = {
   { OSUTF8("failure"), 1, 7, 1 },
   { OSUTF8("success"), 0, 7, 0 }
} ;

const OSUTF8CHAR* ASN1T_E2nodeComponentConfigurationAck_updateOutcome_ToString (OSINT32 value)
{
   OSINT32 idx = value;

   if (idx >= 0 && idx < ASN1T_E2nodeComponentConfigurationAck_updateOutcome_ENUMTABSIZE) {
      return ASN1T_E2nodeComponentConfigurationAck_updateOutcome_ENUMTAB
         [ASN1T_E2nodeComponentConfigurationAck_updateOutcome_ENUMTAB[idx].transidx].name;
   }
   else
      return OSUTF8("_UNKNOWN_");
}

int ASN1T_E2nodeComponentConfigurationAck_updateOutcome_ToEnum (OSCTXT* pctxt,
   const OSUTF8CHAR* value, 
      ASN1T_E2nodeComponentConfigurationAck_updateOutcome* pvalue)
{
   OSSIZE valueLen = rtxUTF8LenBytes (value);
   return ASN1T_E2nodeComponentConfigurationAck_updateOutcome_ToEnum2 (pctxt, value, valueLen, pvalue);
}

int ASN1T_E2nodeComponentConfigurationAck_updateOutcome_ToEnum2 (OSCTXT* pctxt,
   const OSUTF8CHAR* value, OSSIZE valueLen, 
      ASN1T_E2nodeComponentConfigurationAck_updateOutcome* pvalue)
{
   OSINT32 idx = rtxLookupEnum (value, valueLen, 
      ASN1T_E2nodeComponentConfigurationAck_updateOutcome_ENUMTAB, 
      ASN1T_E2nodeComponentConfigurationAck_updateOutcome_ENUMTABSIZE);

   if (idx >= 0) {
      *pvalue = (ASN1T_E2nodeComponentConfigurationAck_updateOutcome)
         ASN1T_E2nodeComponentConfigurationAck_updateOutcome_ENUMTAB[idx].value;
      return 0;
   }
   else {
      rtxErrAddStrParm (pctxt, (const char*)value);
      return LOG_RTERR (pctxt, RTERR_INVENUM);
   }
}

ASN1T_E2nodeComponentConfigurationAck_updateOutcome* 
   new_ASN1T_E2nodeComponentConfigurationAck_updateOutcome (ASN1CType& ccobj)
{
   void* pdata = ccobj.memAlloc (sizeof(ASN1T_E2nodeComponentConfigurationAck_updateOutcome));
   if (0 == pdata) return 0;
   else return new (pdata) ASN1T_E2nodeComponentConfigurationAck_updateOutcome;
}

/* ASN1T_E2nodeComponentConfigurationAck */

ASN1T_E2nodeComponentConfigurationAck* 
   new_ASN1T_E2nodeComponentConfigurationAck (ASN1CType& ccobj)
{
   void* pdata = ccobj.memAlloc (sizeof(ASN1T_E2nodeComponentConfigurationAck));
   if (0 == pdata) return 0;
   else return new (pdata) ASN1T_E2nodeComponentConfigurationAck;
}

ASN1T_E2nodeComponentConfigurationAck::ASN1T_E2nodeComponentConfigurationAck ()
{
   m.failureCausePresent = 0;
}

int asn1Init_E2nodeComponentConfigurationAck (
   ASN1T_E2nodeComponentConfigurationAck* pvalue, OSBOOL free, OSCTXT *pctxt)
{
   if (0 == pvalue) return RTERR_NULLPTR;
   OSCRTLMEMSET (&pvalue->m, 0, sizeof (pvalue->m));
   asn1Init_Cause (&pvalue->failureCause, free, pctxt);
   rtxDListFastInit (&pvalue->extElem1);
   return 0;
}

void asn1Free_E2nodeComponentConfigurationAck (OSCTXT *pctxt, 
   ASN1T_E2nodeComponentConfigurationAck* pvalue)
{
   if (0 == pvalue) return;
   if (pvalue->m.failureCausePresent) {
      asn1Free_Cause (pctxt, &pvalue->failureCause);
   }
   rtxMemFreeOpenSeqExt (pctxt, &pvalue->extElem1);
}

/* ASN1T_TimeToWait */

const OSEnumItem ASN1T_TimeToWait_ENUMTAB[] = {
   { OSUTF8("v10s"), 3, 4, 1 },
   { OSUTF8("v1s"), 0, 3, 3 },
   { OSUTF8("v20s"), 4, 4, 4 },
   { OSUTF8("v2s"), 1, 3, 0 },
   { OSUTF8("v5s"), 2, 3, 2 },
   { OSUTF8("v60s"), 5, 4, 5 }
} ;

const OSUTF8CHAR* ASN1T_TimeToWait_ToString (OSINT32 value)
{
   OSINT32 idx = value;

   if (idx >= 0 && idx < ASN1T_TimeToWait_ENUMTABSIZE) {
      return ASN1T_TimeToWait_ENUMTAB
         [ASN1T_TimeToWait_ENUMTAB[idx].transidx].name;
   }
   else
      return OSUTF8("_UNKNOWN_");
}

int ASN1T_TimeToWait_ToEnum (OSCTXT* pctxt,
   const OSUTF8CHAR* value, ASN1T_TimeToWait* pvalue)
{
   OSSIZE valueLen = rtxUTF8LenBytes (value);
   return ASN1T_TimeToWait_ToEnum2 (pctxt, value, valueLen, pvalue);
}

int ASN1T_TimeToWait_ToEnum2 (OSCTXT* pctxt,
   const OSUTF8CHAR* value, OSSIZE valueLen, ASN1T_TimeToWait* pvalue)
{
   OSINT32 idx = rtxLookupEnum (value, valueLen, ASN1T_TimeToWait_ENUMTAB, 
      ASN1T_TimeToWait_ENUMTABSIZE);

   if (idx >= 0) {
      *pvalue = (ASN1T_TimeToWait)ASN1T_TimeToWait_ENUMTAB[idx].value;
      return 0;
   }
   else {
      rtxErrAddStrParm (pctxt, (const char*)value);
      return LOG_RTERR (pctxt, RTERR_INVENUM);
   }
}

ASN1T_TimeToWait* new_ASN1T_TimeToWait (ASN1CType& ccobj)
{
   void* pdata = ccobj.memAlloc (sizeof(ASN1T_TimeToWait));
   if (0 == pdata) return 0;
   else return new (pdata) ASN1T_TimeToWait;
}

