/**
 * This file was generated by the Objective Systems ASN1C Compiler
 * (http://www.obj-sys.com).  Version: 7.8.2.5, Date: 12-Sep-2025.
 *
 * Command:  asn1c asn1files/E2SM-KPM-v05.00.asn asn1files/asn_flexric/e2sm_rc_v1_03_modified.asn asn1files/asn_flexric/e42ap_v2_03.asn -genTest -per -json -w32 -server -depends -events -genPrtToStr -list -reader -trace -c++ -print -prtfmt details -srcdir src -make Makefile -w32 -table-unions -stream -pdu all
 */
#include "E2AP-IEs.h"
#include "E2AP-Constants.h"
#include "rtxsrc/rtxCharStr.h"
#include "rtsrc/rtPrintToString.h"
#include "rtsrc/rtBCD.h"
#include "rtxsrc/rtxDiag.h"

int asn1PrtToStr_RICrequestID (const char* name, ASN1T_RICrequestID* pvalue, 
   char* buffer, OSSIZE bufSize)
{
   char namebuf[512];

   rtxStrJoin (namebuf, 512, name, ".ricRequestorID", 0, 0, 0);
   if (rtPrintToStringUnsigned (namebuf, pvalue->ricRequestorID, buffer, bufSize) < 0)
   {
      return -1;
   }

   rtxStrJoin (namebuf, 512, name, ".ricInstanceID", 0, 0, 0);
   if (rtPrintToStringUnsigned (namebuf, pvalue->ricInstanceID, buffer, bufSize) < 0)
   {
      return -1;
   }

   rtxStrJoin (namebuf, 512, name, ".extElem1", 0, 0, 0);
   if (rtPrintToStringOpenTypeExt (namebuf, &pvalue->extElem1, buffer, bufSize)  < 0)
   {
      return -1;
   }

   return 0;
}

int ASN1C_RICrequestID::toString (const char* name, char* buffer, OSSIZE bufSize)
{
   if (asn1PrtToStr_RICrequestID (name, &msgData, buffer, bufSize) < 0)
   {
      return -1;
   }
   return 0;
}

int ASN1C_RICrequestID::toString (char* buffer, OSSIZE bufSize)
{
   return toString ("RICrequestID", buffer, bufSize);
}

int asn1PrtToStr_RANfunctionID (const char* name, ASN1T_RANfunctionID* pvalue, 
   char* buffer, OSSIZE bufSize)
{
   if (rtPrintToStringUnsigned (name, *pvalue, buffer, bufSize) < 0)
   {
      return -1;
   }
   return 0;
}

int ASN1C_RANfunctionID::toString (const char* name, char* buffer, OSSIZE bufSize)
{
   if (asn1PrtToStr_RANfunctionID (name, &msgData, buffer, bufSize) < 0)
   {
      return -1;
   }
   return 0;
}

int ASN1C_RANfunctionID::toString (char* buffer, OSSIZE bufSize)
{
   return toString ("RANfunctionID", buffer, bufSize);
}

int asn1PrtToStr_RICeventTriggerDefinition (const char* name, 
   ASN1T_RICeventTriggerDefinition* pvalue, char* buffer, OSSIZE bufSize)
{
   if (rtPrintToStringOctStr (name, pvalue->numocts, pvalue->data, ".", buffer, bufSize) < 0)
   {
      return -1;
   }
   return 0;
}

int ASN1C_RICeventTriggerDefinition::toString (const char* name, char* buffer, OSSIZE bufSize)
{
   if (asn1PrtToStr_RICeventTriggerDefinition (name, &msgData, buffer, bufSize) < 0)
   {
      return -1;
   }
   return 0;
}

int ASN1C_RICeventTriggerDefinition::toString (char* buffer, OSSIZE bufSize)
{
   return toString ("RICeventTriggerDefinition", buffer, bufSize);
}

int asn1PrtToStr_RICactionID (const char* name, ASN1T_RICactionID* pvalue, 
   char* buffer, OSSIZE bufSize)
{
   if (rtPrintToStringUnsigned (name, *pvalue, buffer, bufSize) < 0)
   {
      return -1;
   }
   return 0;
}

int ASN1C_RICactionID::toString (const char* name, char* buffer, OSSIZE bufSize)
{
   if (asn1PrtToStr_RICactionID (name, &msgData, buffer, bufSize) < 0)
   {
      return -1;
   }
   return 0;
}

int ASN1C_RICactionID::toString (char* buffer, OSSIZE bufSize)
{
   return toString ("RICactionID", buffer, bufSize);
}

int asn1PrtToStr_RICactionType (const char* name, ASN1T_RICactionType* pvalue, 
   char* buffer, OSSIZE bufSize)
{
   int stat;
   if(rtPrintToString (name, buffer, bufSize) < 0)
   {
      return -1;
   }
   switch (*pvalue) {
      case 0:
         stat = rtPrintToString (" = report\n", buffer, bufSize);
         break;

      case 1:
         stat = rtPrintToString (" = insert\n", buffer, bufSize);
         break;

      case 2:
         stat = rtPrintToString (" = policy\n", buffer, bufSize);
         break;

      default: stat = rtPrintToStringUnsigned ("", *pvalue, buffer, bufSize);
   }

   if(stat < 0) return -1;
   return 0;
}

int ASN1C_RICactionType::toString (const char* name, char* buffer, OSSIZE bufSize)
{
   if (asn1PrtToStr_RICactionType (name, &msgData, buffer, bufSize) < 0)
   {
      return -1;
   }
   return 0;
}

int ASN1C_RICactionType::toString (char* buffer, OSSIZE bufSize)
{
   return toString ("RICactionType", buffer, bufSize);
}

int asn1PrtToStr_RICactionDefinition (const char* name, 
   ASN1T_RICactionDefinition* pvalue, char* buffer, OSSIZE bufSize)
{
   if (rtPrintToStringOctStr (name, pvalue->numocts, pvalue->data, ".", buffer, bufSize) < 0)
   {
      return -1;
   }
   return 0;
}

int ASN1C_RICactionDefinition::toString (const char* name, char* buffer, OSSIZE bufSize)
{
   if (asn1PrtToStr_RICactionDefinition (name, &msgData, buffer, bufSize) < 0)
   {
      return -1;
   }
   return 0;
}

int ASN1C_RICactionDefinition::toString (char* buffer, OSSIZE bufSize)
{
   return toString ("RICactionDefinition", buffer, bufSize);
}

int asn1PrtToStr_RICsubsequentActionType (const char* name, 
   ASN1T_RICsubsequentActionType* pvalue, char* buffer, OSSIZE bufSize)
{
   int stat;
   if(rtPrintToString (name, buffer, bufSize) < 0)
   {
      return -1;
   }
   switch (*pvalue) {
      case 0:
         stat = rtPrintToString (" = continue\n", buffer, bufSize);
         break;

      case 1:
         stat = rtPrintToString (" = wait\n", buffer, bufSize);
         break;

      default: stat = rtPrintToStringUnsigned ("", *pvalue, buffer, bufSize);
   }

   if(stat < 0) return -1;
   return 0;
}

int ASN1C_RICsubsequentActionType::toString (const char* name, char* buffer, OSSIZE bufSize)
{
   if (asn1PrtToStr_RICsubsequentActionType (name, &msgData, buffer, bufSize) < 0)
   {
      return -1;
   }
   return 0;
}

int ASN1C_RICsubsequentActionType::toString (char* buffer, OSSIZE bufSize)
{
   return toString ("RICsubsequentActionType", buffer, bufSize);
}

int asn1PrtToStr_RICtimeToWait (const char* name, ASN1T_RICtimeToWait* pvalue, 
   char* buffer, OSSIZE bufSize)
{
   int stat;
   if(rtPrintToString (name, buffer, bufSize) < 0)
   {
      return -1;
   }
   switch (*pvalue) {
      case 0:
         stat = rtPrintToString (" = w1ms\n", buffer, bufSize);
         break;

      case 1:
         stat = rtPrintToString (" = w2ms\n", buffer, bufSize);
         break;

      case 2:
         stat = rtPrintToString (" = w5ms\n", buffer, bufSize);
         break;

      case 3:
         stat = rtPrintToString (" = w10ms\n", buffer, bufSize);
         break;

      case 4:
         stat = rtPrintToString (" = w20ms\n", buffer, bufSize);
         break;

      case 5:
         stat = rtPrintToString (" = w30ms\n", buffer, bufSize);
         break;

      case 6:
         stat = rtPrintToString (" = w40ms\n", buffer, bufSize);
         break;

      case 7:
         stat = rtPrintToString (" = w50ms\n", buffer, bufSize);
         break;

      case 8:
         stat = rtPrintToString (" = w100ms\n", buffer, bufSize);
         break;

      case 9:
         stat = rtPrintToString (" = w200ms\n", buffer, bufSize);
         break;

      case 10:
         stat = rtPrintToString (" = w500ms\n", buffer, bufSize);
         break;

      case 11:
         stat = rtPrintToString (" = w1s\n", buffer, bufSize);
         break;

      case 12:
         stat = rtPrintToString (" = w2s\n", buffer, bufSize);
         break;

      case 13:
         stat = rtPrintToString (" = w5s\n", buffer, bufSize);
         break;

      case 14:
         stat = rtPrintToString (" = w10s\n", buffer, bufSize);
         break;

      case 15:
         stat = rtPrintToString (" = w20s\n", buffer, bufSize);
         break;

      case 16:
         stat = rtPrintToString (" = w60s\n", buffer, bufSize);
         break;

      default: stat = rtPrintToStringUnsigned ("", *pvalue, buffer, bufSize);
   }

   if(stat < 0) return -1;
   return 0;
}

int ASN1C_RICtimeToWait::toString (const char* name, char* buffer, OSSIZE bufSize)
{
   if (asn1PrtToStr_RICtimeToWait (name, &msgData, buffer, bufSize) < 0)
   {
      return -1;
   }
   return 0;
}

int ASN1C_RICtimeToWait::toString (char* buffer, OSSIZE bufSize)
{
   return toString ("RICtimeToWait", buffer, bufSize);
}

int asn1PrtToStr_RICsubsequentAction (const char* name, 
   ASN1T_RICsubsequentAction* pvalue, char* buffer, OSSIZE bufSize)
{
   char namebuf[512];

   rtxStrJoin (namebuf, 512, name, ".ricSubsequentActionType", 0, 0, 0);
   if (asn1PrtToStr_RICsubsequentActionType (namebuf, &pvalue->ricSubsequentActionType, buffer, bufSize) < 0)
   {
      return -1;
   }

   rtxStrJoin (namebuf, 512, name, ".ricTimeToWait", 0, 0, 0);
   if (asn1PrtToStr_RICtimeToWait (namebuf, &pvalue->ricTimeToWait, buffer, bufSize) < 0)
   {
      return -1;
   }

   rtxStrJoin (namebuf, 512, name, ".extElem1", 0, 0, 0);
   if (rtPrintToStringOpenTypeExt (namebuf, &pvalue->extElem1, buffer, bufSize)  < 0)
   {
      return -1;
   }

   return 0;
}

int ASN1C_RICsubsequentAction::toString (const char* name, char* buffer, OSSIZE bufSize)
{
   if (asn1PrtToStr_RICsubsequentAction (name, &msgData, buffer, bufSize) < 0)
   {
      return -1;
   }
   return 0;
}

int ASN1C_RICsubsequentAction::toString (char* buffer, OSSIZE bufSize)
{
   return toString ("RICsubsequentAction", buffer, bufSize);
}

int asn1PrtToStr_TransactionID (const char* name, ASN1T_TransactionID* pvalue, 
   char* buffer, OSSIZE bufSize)
{
   if (rtPrintToStringUnsigned (name, *pvalue, buffer, bufSize) < 0)
   {
      return -1;
   }
   return 0;
}

int ASN1C_TransactionID::toString (const char* name, char* buffer, OSSIZE bufSize)
{
   if (asn1PrtToStr_TransactionID (name, &msgData, buffer, bufSize) < 0)
   {
      return -1;
   }
   return 0;
}

int ASN1C_TransactionID::toString (char* buffer, OSSIZE bufSize)
{
   return toString ("TransactionID", buffer, bufSize);
}

int asn1PrtToStr_RANfunctionDefinition (const char* name, 
   ASN1T_RANfunctionDefinition* pvalue, char* buffer, OSSIZE bufSize)
{
   if (rtPrintToStringOctStr (name, pvalue->numocts, pvalue->data, ".", buffer, bufSize) < 0)
   {
      return -1;
   }
   return 0;
}

int ASN1C_RANfunctionDefinition::toString (const char* name, char* buffer, OSSIZE bufSize)
{
   if (asn1PrtToStr_RANfunctionDefinition (name, &msgData, buffer, bufSize) < 0)
   {
      return -1;
   }
   return 0;
}

int ASN1C_RANfunctionDefinition::toString (char* buffer, OSSIZE bufSize)
{
   return toString ("RANfunctionDefinition", buffer, bufSize);
}

int asn1PrtToStr_RANfunctionRevision (const char* name, 
   ASN1T_RANfunctionRevision* pvalue, char* buffer, OSSIZE bufSize)
{
   if (rtPrintToStringUnsigned (name, *pvalue, buffer, bufSize) < 0)
   {
      return -1;
   }
   return 0;
}

int ASN1C_RANfunctionRevision::toString (const char* name, char* buffer, OSSIZE bufSize)
{
   if (asn1PrtToStr_RANfunctionRevision (name, &msgData, buffer, bufSize) < 0)
   {
      return -1;
   }
   return 0;
}

int ASN1C_RANfunctionRevision::toString (char* buffer, OSSIZE bufSize)
{
   return toString ("RANfunctionRevision", buffer, bufSize);
}

int asn1PrtToStr_RANfunctionOID (const char* name, 
   ASN1T_RANfunctionOID pvalue, char* buffer, OSSIZE bufSize)
{
   if(rtPrintToStringCharStr (name, pvalue, buffer, bufSize) < 0)
   {
      return -1;
   }
   return 0;
}

int ASN1C_RANfunctionOID::toString (const char* name, char* buffer, OSSIZE bufSize)
{
   if (asn1PrtToStr_RANfunctionOID (name, msgData, buffer, bufSize) < 0)
   {
      return -1;
   }
   return 0;
}

int ASN1C_RANfunctionOID::toString (char* buffer, OSSIZE bufSize)
{
   return toString ("RANfunctionOID", buffer, bufSize);
}

int asn1PrtToStr_RICcallProcessID (const char* name, 
   ASN1T_RICcallProcessID* pvalue, char* buffer, OSSIZE bufSize)
{
   if (rtPrintToStringOctStr (name, pvalue->numocts, pvalue->data, ".", buffer, bufSize) < 0)
   {
      return -1;
   }
   return 0;
}

int ASN1C_RICcallProcessID::toString (const char* name, char* buffer, OSSIZE bufSize)
{
   if (asn1PrtToStr_RICcallProcessID (name, &msgData, buffer, bufSize) < 0)
   {
      return -1;
   }
   return 0;
}

int ASN1C_RICcallProcessID::toString (char* buffer, OSSIZE bufSize)
{
   return toString ("RICcallProcessID", buffer, bufSize);
}

int asn1PrtToStr_RICcontrolHeader (const char* name, 
   ASN1T_RICcontrolHeader* pvalue, char* buffer, OSSIZE bufSize)
{
   if (rtPrintToStringOctStr (name, pvalue->numocts, pvalue->data, ".", buffer, bufSize) < 0)
   {
      return -1;
   }
   return 0;
}

int ASN1C_RICcontrolHeader::toString (const char* name, char* buffer, OSSIZE bufSize)
{
   if (asn1PrtToStr_RICcontrolHeader (name, &msgData, buffer, bufSize) < 0)
   {
      return -1;
   }
   return 0;
}

int ASN1C_RICcontrolHeader::toString (char* buffer, OSSIZE bufSize)
{
   return toString ("RICcontrolHeader", buffer, bufSize);
}

int asn1PrtToStr_RICcontrolMessage (const char* name, 
   ASN1T_RICcontrolMessage* pvalue, char* buffer, OSSIZE bufSize)
{
   if (rtPrintToStringOctStr (name, pvalue->numocts, pvalue->data, ".", buffer, bufSize) < 0)
   {
      return -1;
   }
   return 0;
}

int ASN1C_RICcontrolMessage::toString (const char* name, char* buffer, OSSIZE bufSize)
{
   if (asn1PrtToStr_RICcontrolMessage (name, &msgData, buffer, bufSize) < 0)
   {
      return -1;
   }
   return 0;
}

int ASN1C_RICcontrolMessage::toString (char* buffer, OSSIZE bufSize)
{
   return toString ("RICcontrolMessage", buffer, bufSize);
}

int asn1PrtToStr_RICcontrolAckRequest (const char* name, 
   ASN1T_RICcontrolAckRequest* pvalue, char* buffer, OSSIZE bufSize)
{
   int stat;
   if(rtPrintToString (name, buffer, bufSize) < 0)
   {
      return -1;
   }
   switch (*pvalue) {
      case 0:
         stat = rtPrintToString (" = noAck\n", buffer, bufSize);
         break;

      case 1:
         stat = rtPrintToString (" = ack\n", buffer, bufSize);
         break;

      default: stat = rtPrintToStringUnsigned ("", *pvalue, buffer, bufSize);
   }

   if(stat < 0) return -1;
   return 0;
}

int ASN1C_RICcontrolAckRequest::toString (const char* name, char* buffer, OSSIZE bufSize)
{
   if (asn1PrtToStr_RICcontrolAckRequest (name, &msgData, buffer, bufSize) < 0)
   {
      return -1;
   }
   return 0;
}

int ASN1C_RICcontrolAckRequest::toString (char* buffer, OSSIZE bufSize)
{
   return toString ("RICcontrolAckRequest", buffer, bufSize);
}

int asn1PrtToStr_PLMN_Identity (const char* name, ASN1T_PLMN_Identity* pvalue, 
   char* buffer, OSSIZE bufSize)
{
   if (rtPrintToStringOctStr (name, OSRTMIN(sizeof(pvalue->data), pvalue->numocts), pvalue->data, ".", buffer, bufSize) < 0)
   {
      return -1;
   }
   return 0;
}

int ASN1C_PLMN_Identity::toString (const char* name, char* buffer, OSSIZE bufSize)
{
   if (asn1PrtToStr_PLMN_Identity (name, &msgData, buffer, bufSize) < 0)
   {
      return -1;
   }
   return 0;
}

int ASN1C_PLMN_Identity::toString (char* buffer, OSSIZE bufSize)
{
   return toString ("PLMN_Identity", buffer, bufSize);
}

int asn1PrtToStr_GNB_ID_Choice (const char* name, ASN1T_GNB_ID_Choice* pvalue, 
   char* buffer, OSSIZE bufSize)
{
   {
   char namebuf2[512], numbuf[32];

   rtxIntToCharStr (pvalue->t, numbuf, sizeof(numbuf), 0);
   rtxStrJoin (namebuf2, sizeof(namebuf2), name, ".t = ", numbuf, "\n", 0);
   if (rtPrintToString (namebuf2, buffer, bufSize) < 0)
   {
      return -1;
   }

   switch (pvalue->t) {
      /* gnb-ID */
      case 1:
      {
         rtxStrJoin (namebuf2, 512, name, ".u.gnb_ID", 0, 0, 0);
         if (rtPrintToStringBitStr (namebuf2, OS_MIN(pvalue->u.gnb_ID->numbits, 32), pvalue->u.gnb_ID->data, ".", buffer, bufSize) < 0)
         {
            return -1;
         }
         break;
      }
      /* extElem1 */
      case 2:
      {
         rtxStrJoin (namebuf2, 512, name, ".u.extElem1", 0, 0, 0);
         if(rtPrintToStringOpenType (namebuf2, pvalue->u.extElem1->numocts, pvalue->u.extElem1->data, ".", buffer, bufSize) < 0)
         {
            return -1;
         }
         break;
      }
      default:;
   }
   }
   return 0;
}

int ASN1C_GNB_ID_Choice::toString (const char* name, char* buffer, OSSIZE bufSize)
{
   if (asn1PrtToStr_GNB_ID_Choice (name, &msgData, buffer, bufSize) < 0)
   {
      return -1;
   }
   return 0;
}

int ASN1C_GNB_ID_Choice::toString (char* buffer, OSSIZE bufSize)
{
   return toString ("GNB_ID_Choice", buffer, bufSize);
}

int asn1PrtToStr_GlobalgNB_ID (const char* name, ASN1T_GlobalgNB_ID* pvalue, 
   char* buffer, OSSIZE bufSize)
{
   char namebuf[512];

   rtxStrJoin (namebuf, 512, name, ".plmn_id", 0, 0, 0);
   if (asn1PrtToStr_PLMN_Identity (namebuf, &pvalue->plmn_id, buffer, bufSize) < 0)
   {
      return -1;
   }

   rtxStrJoin (namebuf, 512, name, ".gnb_id", 0, 0, 0);
   if (asn1PrtToStr_GNB_ID_Choice (namebuf, &pvalue->gnb_id, buffer, bufSize) < 0)
   {
      return -1;
   }

   rtxStrJoin (namebuf, 512, name, ".extElem1", 0, 0, 0);
   if (rtPrintToStringOpenTypeExt (namebuf, &pvalue->extElem1, buffer, bufSize)  < 0)
   {
      return -1;
   }

   return 0;
}

int ASN1C_GlobalgNB_ID::toString (const char* name, char* buffer, OSSIZE bufSize)
{
   if (asn1PrtToStr_GlobalgNB_ID (name, &msgData, buffer, bufSize) < 0)
   {
      return -1;
   }
   return 0;
}

int ASN1C_GlobalgNB_ID::toString (char* buffer, OSSIZE bufSize)
{
   return toString ("GlobalgNB_ID", buffer, bufSize);
}

int asn1PrtToStr_ENGNB_ID (const char* name, ASN1T_ENGNB_ID* pvalue, 
   char* buffer, OSSIZE bufSize)
{
   {
   char namebuf2[512], numbuf[32];

   rtxIntToCharStr (pvalue->t, numbuf, sizeof(numbuf), 0);
   rtxStrJoin (namebuf2, sizeof(namebuf2), name, ".t = ", numbuf, "\n", 0);
   if (rtPrintToString (namebuf2, buffer, bufSize) < 0)
   {
      return -1;
   }

   switch (pvalue->t) {
      /* gNB-ID */
      case 1:
      {
         rtxStrJoin (namebuf2, 512, name, ".u.gNB_ID", 0, 0, 0);
         if (rtPrintToStringBitStr (namebuf2, OS_MIN(pvalue->u.gNB_ID->numbits, 32), pvalue->u.gNB_ID->data, ".", buffer, bufSize) < 0)
         {
            return -1;
         }
         break;
      }
      /* extElem1 */
      case 2:
      {
         rtxStrJoin (namebuf2, 512, name, ".u.extElem1", 0, 0, 0);
         if(rtPrintToStringOpenType (namebuf2, pvalue->u.extElem1->numocts, pvalue->u.extElem1->data, ".", buffer, bufSize) < 0)
         {
            return -1;
         }
         break;
      }
      default:;
   }
   }
   return 0;
}

int ASN1C_ENGNB_ID::toString (const char* name, char* buffer, OSSIZE bufSize)
{
   if (asn1PrtToStr_ENGNB_ID (name, &msgData, buffer, bufSize) < 0)
   {
      return -1;
   }
   return 0;
}

int ASN1C_ENGNB_ID::toString (char* buffer, OSSIZE bufSize)
{
   return toString ("ENGNB_ID", buffer, bufSize);
}

int asn1PrtToStr_E2AP_IEs_GlobalenGNB_ID (const char* name, 
   ASN1T_E2AP_IEs_GlobalenGNB_ID* pvalue, char* buffer, OSSIZE bufSize)
{
   char namebuf[512];

   rtxStrJoin (namebuf, 512, name, ".pLMN_Identity", 0, 0, 0);
   if (asn1PrtToStr_PLMN_Identity (namebuf, &pvalue->pLMN_Identity, buffer, bufSize) < 0)
   {
      return -1;
   }

   rtxStrJoin (namebuf, 512, name, ".gNB_ID", 0, 0, 0);
   if (asn1PrtToStr_ENGNB_ID (namebuf, &pvalue->gNB_ID, buffer, bufSize) < 0)
   {
      return -1;
   }

   rtxStrJoin (namebuf, 512, name, ".extElem1", 0, 0, 0);
   if (rtPrintToStringOpenTypeExt (namebuf, &pvalue->extElem1, buffer, bufSize)  < 0)
   {
      return -1;
   }

   return 0;
}

int ASN1C_E2AP_IEs_GlobalenGNB_ID::toString (const char* name, char* buffer, OSSIZE bufSize)
{
   if (asn1PrtToStr_E2AP_IEs_GlobalenGNB_ID (name, &msgData, buffer, bufSize) < 0)
   {
      return -1;
   }
   return 0;
}

int ASN1C_E2AP_IEs_GlobalenGNB_ID::toString (char* buffer, OSSIZE bufSize)
{
   return toString ("GlobalenGNB_ID", buffer, bufSize);
}

int asn1PrtToStr_E2AP_IEs_GNB_CU_UP_ID (const char* name, 
   ASN1T_E2AP_IEs_GNB_CU_UP_ID* pvalue, char* buffer, OSSIZE bufSize)
{
   if (rtPrintToStringUInt64 (name, *pvalue, buffer, bufSize) < 0)
   {
      return -1;
   }
   return 0;
}

int ASN1C_E2AP_IEs_GNB_CU_UP_ID::toString (const char* name, char* buffer, OSSIZE bufSize)
{
   if (asn1PrtToStr_E2AP_IEs_GNB_CU_UP_ID (name, &msgData, buffer, bufSize) < 0)
   {
      return -1;
   }
   return 0;
}

int ASN1C_E2AP_IEs_GNB_CU_UP_ID::toString (char* buffer, OSSIZE bufSize)
{
   return toString ("GNB_CU_UP_ID", buffer, bufSize);
}

int asn1PrtToStr_E2AP_IEs_GNB_DU_ID (const char* name, 
   ASN1T_E2AP_IEs_GNB_DU_ID* pvalue, char* buffer, OSSIZE bufSize)
{
   if (rtPrintToStringUInt64 (name, *pvalue, buffer, bufSize) < 0)
   {
      return -1;
   }
   return 0;
}

int ASN1C_E2AP_IEs_GNB_DU_ID::toString (const char* name, char* buffer, OSSIZE bufSize)
{
   if (asn1PrtToStr_E2AP_IEs_GNB_DU_ID (name, &msgData, buffer, bufSize) < 0)
   {
      return -1;
   }
   return 0;
}

int ASN1C_E2AP_IEs_GNB_DU_ID::toString (char* buffer, OSSIZE bufSize)
{
   return toString ("GNB_DU_ID", buffer, bufSize);
}

int asn1PrtToStr_GlobalE2node_gNB_ID (const char* name, 
   ASN1T_GlobalE2node_gNB_ID* pvalue, char* buffer, OSSIZE bufSize)
{
   char namebuf[512];

   { char numbuf[32];
   rtxIntToCharStr ((int)pvalue->m.global_en_gNB_IDPresent, numbuf, 32, 0);
   rtxStrJoin (namebuf, 512, name, ".m.global_en_gNB_IDPresent = ", numbuf, "\n", 0);
   if (rtPrintToString (namebuf, buffer, bufSize) < 0) {
      return -1;
   }}
   { char numbuf[32];
   rtxIntToCharStr ((int)pvalue->m.gNB_CU_UP_IDPresent, numbuf, 32, 0);
   rtxStrJoin (namebuf, 512, name, ".m.gNB_CU_UP_IDPresent = ", numbuf, "\n", 0);
   if (rtPrintToString (namebuf, buffer, bufSize) < 0) {
      return -1;
   }}
   { char numbuf[32];
   rtxIntToCharStr ((int)pvalue->m.gNB_DU_IDPresent, numbuf, 32, 0);
   rtxStrJoin (namebuf, 512, name, ".m.gNB_DU_IDPresent = ", numbuf, "\n", 0);
   if (rtPrintToString (namebuf, buffer, bufSize) < 0) {
      return -1;
   }}
   rtxStrJoin (namebuf, 512, name, ".global_gNB_ID", 0, 0, 0);
   if (asn1PrtToStr_GlobalgNB_ID (namebuf, &pvalue->global_gNB_ID, buffer, bufSize) < 0)
   {
      return -1;
   }

   if (pvalue->m.global_en_gNB_IDPresent) {
      rtxStrJoin (namebuf, 512, name, ".global_en_gNB_ID", 0, 0, 0);
      if (asn1PrtToStr_E2AP_IEs_GlobalenGNB_ID (namebuf, &pvalue->global_en_gNB_ID, buffer, bufSize) < 0)
      {
         return -1;
      }
   }

   if (pvalue->m.gNB_CU_UP_IDPresent) {
      rtxStrJoin (namebuf, 512, name, ".gNB_CU_UP_ID", 0, 0, 0);
      if (asn1PrtToStr_E2AP_IEs_GNB_CU_UP_ID (namebuf, &pvalue->gNB_CU_UP_ID, buffer, bufSize) < 0)
      {
         return -1;
      }
   }

   if (pvalue->m.gNB_DU_IDPresent) {
      rtxStrJoin (namebuf, 512, name, ".gNB_DU_ID", 0, 0, 0);
      if (asn1PrtToStr_E2AP_IEs_GNB_DU_ID (namebuf, &pvalue->gNB_DU_ID, buffer, bufSize) < 0)
      {
         return -1;
      }
   }

   rtxStrJoin (namebuf, 512, name, ".extElem1", 0, 0, 0);
   if (rtPrintToStringOpenTypeExt (namebuf, &pvalue->extElem1, buffer, bufSize)  < 0)
   {
      return -1;
   }

   return 0;
}

int ASN1C_GlobalE2node_gNB_ID::toString (const char* name, char* buffer, OSSIZE bufSize)
{
   if (asn1PrtToStr_GlobalE2node_gNB_ID (name, &msgData, buffer, bufSize) < 0)
   {
      return -1;
   }
   return 0;
}

int ASN1C_GlobalE2node_gNB_ID::toString (char* buffer, OSSIZE bufSize)
{
   return toString ("GlobalE2node_gNB_ID", buffer, bufSize);
}

int asn1PrtToStr_GlobalE2node_en_gNB_ID (const char* name, 
   ASN1T_GlobalE2node_en_gNB_ID* pvalue, char* buffer, OSSIZE bufSize)
{
   char namebuf[512];

   { char numbuf[32];
   rtxIntToCharStr ((int)pvalue->m.en_gNB_CU_UP_IDPresent, numbuf, 32, 0);
   rtxStrJoin (namebuf, 512, name, ".m.en_gNB_CU_UP_IDPresent = ", numbuf, "\n", 0);
   if (rtPrintToString (namebuf, buffer, bufSize) < 0) {
      return -1;
   }}
   { char numbuf[32];
   rtxIntToCharStr ((int)pvalue->m.en_gNB_DU_IDPresent, numbuf, 32, 0);
   rtxStrJoin (namebuf, 512, name, ".m.en_gNB_DU_IDPresent = ", numbuf, "\n", 0);
   if (rtPrintToString (namebuf, buffer, bufSize) < 0) {
      return -1;
   }}
   rtxStrJoin (namebuf, 512, name, ".global_en_gNB_ID", 0, 0, 0);
   if (asn1PrtToStr_E2AP_IEs_GlobalenGNB_ID (namebuf, &pvalue->global_en_gNB_ID, buffer, bufSize) < 0)
   {
      return -1;
   }

   if (pvalue->m.en_gNB_CU_UP_IDPresent) {
      rtxStrJoin (namebuf, 512, name, ".en_gNB_CU_UP_ID", 0, 0, 0);
      if (asn1PrtToStr_E2AP_IEs_GNB_CU_UP_ID (namebuf, &pvalue->en_gNB_CU_UP_ID, buffer, bufSize) < 0)
      {
         return -1;
      }
   }

   if (pvalue->m.en_gNB_DU_IDPresent) {
      rtxStrJoin (namebuf, 512, name, ".en_gNB_DU_ID", 0, 0, 0);
      if (asn1PrtToStr_E2AP_IEs_GNB_DU_ID (namebuf, &pvalue->en_gNB_DU_ID, buffer, bufSize) < 0)
      {
         return -1;
      }
   }

   rtxStrJoin (namebuf, 512, name, ".extElem1", 0, 0, 0);
   if (rtPrintToStringOpenTypeExt (namebuf, &pvalue->extElem1, buffer, bufSize)  < 0)
   {
      return -1;
   }

   return 0;
}

int ASN1C_GlobalE2node_en_gNB_ID::toString (const char* name, char* buffer, OSSIZE bufSize)
{
   if (asn1PrtToStr_GlobalE2node_en_gNB_ID (name, &msgData, buffer, bufSize) < 0)
   {
      return -1;
   }
   return 0;
}

int ASN1C_GlobalE2node_en_gNB_ID::toString (char* buffer, OSSIZE bufSize)
{
   return toString ("GlobalE2node_en_gNB_ID", buffer, bufSize);
}

int asn1PrtToStr_ENB_ID_Choice (const char* name, ASN1T_ENB_ID_Choice* pvalue, 
   char* buffer, OSSIZE bufSize)
{
   {
   char namebuf2[512], numbuf[32];

   rtxIntToCharStr (pvalue->t, numbuf, sizeof(numbuf), 0);
   rtxStrJoin (namebuf2, sizeof(namebuf2), name, ".t = ", numbuf, "\n", 0);
   if (rtPrintToString (namebuf2, buffer, bufSize) < 0)
   {
      return -1;
   }

   switch (pvalue->t) {
      /* enb-ID-macro */
      case 1:
      {
         rtxStrJoin (namebuf2, 512, name, ".u.enb_ID_macro", 0, 0, 0);
         if (rtPrintToStringBitStr (namebuf2, OS_MIN(pvalue->u.enb_ID_macro->numbits, 24), pvalue->u.enb_ID_macro->data, ".", buffer, bufSize) < 0)
         {
            return -1;
         }
         break;
      }
      /* enb-ID-shortmacro */
      case 2:
      {
         rtxStrJoin (namebuf2, 512, name, ".u.enb_ID_shortmacro", 0, 0, 0);
         if (rtPrintToStringBitStr (namebuf2, OS_MIN(pvalue->u.enb_ID_shortmacro->numbits, 24), pvalue->u.enb_ID_shortmacro->data, ".", buffer, bufSize) < 0)
         {
            return -1;
         }
         break;
      }
      /* enb-ID-longmacro */
      case 3:
      {
         rtxStrJoin (namebuf2, 512, name, ".u.enb_ID_longmacro", 0, 0, 0);
         if (rtPrintToStringBitStr (namebuf2, OS_MIN(pvalue->u.enb_ID_longmacro->numbits, 24), pvalue->u.enb_ID_longmacro->data, ".", buffer, bufSize) < 0)
         {
            return -1;
         }
         break;
      }
      /* extElem1 */
      case 4:
      {
         rtxStrJoin (namebuf2, 512, name, ".u.extElem1", 0, 0, 0);
         if(rtPrintToStringOpenType (namebuf2, pvalue->u.extElem1->numocts, pvalue->u.extElem1->data, ".", buffer, bufSize) < 0)
         {
            return -1;
         }
         break;
      }
      default:;
   }
   }
   return 0;
}

int ASN1C_ENB_ID_Choice::toString (const char* name, char* buffer, OSSIZE bufSize)
{
   if (asn1PrtToStr_ENB_ID_Choice (name, &msgData, buffer, bufSize) < 0)
   {
      return -1;
   }
   return 0;
}

int ASN1C_ENB_ID_Choice::toString (char* buffer, OSSIZE bufSize)
{
   return toString ("ENB_ID_Choice", buffer, bufSize);
}

int asn1PrtToStr_GlobalngeNB_ID (const char* name, 
   ASN1T_GlobalngeNB_ID* pvalue, char* buffer, OSSIZE bufSize)
{
   char namebuf[512];

   rtxStrJoin (namebuf, 512, name, ".plmn_id", 0, 0, 0);
   if (asn1PrtToStr_PLMN_Identity (namebuf, &pvalue->plmn_id, buffer, bufSize) < 0)
   {
      return -1;
   }

   rtxStrJoin (namebuf, 512, name, ".enb_id", 0, 0, 0);
   if (asn1PrtToStr_ENB_ID_Choice (namebuf, &pvalue->enb_id, buffer, bufSize) < 0)
   {
      return -1;
   }

   rtxStrJoin (namebuf, 512, name, ".extElem1", 0, 0, 0);
   if (rtPrintToStringOpenTypeExt (namebuf, &pvalue->extElem1, buffer, bufSize)  < 0)
   {
      return -1;
   }

   return 0;
}

int ASN1C_GlobalngeNB_ID::toString (const char* name, char* buffer, OSSIZE bufSize)
{
   if (asn1PrtToStr_GlobalngeNB_ID (name, &msgData, buffer, bufSize) < 0)
   {
      return -1;
   }
   return 0;
}

int ASN1C_GlobalngeNB_ID::toString (char* buffer, OSSIZE bufSize)
{
   return toString ("GlobalngeNB_ID", buffer, bufSize);
}

int asn1PrtToStr_E2AP_IEs_ENB_ID (const char* name, 
   ASN1T_E2AP_IEs_ENB_ID* pvalue, char* buffer, OSSIZE bufSize)
{
   {
   char namebuf2[512], numbuf[32];

   rtxIntToCharStr (pvalue->t, numbuf, sizeof(numbuf), 0);
   rtxStrJoin (namebuf2, sizeof(namebuf2), name, ".t = ", numbuf, "\n", 0);
   if (rtPrintToString (namebuf2, buffer, bufSize) < 0)
   {
      return -1;
   }

   switch (pvalue->t) {
      /* macro-eNB-ID */
      case 1:
      {
         rtxStrJoin (namebuf2, 512, name, ".u.macro_eNB_ID", 0, 0, 0);
         if (rtPrintToStringBitStr (namebuf2, OS_MIN(pvalue->u.macro_eNB_ID->numbits, 24), pvalue->u.macro_eNB_ID->data, ".", buffer, bufSize) < 0)
         {
            return -1;
         }
         break;
      }
      /* home-eNB-ID */
      case 2:
      {
         rtxStrJoin (namebuf2, 512, name, ".u.home_eNB_ID", 0, 0, 0);
         if (rtPrintToStringBitStr (namebuf2, OS_MIN(pvalue->u.home_eNB_ID->numbits, 32), pvalue->u.home_eNB_ID->data, ".", buffer, bufSize) < 0)
         {
            return -1;
         }
         break;
      }
      /* short-Macro-eNB-ID */
      case 3:
      {
         rtxStrJoin (namebuf2, 512, name, ".u.short_Macro_eNB_ID", 0, 0, 0);
         if (rtPrintToStringBitStr (namebuf2, OS_MIN(pvalue->u.short_Macro_eNB_ID->numbits, 24), pvalue->u.short_Macro_eNB_ID->data, ".", buffer, bufSize) < 0)
         {
            return -1;
         }
         break;
      }
      /* long-Macro-eNB-ID */
      case 4:
      {
         rtxStrJoin (namebuf2, 512, name, ".u.long_Macro_eNB_ID", 0, 0, 0);
         if (rtPrintToStringBitStr (namebuf2, OS_MIN(pvalue->u.long_Macro_eNB_ID->numbits, 24), pvalue->u.long_Macro_eNB_ID->data, ".", buffer, bufSize) < 0)
         {
            return -1;
         }
         break;
      }
      /* extElem1 */
      case 5:
      {
         rtxStrJoin (namebuf2, 512, name, ".u.extElem1", 0, 0, 0);
         if(rtPrintToStringOpenType (namebuf2, pvalue->u.extElem1->numocts, pvalue->u.extElem1->data, ".", buffer, bufSize) < 0)
         {
            return -1;
         }
         break;
      }
      default:;
   }
   }
   return 0;
}

int ASN1C_E2AP_IEs_ENB_ID::toString (const char* name, char* buffer, OSSIZE bufSize)
{
   if (asn1PrtToStr_E2AP_IEs_ENB_ID (name, &msgData, buffer, bufSize) < 0)
   {
      return -1;
   }
   return 0;
}

int ASN1C_E2AP_IEs_ENB_ID::toString (char* buffer, OSSIZE bufSize)
{
   return toString ("ENB_ID", buffer, bufSize);
}

int asn1PrtToStr_E2AP_IEs_GlobalENB_ID (const char* name, 
   ASN1T_E2AP_IEs_GlobalENB_ID* pvalue, char* buffer, OSSIZE bufSize)
{
   char namebuf[512];

   rtxStrJoin (namebuf, 512, name, ".pLMN_Identity", 0, 0, 0);
   if (asn1PrtToStr_PLMN_Identity (namebuf, &pvalue->pLMN_Identity, buffer, bufSize) < 0)
   {
      return -1;
   }

   rtxStrJoin (namebuf, 512, name, ".eNB_ID", 0, 0, 0);
   if (asn1PrtToStr_E2AP_IEs_ENB_ID (namebuf, &pvalue->eNB_ID, buffer, bufSize) < 0)
   {
      return -1;
   }

   rtxStrJoin (namebuf, 512, name, ".extElem1", 0, 0, 0);
   if (rtPrintToStringOpenTypeExt (namebuf, &pvalue->extElem1, buffer, bufSize)  < 0)
   {
      return -1;
   }

   return 0;
}

int ASN1C_E2AP_IEs_GlobalENB_ID::toString (const char* name, char* buffer, OSSIZE bufSize)
{
   if (asn1PrtToStr_E2AP_IEs_GlobalENB_ID (name, &msgData, buffer, bufSize) < 0)
   {
      return -1;
   }
   return 0;
}

int ASN1C_E2AP_IEs_GlobalENB_ID::toString (char* buffer, OSSIZE bufSize)
{
   return toString ("GlobalENB_ID", buffer, bufSize);
}

int asn1PrtToStr_E2AP_IEs_NGENB_DU_ID (const char* name, 
   ASN1T_E2AP_IEs_NGENB_DU_ID* pvalue, char* buffer, OSSIZE bufSize)
{
   if (rtPrintToStringUInt64 (name, *pvalue, buffer, bufSize) < 0)
   {
      return -1;
   }
   return 0;
}

int ASN1C_E2AP_IEs_NGENB_DU_ID::toString (const char* name, char* buffer, OSSIZE bufSize)
{
   if (asn1PrtToStr_E2AP_IEs_NGENB_DU_ID (name, &msgData, buffer, bufSize) < 0)
   {
      return -1;
   }
   return 0;
}

int ASN1C_E2AP_IEs_NGENB_DU_ID::toString (char* buffer, OSSIZE bufSize)
{
   return toString ("NGENB_DU_ID", buffer, bufSize);
}

int asn1PrtToStr_GlobalE2node_ng_eNB_ID (const char* name, 
   ASN1T_GlobalE2node_ng_eNB_ID* pvalue, char* buffer, OSSIZE bufSize)
{
   char namebuf[512];

   { char numbuf[32];
   rtxIntToCharStr ((int)pvalue->m.global_eNB_IDPresent, numbuf, 32, 0);
   rtxStrJoin (namebuf, 512, name, ".m.global_eNB_IDPresent = ", numbuf, "\n", 0);
   if (rtPrintToString (namebuf, buffer, bufSize) < 0) {
      return -1;
   }}
   { char numbuf[32];
   rtxIntToCharStr ((int)pvalue->m.ngENB_DU_IDPresent, numbuf, 32, 0);
   rtxStrJoin (namebuf, 512, name, ".m.ngENB_DU_IDPresent = ", numbuf, "\n", 0);
   if (rtPrintToString (namebuf, buffer, bufSize) < 0) {
      return -1;
   }}
   rtxStrJoin (namebuf, 512, name, ".global_ng_eNB_ID", 0, 0, 0);
   if (asn1PrtToStr_GlobalngeNB_ID (namebuf, &pvalue->global_ng_eNB_ID, buffer, bufSize) < 0)
   {
      return -1;
   }

   if (pvalue->m.global_eNB_IDPresent) {
      rtxStrJoin (namebuf, 512, name, ".global_eNB_ID", 0, 0, 0);
      if (asn1PrtToStr_E2AP_IEs_GlobalENB_ID (namebuf, &pvalue->global_eNB_ID, buffer, bufSize) < 0)
      {
         return -1;
      }
   }

   if (pvalue->m.ngENB_DU_IDPresent) {
      rtxStrJoin (namebuf, 512, name, ".ngENB_DU_ID", 0, 0, 0);
      if (asn1PrtToStr_E2AP_IEs_NGENB_DU_ID (namebuf, &pvalue->ngENB_DU_ID, buffer, bufSize) < 0)
      {
         return -1;
      }
   }

   rtxStrJoin (namebuf, 512, name, ".extElem1", 0, 0, 0);
   if (rtPrintToStringOpenTypeExt (namebuf, &pvalue->extElem1, buffer, bufSize)  < 0)
   {
      return -1;
   }

   return 0;
}

int ASN1C_GlobalE2node_ng_eNB_ID::toString (const char* name, char* buffer, OSSIZE bufSize)
{
   if (asn1PrtToStr_GlobalE2node_ng_eNB_ID (name, &msgData, buffer, bufSize) < 0)
   {
      return -1;
   }
   return 0;
}

int ASN1C_GlobalE2node_ng_eNB_ID::toString (char* buffer, OSSIZE bufSize)
{
   return toString ("GlobalE2node_ng_eNB_ID", buffer, bufSize);
}

int asn1PrtToStr_GlobalE2node_eNB_ID (const char* name, 
   ASN1T_GlobalE2node_eNB_ID* pvalue, char* buffer, OSSIZE bufSize)
{
   char namebuf[512];

   rtxStrJoin (namebuf, 512, name, ".global_eNB_ID", 0, 0, 0);
   if (asn1PrtToStr_E2AP_IEs_GlobalENB_ID (namebuf, &pvalue->global_eNB_ID, buffer, bufSize) < 0)
   {
      return -1;
   }

   rtxStrJoin (namebuf, 512, name, ".extElem1", 0, 0, 0);
   if (rtPrintToStringOpenTypeExt (namebuf, &pvalue->extElem1, buffer, bufSize)  < 0)
   {
      return -1;
   }

   return 0;
}

int ASN1C_GlobalE2node_eNB_ID::toString (const char* name, char* buffer, OSSIZE bufSize)
{
   if (asn1PrtToStr_GlobalE2node_eNB_ID (name, &msgData, buffer, bufSize) < 0)
   {
      return -1;
   }
   return 0;
}

int ASN1C_GlobalE2node_eNB_ID::toString (char* buffer, OSSIZE bufSize)
{
   return toString ("GlobalE2node_eNB_ID", buffer, bufSize);
}

int asn1PrtToStr_GlobalE2node_ID (const char* name, 
   ASN1T_GlobalE2node_ID* pvalue, char* buffer, OSSIZE bufSize)
{
   {
   char namebuf2[512], numbuf[32];

   rtxIntToCharStr (pvalue->t, numbuf, sizeof(numbuf), 0);
   rtxStrJoin (namebuf2, sizeof(namebuf2), name, ".t = ", numbuf, "\n", 0);
   if (rtPrintToString (namebuf2, buffer, bufSize) < 0)
   {
      return -1;
   }

   switch (pvalue->t) {
      /* gNB */
      case 1:
      {
         rtxStrJoin (namebuf2, 512, name, ".u.gNB", 0, 0, 0);
         if (asn1PrtToStr_GlobalE2node_gNB_ID (namebuf2, pvalue->u.gNB, buffer, bufSize) < 0)
         {
            return -1;
         }
         break;
      }
      /* en-gNB */
      case 2:
      {
         rtxStrJoin (namebuf2, 512, name, ".u.en_gNB", 0, 0, 0);
         if (asn1PrtToStr_GlobalE2node_en_gNB_ID (namebuf2, pvalue->u.en_gNB, buffer, bufSize) < 0)
         {
            return -1;
         }
         break;
      }
      /* ng-eNB */
      case 3:
      {
         rtxStrJoin (namebuf2, 512, name, ".u.ng_eNB", 0, 0, 0);
         if (asn1PrtToStr_GlobalE2node_ng_eNB_ID (namebuf2, pvalue->u.ng_eNB, buffer, bufSize) < 0)
         {
            return -1;
         }
         break;
      }
      /* eNB */
      case 4:
      {
         rtxStrJoin (namebuf2, 512, name, ".u.eNB", 0, 0, 0);
         if (asn1PrtToStr_GlobalE2node_eNB_ID (namebuf2, pvalue->u.eNB, buffer, bufSize) < 0)
         {
            return -1;
         }
         break;
      }
      /* extElem1 */
      case 5:
      {
         rtxStrJoin (namebuf2, 512, name, ".u.extElem1", 0, 0, 0);
         if(rtPrintToStringOpenType (namebuf2, pvalue->u.extElem1->numocts, pvalue->u.extElem1->data, ".", buffer, bufSize) < 0)
         {
            return -1;
         }
         break;
      }
      default:;
   }
   }
   return 0;
}

int ASN1C_GlobalE2node_ID::toString (const char* name, char* buffer, OSSIZE bufSize)
{
   if (asn1PrtToStr_GlobalE2node_ID (name, &msgData, buffer, bufSize) < 0)
   {
      return -1;
   }
   return 0;
}

int ASN1C_GlobalE2node_ID::toString (char* buffer, OSSIZE bufSize)
{
   return toString ("GlobalE2node_ID", buffer, bufSize);
}

int asn1PrtToStr_E2nodeComponentInterfaceType (const char* name, 
   ASN1T_E2nodeComponentInterfaceType* pvalue, char* buffer, OSSIZE bufSize)
{
   int stat;
   if(rtPrintToString (name, buffer, bufSize) < 0)
   {
      return -1;
   }
   switch (*pvalue) {
      case 0:
         stat = rtPrintToString (" = ng\n", buffer, bufSize);
         break;

      case 1:
         stat = rtPrintToString (" = xn\n", buffer, bufSize);
         break;

      case 2:
         stat = rtPrintToString (" = e1\n", buffer, bufSize);
         break;

      case 3:
         stat = rtPrintToString (" = f1\n", buffer, bufSize);
         break;

      case 4:
         stat = rtPrintToString (" = w1\n", buffer, bufSize);
         break;

      case 5:
         stat = rtPrintToString (" = s1\n", buffer, bufSize);
         break;

      case 6:
         stat = rtPrintToString (" = x2\n", buffer, bufSize);
         break;

      default: stat = rtPrintToStringUnsigned ("", *pvalue, buffer, bufSize);
   }

   if(stat < 0) return -1;
   return 0;
}

int ASN1C_E2nodeComponentInterfaceType::toString (const char* name, char* buffer, OSSIZE bufSize)
{
   if (asn1PrtToStr_E2nodeComponentInterfaceType (name, &msgData, buffer, bufSize) < 0)
   {
      return -1;
   }
   return 0;
}

int ASN1C_E2nodeComponentInterfaceType::toString (char* buffer, OSSIZE bufSize)
{
   return toString ("E2nodeComponentInterfaceType", buffer, bufSize);
}

int asn1PrtToStr_AMFName (const char* name, ASN1T_AMFName pvalue, 
   char* buffer, OSSIZE bufSize)
{
   if(rtPrintToStringCharStr (name, pvalue, buffer, bufSize) < 0)
   {
      return -1;
   }
   return 0;
}

int ASN1C_AMFName::toString (const char* name, char* buffer, OSSIZE bufSize)
{
   if (asn1PrtToStr_AMFName (name, msgData, buffer, bufSize) < 0)
   {
      return -1;
   }
   return 0;
}

int ASN1C_AMFName::toString (char* buffer, OSSIZE bufSize)
{
   return toString ("AMFName", buffer, bufSize);
}

int asn1PrtToStr_E2nodeComponentInterfaceNG (const char* name, 
   ASN1T_E2nodeComponentInterfaceNG* pvalue, char* buffer, OSSIZE bufSize)
{
   char namebuf[512];

   rtxStrJoin (namebuf, 512, name, ".amf_name", 0, 0, 0);
   if (asn1PrtToStr_AMFName (namebuf, pvalue->amf_name, buffer, bufSize) < 0)
   {
      return -1;
   }

   rtxStrJoin (namebuf, 512, name, ".extElem1", 0, 0, 0);
   if (rtPrintToStringOpenTypeExt (namebuf, &pvalue->extElem1, buffer, bufSize)  < 0)
   {
      return -1;
   }

   return 0;
}

int ASN1C_E2nodeComponentInterfaceNG::toString (const char* name, char* buffer, OSSIZE bufSize)
{
   if (asn1PrtToStr_E2nodeComponentInterfaceNG (name, &msgData, buffer, bufSize) < 0)
   {
      return -1;
   }
   return 0;
}

int ASN1C_E2nodeComponentInterfaceNG::toString (char* buffer, OSSIZE bufSize)
{
   return toString ("E2nodeComponentInterfaceNG", buffer, bufSize);
}

int asn1PrtToStr_GlobalNG_RANNode_ID (const char* name, 
   ASN1T_GlobalNG_RANNode_ID* pvalue, char* buffer, OSSIZE bufSize)
{
   {
   char namebuf2[512], numbuf[32];

   rtxIntToCharStr (pvalue->t, numbuf, sizeof(numbuf), 0);
   rtxStrJoin (namebuf2, sizeof(namebuf2), name, ".t = ", numbuf, "\n", 0);
   if (rtPrintToString (namebuf2, buffer, bufSize) < 0)
   {
      return -1;
   }

   switch (pvalue->t) {
      /* gNB */
      case 1:
      {
         rtxStrJoin (namebuf2, 512, name, ".u.gNB", 0, 0, 0);
         if (asn1PrtToStr_GlobalgNB_ID (namebuf2, pvalue->u.gNB, buffer, bufSize) < 0)
         {
            return -1;
         }
         break;
      }
      /* ng-eNB */
      case 2:
      {
         rtxStrJoin (namebuf2, 512, name, ".u.ng_eNB", 0, 0, 0);
         if (asn1PrtToStr_GlobalngeNB_ID (namebuf2, pvalue->u.ng_eNB, buffer, bufSize) < 0)
         {
            return -1;
         }
         break;
      }
      /* extElem1 */
      case 3:
      {
         rtxStrJoin (namebuf2, 512, name, ".u.extElem1", 0, 0, 0);
         if(rtPrintToStringOpenType (namebuf2, pvalue->u.extElem1->numocts, pvalue->u.extElem1->data, ".", buffer, bufSize) < 0)
         {
            return -1;
         }
         break;
      }
      default:;
   }
   }
   return 0;
}

int ASN1C_GlobalNG_RANNode_ID::toString (const char* name, char* buffer, OSSIZE bufSize)
{
   if (asn1PrtToStr_GlobalNG_RANNode_ID (name, &msgData, buffer, bufSize) < 0)
   {
      return -1;
   }
   return 0;
}

int ASN1C_GlobalNG_RANNode_ID::toString (char* buffer, OSSIZE bufSize)
{
   return toString ("GlobalNG_RANNode_ID", buffer, bufSize);
}

int asn1PrtToStr_E2nodeComponentInterfaceXn (const char* name, 
   ASN1T_E2nodeComponentInterfaceXn* pvalue, char* buffer, OSSIZE bufSize)
{
   char namebuf[512];

   rtxStrJoin (namebuf, 512, name, ".global_NG_RAN_Node_ID", 0, 0, 0);
   if (asn1PrtToStr_GlobalNG_RANNode_ID (namebuf, &pvalue->global_NG_RAN_Node_ID, buffer, bufSize) < 0)
   {
      return -1;
   }

   rtxStrJoin (namebuf, 512, name, ".extElem1", 0, 0, 0);
   if (rtPrintToStringOpenTypeExt (namebuf, &pvalue->extElem1, buffer, bufSize)  < 0)
   {
      return -1;
   }

   return 0;
}

int ASN1C_E2nodeComponentInterfaceXn::toString (const char* name, char* buffer, OSSIZE bufSize)
{
   if (asn1PrtToStr_E2nodeComponentInterfaceXn (name, &msgData, buffer, bufSize) < 0)
   {
      return -1;
   }
   return 0;
}

int ASN1C_E2nodeComponentInterfaceXn::toString (char* buffer, OSSIZE bufSize)
{
   return toString ("E2nodeComponentInterfaceXn", buffer, bufSize);
}

int asn1PrtToStr_E2nodeComponentInterfaceE1 (const char* name, 
   ASN1T_E2nodeComponentInterfaceE1* pvalue, char* buffer, OSSIZE bufSize)
{
   char namebuf[512];

   rtxStrJoin (namebuf, 512, name, ".gNB_CU_CP_ID", 0, 0, 0);
   if (asn1PrtToStr_E2AP_IEs_GNB_CU_UP_ID (namebuf, &pvalue->gNB_CU_CP_ID, buffer, bufSize) < 0)
   {
      return -1;
   }

   rtxStrJoin (namebuf, 512, name, ".extElem1", 0, 0, 0);
   if (rtPrintToStringOpenTypeExt (namebuf, &pvalue->extElem1, buffer, bufSize)  < 0)
   {
      return -1;
   }

   return 0;
}

int ASN1C_E2nodeComponentInterfaceE1::toString (const char* name, char* buffer, OSSIZE bufSize)
{
   if (asn1PrtToStr_E2nodeComponentInterfaceE1 (name, &msgData, buffer, bufSize) < 0)
   {
      return -1;
   }
   return 0;
}

int ASN1C_E2nodeComponentInterfaceE1::toString (char* buffer, OSSIZE bufSize)
{
   return toString ("E2nodeComponentInterfaceE1", buffer, bufSize);
}

int asn1PrtToStr_E2nodeComponentInterfaceF1 (const char* name, 
   ASN1T_E2nodeComponentInterfaceF1* pvalue, char* buffer, OSSIZE bufSize)
{
   char namebuf[512];

   rtxStrJoin (namebuf, 512, name, ".gNB_DU_ID", 0, 0, 0);
   if (asn1PrtToStr_E2AP_IEs_GNB_DU_ID (namebuf, &pvalue->gNB_DU_ID, buffer, bufSize) < 0)
   {
      return -1;
   }

   rtxStrJoin (namebuf, 512, name, ".extElem1", 0, 0, 0);
   if (rtPrintToStringOpenTypeExt (namebuf, &pvalue->extElem1, buffer, bufSize)  < 0)
   {
      return -1;
   }

   return 0;
}

int ASN1C_E2nodeComponentInterfaceF1::toString (const char* name, char* buffer, OSSIZE bufSize)
{
   if (asn1PrtToStr_E2nodeComponentInterfaceF1 (name, &msgData, buffer, bufSize) < 0)
   {
      return -1;
   }
   return 0;
}

int ASN1C_E2nodeComponentInterfaceF1::toString (char* buffer, OSSIZE bufSize)
{
   return toString ("E2nodeComponentInterfaceF1", buffer, bufSize);
}

int asn1PrtToStr_E2nodeComponentInterfaceW1 (const char* name, 
   ASN1T_E2nodeComponentInterfaceW1* pvalue, char* buffer, OSSIZE bufSize)
{
   char namebuf[512];

   rtxStrJoin (namebuf, 512, name, ".ng_eNB_DU_ID", 0, 0, 0);
   if (asn1PrtToStr_E2AP_IEs_NGENB_DU_ID (namebuf, &pvalue->ng_eNB_DU_ID, buffer, bufSize) < 0)
   {
      return -1;
   }

   rtxStrJoin (namebuf, 512, name, ".extElem1", 0, 0, 0);
   if (rtPrintToStringOpenTypeExt (namebuf, &pvalue->extElem1, buffer, bufSize)  < 0)
   {
      return -1;
   }

   return 0;
}

int ASN1C_E2nodeComponentInterfaceW1::toString (const char* name, char* buffer, OSSIZE bufSize)
{
   if (asn1PrtToStr_E2nodeComponentInterfaceW1 (name, &msgData, buffer, bufSize) < 0)
   {
      return -1;
   }
   return 0;
}

int ASN1C_E2nodeComponentInterfaceW1::toString (char* buffer, OSSIZE bufSize)
{
   return toString ("E2nodeComponentInterfaceW1", buffer, bufSize);
}

int asn1PrtToStr_MMEname (const char* name, ASN1T_MMEname pvalue, 
   char* buffer, OSSIZE bufSize)
{
   if(rtPrintToStringCharStr (name, pvalue, buffer, bufSize) < 0)
   {
      return -1;
   }
   return 0;
}

int ASN1C_MMEname::toString (const char* name, char* buffer, OSSIZE bufSize)
{
   if (asn1PrtToStr_MMEname (name, msgData, buffer, bufSize) < 0)
   {
      return -1;
   }
   return 0;
}

int ASN1C_MMEname::toString (char* buffer, OSSIZE bufSize)
{
   return toString ("MMEname", buffer, bufSize);
}

int asn1PrtToStr_E2nodeComponentInterfaceS1 (const char* name, 
   ASN1T_E2nodeComponentInterfaceS1* pvalue, char* buffer, OSSIZE bufSize)
{
   char namebuf[512];

   rtxStrJoin (namebuf, 512, name, ".mme_name", 0, 0, 0);
   if (asn1PrtToStr_MMEname (namebuf, pvalue->mme_name, buffer, bufSize) < 0)
   {
      return -1;
   }

   rtxStrJoin (namebuf, 512, name, ".extElem1", 0, 0, 0);
   if (rtPrintToStringOpenTypeExt (namebuf, &pvalue->extElem1, buffer, bufSize)  < 0)
   {
      return -1;
   }

   return 0;
}

int ASN1C_E2nodeComponentInterfaceS1::toString (const char* name, char* buffer, OSSIZE bufSize)
{
   if (asn1PrtToStr_E2nodeComponentInterfaceS1 (name, &msgData, buffer, bufSize) < 0)
   {
      return -1;
   }
   return 0;
}

int ASN1C_E2nodeComponentInterfaceS1::toString (char* buffer, OSSIZE bufSize)
{
   return toString ("E2nodeComponentInterfaceS1", buffer, bufSize);
}

int asn1PrtToStr_E2nodeComponentInterfaceX2 (const char* name, 
   ASN1T_E2nodeComponentInterfaceX2* pvalue, char* buffer, OSSIZE bufSize)
{
   char namebuf[512];

   { char numbuf[32];
   rtxIntToCharStr ((int)pvalue->m.global_eNB_IDPresent, numbuf, 32, 0);
   rtxStrJoin (namebuf, 512, name, ".m.global_eNB_IDPresent = ", numbuf, "\n", 0);
   if (rtPrintToString (namebuf, buffer, bufSize) < 0) {
      return -1;
   }}
   { char numbuf[32];
   rtxIntToCharStr ((int)pvalue->m.global_en_gNB_IDPresent, numbuf, 32, 0);
   rtxStrJoin (namebuf, 512, name, ".m.global_en_gNB_IDPresent = ", numbuf, "\n", 0);
   if (rtPrintToString (namebuf, buffer, bufSize) < 0) {
      return -1;
   }}
   if (pvalue->m.global_eNB_IDPresent) {
      rtxStrJoin (namebuf, 512, name, ".global_eNB_ID", 0, 0, 0);
      if (asn1PrtToStr_E2AP_IEs_GlobalENB_ID (namebuf, &pvalue->global_eNB_ID, buffer, bufSize) < 0)
      {
         return -1;
      }
   }

   if (pvalue->m.global_en_gNB_IDPresent) {
      rtxStrJoin (namebuf, 512, name, ".global_en_gNB_ID", 0, 0, 0);
      if (asn1PrtToStr_E2AP_IEs_GlobalenGNB_ID (namebuf, &pvalue->global_en_gNB_ID, buffer, bufSize) < 0)
      {
         return -1;
      }
   }

   rtxStrJoin (namebuf, 512, name, ".extElem1", 0, 0, 0);
   if (rtPrintToStringOpenTypeExt (namebuf, &pvalue->extElem1, buffer, bufSize)  < 0)
   {
      return -1;
   }

   return 0;
}

int ASN1C_E2nodeComponentInterfaceX2::toString (const char* name, char* buffer, OSSIZE bufSize)
{
   if (asn1PrtToStr_E2nodeComponentInterfaceX2 (name, &msgData, buffer, bufSize) < 0)
   {
      return -1;
   }
   return 0;
}

int ASN1C_E2nodeComponentInterfaceX2::toString (char* buffer, OSSIZE bufSize)
{
   return toString ("E2nodeComponentInterfaceX2", buffer, bufSize);
}

int asn1PrtToStr_E2nodeComponentID (const char* name, 
   ASN1T_E2nodeComponentID* pvalue, char* buffer, OSSIZE bufSize)
{
   {
   char namebuf2[512], numbuf[32];

   rtxIntToCharStr (pvalue->t, numbuf, sizeof(numbuf), 0);
   rtxStrJoin (namebuf2, sizeof(namebuf2), name, ".t = ", numbuf, "\n", 0);
   if (rtPrintToString (namebuf2, buffer, bufSize) < 0)
   {
      return -1;
   }

   switch (pvalue->t) {
      /* e2nodeComponentInterfaceTypeNG */
      case 1:
      {
         rtxStrJoin (namebuf2, 512, name, ".u.e2nodeComponentInterfaceTypeNG", 0, 0, 0);
         if (asn1PrtToStr_E2nodeComponentInterfaceNG (namebuf2, pvalue->u.e2nodeComponentInterfaceTypeNG, buffer, bufSize) < 0)
         {
            return -1;
         }
         break;
      }
      /* e2nodeComponentInterfaceTypeXn */
      case 2:
      {
         rtxStrJoin (namebuf2, 512, name, ".u.e2nodeComponentInterfaceTypeXn", 0, 0, 0);
         if (asn1PrtToStr_E2nodeComponentInterfaceXn (namebuf2, pvalue->u.e2nodeComponentInterfaceTypeXn, buffer, bufSize) < 0)
         {
            return -1;
         }
         break;
      }
      /* e2nodeComponentInterfaceTypeE1 */
      case 3:
      {
         rtxStrJoin (namebuf2, 512, name, ".u.e2nodeComponentInterfaceTypeE1", 0, 0, 0);
         if (asn1PrtToStr_E2nodeComponentInterfaceE1 (namebuf2, pvalue->u.e2nodeComponentInterfaceTypeE1, buffer, bufSize) < 0)
         {
            return -1;
         }
         break;
      }
      /* e2nodeComponentInterfaceTypeF1 */
      case 4:
      {
         rtxStrJoin (namebuf2, 512, name, ".u.e2nodeComponentInterfaceTypeF1", 0, 0, 0);
         if (asn1PrtToStr_E2nodeComponentInterfaceF1 (namebuf2, pvalue->u.e2nodeComponentInterfaceTypeF1, buffer, bufSize) < 0)
         {
            return -1;
         }
         break;
      }
      /* e2nodeComponentInterfaceTypeW1 */
      case 5:
      {
         rtxStrJoin (namebuf2, 512, name, ".u.e2nodeComponentInterfaceTypeW1", 0, 0, 0);
         if (asn1PrtToStr_E2nodeComponentInterfaceW1 (namebuf2, pvalue->u.e2nodeComponentInterfaceTypeW1, buffer, bufSize) < 0)
         {
            return -1;
         }
         break;
      }
      /* e2nodeComponentInterfaceTypeS1 */
      case 6:
      {
         rtxStrJoin (namebuf2, 512, name, ".u.e2nodeComponentInterfaceTypeS1", 0, 0, 0);
         if (asn1PrtToStr_E2nodeComponentInterfaceS1 (namebuf2, pvalue->u.e2nodeComponentInterfaceTypeS1, buffer, bufSize) < 0)
         {
            return -1;
         }
         break;
      }
      /* e2nodeComponentInterfaceTypeX2 */
      case 7:
      {
         rtxStrJoin (namebuf2, 512, name, ".u.e2nodeComponentInterfaceTypeX2", 0, 0, 0);
         if (asn1PrtToStr_E2nodeComponentInterfaceX2 (namebuf2, pvalue->u.e2nodeComponentInterfaceTypeX2, buffer, bufSize) < 0)
         {
            return -1;
         }
         break;
      }
      /* extElem1 */
      case 8:
      {
         rtxStrJoin (namebuf2, 512, name, ".u.extElem1", 0, 0, 0);
         if(rtPrintToStringOpenType (namebuf2, pvalue->u.extElem1->numocts, pvalue->u.extElem1->data, ".", buffer, bufSize) < 0)
         {
            return -1;
         }
         break;
      }
      default:;
   }
   }
   return 0;
}

int ASN1C_E2nodeComponentID::toString (const char* name, char* buffer, OSSIZE bufSize)
{
   if (asn1PrtToStr_E2nodeComponentID (name, &msgData, buffer, bufSize) < 0)
   {
      return -1;
   }
   return 0;
}

int ASN1C_E2nodeComponentID::toString (char* buffer, OSSIZE bufSize)
{
   return toString ("E2nodeComponentID", buffer, bufSize);
}

int asn1PrtToStr_E2nodeComponentConfiguration (const char* name, 
   ASN1T_E2nodeComponentConfiguration* pvalue, char* buffer, OSSIZE bufSize)
{
   char namebuf[512];

   rtxStrJoin (namebuf, 512, name, ".e2nodeComponentRequestPart", 0, 0, 0);
   if (rtPrintToStringOctStr (namebuf, pvalue->e2nodeComponentRequestPart.numocts, pvalue->e2nodeComponentRequestPart.data, ".", buffer, bufSize) < 0)
   {
      return -1;
   }

   rtxStrJoin (namebuf, 512, name, ".e2nodeComponentResponsePart", 0, 0, 0);
   if (rtPrintToStringOctStr (namebuf, pvalue->e2nodeComponentResponsePart.numocts, pvalue->e2nodeComponentResponsePart.data, ".", buffer, bufSize) < 0)
   {
      return -1;
   }

   rtxStrJoin (namebuf, 512, name, ".extElem1", 0, 0, 0);
   if (rtPrintToStringOpenTypeExt (namebuf, &pvalue->extElem1, buffer, bufSize)  < 0)
   {
      return -1;
   }

   return 0;
}

int ASN1C_E2nodeComponentConfiguration::toString (const char* name, char* buffer, OSSIZE bufSize)
{
   if (asn1PrtToStr_E2nodeComponentConfiguration (name, &msgData, buffer, bufSize) < 0)
   {
      return -1;
   }
   return 0;
}

int ASN1C_E2nodeComponentConfiguration::toString (char* buffer, OSSIZE bufSize)
{
   return toString ("E2nodeComponentConfiguration", buffer, bufSize);
}

int asn1PrtToStr_TNLinformation (const char* name, 
   ASN1T_TNLinformation* pvalue, char* buffer, OSSIZE bufSize)
{
   char namebuf[512];

   { char numbuf[32];
   rtxIntToCharStr ((int)pvalue->m.tnlPortPresent, numbuf, 32, 0);
   rtxStrJoin (namebuf, 512, name, ".m.tnlPortPresent = ", numbuf, "\n", 0);
   if (rtPrintToString (namebuf, buffer, bufSize) < 0) {
      return -1;
   }}
   rtxStrJoin (namebuf, 512, name, ".tnlAddress", 0, 0, 0);
   if (rtPrintToStringBitStr (namebuf, pvalue->tnlAddress.numbits, pvalue->tnlAddress.data, ".", buffer, bufSize) < 0)
   {
      return -1;
   }

   if (pvalue->m.tnlPortPresent) {
      rtxStrJoin (namebuf, 512, name, ".tnlPort", 0, 0, 0);
      if (rtPrintToStringBitStr (namebuf, OS_MIN(pvalue->tnlPort.numbits, 16), pvalue->tnlPort.data, ".", buffer, bufSize) < 0)
      {
         return -1;
      }
   }

   rtxStrJoin (namebuf, 512, name, ".extElem1", 0, 0, 0);
   if (rtPrintToStringOpenTypeExt (namebuf, &pvalue->extElem1, buffer, bufSize)  < 0)
   {
      return -1;
   }

   return 0;
}

int ASN1C_TNLinformation::toString (const char* name, char* buffer, OSSIZE bufSize)
{
   if (asn1PrtToStr_TNLinformation (name, &msgData, buffer, bufSize) < 0)
   {
      return -1;
   }
   return 0;
}

int ASN1C_TNLinformation::toString (char* buffer, OSSIZE bufSize)
{
   return toString ("TNLinformation", buffer, bufSize);
}

int asn1PrtToStr_TNLusage (const char* name, ASN1T_TNLusage* pvalue, 
   char* buffer, OSSIZE bufSize)
{
   int stat;
   if(rtPrintToString (name, buffer, bufSize) < 0)
   {
      return -1;
   }
   switch (*pvalue) {
      case 0:
         stat = rtPrintToString (" = ric-service\n", buffer, bufSize);
         break;

      case 1:
         stat = rtPrintToString (" = support-function\n", buffer, bufSize);
         break;

      case 2:
         stat = rtPrintToString (" = both\n", buffer, bufSize);
         break;

      default: stat = rtPrintToStringUnsigned ("", *pvalue, buffer, bufSize);
   }

   if(stat < 0) return -1;
   return 0;
}

int ASN1C_TNLusage::toString (const char* name, char* buffer, OSSIZE bufSize)
{
   if (asn1PrtToStr_TNLusage (name, &msgData, buffer, bufSize) < 0)
   {
      return -1;
   }
   return 0;
}

int ASN1C_TNLusage::toString (char* buffer, OSSIZE bufSize)
{
   return toString ("TNLusage", buffer, bufSize);
}

int asn1PrtToStr_CauseRICrequest (const char* name, 
   ASN1T_CauseRICrequest* pvalue, char* buffer, OSSIZE bufSize)
{
   int stat;
   if(rtPrintToString (name, buffer, bufSize) < 0)
   {
      return -1;
   }
   switch (*pvalue) {
      case 0:
         stat = rtPrintToString (" = ran-function-id-invalid\n", buffer, bufSize);
         break;

      case 1:
         stat = rtPrintToString (" = action-not-supported\n", buffer, bufSize);
         break;

      case 2:
         stat = rtPrintToString (" = excessive-actions\n", buffer, bufSize);
         break;

      case 3:
         stat = rtPrintToString (" = duplicate-action\n", buffer, bufSize);
         break;

      case 4:
         stat = rtPrintToString (" = duplicate-event-trigger\n", buffer, bufSize);
         break;

      case 5:
         stat = rtPrintToString (" = function-resource-limit\n", buffer, bufSize);
         break;

      case 6:
         stat = rtPrintToString (" = request-id-unknown\n", buffer, bufSize);
         break;

      case 7:
         stat = rtPrintToString (" = inconsistent-action-subsequent-action-sequence\n", buffer, bufSize);
         break;

      case 8:
         stat = rtPrintToString (" = control-message-invalid\n", buffer, bufSize);
         break;

      case 9:
         stat = rtPrintToString (" = ric-call-process-id-invalid\n", buffer, bufSize);
         break;

      case 10:
         stat = rtPrintToString (" = control-timer-expired\n", buffer, bufSize);
         break;

      case 11:
         stat = rtPrintToString (" = control-failed-to-execute\n", buffer, bufSize);
         break;

      case 12:
         stat = rtPrintToString (" = system-not-ready\n", buffer, bufSize);
         break;

      case 13:
         stat = rtPrintToString (" = unspecified\n", buffer, bufSize);
         break;

      default: stat = rtPrintToStringUnsigned ("", *pvalue, buffer, bufSize);
   }

   if(stat < 0) return -1;
   return 0;
}

int ASN1C_CauseRICrequest::toString (const char* name, char* buffer, OSSIZE bufSize)
{
   if (asn1PrtToStr_CauseRICrequest (name, &msgData, buffer, bufSize) < 0)
   {
      return -1;
   }
   return 0;
}

int ASN1C_CauseRICrequest::toString (char* buffer, OSSIZE bufSize)
{
   return toString ("CauseRICrequest", buffer, bufSize);
}

int asn1PrtToStr_CauseRICservice (const char* name, 
   ASN1T_CauseRICservice* pvalue, char* buffer, OSSIZE bufSize)
{
   int stat;
   if(rtPrintToString (name, buffer, bufSize) < 0)
   {
      return -1;
   }
   switch (*pvalue) {
      case 0:
         stat = rtPrintToString (" = ran-function-not-supported\n", buffer, bufSize);
         break;

      case 1:
         stat = rtPrintToString (" = excessive-functions\n", buffer, bufSize);
         break;

      case 2:
         stat = rtPrintToString (" = ric-resource-limit\n", buffer, bufSize);
         break;

      default: stat = rtPrintToStringUnsigned ("", *pvalue, buffer, bufSize);
   }

   if(stat < 0) return -1;
   return 0;
}

int ASN1C_CauseRICservice::toString (const char* name, char* buffer, OSSIZE bufSize)
{
   if (asn1PrtToStr_CauseRICservice (name, &msgData, buffer, bufSize) < 0)
   {
      return -1;
   }
   return 0;
}

int ASN1C_CauseRICservice::toString (char* buffer, OSSIZE bufSize)
{
   return toString ("CauseRICservice", buffer, bufSize);
}

int asn1PrtToStr_CauseE2node (const char* name, ASN1T_CauseE2node* pvalue, 
   char* buffer, OSSIZE bufSize)
{
   int stat;
   if(rtPrintToString (name, buffer, bufSize) < 0)
   {
      return -1;
   }
   switch (*pvalue) {
      case 0:
         stat = rtPrintToString (" = e2node-component-unknown\n", buffer, bufSize);
         break;

      default: stat = rtPrintToStringUnsigned ("", *pvalue, buffer, bufSize);
   }

   if(stat < 0) return -1;
   return 0;
}

int ASN1C_CauseE2node::toString (const char* name, char* buffer, OSSIZE bufSize)
{
   if (asn1PrtToStr_CauseE2node (name, &msgData, buffer, bufSize) < 0)
   {
      return -1;
   }
   return 0;
}

int ASN1C_CauseE2node::toString (char* buffer, OSSIZE bufSize)
{
   return toString ("CauseE2node", buffer, bufSize);
}

int asn1PrtToStr_CauseTransport (const char* name, 
   ASN1T_CauseTransport* pvalue, char* buffer, OSSIZE bufSize)
{
   int stat;
   if(rtPrintToString (name, buffer, bufSize) < 0)
   {
      return -1;
   }
   switch (*pvalue) {
      case 0:
         stat = rtPrintToString (" = unspecified\n", buffer, bufSize);
         break;

      case 1:
         stat = rtPrintToString (" = transport-resource-unavailable\n", buffer, bufSize);
         break;

      default: stat = rtPrintToStringUnsigned ("", *pvalue, buffer, bufSize);
   }

   if(stat < 0) return -1;
   return 0;
}

int ASN1C_CauseTransport::toString (const char* name, char* buffer, OSSIZE bufSize)
{
   if (asn1PrtToStr_CauseTransport (name, &msgData, buffer, bufSize) < 0)
   {
      return -1;
   }
   return 0;
}

int ASN1C_CauseTransport::toString (char* buffer, OSSIZE bufSize)
{
   return toString ("CauseTransport", buffer, bufSize);
}

int asn1PrtToStr_CauseProtocol (const char* name, ASN1T_CauseProtocol* pvalue, 
   char* buffer, OSSIZE bufSize)
{
   int stat;
   if(rtPrintToString (name, buffer, bufSize) < 0)
   {
      return -1;
   }
   switch (*pvalue) {
      case 0:
         stat = rtPrintToString (" = transfer-syntax-error\n", buffer, bufSize);
         break;

      case 1:
         stat = rtPrintToString (" = abstract-syntax-error-reject\n", buffer, bufSize);
         break;

      case 2:
         stat = rtPrintToString (" = abstract-syntax-error-ignore-and-notify\n", buffer, bufSize);
         break;

      case 3:
         stat = rtPrintToString (" = message-not-compatible-with-receiver-state\n", buffer, bufSize);
         break;

      case 4:
         stat = rtPrintToString (" = semantic-error\n", buffer, bufSize);
         break;

      case 5:
         stat = rtPrintToString (" = abstract-syntax-error-falsely-constructed-message\n", buffer, bufSize);
         break;

      case 6:
         stat = rtPrintToString (" = unspecified\n", buffer, bufSize);
         break;

      default: stat = rtPrintToStringUnsigned ("", *pvalue, buffer, bufSize);
   }

   if(stat < 0) return -1;
   return 0;
}

int ASN1C_CauseProtocol::toString (const char* name, char* buffer, OSSIZE bufSize)
{
   if (asn1PrtToStr_CauseProtocol (name, &msgData, buffer, bufSize) < 0)
   {
      return -1;
   }
   return 0;
}

int ASN1C_CauseProtocol::toString (char* buffer, OSSIZE bufSize)
{
   return toString ("CauseProtocol", buffer, bufSize);
}

int asn1PrtToStr_CauseMisc (const char* name, ASN1T_CauseMisc* pvalue, 
   char* buffer, OSSIZE bufSize)
{
   int stat;
   if(rtPrintToString (name, buffer, bufSize) < 0)
   {
      return -1;
   }
   switch (*pvalue) {
      case 0:
         stat = rtPrintToString (" = control-processing-overload\n", buffer, bufSize);
         break;

      case 1:
         stat = rtPrintToString (" = hardware-failure\n", buffer, bufSize);
         break;

      case 2:
         stat = rtPrintToString (" = om-intervention\n", buffer, bufSize);
         break;

      case 3:
         stat = rtPrintToString (" = unspecified\n", buffer, bufSize);
         break;

      default: stat = rtPrintToStringUnsigned ("", *pvalue, buffer, bufSize);
   }

   if(stat < 0) return -1;
   return 0;
}

int ASN1C_CauseMisc::toString (const char* name, char* buffer, OSSIZE bufSize)
{
   if (asn1PrtToStr_CauseMisc (name, &msgData, buffer, bufSize) < 0)
   {
      return -1;
   }
   return 0;
}

int ASN1C_CauseMisc::toString (char* buffer, OSSIZE bufSize)
{
   return toString ("CauseMisc", buffer, bufSize);
}

int asn1PrtToStr_Cause (const char* name, ASN1T_Cause* pvalue, char* buffer, 
   OSSIZE bufSize)
{
   {
   char namebuf2[512], numbuf[32];

   rtxIntToCharStr (pvalue->t, numbuf, sizeof(numbuf), 0);
   rtxStrJoin (namebuf2, sizeof(namebuf2), name, ".t = ", numbuf, "\n", 0);
   if (rtPrintToString (namebuf2, buffer, bufSize) < 0)
   {
      return -1;
   }

   switch (pvalue->t) {
      /* ricRequest */
      case 1:
      {
         rtxStrJoin (namebuf2, 512, name, ".u.ricRequest", 0, 0, 0);
         if (asn1PrtToStr_CauseRICrequest (namebuf2, &pvalue->u.ricRequest, buffer, bufSize) < 0)
         {
            return -1;
         }
         break;
      }
      /* ricService */
      case 2:
      {
         rtxStrJoin (namebuf2, 512, name, ".u.ricService", 0, 0, 0);
         if (asn1PrtToStr_CauseRICservice (namebuf2, &pvalue->u.ricService, buffer, bufSize) < 0)
         {
            return -1;
         }
         break;
      }
      /* e2Node */
      case 3:
      {
         rtxStrJoin (namebuf2, 512, name, ".u.e2Node", 0, 0, 0);
         if (asn1PrtToStr_CauseE2node (namebuf2, &pvalue->u.e2Node, buffer, bufSize) < 0)
         {
            return -1;
         }
         break;
      }
      /* transport */
      case 4:
      {
         rtxStrJoin (namebuf2, 512, name, ".u.transport", 0, 0, 0);
         if (asn1PrtToStr_CauseTransport (namebuf2, &pvalue->u.transport, buffer, bufSize) < 0)
         {
            return -1;
         }
         break;
      }
      /* protocol */
      case 5:
      {
         rtxStrJoin (namebuf2, 512, name, ".u.protocol", 0, 0, 0);
         if (asn1PrtToStr_CauseProtocol (namebuf2, &pvalue->u.protocol, buffer, bufSize) < 0)
         {
            return -1;
         }
         break;
      }
      /* misc */
      case 6:
      {
         rtxStrJoin (namebuf2, 512, name, ".u.misc", 0, 0, 0);
         if (asn1PrtToStr_CauseMisc (namebuf2, &pvalue->u.misc, buffer, bufSize) < 0)
         {
            return -1;
         }
         break;
      }
      /* extElem1 */
      case 7:
      {
         rtxStrJoin (namebuf2, 512, name, ".u.extElem1", 0, 0, 0);
         if(rtPrintToStringOpenType (namebuf2, pvalue->u.extElem1->numocts, pvalue->u.extElem1->data, ".", buffer, bufSize) < 0)
         {
            return -1;
         }
         break;
      }
      default:;
   }
   }
   return 0;
}

int ASN1C_Cause::toString (const char* name, char* buffer, OSSIZE bufSize)
{
   if (asn1PrtToStr_Cause (name, &msgData, buffer, bufSize) < 0)
   {
      return -1;
   }
   return 0;
}

int ASN1C_Cause::toString (char* buffer, OSSIZE bufSize)
{
   return toString ("Cause", buffer, bufSize);
}

int asn1PrtToStr_XAPP_ID (const char* name, ASN1T_XAPP_ID* pvalue, 
   char* buffer, OSSIZE bufSize)
{
   if (rtPrintToStringUnsigned (name, *pvalue, buffer, bufSize) < 0)
   {
      return -1;
   }
   return 0;
}

int ASN1C_XAPP_ID::toString (const char* name, char* buffer, OSSIZE bufSize)
{
   if (asn1PrtToStr_XAPP_ID (name, &msgData, buffer, bufSize) < 0)
   {
      return -1;
   }
   return 0;
}

int ASN1C_XAPP_ID::toString (char* buffer, OSSIZE bufSize)
{
   return toString ("XAPP_ID", buffer, bufSize);
}

int asn1PrtToStr_RICindicationSN (const char* name, 
   ASN1T_RICindicationSN* pvalue, char* buffer, OSSIZE bufSize)
{
   if (rtPrintToStringUnsigned (name, *pvalue, buffer, bufSize) < 0)
   {
      return -1;
   }
   return 0;
}

int ASN1C_RICindicationSN::toString (const char* name, char* buffer, OSSIZE bufSize)
{
   if (asn1PrtToStr_RICindicationSN (name, &msgData, buffer, bufSize) < 0)
   {
      return -1;
   }
   return 0;
}

int ASN1C_RICindicationSN::toString (char* buffer, OSSIZE bufSize)
{
   return toString ("RICindicationSN", buffer, bufSize);
}

int asn1PrtToStr_RICindicationType (const char* name, 
   ASN1T_RICindicationType* pvalue, char* buffer, OSSIZE bufSize)
{
   int stat;
   if(rtPrintToString (name, buffer, bufSize) < 0)
   {
      return -1;
   }
   switch (*pvalue) {
      case 0:
         stat = rtPrintToString (" = report\n", buffer, bufSize);
         break;

      case 1:
         stat = rtPrintToString (" = insert\n", buffer, bufSize);
         break;

      default: stat = rtPrintToStringUnsigned ("", *pvalue, buffer, bufSize);
   }

   if(stat < 0) return -1;
   return 0;
}

int ASN1C_RICindicationType::toString (const char* name, char* buffer, OSSIZE bufSize)
{
   if (asn1PrtToStr_RICindicationType (name, &msgData, buffer, bufSize) < 0)
   {
      return -1;
   }
   return 0;
}

int ASN1C_RICindicationType::toString (char* buffer, OSSIZE bufSize)
{
   return toString ("RICindicationType", buffer, bufSize);
}

int asn1PrtToStr_RICindicationHeader (const char* name, 
   ASN1T_RICindicationHeader* pvalue, char* buffer, OSSIZE bufSize)
{
   if (rtPrintToStringOctStr (name, pvalue->numocts, pvalue->data, ".", buffer, bufSize) < 0)
   {
      return -1;
   }
   return 0;
}

int ASN1C_RICindicationHeader::toString (const char* name, char* buffer, OSSIZE bufSize)
{
   if (asn1PrtToStr_RICindicationHeader (name, &msgData, buffer, bufSize) < 0)
   {
      return -1;
   }
   return 0;
}

int ASN1C_RICindicationHeader::toString (char* buffer, OSSIZE bufSize)
{
   return toString ("RICindicationHeader", buffer, bufSize);
}

int asn1PrtToStr_RICindicationMessage (const char* name, 
   ASN1T_RICindicationMessage* pvalue, char* buffer, OSSIZE bufSize)
{
   if (rtPrintToStringOctStr (name, pvalue->numocts, pvalue->data, ".", buffer, bufSize) < 0)
   {
      return -1;
   }
   return 0;
}

int ASN1C_RICindicationMessage::toString (const char* name, char* buffer, OSSIZE bufSize)
{
   if (asn1PrtToStr_RICindicationMessage (name, &msgData, buffer, bufSize) < 0)
   {
      return -1;
   }
   return 0;
}

int ASN1C_RICindicationMessage::toString (char* buffer, OSSIZE bufSize)
{
   return toString ("RICindicationMessage", buffer, bufSize);
}

int asn1PrtToStr_TypeOfError (const char* name, ASN1T_TypeOfError* pvalue, 
   char* buffer, OSSIZE bufSize)
{
   int stat;
   if(rtPrintToString (name, buffer, bufSize) < 0)
   {
      return -1;
   }
   switch (*pvalue) {
      case 0:
         stat = rtPrintToString (" = not-understood\n", buffer, bufSize);
         break;

      case 1:
         stat = rtPrintToString (" = missing\n", buffer, bufSize);
         break;

      default: stat = rtPrintToStringUnsigned ("", *pvalue, buffer, bufSize);
   }

   if(stat < 0) return -1;
   return 0;
}

int ASN1C_TypeOfError::toString (const char* name, char* buffer, OSSIZE bufSize)
{
   if (asn1PrtToStr_TypeOfError (name, &msgData, buffer, bufSize) < 0)
   {
      return -1;
   }
   return 0;
}

int ASN1C_TypeOfError::toString (char* buffer, OSSIZE bufSize)
{
   return toString ("TypeOfError", buffer, bufSize);
}

int asn1PrtToStr_CriticalityDiagnostics_IE_Item (const char* name, 
   ASN1T_CriticalityDiagnostics_IE_Item* pvalue, char* buffer, OSSIZE bufSize)
{
   char namebuf[512];

   rtxStrJoin (namebuf, 512, name, ".iECriticality", 0, 0, 0);
   if (asn1PrtToStr_Criticality (namebuf, &pvalue->iECriticality, buffer, bufSize) < 0)
   {
      return -1;
   }

   rtxStrJoin (namebuf, 512, name, ".iE_ID", 0, 0, 0);
   if (asn1PrtToStr_ProtocolIE_ID (namebuf, &pvalue->iE_ID, buffer, bufSize) < 0)
   {
      return -1;
   }

   rtxStrJoin (namebuf, 512, name, ".typeOfError", 0, 0, 0);
   if (asn1PrtToStr_TypeOfError (namebuf, &pvalue->typeOfError, buffer, bufSize) < 0)
   {
      return -1;
   }

   rtxStrJoin (namebuf, 512, name, ".extElem1", 0, 0, 0);
   if (rtPrintToStringOpenTypeExt (namebuf, &pvalue->extElem1, buffer, bufSize)  < 0)
   {
      return -1;
   }

   return 0;
}

int ASN1C_CriticalityDiagnostics_IE_Item::toString (const char* name, char* buffer, OSSIZE bufSize)
{
   if (asn1PrtToStr_CriticalityDiagnostics_IE_Item (name, &msgData, buffer, bufSize) < 0)
   {
      return -1;
   }
   return 0;
}

int ASN1C_CriticalityDiagnostics_IE_Item::toString (char* buffer, OSSIZE bufSize)
{
   return toString ("CriticalityDiagnostics_IE_Item", buffer, bufSize);
}

int asn1PrtToStr_CriticalityDiagnostics_IE_List (const char* name, 
   ASN1T_CriticalityDiagnostics_IE_List* pvalue, char* buffer, OSSIZE bufSize)
{
   ASN1T_CriticalityDiagnostics_IE_Item* pdata0;
   OSRTDListNode* pnode;
   char namebuf[512];
   char numbuf[32];

   rtxSizeToCharStr (pvalue->count, numbuf, sizeof(numbuf), 0);
   rtxStrJoin (namebuf, 512, name, ".count = ", numbuf, "\n", 0);
   if(rtPrintToString (namebuf, buffer, bufSize) < 0)
   {
      return -1;
   }

   {
   OSUINT32 xx1 = 0;

   for (pnode = pvalue->head; pnode != 0 && xx1 < pvalue->count; pnode = pnode->next) {
      pdata0 = ((ASN1T_CriticalityDiagnostics_IE_Item*)pnode->data);
      rtxUIntToCharStr (xx1, numbuf, sizeof(numbuf), 0);
      rtxStrJoin (namebuf, sizeof(namebuf), name, ".elem[", numbuf, "]", 0);
      if (asn1PrtToStr_CriticalityDiagnostics_IE_Item (namebuf, pdata0, buffer, bufSize) < 0)
      {
         return -1;
      }
      xx1++;
   }
   }
   return 0;
}

int ASN1C_CriticalityDiagnostics_IE_List::toString (const char* name, char* buffer, OSSIZE bufSize)
{
   if (asn1PrtToStr_CriticalityDiagnostics_IE_List (name, &msgData, buffer, bufSize) < 0)
   {
      return -1;
   }
   return 0;
}

int ASN1C_CriticalityDiagnostics_IE_List::toString (char* buffer, OSSIZE bufSize)
{
   return toString ("CriticalityDiagnostics_IE_List", buffer, bufSize);
}

int asn1PrtToStr_CriticalityDiagnostics (const char* name, 
   ASN1T_CriticalityDiagnostics* pvalue, char* buffer, OSSIZE bufSize)
{
   char namebuf[512];

   { char numbuf[32];
   rtxIntToCharStr ((int)pvalue->m.procedureCodePresent, numbuf, 32, 0);
   rtxStrJoin (namebuf, 512, name, ".m.procedureCodePresent = ", numbuf, "\n", 0);
   if (rtPrintToString (namebuf, buffer, bufSize) < 0) {
      return -1;
   }}
   { char numbuf[32];
   rtxIntToCharStr ((int)pvalue->m.triggeringMessagePresent, numbuf, 32, 0);
   rtxStrJoin (namebuf, 512, name, ".m.triggeringMessagePresent = ", numbuf, "\n", 0);
   if (rtPrintToString (namebuf, buffer, bufSize) < 0) {
      return -1;
   }}
   { char numbuf[32];
   rtxIntToCharStr ((int)pvalue->m.procedureCriticalityPresent, numbuf, 32, 0);
   rtxStrJoin (namebuf, 512, name, ".m.procedureCriticalityPresent = ", numbuf, "\n", 0);
   if (rtPrintToString (namebuf, buffer, bufSize) < 0) {
      return -1;
   }}
   { char numbuf[32];
   rtxIntToCharStr ((int)pvalue->m.ricRequestorIDPresent, numbuf, 32, 0);
   rtxStrJoin (namebuf, 512, name, ".m.ricRequestorIDPresent = ", numbuf, "\n", 0);
   if (rtPrintToString (namebuf, buffer, bufSize) < 0) {
      return -1;
   }}
   { char numbuf[32];
   rtxIntToCharStr ((int)pvalue->m.iEsCriticalityDiagnosticsPresent, numbuf, 32, 0);
   rtxStrJoin (namebuf, 512, name, ".m.iEsCriticalityDiagnosticsPresent = ", numbuf, "\n", 0);
   if (rtPrintToString (namebuf, buffer, bufSize) < 0) {
      return -1;
   }}
   if (pvalue->m.procedureCodePresent) {
      rtxStrJoin (namebuf, 512, name, ".procedureCode", 0, 0, 0);
      if (asn1PrtToStr_ProcedureCode (namebuf, &pvalue->procedureCode, buffer, bufSize) < 0)
      {
         return -1;
      }
   }

   if (pvalue->m.triggeringMessagePresent) {
      rtxStrJoin (namebuf, 512, name, ".triggeringMessage", 0, 0, 0);
      if (asn1PrtToStr_TriggeringMessage (namebuf, &pvalue->triggeringMessage, buffer, bufSize) < 0)
      {
         return -1;
      }
   }

   if (pvalue->m.procedureCriticalityPresent) {
      rtxStrJoin (namebuf, 512, name, ".procedureCriticality", 0, 0, 0);
      if (asn1PrtToStr_Criticality (namebuf, &pvalue->procedureCriticality, buffer, bufSize) < 0)
      {
         return -1;
      }
   }

   if (pvalue->m.ricRequestorIDPresent) {
      rtxStrJoin (namebuf, 512, name, ".ricRequestorID", 0, 0, 0);
      if (asn1PrtToStr_RICrequestID (namebuf, &pvalue->ricRequestorID, buffer, bufSize) < 0)
      {
         return -1;
      }
   }

   if (pvalue->m.iEsCriticalityDiagnosticsPresent) {
      rtxStrJoin (namebuf, 512, name, ".iEsCriticalityDiagnostics", 0, 0, 0);
      if (asn1PrtToStr_CriticalityDiagnostics_IE_List (namebuf, &pvalue->iEsCriticalityDiagnostics, buffer, bufSize) < 0)
      {
         return -1;
      }
   }

   rtxStrJoin (namebuf, 512, name, ".extElem1", 0, 0, 0);
   if (rtPrintToStringOpenTypeExt (namebuf, &pvalue->extElem1, buffer, bufSize)  < 0)
   {
      return -1;
   }

   return 0;
}

int ASN1C_CriticalityDiagnostics::toString (const char* name, char* buffer, OSSIZE bufSize)
{
   if (asn1PrtToStr_CriticalityDiagnostics (name, &msgData, buffer, bufSize) < 0)
   {
      return -1;
   }
   return 0;
}

int ASN1C_CriticalityDiagnostics::toString (char* buffer, OSSIZE bufSize)
{
   return toString ("CriticalityDiagnostics", buffer, bufSize);
}

int asn1PrtToStr_RICcontrolOutcome (const char* name, 
   ASN1T_RICcontrolOutcome* pvalue, char* buffer, OSSIZE bufSize)
{
   if (rtPrintToStringOctStr (name, pvalue->numocts, pvalue->data, ".", buffer, bufSize) < 0)
   {
      return -1;
   }
   return 0;
}

int ASN1C_RICcontrolOutcome::toString (const char* name, char* buffer, OSSIZE bufSize)
{
   if (asn1PrtToStr_RICcontrolOutcome (name, &msgData, buffer, bufSize) < 0)
   {
      return -1;
   }
   return 0;
}

int ASN1C_RICcontrolOutcome::toString (char* buffer, OSSIZE bufSize)
{
   return toString ("RICcontrolOutcome", buffer, bufSize);
}

int asn1PrtToStr_GlobalRIC_ID (const char* name, ASN1T_GlobalRIC_ID* pvalue, 
   char* buffer, OSSIZE bufSize)
{
   char namebuf[512];

   rtxStrJoin (namebuf, 512, name, ".pLMN_Identity", 0, 0, 0);
   if (asn1PrtToStr_PLMN_Identity (namebuf, &pvalue->pLMN_Identity, buffer, bufSize) < 0)
   {
      return -1;
   }

   rtxStrJoin (namebuf, 512, name, ".ric_ID", 0, 0, 0);
   if (rtPrintToStringBitStr (namebuf, OS_MIN(pvalue->ric_ID.numbits, 24), pvalue->ric_ID.data, ".", buffer, bufSize) < 0)
   {
      return -1;
   }

   rtxStrJoin (namebuf, 512, name, ".extElem1", 0, 0, 0);
   if (rtPrintToStringOpenTypeExt (namebuf, &pvalue->extElem1, buffer, bufSize)  < 0)
   {
      return -1;
   }

   return 0;
}

int ASN1C_GlobalRIC_ID::toString (const char* name, char* buffer, OSSIZE bufSize)
{
   if (asn1PrtToStr_GlobalRIC_ID (name, &msgData, buffer, bufSize) < 0)
   {
      return -1;
   }
   return 0;
}

int ASN1C_GlobalRIC_ID::toString (char* buffer, OSSIZE bufSize)
{
   return toString ("GlobalRIC_ID", buffer, bufSize);
}

int asn1PrtToStr_E2nodeComponentConfigurationAck_updateOutcome (
   const char* name, 
   ASN1T_E2nodeComponentConfigurationAck_updateOutcome* pvalue, char* buffer, 
   OSSIZE bufSize)
{
   int stat;
   if(rtPrintToString (name, buffer, bufSize) < 0)
   {
      return -1;
   }
   switch (*pvalue) {
      case 0:
         stat = rtPrintToString (" = success\n", buffer, bufSize);
         break;

      case 1:
         stat = rtPrintToString (" = failure\n", buffer, bufSize);
         break;

      default: stat = rtPrintToStringUnsigned ("", *pvalue, buffer, bufSize);
   }

   if(stat < 0) return -1;
   return 0;
}

int ASN1C_E2nodeComponentConfigurationAck_updateOutcome::toString (const char* name, char* buffer, OSSIZE bufSize)
{
   if (asn1PrtToStr_E2nodeComponentConfigurationAck_updateOutcome (name, &msgData, buffer, bufSize) < 0)
   {
      return -1;
   }
   return 0;
}

int ASN1C_E2nodeComponentConfigurationAck_updateOutcome::toString (char* buffer, OSSIZE bufSize)
{
   return toString ("E2nodeComponentConfigurationAck_updateOutcome", buffer, bufSize);
}

int asn1PrtToStr_E2nodeComponentConfigurationAck (const char* name, 
   ASN1T_E2nodeComponentConfigurationAck* pvalue, char* buffer, OSSIZE bufSize)
{
   char namebuf[512];

   { char numbuf[32];
   rtxIntToCharStr ((int)pvalue->m.failureCausePresent, numbuf, 32, 0);
   rtxStrJoin (namebuf, 512, name, ".m.failureCausePresent = ", numbuf, "\n", 0);
   if (rtPrintToString (namebuf, buffer, bufSize) < 0) {
      return -1;
   }}
   rtxStrJoin (namebuf, 512, name, ".updateOutcome", 0, 0, 0);
   if (asn1PrtToStr_E2nodeComponentConfigurationAck_updateOutcome (namebuf, &pvalue->updateOutcome, buffer, bufSize) < 0)
   {
      return -1;
   }

   if (pvalue->m.failureCausePresent) {
      rtxStrJoin (namebuf, 512, name, ".failureCause", 0, 0, 0);
      if (asn1PrtToStr_Cause (namebuf, &pvalue->failureCause, buffer, bufSize) < 0)
      {
         return -1;
      }
   }

   rtxStrJoin (namebuf, 512, name, ".extElem1", 0, 0, 0);
   if (rtPrintToStringOpenTypeExt (namebuf, &pvalue->extElem1, buffer, bufSize)  < 0)
   {
      return -1;
   }

   return 0;
}

int ASN1C_E2nodeComponentConfigurationAck::toString (const char* name, char* buffer, OSSIZE bufSize)
{
   if (asn1PrtToStr_E2nodeComponentConfigurationAck (name, &msgData, buffer, bufSize) < 0)
   {
      return -1;
   }
   return 0;
}

int ASN1C_E2nodeComponentConfigurationAck::toString (char* buffer, OSSIZE bufSize)
{
   return toString ("E2nodeComponentConfigurationAck", buffer, bufSize);
}

int asn1PrtToStr_TimeToWait (const char* name, ASN1T_TimeToWait* pvalue, 
   char* buffer, OSSIZE bufSize)
{
   int stat;
   if(rtPrintToString (name, buffer, bufSize) < 0)
   {
      return -1;
   }
   switch (*pvalue) {
      case 0:
         stat = rtPrintToString (" = v1s\n", buffer, bufSize);
         break;

      case 1:
         stat = rtPrintToString (" = v2s\n", buffer, bufSize);
         break;

      case 2:
         stat = rtPrintToString (" = v5s\n", buffer, bufSize);
         break;

      case 3:
         stat = rtPrintToString (" = v10s\n", buffer, bufSize);
         break;

      case 4:
         stat = rtPrintToString (" = v20s\n", buffer, bufSize);
         break;

      case 5:
         stat = rtPrintToString (" = v60s\n", buffer, bufSize);
         break;

      default: stat = rtPrintToStringUnsigned ("", *pvalue, buffer, bufSize);
   }

   if(stat < 0) return -1;
   return 0;
}

int ASN1C_TimeToWait::toString (const char* name, char* buffer, OSSIZE bufSize)
{
   if (asn1PrtToStr_TimeToWait (name, &msgData, buffer, bufSize) < 0)
   {
      return -1;
   }
   return 0;
}

int ASN1C_TimeToWait::toString (char* buffer, OSSIZE bufSize)
{
   return toString ("TimeToWait", buffer, bufSize);
}

