/**
 * This file was generated by the Objective Systems ASN1C Compiler
 * (http://www.obj-sys.com).  Version: 7.8.2.5, Date: 12-Sep-2025.
 *
 * Command:  asn1c asn1files/E2SM-KPM-v05.00.asn asn1files/asn_flexric/e2sm_rc_v1_03_modified.asn asn1files/asn_flexric/e42ap_v2_03.asn -genTest -per -json -w32 -server -depends -events -genPrtToStr -list -reader -trace -c++ -print -prtfmt details -srcdir src -make Makefile -w32 -table-unions -stream -pdu all
 */
#include "E2AP-CommonDataTypes.h"
#include "rtxsrc/rtxCharStr.h"
#include "rtsrc/rtPrintToString.h"
#include "rtsrc/rtBCD.h"
#include "rtxsrc/rtxDiag.h"

int asn1PrtToStr_ProcedureCode (const char* name, ASN1T_ProcedureCode* pvalue, 
   char* buffer, OSSIZE bufSize)
{
   if (rtPrintToStringUnsigned (name, *pvalue, buffer, bufSize) < 0)
   {
      return -1;
   }
   return 0;
}

int ASN1C_ProcedureCode::toString (const char* name, char* buffer, OSSIZE bufSize)
{
   if (asn1PrtToStr_ProcedureCode (name, &msgData, buffer, bufSize) < 0)
   {
      return -1;
   }
   return 0;
}

int ASN1C_ProcedureCode::toString (char* buffer, OSSIZE bufSize)
{
   return toString ("ProcedureCode", buffer, bufSize);
}

int asn1PrtToStr_Criticality (const char* name, ASN1T_Criticality* pvalue, 
   char* buffer, OSSIZE bufSize)
{
   int stat;
   if(rtPrintToString (name, buffer, bufSize) < 0)
   {
      return -1;
   }
   switch (*pvalue) {
      case 0:
         stat = rtPrintToString (" = reject\n", buffer, bufSize);
         break;

      case 1:
         stat = rtPrintToString (" = ignore\n", buffer, bufSize);
         break;

      case 2:
         stat = rtPrintToString (" = notify\n", buffer, bufSize);
         break;

      default:
      stat = rtPrintToString (" = ???\n", buffer, bufSize);
   }

   if(stat < 0) return -1;
   return 0;
}

int ASN1C_Criticality::toString (const char* name, char* buffer, OSSIZE bufSize)
{
   if (asn1PrtToStr_Criticality (name, &msgData, buffer, bufSize) < 0)
   {
      return -1;
   }
   return 0;
}

int ASN1C_Criticality::toString (char* buffer, OSSIZE bufSize)
{
   return toString ("Criticality", buffer, bufSize);
}

int asn1PrtToStr_ProtocolIE_ID (const char* name, ASN1T_ProtocolIE_ID* pvalue, 
   char* buffer, OSSIZE bufSize)
{
   if (rtPrintToStringUnsigned (name, *pvalue, buffer, bufSize) < 0)
   {
      return -1;
   }
   return 0;
}

int ASN1C_ProtocolIE_ID::toString (const char* name, char* buffer, OSSIZE bufSize)
{
   if (asn1PrtToStr_ProtocolIE_ID (name, &msgData, buffer, bufSize) < 0)
   {
      return -1;
   }
   return 0;
}

int ASN1C_ProtocolIE_ID::toString (char* buffer, OSSIZE bufSize)
{
   return toString ("ProtocolIE_ID", buffer, bufSize);
}

int asn1PrtToStr_TriggeringMessage (const char* name, 
   ASN1T_TriggeringMessage* pvalue, char* buffer, OSSIZE bufSize)
{
   int stat;
   if(rtPrintToString (name, buffer, bufSize) < 0)
   {
      return -1;
   }
   switch (*pvalue) {
      case 0:
         stat = rtPrintToString (" = initiating-message\n", buffer, bufSize);
         break;

      case 1:
         stat = rtPrintToString (" = successful-outcome\n", buffer, bufSize);
         break;

      case 2:
         stat = rtPrintToString (" = unsuccessfull-outcome\n", buffer, bufSize);
         break;

      default:
      stat = rtPrintToString (" = ???\n", buffer, bufSize);
   }

   if(stat < 0) return -1;
   return 0;
}

int ASN1C_TriggeringMessage::toString (const char* name, char* buffer, OSSIZE bufSize)
{
   if (asn1PrtToStr_TriggeringMessage (name, &msgData, buffer, bufSize) < 0)
   {
      return -1;
   }
   return 0;
}

int ASN1C_TriggeringMessage::toString (char* buffer, OSSIZE bufSize)
{
   return toString ("TriggeringMessage", buffer, bufSize);
}

int asn1PrtToStr_Presence (const char* name, ASN1T_Presence* pvalue, 
   char* buffer, OSSIZE bufSize)
{
   int stat;
   if(rtPrintToString (name, buffer, bufSize) < 0)
   {
      return -1;
   }
   switch (*pvalue) {
      case 0:
         stat = rtPrintToString (" = optional\n", buffer, bufSize);
         break;

      case 1:
         stat = rtPrintToString (" = conditional\n", buffer, bufSize);
         break;

      case 2:
         stat = rtPrintToString (" = mandatory\n", buffer, bufSize);
         break;

      default:
      stat = rtPrintToString (" = ???\n", buffer, bufSize);
   }

   if(stat < 0) return -1;
   return 0;
}

int ASN1C_Presence::toString (const char* name, char* buffer, OSSIZE bufSize)
{
   if (asn1PrtToStr_Presence (name, &msgData, buffer, bufSize) < 0)
   {
      return -1;
   }
   return 0;
}

int ASN1C_Presence::toString (char* buffer, OSSIZE bufSize)
{
   return toString ("Presence", buffer, bufSize);
}

