/**
 * This file was generated by the Objective Systems ASN1C Compiler
 * (http://www.obj-sys.com).  Version: 7.8.2.5, Date: 27-Jun-2025.
 *
 * Command:  asn1c ./asn1files/E2SM-KPM-v05.00.asn ./asn1files/asn_flexric/e2sm_rc_v1_03_modified.asn ./asn1files/asn_flexric/e42ap_v2_03.asn -cpp -json -per -depends -events -oh ./src -i asn1files -i asn1files/asn_flexric -o ./src -genprint -printformat details -genprttostr -printformat details -stream -table-unions -gentest -trace
 */
#include "E2SM-COMMON-IEs.h"
#include "rtxsrc/rtxCharStr.h"
#include "rtsrc/rtPrintToString.h"
#include "rtsrc/rtBCD.h"
#include "rtxsrc/rtxDiag.h"

int asn1PrtToStr_PLMNIdentity (const char* name, ASN1T_PLMNIdentity* pvalue, 
   char* buffer, OSSIZE bufSize)
{
   if (rtPrintToStringOctStr (name, OSRTMIN(sizeof(pvalue->data), pvalue->numocts), pvalue->data, ".", buffer, bufSize) < 0)
   {
      return -1;
   }
   return 0;
}

int asn1PrtToStr_SST (const char* name, ASN1T_SST* pvalue, char* buffer, 
   OSSIZE bufSize)
{
   if (rtPrintToStringOctStr (name, OSRTMIN(sizeof(pvalue->data), pvalue->numocts), pvalue->data, ".", buffer, bufSize) < 0)
   {
      return -1;
   }
   return 0;
}

int asn1PrtToStr_SD (const char* name, ASN1T_SD* pvalue, char* buffer, 
   OSSIZE bufSize)
{
   if (rtPrintToStringOctStr (name, OSRTMIN(sizeof(pvalue->data), pvalue->numocts), pvalue->data, ".", buffer, bufSize) < 0)
   {
      return -1;
   }
   return 0;
}

int asn1PrtToStr_S_NSSAI (const char* name, ASN1T_S_NSSAI* pvalue, 
   char* buffer, OSSIZE bufSize)
{
   char namebuf[512];

   { char numbuf[32];
   rtxIntToCharStr ((int)pvalue->m.sDPresent, numbuf, 32, 0);
   rtxStrJoin (namebuf, 512, name, ".m.sDPresent = ", numbuf, "\n", 0);
   if (rtPrintToString (namebuf, buffer, bufSize) < 0) {
      return -1;
   }}
   rtxStrJoin (namebuf, 512, name, ".sST", 0, 0, 0);
   if (asn1PrtToStr_SST (namebuf, &pvalue->sST, buffer, bufSize) < 0)
   {
      return -1;
   }

   if (pvalue->m.sDPresent) {
      rtxStrJoin (namebuf, 512, name, ".sD", 0, 0, 0);
      if (asn1PrtToStr_SD (namebuf, &pvalue->sD, buffer, bufSize) < 0)
      {
         return -1;
      }
   }

   rtxStrJoin (namebuf, 512, name, ".extElem1", 0, 0, 0);
   if (rtPrintToStringOpenTypeExt (namebuf, &pvalue->extElem1, buffer, bufSize)  < 0)
   {
      return -1;
   }

   return 0;
}

int asn1PrtToStr_FiveQI (const char* name, ASN1T_FiveQI* pvalue, char* buffer, 
   OSSIZE bufSize)
{
   if (rtPrintToStringUnsigned (name, *pvalue, buffer, bufSize) < 0)
   {
      return -1;
   }
   return 0;
}

int asn1PrtToStr_QosFlowIdentifier (const char* name, 
   ASN1T_QosFlowIdentifier* pvalue, char* buffer, OSSIZE bufSize)
{
   if (rtPrintToStringUnsigned (name, *pvalue, buffer, bufSize) < 0)
   {
      return -1;
   }
   return 0;
}

int asn1PrtToStr_QCI (const char* name, ASN1T_QCI* pvalue, char* buffer, 
   OSSIZE bufSize)
{
   if (rtPrintToStringUnsigned (name, *pvalue, buffer, bufSize) < 0)
   {
      return -1;
   }
   return 0;
}

int asn1PrtToStr_NRCellIdentity (const char* name, 
   ASN1T_NRCellIdentity* pvalue, char* buffer, OSSIZE bufSize)
{
   if (rtPrintToStringBitStr (name, OS_MIN(pvalue->numbits, 40), pvalue->data, ".", buffer, bufSize) < 0)
   {
      return -1;
   }
   return 0;
}

int asn1PrtToStr_NR_CGI (const char* name, ASN1T_NR_CGI* pvalue, char* buffer, 
   OSSIZE bufSize)
{
   char namebuf[512];

   rtxStrJoin (namebuf, 512, name, ".pLMNIdentity", 0, 0, 0);
   if (asn1PrtToStr_PLMNIdentity (namebuf, &pvalue->pLMNIdentity, buffer, bufSize) < 0)
   {
      return -1;
   }

   rtxStrJoin (namebuf, 512, name, ".nRCellIdentity", 0, 0, 0);
   if (asn1PrtToStr_NRCellIdentity (namebuf, &pvalue->nRCellIdentity, buffer, bufSize) < 0)
   {
      return -1;
   }

   rtxStrJoin (namebuf, 512, name, ".extElem1", 0, 0, 0);
   if (rtPrintToStringOpenTypeExt (namebuf, &pvalue->extElem1, buffer, bufSize)  < 0)
   {
      return -1;
   }

   return 0;
}

int asn1PrtToStr_EUTRACellIdentity (const char* name, 
   ASN1T_EUTRACellIdentity* pvalue, char* buffer, OSSIZE bufSize)
{
   if (rtPrintToStringBitStr (name, OS_MIN(pvalue->numbits, 32), pvalue->data, ".", buffer, bufSize) < 0)
   {
      return -1;
   }
   return 0;
}

int asn1PrtToStr_EUTRA_CGI (const char* name, ASN1T_EUTRA_CGI* pvalue, 
   char* buffer, OSSIZE bufSize)
{
   char namebuf[512];

   rtxStrJoin (namebuf, 512, name, ".pLMNIdentity", 0, 0, 0);
   if (asn1PrtToStr_PLMNIdentity (namebuf, &pvalue->pLMNIdentity, buffer, bufSize) < 0)
   {
      return -1;
   }

   rtxStrJoin (namebuf, 512, name, ".eUTRACellIdentity", 0, 0, 0);
   if (asn1PrtToStr_EUTRACellIdentity (namebuf, &pvalue->eUTRACellIdentity, buffer, bufSize) < 0)
   {
      return -1;
   }

   rtxStrJoin (namebuf, 512, name, ".extElem1", 0, 0, 0);
   if (rtPrintToStringOpenTypeExt (namebuf, &pvalue->extElem1, buffer, bufSize)  < 0)
   {
      return -1;
   }

   return 0;
}

int asn1PrtToStr_CGI (const char* name, ASN1T_CGI* pvalue, char* buffer, 
   OSSIZE bufSize)
{
   {
   char namebuf2[512], numbuf[32];

   rtxIntToCharStr (pvalue->t, numbuf, sizeof(numbuf), 0);
   rtxStrJoin (namebuf2, sizeof(namebuf2), name, ".t = ", numbuf, "\n", 0);
   if (rtPrintToString (namebuf2, buffer, bufSize) < 0)
   {
      return -1;
   }

   switch (pvalue->t) {
      /* nR-CGI */
      case 1:
      {
         rtxStrJoin (namebuf2, 512, name, ".u.nR_CGI", 0, 0, 0);
         if (asn1PrtToStr_NR_CGI (namebuf2, pvalue->u.nR_CGI, buffer, bufSize) < 0)
         {
            return -1;
         }
         break;
      }
      /* eUTRA-CGI */
      case 2:
      {
         rtxStrJoin (namebuf2, 512, name, ".u.eUTRA_CGI", 0, 0, 0);
         if (asn1PrtToStr_EUTRA_CGI (namebuf2, pvalue->u.eUTRA_CGI, buffer, bufSize) < 0)
         {
            return -1;
         }
         break;
      }
      /* extElem1 */
      case 3:
      {
         rtxStrJoin (namebuf2, 512, name, ".u.extElem1", 0, 0, 0);
         if(rtPrintToStringOpenType (namebuf2, pvalue->u.extElem1->numocts, pvalue->u.extElem1->data, ".", buffer, bufSize) < 0)
         {
            return -1;
         }
         break;
      }
      default:;
   }
   }
   return 0;
}

int asn1PrtToStr_AMF_UE_NGAP_ID (const char* name, 
   ASN1T_AMF_UE_NGAP_ID* pvalue, char* buffer, OSSIZE bufSize)
{
   if (rtPrintToStringUInt64 (name, *pvalue, buffer, bufSize) < 0)
   {
      return -1;
   }
   return 0;
}

int asn1PrtToStr_AMFRegionID (const char* name, ASN1T_AMFRegionID* pvalue, 
   char* buffer, OSSIZE bufSize)
{
   if (rtPrintToStringBitStr (name, OS_MIN(pvalue->numbits, 8), pvalue->data, ".", buffer, bufSize) < 0)
   {
      return -1;
   }
   return 0;
}

int asn1PrtToStr_AMFSetID (const char* name, ASN1T_AMFSetID* pvalue, 
   char* buffer, OSSIZE bufSize)
{
   if (rtPrintToStringBitStr (name, OS_MIN(pvalue->numbits, 16), pvalue->data, ".", buffer, bufSize) < 0)
   {
      return -1;
   }
   return 0;
}

int asn1PrtToStr_AMFPointer (const char* name, ASN1T_AMFPointer* pvalue, 
   char* buffer, OSSIZE bufSize)
{
   if (rtPrintToStringBitStr (name, OS_MIN(pvalue->numbits, 8), pvalue->data, ".", buffer, bufSize) < 0)
   {
      return -1;
   }
   return 0;
}

int asn1PrtToStr_GUAMI (const char* name, ASN1T_GUAMI* pvalue, char* buffer, 
   OSSIZE bufSize)
{
   char namebuf[512];

   rtxStrJoin (namebuf, 512, name, ".pLMNIdentity", 0, 0, 0);
   if (asn1PrtToStr_PLMNIdentity (namebuf, &pvalue->pLMNIdentity, buffer, bufSize) < 0)
   {
      return -1;
   }

   rtxStrJoin (namebuf, 512, name, ".aMFRegionID", 0, 0, 0);
   if (asn1PrtToStr_AMFRegionID (namebuf, &pvalue->aMFRegionID, buffer, bufSize) < 0)
   {
      return -1;
   }

   rtxStrJoin (namebuf, 512, name, ".aMFSetID", 0, 0, 0);
   if (asn1PrtToStr_AMFSetID (namebuf, &pvalue->aMFSetID, buffer, bufSize) < 0)
   {
      return -1;
   }

   rtxStrJoin (namebuf, 512, name, ".aMFPointer", 0, 0, 0);
   if (asn1PrtToStr_AMFPointer (namebuf, &pvalue->aMFPointer, buffer, bufSize) < 0)
   {
      return -1;
   }

   rtxStrJoin (namebuf, 512, name, ".extElem1", 0, 0, 0);
   if (rtPrintToStringOpenTypeExt (namebuf, &pvalue->extElem1, buffer, bufSize)  < 0)
   {
      return -1;
   }

   return 0;
}

int asn1PrtToStr_GNB_CU_UE_F1AP_ID (const char* name, 
   ASN1T_GNB_CU_UE_F1AP_ID* pvalue, char* buffer, OSSIZE bufSize)
{
   if (rtPrintToStringUnsigned (name, *pvalue, buffer, bufSize) < 0)
   {
      return -1;
   }
   return 0;
}

int asn1PrtToStr_UEID_GNB_CU_CP_F1AP_ID_Item (const char* name, 
   ASN1T_UEID_GNB_CU_CP_F1AP_ID_Item* pvalue, char* buffer, OSSIZE bufSize)
{
   char namebuf[512];

   rtxStrJoin (namebuf, 512, name, ".gNB_CU_UE_F1AP_ID", 0, 0, 0);
   if (asn1PrtToStr_GNB_CU_UE_F1AP_ID (namebuf, &pvalue->gNB_CU_UE_F1AP_ID, buffer, bufSize) < 0)
   {
      return -1;
   }

   rtxStrJoin (namebuf, 512, name, ".extElem1", 0, 0, 0);
   if (rtPrintToStringOpenTypeExt (namebuf, &pvalue->extElem1, buffer, bufSize)  < 0)
   {
      return -1;
   }

   return 0;
}

int asn1PrtToStr_UEID_GNB_CU_F1AP_ID_List (const char* name, 
   ASN1T_UEID_GNB_CU_F1AP_ID_List* pvalue, char* buffer, OSSIZE bufSize)
{
   ASN1T_UEID_GNB_CU_CP_F1AP_ID_Item* pdata0;
   OSRTDListNode* pnode;
   char namebuf[512];
   char numbuf[32];

   rtxSizeToCharStr (pvalue->count, numbuf, sizeof(numbuf), 0);
   rtxStrJoin (namebuf, 512, name, ".count = ", numbuf, "\n", 0);
   if(rtPrintToString (namebuf, buffer, bufSize) < 0)
   {
      return -1;
   }

   {
   OSUINT32 xx1 = 0;

   for (pnode = pvalue->head; pnode != 0 && xx1 < pvalue->count; pnode = pnode->next) {
      pdata0 = ((ASN1T_UEID_GNB_CU_CP_F1AP_ID_Item*)pnode->data);
      rtxUIntToCharStr (xx1, numbuf, sizeof(numbuf), 0);
      rtxStrJoin (namebuf, sizeof(namebuf), name, ".elem[", numbuf, "]", 0);
      if (asn1PrtToStr_UEID_GNB_CU_CP_F1AP_ID_Item (namebuf, pdata0, buffer, bufSize) < 0)
      {
         return -1;
      }
      xx1++;
   }
   }
   return 0;
}

int asn1PrtToStr_GNB_CU_CP_UE_E1AP_ID (const char* name, 
   ASN1T_GNB_CU_CP_UE_E1AP_ID* pvalue, char* buffer, OSSIZE bufSize)
{
   if (rtPrintToStringUnsigned (name, *pvalue, buffer, bufSize) < 0)
   {
      return -1;
   }
   return 0;
}

int asn1PrtToStr_UEID_GNB_CU_CP_E1AP_ID_Item (const char* name, 
   ASN1T_UEID_GNB_CU_CP_E1AP_ID_Item* pvalue, char* buffer, OSSIZE bufSize)
{
   char namebuf[512];

   rtxStrJoin (namebuf, 512, name, ".gNB_CU_CP_UE_E1AP_ID", 0, 0, 0);
   if (asn1PrtToStr_GNB_CU_CP_UE_E1AP_ID (namebuf, &pvalue->gNB_CU_CP_UE_E1AP_ID, buffer, bufSize) < 0)
   {
      return -1;
   }

   rtxStrJoin (namebuf, 512, name, ".extElem1", 0, 0, 0);
   if (rtPrintToStringOpenTypeExt (namebuf, &pvalue->extElem1, buffer, bufSize)  < 0)
   {
      return -1;
   }

   return 0;
}

int asn1PrtToStr_UEID_GNB_CU_CP_E1AP_ID_List (const char* name, 
   ASN1T_UEID_GNB_CU_CP_E1AP_ID_List* pvalue, char* buffer, OSSIZE bufSize)
{
   ASN1T_UEID_GNB_CU_CP_E1AP_ID_Item* pdata0;
   OSRTDListNode* pnode;
   char namebuf[512];
   char numbuf[32];

   rtxSizeToCharStr (pvalue->count, numbuf, sizeof(numbuf), 0);
   rtxStrJoin (namebuf, 512, name, ".count = ", numbuf, "\n", 0);
   if(rtPrintToString (namebuf, buffer, bufSize) < 0)
   {
      return -1;
   }

   {
   OSUINT32 xx1 = 0;

   for (pnode = pvalue->head; pnode != 0 && xx1 < pvalue->count; pnode = pnode->next) {
      pdata0 = ((ASN1T_UEID_GNB_CU_CP_E1AP_ID_Item*)pnode->data);
      rtxUIntToCharStr (xx1, numbuf, sizeof(numbuf), 0);
      rtxStrJoin (namebuf, sizeof(namebuf), name, ".elem[", numbuf, "]", 0);
      if (asn1PrtToStr_UEID_GNB_CU_CP_E1AP_ID_Item (namebuf, pdata0, buffer, bufSize) < 0)
      {
         return -1;
      }
      xx1++;
   }
   }
   return 0;
}

int asn1PrtToStr_RANUEID (const char* name, ASN1T_RANUEID* pvalue, 
   char* buffer, OSSIZE bufSize)
{
   if (rtPrintToStringOctStr (name, OSRTMIN(sizeof(pvalue->data), pvalue->numocts), pvalue->data, ".", buffer, bufSize) < 0)
   {
      return -1;
   }
   return 0;
}

int asn1PrtToStr_NG_RANnodeUEXnAPID (const char* name, 
   ASN1T_NG_RANnodeUEXnAPID* pvalue, char* buffer, OSSIZE bufSize)
{
   if (rtPrintToStringUnsigned (name, *pvalue, buffer, bufSize) < 0)
   {
      return -1;
   }
   return 0;
}

int asn1PrtToStr_GNB_ID (const char* name, ASN1T_GNB_ID* pvalue, char* buffer, 
   OSSIZE bufSize)
{
   {
   char namebuf2[512], numbuf[32];

   rtxIntToCharStr (pvalue->t, numbuf, sizeof(numbuf), 0);
   rtxStrJoin (namebuf2, sizeof(namebuf2), name, ".t = ", numbuf, "\n", 0);
   if (rtPrintToString (namebuf2, buffer, bufSize) < 0)
   {
      return -1;
   }

   switch (pvalue->t) {
      /* gNB-ID */
      case 1:
      {
         rtxStrJoin (namebuf2, 512, name, ".u.gNB_ID", 0, 0, 0);
         if (rtPrintToStringBitStr (namebuf2, OS_MIN(pvalue->u.gNB_ID->numbits, 32), pvalue->u.gNB_ID->data, ".", buffer, bufSize) < 0)
         {
            return -1;
         }
         break;
      }
      /* extElem1 */
      case 2:
      {
         rtxStrJoin (namebuf2, 512, name, ".u.extElem1", 0, 0, 0);
         if(rtPrintToStringOpenType (namebuf2, pvalue->u.extElem1->numocts, pvalue->u.extElem1->data, ".", buffer, bufSize) < 0)
         {
            return -1;
         }
         break;
      }
      default:;
   }
   }
   return 0;
}

int asn1PrtToStr_GlobalGNB_ID (const char* name, ASN1T_GlobalGNB_ID* pvalue, 
   char* buffer, OSSIZE bufSize)
{
   char namebuf[512];

   rtxStrJoin (namebuf, 512, name, ".pLMNIdentity", 0, 0, 0);
   if (asn1PrtToStr_PLMNIdentity (namebuf, &pvalue->pLMNIdentity, buffer, bufSize) < 0)
   {
      return -1;
   }

   rtxStrJoin (namebuf, 512, name, ".gNB_ID", 0, 0, 0);
   if (asn1PrtToStr_GNB_ID (namebuf, &pvalue->gNB_ID, buffer, bufSize) < 0)
   {
      return -1;
   }

   rtxStrJoin (namebuf, 512, name, ".extElem1", 0, 0, 0);
   if (rtPrintToStringOpenTypeExt (namebuf, &pvalue->extElem1, buffer, bufSize)  < 0)
   {
      return -1;
   }

   return 0;
}

int asn1PrtToStr_NgENB_ID (const char* name, ASN1T_NgENB_ID* pvalue, 
   char* buffer, OSSIZE bufSize)
{
   {
   char namebuf2[512], numbuf[32];

   rtxIntToCharStr (pvalue->t, numbuf, sizeof(numbuf), 0);
   rtxStrJoin (namebuf2, sizeof(namebuf2), name, ".t = ", numbuf, "\n", 0);
   if (rtPrintToString (namebuf2, buffer, bufSize) < 0)
   {
      return -1;
   }

   switch (pvalue->t) {
      /* macroNgENB-ID */
      case 1:
      {
         rtxStrJoin (namebuf2, 512, name, ".u.macroNgENB_ID", 0, 0, 0);
         if (rtPrintToStringBitStr (namebuf2, OS_MIN(pvalue->u.macroNgENB_ID->numbits, 24), pvalue->u.macroNgENB_ID->data, ".", buffer, bufSize) < 0)
         {
            return -1;
         }
         break;
      }
      /* shortMacroNgENB-ID */
      case 2:
      {
         rtxStrJoin (namebuf2, 512, name, ".u.shortMacroNgENB_ID", 0, 0, 0);
         if (rtPrintToStringBitStr (namebuf2, OS_MIN(pvalue->u.shortMacroNgENB_ID->numbits, 24), pvalue->u.shortMacroNgENB_ID->data, ".", buffer, bufSize) < 0)
         {
            return -1;
         }
         break;
      }
      /* longMacroNgENB-ID */
      case 3:
      {
         rtxStrJoin (namebuf2, 512, name, ".u.longMacroNgENB_ID", 0, 0, 0);
         if (rtPrintToStringBitStr (namebuf2, OS_MIN(pvalue->u.longMacroNgENB_ID->numbits, 24), pvalue->u.longMacroNgENB_ID->data, ".", buffer, bufSize) < 0)
         {
            return -1;
         }
         break;
      }
      /* extElem1 */
      case 4:
      {
         rtxStrJoin (namebuf2, 512, name, ".u.extElem1", 0, 0, 0);
         if(rtPrintToStringOpenType (namebuf2, pvalue->u.extElem1->numocts, pvalue->u.extElem1->data, ".", buffer, bufSize) < 0)
         {
            return -1;
         }
         break;
      }
      default:;
   }
   }
   return 0;
}

int asn1PrtToStr_GlobalNgENB_ID (const char* name, 
   ASN1T_GlobalNgENB_ID* pvalue, char* buffer, OSSIZE bufSize)
{
   char namebuf[512];

   rtxStrJoin (namebuf, 512, name, ".pLMNIdentity", 0, 0, 0);
   if (asn1PrtToStr_PLMNIdentity (namebuf, &pvalue->pLMNIdentity, buffer, bufSize) < 0)
   {
      return -1;
   }

   rtxStrJoin (namebuf, 512, name, ".ngENB_ID", 0, 0, 0);
   if (asn1PrtToStr_NgENB_ID (namebuf, &pvalue->ngENB_ID, buffer, bufSize) < 0)
   {
      return -1;
   }

   rtxStrJoin (namebuf, 512, name, ".extElem1", 0, 0, 0);
   if (rtPrintToStringOpenTypeExt (namebuf, &pvalue->extElem1, buffer, bufSize)  < 0)
   {
      return -1;
   }

   return 0;
}

int asn1PrtToStr_GlobalNGRANNodeID (const char* name, 
   ASN1T_GlobalNGRANNodeID* pvalue, char* buffer, OSSIZE bufSize)
{
   {
   char namebuf2[512], numbuf[32];

   rtxIntToCharStr (pvalue->t, numbuf, sizeof(numbuf), 0);
   rtxStrJoin (namebuf2, sizeof(namebuf2), name, ".t = ", numbuf, "\n", 0);
   if (rtPrintToString (namebuf2, buffer, bufSize) < 0)
   {
      return -1;
   }

   switch (pvalue->t) {
      /* gNB */
      case 1:
      {
         rtxStrJoin (namebuf2, 512, name, ".u.gNB", 0, 0, 0);
         if (asn1PrtToStr_GlobalGNB_ID (namebuf2, pvalue->u.gNB, buffer, bufSize) < 0)
         {
            return -1;
         }
         break;
      }
      /* ng-eNB */
      case 2:
      {
         rtxStrJoin (namebuf2, 512, name, ".u.ng_eNB", 0, 0, 0);
         if (asn1PrtToStr_GlobalNgENB_ID (namebuf2, pvalue->u.ng_eNB, buffer, bufSize) < 0)
         {
            return -1;
         }
         break;
      }
      /* extElem1 */
      case 3:
      {
         rtxStrJoin (namebuf2, 512, name, ".u.extElem1", 0, 0, 0);
         if(rtPrintToStringOpenType (namebuf2, pvalue->u.extElem1->numocts, pvalue->u.extElem1->data, ".", buffer, bufSize) < 0)
         {
            return -1;
         }
         break;
      }
      default:;
   }
   }
   return 0;
}

int asn1PrtToStr_UEID_GNB (const char* name, ASN1T_UEID_GNB* pvalue, 
   char* buffer, OSSIZE bufSize)
{
   char namebuf[512];

   { char numbuf[32];
   rtxIntToCharStr ((int)pvalue->m.gNB_CU_UE_F1AP_ID_ListPresent, numbuf, 32, 0);
   rtxStrJoin (namebuf, 512, name, ".m.gNB_CU_UE_F1AP_ID_ListPresent = ", numbuf, "\n", 0);
   if (rtPrintToString (namebuf, buffer, bufSize) < 0) {
      return -1;
   }}
   { char numbuf[32];
   rtxIntToCharStr ((int)pvalue->m.gNB_CU_CP_UE_E1AP_ID_ListPresent, numbuf, 32, 0);
   rtxStrJoin (namebuf, 512, name, ".m.gNB_CU_CP_UE_E1AP_ID_ListPresent = ", numbuf, "\n", 0);
   if (rtPrintToString (namebuf, buffer, bufSize) < 0) {
      return -1;
   }}
   { char numbuf[32];
   rtxIntToCharStr ((int)pvalue->m.ran_UEIDPresent, numbuf, 32, 0);
   rtxStrJoin (namebuf, 512, name, ".m.ran_UEIDPresent = ", numbuf, "\n", 0);
   if (rtPrintToString (namebuf, buffer, bufSize) < 0) {
      return -1;
   }}
   { char numbuf[32];
   rtxIntToCharStr ((int)pvalue->m.m_NG_RAN_UE_XnAP_IDPresent, numbuf, 32, 0);
   rtxStrJoin (namebuf, 512, name, ".m.m_NG_RAN_UE_XnAP_IDPresent = ", numbuf, "\n", 0);
   if (rtPrintToString (namebuf, buffer, bufSize) < 0) {
      return -1;
   }}
   { char numbuf[32];
   rtxIntToCharStr ((int)pvalue->m.globalGNB_IDPresent, numbuf, 32, 0);
   rtxStrJoin (namebuf, 512, name, ".m.globalGNB_IDPresent = ", numbuf, "\n", 0);
   if (rtPrintToString (namebuf, buffer, bufSize) < 0) {
      return -1;
   }}
   { char numbuf[32];
   rtxIntToCharStr ((int)pvalue->m.globalNG_RANNode_IDPresent, numbuf, 32, 0);
   rtxStrJoin (namebuf, 512, name, ".m.globalNG_RANNode_IDPresent = ", numbuf, "\n", 0);
   if (rtPrintToString (namebuf, buffer, bufSize) < 0) {
      return -1;
   }}
   rtxStrJoin (namebuf, 512, name, ".amf_UE_NGAP_ID", 0, 0, 0);
   if (asn1PrtToStr_AMF_UE_NGAP_ID (namebuf, &pvalue->amf_UE_NGAP_ID, buffer, bufSize) < 0)
   {
      return -1;
   }

   rtxStrJoin (namebuf, 512, name, ".guami", 0, 0, 0);
   if (asn1PrtToStr_GUAMI (namebuf, &pvalue->guami, buffer, bufSize) < 0)
   {
      return -1;
   }

   if (pvalue->m.gNB_CU_UE_F1AP_ID_ListPresent) {
      rtxStrJoin (namebuf, 512, name, ".gNB_CU_UE_F1AP_ID_List", 0, 0, 0);
      if (asn1PrtToStr_UEID_GNB_CU_F1AP_ID_List (namebuf, &pvalue->gNB_CU_UE_F1AP_ID_List, buffer, bufSize) < 0)
      {
         return -1;
      }
   }

   if (pvalue->m.gNB_CU_CP_UE_E1AP_ID_ListPresent) {
      rtxStrJoin (namebuf, 512, name, ".gNB_CU_CP_UE_E1AP_ID_List", 0, 0, 0);
      if (asn1PrtToStr_UEID_GNB_CU_CP_E1AP_ID_List (namebuf, &pvalue->gNB_CU_CP_UE_E1AP_ID_List, buffer, bufSize) < 0)
      {
         return -1;
      }
   }

   if (pvalue->m.ran_UEIDPresent) {
      rtxStrJoin (namebuf, 512, name, ".ran_UEID", 0, 0, 0);
      if (asn1PrtToStr_RANUEID (namebuf, &pvalue->ran_UEID, buffer, bufSize) < 0)
      {
         return -1;
      }
   }

   if (pvalue->m.m_NG_RAN_UE_XnAP_IDPresent) {
      rtxStrJoin (namebuf, 512, name, ".m_NG_RAN_UE_XnAP_ID", 0, 0, 0);
      if (asn1PrtToStr_NG_RANnodeUEXnAPID (namebuf, &pvalue->m_NG_RAN_UE_XnAP_ID, buffer, bufSize) < 0)
      {
         return -1;
      }
   }

   if (pvalue->m.globalGNB_IDPresent) {
      rtxStrJoin (namebuf, 512, name, ".globalGNB_ID", 0, 0, 0);
      if (asn1PrtToStr_GlobalGNB_ID (namebuf, &pvalue->globalGNB_ID, buffer, bufSize) < 0)
      {
         return -1;
      }
   }

   if (pvalue->m.globalNG_RANNode_IDPresent) {
      rtxStrJoin (namebuf, 512, name, ".globalNG_RANNode_ID", 0, 0, 0);
      if (asn1PrtToStr_GlobalNGRANNodeID (namebuf, &pvalue->globalNG_RANNode_ID, buffer, bufSize) < 0)
      {
         return -1;
      }
   }

   rtxStrJoin (namebuf, 512, name, ".extElem1", 0, 0, 0);
   if (rtPrintToStringOpenTypeExt (namebuf, &pvalue->extElem1, buffer, bufSize)  < 0)
   {
      return -1;
   }

   return 0;
}

int asn1PrtToStr_UEID_GNB_DU (const char* name, ASN1T_UEID_GNB_DU* pvalue, 
   char* buffer, OSSIZE bufSize)
{
   char namebuf[512];

   { char numbuf[32];
   rtxIntToCharStr ((int)pvalue->m.ran_UEIDPresent, numbuf, 32, 0);
   rtxStrJoin (namebuf, 512, name, ".m.ran_UEIDPresent = ", numbuf, "\n", 0);
   if (rtPrintToString (namebuf, buffer, bufSize) < 0) {
      return -1;
   }}
   rtxStrJoin (namebuf, 512, name, ".gNB_CU_UE_F1AP_ID", 0, 0, 0);
   if (asn1PrtToStr_GNB_CU_UE_F1AP_ID (namebuf, &pvalue->gNB_CU_UE_F1AP_ID, buffer, bufSize) < 0)
   {
      return -1;
   }

   if (pvalue->m.ran_UEIDPresent) {
      rtxStrJoin (namebuf, 512, name, ".ran_UEID", 0, 0, 0);
      if (asn1PrtToStr_RANUEID (namebuf, &pvalue->ran_UEID, buffer, bufSize) < 0)
      {
         return -1;
      }
   }

   rtxStrJoin (namebuf, 512, name, ".extElem1", 0, 0, 0);
   if (rtPrintToStringOpenTypeExt (namebuf, &pvalue->extElem1, buffer, bufSize)  < 0)
   {
      return -1;
   }

   return 0;
}

int asn1PrtToStr_UEID_GNB_CU_UP (const char* name, 
   ASN1T_UEID_GNB_CU_UP* pvalue, char* buffer, OSSIZE bufSize)
{
   char namebuf[512];

   { char numbuf[32];
   rtxIntToCharStr ((int)pvalue->m.ran_UEIDPresent, numbuf, 32, 0);
   rtxStrJoin (namebuf, 512, name, ".m.ran_UEIDPresent = ", numbuf, "\n", 0);
   if (rtPrintToString (namebuf, buffer, bufSize) < 0) {
      return -1;
   }}
   rtxStrJoin (namebuf, 512, name, ".gNB_CU_CP_UE_E1AP_ID", 0, 0, 0);
   if (asn1PrtToStr_GNB_CU_CP_UE_E1AP_ID (namebuf, &pvalue->gNB_CU_CP_UE_E1AP_ID, buffer, bufSize) < 0)
   {
      return -1;
   }

   if (pvalue->m.ran_UEIDPresent) {
      rtxStrJoin (namebuf, 512, name, ".ran_UEID", 0, 0, 0);
      if (asn1PrtToStr_RANUEID (namebuf, &pvalue->ran_UEID, buffer, bufSize) < 0)
      {
         return -1;
      }
   }

   rtxStrJoin (namebuf, 512, name, ".extElem1", 0, 0, 0);
   if (rtPrintToStringOpenTypeExt (namebuf, &pvalue->extElem1, buffer, bufSize)  < 0)
   {
      return -1;
   }

   return 0;
}

int asn1PrtToStr_NGENB_CU_UE_W1AP_ID (const char* name, 
   ASN1T_NGENB_CU_UE_W1AP_ID* pvalue, char* buffer, OSSIZE bufSize)
{
   if (rtPrintToStringUnsigned (name, *pvalue, buffer, bufSize) < 0)
   {
      return -1;
   }
   return 0;
}

int asn1PrtToStr_UEID_NG_ENB (const char* name, ASN1T_UEID_NG_ENB* pvalue, 
   char* buffer, OSSIZE bufSize)
{
   char namebuf[512];

   { char numbuf[32];
   rtxIntToCharStr ((int)pvalue->m.ng_eNB_CU_UE_W1AP_IDPresent, numbuf, 32, 0);
   rtxStrJoin (namebuf, 512, name, ".m.ng_eNB_CU_UE_W1AP_IDPresent = ", numbuf, "\n", 0);
   if (rtPrintToString (namebuf, buffer, bufSize) < 0) {
      return -1;
   }}
   { char numbuf[32];
   rtxIntToCharStr ((int)pvalue->m.m_NG_RAN_UE_XnAP_IDPresent, numbuf, 32, 0);
   rtxStrJoin (namebuf, 512, name, ".m.m_NG_RAN_UE_XnAP_IDPresent = ", numbuf, "\n", 0);
   if (rtPrintToString (namebuf, buffer, bufSize) < 0) {
      return -1;
   }}
   { char numbuf[32];
   rtxIntToCharStr ((int)pvalue->m.globalNgENB_IDPresent, numbuf, 32, 0);
   rtxStrJoin (namebuf, 512, name, ".m.globalNgENB_IDPresent = ", numbuf, "\n", 0);
   if (rtPrintToString (namebuf, buffer, bufSize) < 0) {
      return -1;
   }}
   { char numbuf[32];
   rtxIntToCharStr ((int)pvalue->m.globalNG_RANNode_IDPresent, numbuf, 32, 0);
   rtxStrJoin (namebuf, 512, name, ".m.globalNG_RANNode_IDPresent = ", numbuf, "\n", 0);
   if (rtPrintToString (namebuf, buffer, bufSize) < 0) {
      return -1;
   }}
   rtxStrJoin (namebuf, 512, name, ".amf_UE_NGAP_ID", 0, 0, 0);
   if (asn1PrtToStr_AMF_UE_NGAP_ID (namebuf, &pvalue->amf_UE_NGAP_ID, buffer, bufSize) < 0)
   {
      return -1;
   }

   rtxStrJoin (namebuf, 512, name, ".guami", 0, 0, 0);
   if (asn1PrtToStr_GUAMI (namebuf, &pvalue->guami, buffer, bufSize) < 0)
   {
      return -1;
   }

   if (pvalue->m.ng_eNB_CU_UE_W1AP_IDPresent) {
      rtxStrJoin (namebuf, 512, name, ".ng_eNB_CU_UE_W1AP_ID", 0, 0, 0);
      if (asn1PrtToStr_NGENB_CU_UE_W1AP_ID (namebuf, &pvalue->ng_eNB_CU_UE_W1AP_ID, buffer, bufSize) < 0)
      {
         return -1;
      }
   }

   if (pvalue->m.m_NG_RAN_UE_XnAP_IDPresent) {
      rtxStrJoin (namebuf, 512, name, ".m_NG_RAN_UE_XnAP_ID", 0, 0, 0);
      if (asn1PrtToStr_NG_RANnodeUEXnAPID (namebuf, &pvalue->m_NG_RAN_UE_XnAP_ID, buffer, bufSize) < 0)
      {
         return -1;
      }
   }

   if (pvalue->m.globalNgENB_IDPresent) {
      rtxStrJoin (namebuf, 512, name, ".globalNgENB_ID", 0, 0, 0);
      if (asn1PrtToStr_GlobalNgENB_ID (namebuf, &pvalue->globalNgENB_ID, buffer, bufSize) < 0)
      {
         return -1;
      }
   }

   if (pvalue->m.globalNG_RANNode_IDPresent) {
      rtxStrJoin (namebuf, 512, name, ".globalNG_RANNode_ID", 0, 0, 0);
      if (asn1PrtToStr_GlobalNGRANNodeID (namebuf, &pvalue->globalNG_RANNode_ID, buffer, bufSize) < 0)
      {
         return -1;
      }
   }

   rtxStrJoin (namebuf, 512, name, ".extElem1", 0, 0, 0);
   if (rtPrintToStringOpenTypeExt (namebuf, &pvalue->extElem1, buffer, bufSize)  < 0)
   {
      return -1;
   }

   return 0;
}

int asn1PrtToStr_UEID_NG_ENB_DU (const char* name, 
   ASN1T_UEID_NG_ENB_DU* pvalue, char* buffer, OSSIZE bufSize)
{
   char namebuf[512];

   rtxStrJoin (namebuf, 512, name, ".ng_eNB_CU_UE_W1AP_ID", 0, 0, 0);
   if (asn1PrtToStr_NGENB_CU_UE_W1AP_ID (namebuf, &pvalue->ng_eNB_CU_UE_W1AP_ID, buffer, bufSize) < 0)
   {
      return -1;
   }

   rtxStrJoin (namebuf, 512, name, ".extElem1", 0, 0, 0);
   if (rtPrintToStringOpenTypeExt (namebuf, &pvalue->extElem1, buffer, bufSize)  < 0)
   {
      return -1;
   }

   return 0;
}

int asn1PrtToStr_ENB_UE_X2AP_ID (const char* name, 
   ASN1T_ENB_UE_X2AP_ID* pvalue, char* buffer, OSSIZE bufSize)
{
   if (rtPrintToStringUnsigned (name, *pvalue, buffer, bufSize) < 0)
   {
      return -1;
   }
   return 0;
}

int asn1PrtToStr_ENB_UE_X2AP_ID_Extension (const char* name, 
   ASN1T_ENB_UE_X2AP_ID_Extension* pvalue, char* buffer, OSSIZE bufSize)
{
   if (rtPrintToStringUnsigned (name, *pvalue, buffer, bufSize) < 0)
   {
      return -1;
   }
   return 0;
}

int asn1PrtToStr_ENB_ID (const char* name, ASN1T_ENB_ID* pvalue, char* buffer, 
   OSSIZE bufSize)
{
   {
   char namebuf2[512], numbuf[32];

   rtxIntToCharStr (pvalue->t, numbuf, sizeof(numbuf), 0);
   rtxStrJoin (namebuf2, sizeof(namebuf2), name, ".t = ", numbuf, "\n", 0);
   if (rtPrintToString (namebuf2, buffer, bufSize) < 0)
   {
      return -1;
   }

   switch (pvalue->t) {
      /* macro-eNB-ID */
      case 1:
      {
         rtxStrJoin (namebuf2, 512, name, ".u.macro_eNB_ID", 0, 0, 0);
         if (rtPrintToStringBitStr (namebuf2, OS_MIN(pvalue->u.macro_eNB_ID->numbits, 24), pvalue->u.macro_eNB_ID->data, ".", buffer, bufSize) < 0)
         {
            return -1;
         }
         break;
      }
      /* home-eNB-ID */
      case 2:
      {
         rtxStrJoin (namebuf2, 512, name, ".u.home_eNB_ID", 0, 0, 0);
         if (rtPrintToStringBitStr (namebuf2, OS_MIN(pvalue->u.home_eNB_ID->numbits, 32), pvalue->u.home_eNB_ID->data, ".", buffer, bufSize) < 0)
         {
            return -1;
         }
         break;
      }
      /* short-Macro-eNB-ID */
      case 3:
      {
         rtxStrJoin (namebuf2, 512, name, ".u.short_Macro_eNB_ID", 0, 0, 0);
         if (rtPrintToStringBitStr (namebuf2, OS_MIN(pvalue->u.short_Macro_eNB_ID->numbits, 24), pvalue->u.short_Macro_eNB_ID->data, ".", buffer, bufSize) < 0)
         {
            return -1;
         }
         break;
      }
      /* long-Macro-eNB-ID */
      case 4:
      {
         rtxStrJoin (namebuf2, 512, name, ".u.long_Macro_eNB_ID", 0, 0, 0);
         if (rtPrintToStringBitStr (namebuf2, OS_MIN(pvalue->u.long_Macro_eNB_ID->numbits, 24), pvalue->u.long_Macro_eNB_ID->data, ".", buffer, bufSize) < 0)
         {
            return -1;
         }
         break;
      }
      /* extElem1 */
      case 5:
      {
         rtxStrJoin (namebuf2, 512, name, ".u.extElem1", 0, 0, 0);
         if(rtPrintToStringOpenType (namebuf2, pvalue->u.extElem1->numocts, pvalue->u.extElem1->data, ".", buffer, bufSize) < 0)
         {
            return -1;
         }
         break;
      }
      default:;
   }
   }
   return 0;
}

int asn1PrtToStr_GlobalENB_ID (const char* name, ASN1T_GlobalENB_ID* pvalue, 
   char* buffer, OSSIZE bufSize)
{
   char namebuf[512];

   rtxStrJoin (namebuf, 512, name, ".pLMNIdentity", 0, 0, 0);
   if (asn1PrtToStr_PLMNIdentity (namebuf, &pvalue->pLMNIdentity, buffer, bufSize) < 0)
   {
      return -1;
   }

   rtxStrJoin (namebuf, 512, name, ".eNB_ID", 0, 0, 0);
   if (asn1PrtToStr_ENB_ID (namebuf, &pvalue->eNB_ID, buffer, bufSize) < 0)
   {
      return -1;
   }

   rtxStrJoin (namebuf, 512, name, ".extElem1", 0, 0, 0);
   if (rtPrintToStringOpenTypeExt (namebuf, &pvalue->extElem1, buffer, bufSize)  < 0)
   {
      return -1;
   }

   return 0;
}

int asn1PrtToStr_UEID_EN_GNB (const char* name, ASN1T_UEID_EN_GNB* pvalue, 
   char* buffer, OSSIZE bufSize)
{
   char namebuf[512];

   { char numbuf[32];
   rtxIntToCharStr ((int)pvalue->m.m_eNB_UE_X2AP_ID_ExtensionPresent, numbuf, 32, 0);
   rtxStrJoin (namebuf, 512, name, ".m.m_eNB_UE_X2AP_ID_ExtensionPresent = ", numbuf, "\n", 0);
   if (rtPrintToString (namebuf, buffer, bufSize) < 0) {
      return -1;
   }}
   { char numbuf[32];
   rtxIntToCharStr ((int)pvalue->m.gNB_CU_UE_F1AP_IDPresent, numbuf, 32, 0);
   rtxStrJoin (namebuf, 512, name, ".m.gNB_CU_UE_F1AP_IDPresent = ", numbuf, "\n", 0);
   if (rtPrintToString (namebuf, buffer, bufSize) < 0) {
      return -1;
   }}
   { char numbuf[32];
   rtxIntToCharStr ((int)pvalue->m.gNB_CU_CP_UE_E1AP_ID_ListPresent, numbuf, 32, 0);
   rtxStrJoin (namebuf, 512, name, ".m.gNB_CU_CP_UE_E1AP_ID_ListPresent = ", numbuf, "\n", 0);
   if (rtPrintToString (namebuf, buffer, bufSize) < 0) {
      return -1;
   }}
   { char numbuf[32];
   rtxIntToCharStr ((int)pvalue->m.ran_UEIDPresent, numbuf, 32, 0);
   rtxStrJoin (namebuf, 512, name, ".m.ran_UEIDPresent = ", numbuf, "\n", 0);
   if (rtPrintToString (namebuf, buffer, bufSize) < 0) {
      return -1;
   }}
   rtxStrJoin (namebuf, 512, name, ".m_eNB_UE_X2AP_ID", 0, 0, 0);
   if (asn1PrtToStr_ENB_UE_X2AP_ID (namebuf, &pvalue->m_eNB_UE_X2AP_ID, buffer, bufSize) < 0)
   {
      return -1;
   }

   if (pvalue->m.m_eNB_UE_X2AP_ID_ExtensionPresent) {
      rtxStrJoin (namebuf, 512, name, ".m_eNB_UE_X2AP_ID_Extension", 0, 0, 0);
      if (asn1PrtToStr_ENB_UE_X2AP_ID_Extension (namebuf, &pvalue->m_eNB_UE_X2AP_ID_Extension, buffer, bufSize) < 0)
      {
         return -1;
      }
   }

   rtxStrJoin (namebuf, 512, name, ".globalENB_ID", 0, 0, 0);
   if (asn1PrtToStr_GlobalENB_ID (namebuf, &pvalue->globalENB_ID, buffer, bufSize) < 0)
   {
      return -1;
   }

   if (pvalue->m.gNB_CU_UE_F1AP_IDPresent) {
      rtxStrJoin (namebuf, 512, name, ".gNB_CU_UE_F1AP_ID", 0, 0, 0);
      if (asn1PrtToStr_GNB_CU_UE_F1AP_ID (namebuf, &pvalue->gNB_CU_UE_F1AP_ID, buffer, bufSize) < 0)
      {
         return -1;
      }
   }

   if (pvalue->m.gNB_CU_CP_UE_E1AP_ID_ListPresent) {
      rtxStrJoin (namebuf, 512, name, ".gNB_CU_CP_UE_E1AP_ID_List", 0, 0, 0);
      if (asn1PrtToStr_UEID_GNB_CU_CP_E1AP_ID_List (namebuf, &pvalue->gNB_CU_CP_UE_E1AP_ID_List, buffer, bufSize) < 0)
      {
         return -1;
      }
   }

   if (pvalue->m.ran_UEIDPresent) {
      rtxStrJoin (namebuf, 512, name, ".ran_UEID", 0, 0, 0);
      if (asn1PrtToStr_RANUEID (namebuf, &pvalue->ran_UEID, buffer, bufSize) < 0)
      {
         return -1;
      }
   }

   rtxStrJoin (namebuf, 512, name, ".extElem1", 0, 0, 0);
   if (rtPrintToStringOpenTypeExt (namebuf, &pvalue->extElem1, buffer, bufSize)  < 0)
   {
      return -1;
   }

   return 0;
}

int asn1PrtToStr_MME_UE_S1AP_ID (const char* name, 
   ASN1T_MME_UE_S1AP_ID* pvalue, char* buffer, OSSIZE bufSize)
{
   if (rtPrintToStringUnsigned (name, *pvalue, buffer, bufSize) < 0)
   {
      return -1;
   }
   return 0;
}

int asn1PrtToStr_MME_Group_ID (const char* name, ASN1T_MME_Group_ID* pvalue, 
   char* buffer, OSSIZE bufSize)
{
   if (rtPrintToStringOctStr (name, OSRTMIN(sizeof(pvalue->data), pvalue->numocts), pvalue->data, ".", buffer, bufSize) < 0)
   {
      return -1;
   }
   return 0;
}

int asn1PrtToStr_MME_Code (const char* name, ASN1T_MME_Code* pvalue, 
   char* buffer, OSSIZE bufSize)
{
   if (rtPrintToStringOctStr (name, OSRTMIN(sizeof(pvalue->data), pvalue->numocts), pvalue->data, ".", buffer, bufSize) < 0)
   {
      return -1;
   }
   return 0;
}

int asn1PrtToStr_GUMMEI (const char* name, ASN1T_GUMMEI* pvalue, char* buffer, 
   OSSIZE bufSize)
{
   char namebuf[512];

   rtxStrJoin (namebuf, 512, name, ".pLMN_Identity", 0, 0, 0);
   if (asn1PrtToStr_PLMNIdentity (namebuf, &pvalue->pLMN_Identity, buffer, bufSize) < 0)
   {
      return -1;
   }

   rtxStrJoin (namebuf, 512, name, ".mME_Group_ID", 0, 0, 0);
   if (asn1PrtToStr_MME_Group_ID (namebuf, &pvalue->mME_Group_ID, buffer, bufSize) < 0)
   {
      return -1;
   }

   rtxStrJoin (namebuf, 512, name, ".mME_Code", 0, 0, 0);
   if (asn1PrtToStr_MME_Code (namebuf, &pvalue->mME_Code, buffer, bufSize) < 0)
   {
      return -1;
   }

   rtxStrJoin (namebuf, 512, name, ".extElem1", 0, 0, 0);
   if (rtPrintToStringOpenTypeExt (namebuf, &pvalue->extElem1, buffer, bufSize)  < 0)
   {
      return -1;
   }

   return 0;
}

int asn1PrtToStr_UEID_ENB (const char* name, ASN1T_UEID_ENB* pvalue, 
   char* buffer, OSSIZE bufSize)
{
   char namebuf[512];

   { char numbuf[32];
   rtxIntToCharStr ((int)pvalue->m.m_eNB_UE_X2AP_IDPresent, numbuf, 32, 0);
   rtxStrJoin (namebuf, 512, name, ".m.m_eNB_UE_X2AP_IDPresent = ", numbuf, "\n", 0);
   if (rtPrintToString (namebuf, buffer, bufSize) < 0) {
      return -1;
   }}
   { char numbuf[32];
   rtxIntToCharStr ((int)pvalue->m.m_eNB_UE_X2AP_ID_ExtensionPresent, numbuf, 32, 0);
   rtxStrJoin (namebuf, 512, name, ".m.m_eNB_UE_X2AP_ID_ExtensionPresent = ", numbuf, "\n", 0);
   if (rtPrintToString (namebuf, buffer, bufSize) < 0) {
      return -1;
   }}
   { char numbuf[32];
   rtxIntToCharStr ((int)pvalue->m.globalENB_IDPresent, numbuf, 32, 0);
   rtxStrJoin (namebuf, 512, name, ".m.globalENB_IDPresent = ", numbuf, "\n", 0);
   if (rtPrintToString (namebuf, buffer, bufSize) < 0) {
      return -1;
   }}
   rtxStrJoin (namebuf, 512, name, ".mME_UE_S1AP_ID", 0, 0, 0);
   if (asn1PrtToStr_MME_UE_S1AP_ID (namebuf, &pvalue->mME_UE_S1AP_ID, buffer, bufSize) < 0)
   {
      return -1;
   }

   rtxStrJoin (namebuf, 512, name, ".gUMMEI", 0, 0, 0);
   if (asn1PrtToStr_GUMMEI (namebuf, &pvalue->gUMMEI, buffer, bufSize) < 0)
   {
      return -1;
   }

   if (pvalue->m.m_eNB_UE_X2AP_IDPresent) {
      rtxStrJoin (namebuf, 512, name, ".m_eNB_UE_X2AP_ID", 0, 0, 0);
      if (asn1PrtToStr_ENB_UE_X2AP_ID (namebuf, &pvalue->m_eNB_UE_X2AP_ID, buffer, bufSize) < 0)
      {
         return -1;
      }
   }

   if (pvalue->m.m_eNB_UE_X2AP_ID_ExtensionPresent) {
      rtxStrJoin (namebuf, 512, name, ".m_eNB_UE_X2AP_ID_Extension", 0, 0, 0);
      if (asn1PrtToStr_ENB_UE_X2AP_ID_Extension (namebuf, &pvalue->m_eNB_UE_X2AP_ID_Extension, buffer, bufSize) < 0)
      {
         return -1;
      }
   }

   if (pvalue->m.globalENB_IDPresent) {
      rtxStrJoin (namebuf, 512, name, ".globalENB_ID", 0, 0, 0);
      if (asn1PrtToStr_GlobalENB_ID (namebuf, &pvalue->globalENB_ID, buffer, bufSize) < 0)
      {
         return -1;
      }
   }

   rtxStrJoin (namebuf, 512, name, ".extElem1", 0, 0, 0);
   if (rtPrintToStringOpenTypeExt (namebuf, &pvalue->extElem1, buffer, bufSize)  < 0)
   {
      return -1;
   }

   return 0;
}

int asn1PrtToStr_UEID (const char* name, ASN1T_UEID* pvalue, char* buffer, 
   OSSIZE bufSize)
{
   {
   char namebuf2[512], numbuf[32];

   rtxIntToCharStr (pvalue->t, numbuf, sizeof(numbuf), 0);
   rtxStrJoin (namebuf2, sizeof(namebuf2), name, ".t = ", numbuf, "\n", 0);
   if (rtPrintToString (namebuf2, buffer, bufSize) < 0)
   {
      return -1;
   }

   switch (pvalue->t) {
      /* gNB-UEID */
      case 1:
      {
         rtxStrJoin (namebuf2, 512, name, ".u.gNB_UEID", 0, 0, 0);
         if (asn1PrtToStr_UEID_GNB (namebuf2, pvalue->u.gNB_UEID, buffer, bufSize) < 0)
         {
            return -1;
         }
         break;
      }
      /* gNB-DU-UEID */
      case 2:
      {
         rtxStrJoin (namebuf2, 512, name, ".u.gNB_DU_UEID", 0, 0, 0);
         if (asn1PrtToStr_UEID_GNB_DU (namebuf2, pvalue->u.gNB_DU_UEID, buffer, bufSize) < 0)
         {
            return -1;
         }
         break;
      }
      /* gNB-CU-UP-UEID */
      case 3:
      {
         rtxStrJoin (namebuf2, 512, name, ".u.gNB_CU_UP_UEID", 0, 0, 0);
         if (asn1PrtToStr_UEID_GNB_CU_UP (namebuf2, pvalue->u.gNB_CU_UP_UEID, buffer, bufSize) < 0)
         {
            return -1;
         }
         break;
      }
      /* ng-eNB-UEID */
      case 4:
      {
         rtxStrJoin (namebuf2, 512, name, ".u.ng_eNB_UEID", 0, 0, 0);
         if (asn1PrtToStr_UEID_NG_ENB (namebuf2, pvalue->u.ng_eNB_UEID, buffer, bufSize) < 0)
         {
            return -1;
         }
         break;
      }
      /* ng-eNB-DU-UEID */
      case 5:
      {
         rtxStrJoin (namebuf2, 512, name, ".u.ng_eNB_DU_UEID", 0, 0, 0);
         if (asn1PrtToStr_UEID_NG_ENB_DU (namebuf2, pvalue->u.ng_eNB_DU_UEID, buffer, bufSize) < 0)
         {
            return -1;
         }
         break;
      }
      /* en-gNB-UEID */
      case 6:
      {
         rtxStrJoin (namebuf2, 512, name, ".u.en_gNB_UEID", 0, 0, 0);
         if (asn1PrtToStr_UEID_EN_GNB (namebuf2, pvalue->u.en_gNB_UEID, buffer, bufSize) < 0)
         {
            return -1;
         }
         break;
      }
      /* eNB-UEID */
      case 7:
      {
         rtxStrJoin (namebuf2, 512, name, ".u.eNB_UEID", 0, 0, 0);
         if (asn1PrtToStr_UEID_ENB (namebuf2, pvalue->u.eNB_UEID, buffer, bufSize) < 0)
         {
            return -1;
         }
         break;
      }
      /* extElem1 */
      case 8:
      {
         rtxStrJoin (namebuf2, 512, name, ".u.extElem1", 0, 0, 0);
         if(rtPrintToStringOpenType (namebuf2, pvalue->u.extElem1->numocts, pvalue->u.extElem1->data, ".", buffer, bufSize) < 0)
         {
            return -1;
         }
         break;
      }
      default:;
   }
   }
   return 0;
}

int asn1PrtToStr_RIC_Style_Type (const char* name, 
   ASN1T_RIC_Style_Type* pvalue, char* buffer, OSSIZE bufSize)
{
   if (rtPrintToStringInteger (name, *pvalue, buffer, bufSize) < 0)
   {
      return -1;
   }
   return 0;
}

int asn1PrtToStr_RANfunction_Name (const char* name, 
   ASN1T_RANfunction_Name* pvalue, char* buffer, OSSIZE bufSize)
{
   char namebuf[512];

   { char numbuf[32];
   rtxIntToCharStr ((int)pvalue->m.ranFunction_InstancePresent, numbuf, 32, 0);
   rtxStrJoin (namebuf, 512, name, ".m.ranFunction_InstancePresent = ", numbuf, "\n", 0);
   if (rtPrintToString (namebuf, buffer, bufSize) < 0) {
      return -1;
   }}
   rtxStrJoin (namebuf, 512, name, ".ranFunction_ShortName", 0, 0, 0);
   if(rtPrintToStringCharStr (namebuf, pvalue->ranFunction_ShortName, buffer, bufSize) < 0)
   {
      return -1;
   }

   rtxStrJoin (namebuf, 512, name, ".ranFunction_E2SM_OID", 0, 0, 0);
   if(rtPrintToStringCharStr (namebuf, pvalue->ranFunction_E2SM_OID, buffer, bufSize) < 0)
   {
      return -1;
   }

   rtxStrJoin (namebuf, 512, name, ".ranFunction_Description", 0, 0, 0);
   if(rtPrintToStringCharStr (namebuf, pvalue->ranFunction_Description, buffer, bufSize) < 0)
   {
      return -1;
   }

   if (pvalue->m.ranFunction_InstancePresent) {
      rtxStrJoin (namebuf, 512, name, ".ranFunction_Instance", 0, 0, 0);
      if (rtPrintToStringInteger (namebuf, pvalue->ranFunction_Instance, buffer, bufSize) < 0)
      {
         return -1;
      }
   }

   rtxStrJoin (namebuf, 512, name, ".extElem1", 0, 0, 0);
   if (rtPrintToStringOpenTypeExt (namebuf, &pvalue->extElem1, buffer, bufSize)  < 0)
   {
      return -1;
   }

   return 0;
}

int asn1PrtToStr_RIC_Style_Name (const char* name, 
   ASN1T_RIC_Style_Name pvalue, char* buffer, OSSIZE bufSize)
{
   if(rtPrintToStringCharStr (name, pvalue, buffer, bufSize) < 0)
   {
      return -1;
   }
   return 0;
}

int asn1PrtToStr_RIC_Format_Type (const char* name, 
   ASN1T_RIC_Format_Type* pvalue, char* buffer, OSSIZE bufSize)
{
   if (rtPrintToStringInteger (name, *pvalue, buffer, bufSize) < 0)
   {
      return -1;
   }
   return 0;
}

int asn1PrtToStr_InterfaceType (const char* name, ASN1T_InterfaceType* pvalue, 
   char* buffer, OSSIZE bufSize)
{
   int stat;
   if(rtPrintToString (name, buffer, bufSize) < 0)
   {
      return -1;
   }
   switch (*pvalue) {
      case 0:
         stat = rtPrintToString (" = nG\n", buffer, bufSize);
         break;

      case 1:
         stat = rtPrintToString (" = xn\n", buffer, bufSize);
         break;

      case 2:
         stat = rtPrintToString (" = f1\n", buffer, bufSize);
         break;

      case 3:
         stat = rtPrintToString (" = e1\n", buffer, bufSize);
         break;

      case 4:
         stat = rtPrintToString (" = s1\n", buffer, bufSize);
         break;

      case 5:
         stat = rtPrintToString (" = x2\n", buffer, bufSize);
         break;

      case 6:
         stat = rtPrintToString (" = w1\n", buffer, bufSize);
         break;

      default: stat = rtPrintToStringUnsigned ("", *pvalue, buffer, bufSize);
   }

   if(stat < 0) return -1;
   return 0;
}

int asn1PrtToStr_RRCclass_LTE (const char* name, ASN1T_RRCclass_LTE* pvalue, 
   char* buffer, OSSIZE bufSize)
{
   int stat;
   if(rtPrintToString (name, buffer, bufSize) < 0)
   {
      return -1;
   }
   switch (*pvalue) {
      case 0:
         stat = rtPrintToString (" = bCCH-BCH\n", buffer, bufSize);
         break;

      case 1:
         stat = rtPrintToString (" = bCCH-BCH-MBMS\n", buffer, bufSize);
         break;

      case 2:
         stat = rtPrintToString (" = bCCH-DL-SCH\n", buffer, bufSize);
         break;

      case 3:
         stat = rtPrintToString (" = bCCH-DL-SCH-BR\n", buffer, bufSize);
         break;

      case 4:
         stat = rtPrintToString (" = bCCH-DL-SCH-MBMS\n", buffer, bufSize);
         break;

      case 5:
         stat = rtPrintToString (" = mCCH\n", buffer, bufSize);
         break;

      case 6:
         stat = rtPrintToString (" = pCCH\n", buffer, bufSize);
         break;

      case 7:
         stat = rtPrintToString (" = dL-CCCH\n", buffer, bufSize);
         break;

      case 8:
         stat = rtPrintToString (" = dL-DCCH\n", buffer, bufSize);
         break;

      case 9:
         stat = rtPrintToString (" = uL-CCCH\n", buffer, bufSize);
         break;

      case 10:
         stat = rtPrintToString (" = uL-DCCH\n", buffer, bufSize);
         break;

      case 11:
         stat = rtPrintToString (" = sC-MCCH\n", buffer, bufSize);
         break;

      default: stat = rtPrintToStringUnsigned ("", *pvalue, buffer, bufSize);
   }

   if(stat < 0) return -1;
   return 0;
}

int asn1PrtToStr_RRCclass_NR (const char* name, ASN1T_RRCclass_NR* pvalue, 
   char* buffer, OSSIZE bufSize)
{
   int stat;
   if(rtPrintToString (name, buffer, bufSize) < 0)
   {
      return -1;
   }
   switch (*pvalue) {
      case 0:
         stat = rtPrintToString (" = bCCH-BCH\n", buffer, bufSize);
         break;

      case 1:
         stat = rtPrintToString (" = bCCH-DL-SCH\n", buffer, bufSize);
         break;

      case 2:
         stat = rtPrintToString (" = dL-CCCH\n", buffer, bufSize);
         break;

      case 3:
         stat = rtPrintToString (" = dL-DCCH\n", buffer, bufSize);
         break;

      case 4:
         stat = rtPrintToString (" = pCCH\n", buffer, bufSize);
         break;

      case 5:
         stat = rtPrintToString (" = uL-CCCH\n", buffer, bufSize);
         break;

      case 6:
         stat = rtPrintToString (" = uL-CCCH1\n", buffer, bufSize);
         break;

      case 7:
         stat = rtPrintToString (" = uL-DCCH\n", buffer, bufSize);
         break;

      default: stat = rtPrintToStringUnsigned ("", *pvalue, buffer, bufSize);
   }

   if(stat < 0) return -1;
   return 0;
}

int asn1PrtToStr_SubscriberProfileIDforRFP (const char* name, 
   ASN1T_SubscriberProfileIDforRFP* pvalue, char* buffer, OSSIZE bufSize)
{
   if (rtPrintToStringUnsigned (name, *pvalue, buffer, bufSize) < 0)
   {
      return -1;
   }
   return 0;
}

int ASN1C_SubscriberProfileIDforRFP::toString (const char* name, char* buffer, OSSIZE bufSize)
{
   if (asn1PrtToStr_SubscriberProfileIDforRFP (name, &msgData, buffer, bufSize) < 0)
   {
      return -1;
   }
   return 0;
}

int ASN1C_SubscriberProfileIDforRFP::toString (char* buffer, OSSIZE bufSize)
{
   return toString ("SubscriberProfileIDforRFP", buffer, bufSize);
}

int asn1PrtToStr_E_UTRA_ARFCN (const char* name, ASN1T_E_UTRA_ARFCN* pvalue, 
   char* buffer, OSSIZE bufSize)
{
   if (rtPrintToStringUnsigned (name, *pvalue, buffer, bufSize) < 0)
   {
      return -1;
   }
   return 0;
}

int asn1PrtToStr_E_UTRA_PCI (const char* name, ASN1T_E_UTRA_PCI* pvalue, 
   char* buffer, OSSIZE bufSize)
{
   if (rtPrintToStringUnsigned (name, *pvalue, buffer, bufSize) < 0)
   {
      return -1;
   }
   return 0;
}

int asn1PrtToStr_E_UTRA_TAC (const char* name, ASN1T_E_UTRA_TAC* pvalue, 
   char* buffer, OSSIZE bufSize)
{
   if (rtPrintToStringOctStr (name, OSRTMIN(sizeof(pvalue->data), pvalue->numocts), pvalue->data, ".", buffer, bufSize) < 0)
   {
      return -1;
   }
   return 0;
}

int asn1PrtToStr_NGENB_DU_ID (const char* name, ASN1T_NGENB_DU_ID* pvalue, 
   char* buffer, OSSIZE bufSize)
{
   if (rtPrintToStringUInt64 (name, *pvalue, buffer, bufSize) < 0)
   {
      return -1;
   }
   return 0;
}

int asn1PrtToStr_IndexToRFSP (const char* name, ASN1T_IndexToRFSP* pvalue, 
   char* buffer, OSSIZE bufSize)
{
   if (rtPrintToStringUnsigned (name, *pvalue, buffer, bufSize) < 0)
   {
      return -1;
   }
   return 0;
}

int ASN1C_IndexToRFSP::toString (const char* name, char* buffer, OSSIZE bufSize)
{
   if (asn1PrtToStr_IndexToRFSP (name, &msgData, buffer, bufSize) < 0)
   {
      return -1;
   }
   return 0;
}

int ASN1C_IndexToRFSP::toString (char* buffer, OSSIZE bufSize)
{
   return toString ("IndexToRFSP", buffer, bufSize);
}

int asn1PrtToStr_GNB_CU_UP_ID (const char* name, ASN1T_GNB_CU_UP_ID* pvalue, 
   char* buffer, OSSIZE bufSize)
{
   if (rtPrintToStringUInt64 (name, *pvalue, buffer, bufSize) < 0)
   {
      return -1;
   }
   return 0;
}

int asn1PrtToStr_FiveGS_TAC (const char* name, ASN1T_FiveGS_TAC* pvalue, 
   char* buffer, OSSIZE bufSize)
{
   if (rtPrintToStringOctStr (name, OSRTMIN(sizeof(pvalue->data), pvalue->numocts), pvalue->data, ".", buffer, bufSize) < 0)
   {
      return -1;
   }
   return 0;
}

int asn1PrtToStr_GNB_DU_ID (const char* name, ASN1T_GNB_DU_ID* pvalue, 
   char* buffer, OSSIZE bufSize)
{
   if (rtPrintToStringUInt64 (name, *pvalue, buffer, bufSize) < 0)
   {
      return -1;
   }
   return 0;
}

int asn1PrtToStr_NR_PCI (const char* name, ASN1T_NR_PCI* pvalue, char* buffer, 
   OSSIZE bufSize)
{
   if (rtPrintToStringUnsigned (name, *pvalue, buffer, bufSize) < 0)
   {
      return -1;
   }
   return 0;
}

int asn1PrtToStr_NRFrequencyShift7p5khz (const char* name, 
   ASN1T_NRFrequencyShift7p5khz* pvalue, char* buffer, OSSIZE bufSize)
{
   int stat;
   if(rtPrintToString (name, buffer, bufSize) < 0)
   {
      return -1;
   }
   switch (*pvalue) {
      case 0:
         stat = rtPrintToString (" = false\n", buffer, bufSize);
         break;

      case 1:
         stat = rtPrintToString (" = true\n", buffer, bufSize);
         break;

      default: stat = rtPrintToStringUnsigned ("", *pvalue, buffer, bufSize);
   }

   if(stat < 0) return -1;
   return 0;
}

int asn1PrtToStr_Interface_MessageID_messageType (const char* name, 
   ASN1T_Interface_MessageID_messageType* pvalue, char* buffer, OSSIZE bufSize)
{
   int stat;
   if(rtPrintToString (name, buffer, bufSize) < 0)
   {
      return -1;
   }
   switch (*pvalue) {
      case 0:
         stat = rtPrintToString (" = initiatingMessage\n", buffer, bufSize);
         break;

      case 1:
         stat = rtPrintToString (" = successfulOutcome\n", buffer, bufSize);
         break;

      case 2:
         stat = rtPrintToString (" = unsuccessfulOutcome\n", buffer, bufSize);
         break;

      default: stat = rtPrintToStringUnsigned ("", *pvalue, buffer, bufSize);
   }

   if(stat < 0) return -1;
   return 0;
}

int asn1PrtToStr_CoreCPID (const char* name, ASN1T_CoreCPID* pvalue, 
   char* buffer, OSSIZE bufSize)
{
   {
   char namebuf2[512], numbuf[32];

   rtxIntToCharStr (pvalue->t, numbuf, sizeof(numbuf), 0);
   rtxStrJoin (namebuf2, sizeof(namebuf2), name, ".t = ", numbuf, "\n", 0);
   if (rtPrintToString (namebuf2, buffer, bufSize) < 0)
   {
      return -1;
   }

   switch (pvalue->t) {
      /* fiveGC */
      case 1:
      {
         rtxStrJoin (namebuf2, 512, name, ".u.fiveGC", 0, 0, 0);
         if (asn1PrtToStr_GUAMI (namebuf2, pvalue->u.fiveGC, buffer, bufSize) < 0)
         {
            return -1;
         }
         break;
      }
      /* ePC */
      case 2:
      {
         rtxStrJoin (namebuf2, 512, name, ".u.ePC", 0, 0, 0);
         if (asn1PrtToStr_GUMMEI (namebuf2, pvalue->u.ePC, buffer, bufSize) < 0)
         {
            return -1;
         }
         break;
      }
      /* extElem1 */
      case 3:
      {
         rtxStrJoin (namebuf2, 512, name, ".u.extElem1", 0, 0, 0);
         if(rtPrintToStringOpenType (namebuf2, pvalue->u.extElem1->numocts, pvalue->u.extElem1->data, ".", buffer, bufSize) < 0)
         {
            return -1;
         }
         break;
      }
      default:;
   }
   }
   return 0;
}

int ASN1C_CoreCPID::toString (const char* name, char* buffer, OSSIZE bufSize)
{
   if (asn1PrtToStr_CoreCPID (name, &msgData, buffer, bufSize) < 0)
   {
      return -1;
   }
   return 0;
}

int ASN1C_CoreCPID::toString (char* buffer, OSSIZE bufSize)
{
   return toString ("CoreCPID", buffer, bufSize);
}

int asn1PrtToStr_InterfaceID_NG (const char* name, 
   ASN1T_InterfaceID_NG* pvalue, char* buffer, OSSIZE bufSize)
{
   char namebuf[512];

   rtxStrJoin (namebuf, 512, name, ".guami", 0, 0, 0);
   if (asn1PrtToStr_GUAMI (namebuf, &pvalue->guami, buffer, bufSize) < 0)
   {
      return -1;
   }

   rtxStrJoin (namebuf, 512, name, ".extElem1", 0, 0, 0);
   if (rtPrintToStringOpenTypeExt (namebuf, &pvalue->extElem1, buffer, bufSize)  < 0)
   {
      return -1;
   }

   return 0;
}

int asn1PrtToStr_InterfaceID_Xn (const char* name, 
   ASN1T_InterfaceID_Xn* pvalue, char* buffer, OSSIZE bufSize)
{
   char namebuf[512];

   rtxStrJoin (namebuf, 512, name, ".global_NG_RAN_ID", 0, 0, 0);
   if (asn1PrtToStr_GlobalNGRANNodeID (namebuf, &pvalue->global_NG_RAN_ID, buffer, bufSize) < 0)
   {
      return -1;
   }

   rtxStrJoin (namebuf, 512, name, ".extElem1", 0, 0, 0);
   if (rtPrintToStringOpenTypeExt (namebuf, &pvalue->extElem1, buffer, bufSize)  < 0)
   {
      return -1;
   }

   return 0;
}

int asn1PrtToStr_InterfaceID_F1 (const char* name, 
   ASN1T_InterfaceID_F1* pvalue, char* buffer, OSSIZE bufSize)
{
   char namebuf[512];

   rtxStrJoin (namebuf, 512, name, ".globalGNB_ID", 0, 0, 0);
   if (asn1PrtToStr_GlobalGNB_ID (namebuf, &pvalue->globalGNB_ID, buffer, bufSize) < 0)
   {
      return -1;
   }

   rtxStrJoin (namebuf, 512, name, ".gNB_DU_ID", 0, 0, 0);
   if (asn1PrtToStr_GNB_DU_ID (namebuf, &pvalue->gNB_DU_ID, buffer, bufSize) < 0)
   {
      return -1;
   }

   rtxStrJoin (namebuf, 512, name, ".extElem1", 0, 0, 0);
   if (rtPrintToStringOpenTypeExt (namebuf, &pvalue->extElem1, buffer, bufSize)  < 0)
   {
      return -1;
   }

   return 0;
}

int asn1PrtToStr_InterfaceID_E1 (const char* name, 
   ASN1T_InterfaceID_E1* pvalue, char* buffer, OSSIZE bufSize)
{
   char namebuf[512];

   rtxStrJoin (namebuf, 512, name, ".globalGNB_ID", 0, 0, 0);
   if (asn1PrtToStr_GlobalGNB_ID (namebuf, &pvalue->globalGNB_ID, buffer, bufSize) < 0)
   {
      return -1;
   }

   rtxStrJoin (namebuf, 512, name, ".gNB_CU_UP_ID", 0, 0, 0);
   if (asn1PrtToStr_GNB_CU_UP_ID (namebuf, &pvalue->gNB_CU_UP_ID, buffer, bufSize) < 0)
   {
      return -1;
   }

   rtxStrJoin (namebuf, 512, name, ".extElem1", 0, 0, 0);
   if (rtPrintToStringOpenTypeExt (namebuf, &pvalue->extElem1, buffer, bufSize)  < 0)
   {
      return -1;
   }

   return 0;
}

int asn1PrtToStr_InterfaceID_S1 (const char* name, 
   ASN1T_InterfaceID_S1* pvalue, char* buffer, OSSIZE bufSize)
{
   char namebuf[512];

   rtxStrJoin (namebuf, 512, name, ".gUMMEI", 0, 0, 0);
   if (asn1PrtToStr_GUMMEI (namebuf, &pvalue->gUMMEI, buffer, bufSize) < 0)
   {
      return -1;
   }

   rtxStrJoin (namebuf, 512, name, ".extElem1", 0, 0, 0);
   if (rtPrintToStringOpenTypeExt (namebuf, &pvalue->extElem1, buffer, bufSize)  < 0)
   {
      return -1;
   }

   return 0;
}

int asn1PrtToStr_EN_GNB_ID (const char* name, ASN1T_EN_GNB_ID* pvalue, 
   char* buffer, OSSIZE bufSize)
{
   {
   char namebuf2[512], numbuf[32];

   rtxIntToCharStr (pvalue->t, numbuf, sizeof(numbuf), 0);
   rtxStrJoin (namebuf2, sizeof(namebuf2), name, ".t = ", numbuf, "\n", 0);
   if (rtPrintToString (namebuf2, buffer, bufSize) < 0)
   {
      return -1;
   }

   switch (pvalue->t) {
      /* en-gNB-ID */
      case 1:
      {
         rtxStrJoin (namebuf2, 512, name, ".u.en_gNB_ID", 0, 0, 0);
         if (rtPrintToStringBitStr (namebuf2, OS_MIN(pvalue->u.en_gNB_ID->numbits, 32), pvalue->u.en_gNB_ID->data, ".", buffer, bufSize) < 0)
         {
            return -1;
         }
         break;
      }
      /* extElem1 */
      case 2:
      {
         rtxStrJoin (namebuf2, 512, name, ".u.extElem1", 0, 0, 0);
         if(rtPrintToStringOpenType (namebuf2, pvalue->u.extElem1->numocts, pvalue->u.extElem1->data, ".", buffer, bufSize) < 0)
         {
            return -1;
         }
         break;
      }
      default:;
   }
   }
   return 0;
}

int asn1PrtToStr_GlobalenGNB_ID (const char* name, 
   ASN1T_GlobalenGNB_ID* pvalue, char* buffer, OSSIZE bufSize)
{
   char namebuf[512];

   rtxStrJoin (namebuf, 512, name, ".pLMN_Identity", 0, 0, 0);
   if (asn1PrtToStr_PLMNIdentity (namebuf, &pvalue->pLMN_Identity, buffer, bufSize) < 0)
   {
      return -1;
   }

   rtxStrJoin (namebuf, 512, name, ".en_gNB_ID", 0, 0, 0);
   if (asn1PrtToStr_EN_GNB_ID (namebuf, &pvalue->en_gNB_ID, buffer, bufSize) < 0)
   {
      return -1;
   }

   rtxStrJoin (namebuf, 512, name, ".extElem1", 0, 0, 0);
   if (rtPrintToStringOpenTypeExt (namebuf, &pvalue->extElem1, buffer, bufSize)  < 0)
   {
      return -1;
   }

   return 0;
}

int asn1PrtToStr_InterfaceID_X2_nodeType (const char* name, 
   ASN1T_InterfaceID_X2_nodeType* pvalue, char* buffer, OSSIZE bufSize)
{
   {
   char namebuf2[512], numbuf[32];

   rtxIntToCharStr (pvalue->t, numbuf, sizeof(numbuf), 0);
   rtxStrJoin (namebuf2, sizeof(namebuf2), name, ".t = ", numbuf, "\n", 0);
   if (rtPrintToString (namebuf2, buffer, bufSize) < 0)
   {
      return -1;
   }

   switch (pvalue->t) {
      /* global-eNB-ID */
      case 1:
      {
         rtxStrJoin (namebuf2, 512, name, ".u.global_eNB_ID", 0, 0, 0);
         if (asn1PrtToStr_GlobalENB_ID (namebuf2, pvalue->u.global_eNB_ID, buffer, bufSize) < 0)
         {
            return -1;
         }
         break;
      }
      /* global-en-gNB-ID */
      case 2:
      {
         rtxStrJoin (namebuf2, 512, name, ".u.global_en_gNB_ID", 0, 0, 0);
         if (asn1PrtToStr_GlobalenGNB_ID (namebuf2, pvalue->u.global_en_gNB_ID, buffer, bufSize) < 0)
         {
            return -1;
         }
         break;
      }
      /* extElem1 */
      case 3:
      {
         rtxStrJoin (namebuf2, 512, name, ".u.extElem1", 0, 0, 0);
         if(rtPrintToStringOpenType (namebuf2, pvalue->u.extElem1->numocts, pvalue->u.extElem1->data, ".", buffer, bufSize) < 0)
         {
            return -1;
         }
         break;
      }
      default:;
   }
   }
   return 0;
}

int asn1PrtToStr_InterfaceID_X2 (const char* name, 
   ASN1T_InterfaceID_X2* pvalue, char* buffer, OSSIZE bufSize)
{
   char namebuf[512];

   rtxStrJoin (namebuf, 512, name, ".nodeType", 0, 0, 0);
   if (asn1PrtToStr_InterfaceID_X2_nodeType (namebuf, &pvalue->nodeType, buffer, bufSize) < 0)
   {
      return -1;
   }

   rtxStrJoin (namebuf, 512, name, ".extElem1", 0, 0, 0);
   if (rtPrintToStringOpenTypeExt (namebuf, &pvalue->extElem1, buffer, bufSize)  < 0)
   {
      return -1;
   }

   return 0;
}

int asn1PrtToStr_InterfaceID_W1 (const char* name, 
   ASN1T_InterfaceID_W1* pvalue, char* buffer, OSSIZE bufSize)
{
   char namebuf[512];

   rtxStrJoin (namebuf, 512, name, ".global_ng_eNB_ID", 0, 0, 0);
   if (asn1PrtToStr_GlobalNgENB_ID (namebuf, &pvalue->global_ng_eNB_ID, buffer, bufSize) < 0)
   {
      return -1;
   }

   rtxStrJoin (namebuf, 512, name, ".ng_eNB_DU_ID", 0, 0, 0);
   if (asn1PrtToStr_NGENB_DU_ID (namebuf, &pvalue->ng_eNB_DU_ID, buffer, bufSize) < 0)
   {
      return -1;
   }

   rtxStrJoin (namebuf, 512, name, ".extElem1", 0, 0, 0);
   if (rtPrintToStringOpenTypeExt (namebuf, &pvalue->extElem1, buffer, bufSize)  < 0)
   {
      return -1;
   }

   return 0;
}

int asn1PrtToStr_InterfaceIdentifier (const char* name, 
   ASN1T_InterfaceIdentifier* pvalue, char* buffer, OSSIZE bufSize)
{
   {
   char namebuf2[512], numbuf[32];

   rtxIntToCharStr (pvalue->t, numbuf, sizeof(numbuf), 0);
   rtxStrJoin (namebuf2, sizeof(namebuf2), name, ".t = ", numbuf, "\n", 0);
   if (rtPrintToString (namebuf2, buffer, bufSize) < 0)
   {
      return -1;
   }

   switch (pvalue->t) {
      /* nG */
      case 1:
      {
         rtxStrJoin (namebuf2, 512, name, ".u.nG", 0, 0, 0);
         if (asn1PrtToStr_InterfaceID_NG (namebuf2, pvalue->u.nG, buffer, bufSize) < 0)
         {
            return -1;
         }
         break;
      }
      /* xN */
      case 2:
      {
         rtxStrJoin (namebuf2, 512, name, ".u.xN", 0, 0, 0);
         if (asn1PrtToStr_InterfaceID_Xn (namebuf2, pvalue->u.xN, buffer, bufSize) < 0)
         {
            return -1;
         }
         break;
      }
      /* f1 */
      case 3:
      {
         rtxStrJoin (namebuf2, 512, name, ".u.f1", 0, 0, 0);
         if (asn1PrtToStr_InterfaceID_F1 (namebuf2, pvalue->u.f1, buffer, bufSize) < 0)
         {
            return -1;
         }
         break;
      }
      /* e1 */
      case 4:
      {
         rtxStrJoin (namebuf2, 512, name, ".u.e1", 0, 0, 0);
         if (asn1PrtToStr_InterfaceID_E1 (namebuf2, pvalue->u.e1, buffer, bufSize) < 0)
         {
            return -1;
         }
         break;
      }
      /* s1 */
      case 5:
      {
         rtxStrJoin (namebuf2, 512, name, ".u.s1", 0, 0, 0);
         if (asn1PrtToStr_InterfaceID_S1 (namebuf2, pvalue->u.s1, buffer, bufSize) < 0)
         {
            return -1;
         }
         break;
      }
      /* x2 */
      case 6:
      {
         rtxStrJoin (namebuf2, 512, name, ".u.x2", 0, 0, 0);
         if (asn1PrtToStr_InterfaceID_X2 (namebuf2, pvalue->u.x2, buffer, bufSize) < 0)
         {
            return -1;
         }
         break;
      }
      /* w1 */
      case 7:
      {
         rtxStrJoin (namebuf2, 512, name, ".u.w1", 0, 0, 0);
         if (asn1PrtToStr_InterfaceID_W1 (namebuf2, pvalue->u.w1, buffer, bufSize) < 0)
         {
            return -1;
         }
         break;
      }
      /* extElem1 */
      case 8:
      {
         rtxStrJoin (namebuf2, 512, name, ".u.extElem1", 0, 0, 0);
         if(rtPrintToStringOpenType (namebuf2, pvalue->u.extElem1->numocts, pvalue->u.extElem1->data, ".", buffer, bufSize) < 0)
         {
            return -1;
         }
         break;
      }
      default:;
   }
   }
   return 0;
}

int asn1PrtToStr_Interface_MessageID (const char* name, 
   ASN1T_Interface_MessageID* pvalue, char* buffer, OSSIZE bufSize)
{
   char namebuf[512];

   rtxStrJoin (namebuf, 512, name, ".interfaceProcedureID", 0, 0, 0);
   if (rtPrintToStringInteger (namebuf, pvalue->interfaceProcedureID, buffer, bufSize) < 0)
   {
      return -1;
   }

   rtxStrJoin (namebuf, 512, name, ".messageType", 0, 0, 0);
   if (asn1PrtToStr_Interface_MessageID_messageType (namebuf, &pvalue->messageType, buffer, bufSize) < 0)
   {
      return -1;
   }

   rtxStrJoin (namebuf, 512, name, ".extElem1", 0, 0, 0);
   if (rtPrintToStringOpenTypeExt (namebuf, &pvalue->extElem1, buffer, bufSize)  < 0)
   {
      return -1;
   }

   return 0;
}

int asn1PrtToStr_GroupID (const char* name, ASN1T_GroupID* pvalue, 
   char* buffer, OSSIZE bufSize)
{
   {
   char namebuf2[512], numbuf[32];

   rtxIntToCharStr (pvalue->t, numbuf, sizeof(numbuf), 0);
   rtxStrJoin (namebuf2, sizeof(namebuf2), name, ".t = ", numbuf, "\n", 0);
   if (rtPrintToString (namebuf2, buffer, bufSize) < 0)
   {
      return -1;
   }

   switch (pvalue->t) {
      /* fiveGC */
      case 1:
      {
         rtxStrJoin (namebuf2, 512, name, ".u.fiveGC", 0, 0, 0);
         if (asn1PrtToStr_FiveQI (namebuf2, &pvalue->u.fiveGC, buffer, bufSize) < 0)
         {
            return -1;
         }
         break;
      }
      /* ePC */
      case 2:
      {
         rtxStrJoin (namebuf2, 512, name, ".u.ePC", 0, 0, 0);
         if (asn1PrtToStr_QCI (namebuf2, &pvalue->u.ePC, buffer, bufSize) < 0)
         {
            return -1;
         }
         break;
      }
      /* extElem1 */
      case 3:
      {
         rtxStrJoin (namebuf2, 512, name, ".u.extElem1", 0, 0, 0);
         if(rtPrintToStringOpenType (namebuf2, pvalue->u.extElem1->numocts, pvalue->u.extElem1->data, ".", buffer, bufSize) < 0)
         {
            return -1;
         }
         break;
      }
      default:;
   }
   }
   return 0;
}

int ASN1C_GroupID::toString (const char* name, char* buffer, OSSIZE bufSize)
{
   if (asn1PrtToStr_GroupID (name, &msgData, buffer, bufSize) < 0)
   {
      return -1;
   }
   return 0;
}

int ASN1C_GroupID::toString (char* buffer, OSSIZE bufSize)
{
   return toString ("GroupID", buffer, bufSize);
}

int asn1PrtToStr_QoSID (const char* name, ASN1T_QoSID* pvalue, char* buffer, 
   OSSIZE bufSize)
{
   {
   char namebuf2[512], numbuf[32];

   rtxIntToCharStr (pvalue->t, numbuf, sizeof(numbuf), 0);
   rtxStrJoin (namebuf2, sizeof(namebuf2), name, ".t = ", numbuf, "\n", 0);
   if (rtPrintToString (namebuf2, buffer, bufSize) < 0)
   {
      return -1;
   }

   switch (pvalue->t) {
      /* fiveGC */
      case 1:
      {
         rtxStrJoin (namebuf2, 512, name, ".u.fiveGC", 0, 0, 0);
         if (asn1PrtToStr_FiveQI (namebuf2, &pvalue->u.fiveGC, buffer, bufSize) < 0)
         {
            return -1;
         }
         break;
      }
      /* ePC */
      case 2:
      {
         rtxStrJoin (namebuf2, 512, name, ".u.ePC", 0, 0, 0);
         if (asn1PrtToStr_QCI (namebuf2, &pvalue->u.ePC, buffer, bufSize) < 0)
         {
            return -1;
         }
         break;
      }
      /* extElem1 */
      case 3:
      {
         rtxStrJoin (namebuf2, 512, name, ".u.extElem1", 0, 0, 0);
         if(rtPrintToStringOpenType (namebuf2, pvalue->u.extElem1->numocts, pvalue->u.extElem1->data, ".", buffer, bufSize) < 0)
         {
            return -1;
         }
         break;
      }
      default:;
   }
   }
   return 0;
}

int ASN1C_QoSID::toString (const char* name, char* buffer, OSSIZE bufSize)
{
   if (asn1PrtToStr_QoSID (name, &msgData, buffer, bufSize) < 0)
   {
      return -1;
   }
   return 0;
}

int ASN1C_QoSID::toString (char* buffer, OSSIZE bufSize)
{
   return toString ("QoSID", buffer, bufSize);
}

int asn1PrtToStr_RRC_MessageID_rrcType (const char* name, 
   ASN1T_RRC_MessageID_rrcType* pvalue, char* buffer, OSSIZE bufSize)
{
   {
   char namebuf2[512], numbuf[32];

   rtxIntToCharStr (pvalue->t, numbuf, sizeof(numbuf), 0);
   rtxStrJoin (namebuf2, sizeof(namebuf2), name, ".t = ", numbuf, "\n", 0);
   if (rtPrintToString (namebuf2, buffer, bufSize) < 0)
   {
      return -1;
   }

   switch (pvalue->t) {
      /* lTE */
      case 1:
      {
         rtxStrJoin (namebuf2, 512, name, ".u.lTE", 0, 0, 0);
         if (asn1PrtToStr_RRCclass_LTE (namebuf2, &pvalue->u.lTE, buffer, bufSize) < 0)
         {
            return -1;
         }
         break;
      }
      /* nR */
      case 2:
      {
         rtxStrJoin (namebuf2, 512, name, ".u.nR", 0, 0, 0);
         if (asn1PrtToStr_RRCclass_NR (namebuf2, &pvalue->u.nR, buffer, bufSize) < 0)
         {
            return -1;
         }
         break;
      }
      /* extElem1 */
      case 3:
      {
         rtxStrJoin (namebuf2, 512, name, ".u.extElem1", 0, 0, 0);
         if(rtPrintToStringOpenType (namebuf2, pvalue->u.extElem1->numocts, pvalue->u.extElem1->data, ".", buffer, bufSize) < 0)
         {
            return -1;
         }
         break;
      }
      default:;
   }
   }
   return 0;
}

int asn1PrtToStr_RRC_MessageID (const char* name, ASN1T_RRC_MessageID* pvalue, 
   char* buffer, OSSIZE bufSize)
{
   char namebuf[512];

   rtxStrJoin (namebuf, 512, name, ".rrcType", 0, 0, 0);
   if (asn1PrtToStr_RRC_MessageID_rrcType (namebuf, &pvalue->rrcType, buffer, bufSize) < 0)
   {
      return -1;
   }

   rtxStrJoin (namebuf, 512, name, ".messageID", 0, 0, 0);
   if (rtPrintToStringInteger (namebuf, pvalue->messageID, buffer, bufSize) < 0)
   {
      return -1;
   }

   rtxStrJoin (namebuf, 512, name, ".extElem1", 0, 0, 0);
   if (rtPrintToStringOpenTypeExt (namebuf, &pvalue->extElem1, buffer, bufSize)  < 0)
   {
      return -1;
   }

   return 0;
}

int asn1PrtToStr_NR_ARFCN (const char* name, ASN1T_NR_ARFCN* pvalue, 
   char* buffer, OSSIZE bufSize)
{
   char namebuf[512];

   rtxStrJoin (namebuf, 512, name, ".nRARFCN", 0, 0, 0);
   if (rtPrintToStringUnsigned (namebuf, pvalue->nRARFCN, buffer, bufSize) < 0)
   {
      return -1;
   }

   rtxStrJoin (namebuf, 512, name, ".extElem1", 0, 0, 0);
   if (rtPrintToStringOpenTypeExt (namebuf, &pvalue->extElem1, buffer, bufSize)  < 0)
   {
      return -1;
   }

   return 0;
}

int asn1PrtToStr_ServingCell_ARFCN (const char* name, 
   ASN1T_ServingCell_ARFCN* pvalue, char* buffer, OSSIZE bufSize)
{
   {
   char namebuf2[512], numbuf[32];

   rtxIntToCharStr (pvalue->t, numbuf, sizeof(numbuf), 0);
   rtxStrJoin (namebuf2, sizeof(namebuf2), name, ".t = ", numbuf, "\n", 0);
   if (rtPrintToString (namebuf2, buffer, bufSize) < 0)
   {
      return -1;
   }

   switch (pvalue->t) {
      /* nR */
      case 1:
      {
         rtxStrJoin (namebuf2, 512, name, ".u.nR", 0, 0, 0);
         if (asn1PrtToStr_NR_ARFCN (namebuf2, pvalue->u.nR, buffer, bufSize) < 0)
         {
            return -1;
         }
         break;
      }
      /* eUTRA */
      case 2:
      {
         rtxStrJoin (namebuf2, 512, name, ".u.eUTRA", 0, 0, 0);
         if (asn1PrtToStr_E_UTRA_ARFCN (namebuf2, &pvalue->u.eUTRA, buffer, bufSize) < 0)
         {
            return -1;
         }
         break;
      }
      /* extElem1 */
      case 3:
      {
         rtxStrJoin (namebuf2, 512, name, ".u.extElem1", 0, 0, 0);
         if(rtPrintToStringOpenType (namebuf2, pvalue->u.extElem1->numocts, pvalue->u.extElem1->data, ".", buffer, bufSize) < 0)
         {
            return -1;
         }
         break;
      }
      default:;
   }
   }
   return 0;
}

int asn1PrtToStr_ServingCell_PCI (const char* name, 
   ASN1T_ServingCell_PCI* pvalue, char* buffer, OSSIZE bufSize)
{
   {
   char namebuf2[512], numbuf[32];

   rtxIntToCharStr (pvalue->t, numbuf, sizeof(numbuf), 0);
   rtxStrJoin (namebuf2, sizeof(namebuf2), name, ".t = ", numbuf, "\n", 0);
   if (rtPrintToString (namebuf2, buffer, bufSize) < 0)
   {
      return -1;
   }

   switch (pvalue->t) {
      /* nR */
      case 1:
      {
         rtxStrJoin (namebuf2, 512, name, ".u.nR", 0, 0, 0);
         if (asn1PrtToStr_NR_PCI (namebuf2, &pvalue->u.nR, buffer, bufSize) < 0)
         {
            return -1;
         }
         break;
      }
      /* eUTRA */
      case 2:
      {
         rtxStrJoin (namebuf2, 512, name, ".u.eUTRA", 0, 0, 0);
         if (asn1PrtToStr_E_UTRA_PCI (namebuf2, &pvalue->u.eUTRA, buffer, bufSize) < 0)
         {
            return -1;
         }
         break;
      }
      /* extElem1 */
      case 3:
      {
         rtxStrJoin (namebuf2, 512, name, ".u.extElem1", 0, 0, 0);
         if(rtPrintToStringOpenType (namebuf2, pvalue->u.extElem1->numocts, pvalue->u.extElem1->data, ".", buffer, bufSize) < 0)
         {
            return -1;
         }
         break;
      }
      default:;
   }
   }
   return 0;
}

int asn1PrtToStr_FreqBandNrItem (const char* name, 
   ASN1T_FreqBandNrItem* pvalue, char* buffer, OSSIZE bufSize)
{
   char namebuf[512];

   rtxStrJoin (namebuf, 512, name, ".freqBandIndicatorNr", 0, 0, 0);
   if (rtPrintToStringUnsigned (namebuf, pvalue->freqBandIndicatorNr, buffer, bufSize) < 0)
   {
      return -1;
   }

   rtxStrJoin (namebuf, 512, name, ".extElem1", 0, 0, 0);
   if (rtPrintToStringOpenTypeExt (namebuf, &pvalue->extElem1, buffer, bufSize)  < 0)
   {
      return -1;
   }

   return 0;
}

int ASN1C_FreqBandNrItem::toString (const char* name, char* buffer, OSSIZE bufSize)
{
   if (asn1PrtToStr_FreqBandNrItem (name, &msgData, buffer, bufSize) < 0)
   {
      return -1;
   }
   return 0;
}

int ASN1C_FreqBandNrItem::toString (char* buffer, OSSIZE bufSize)
{
   return toString ("FreqBandNrItem", buffer, bufSize);
}

int asn1PrtToStr_SupportedSULFreqBandItem (const char* name, 
   ASN1T_SupportedSULFreqBandItem* pvalue, char* buffer, OSSIZE bufSize)
{
   char namebuf[512];

   rtxStrJoin (namebuf, 512, name, ".freqBandIndicatorNr", 0, 0, 0);
   if (rtPrintToStringUnsigned (namebuf, pvalue->freqBandIndicatorNr, buffer, bufSize) < 0)
   {
      return -1;
   }

   rtxStrJoin (namebuf, 512, name, ".extElem1", 0, 0, 0);
   if (rtPrintToStringOpenTypeExt (namebuf, &pvalue->extElem1, buffer, bufSize)  < 0)
   {
      return -1;
   }

   return 0;
}

int asn1PrtToStr_SupportedSULBandList (const char* name, 
   ASN1T_SupportedSULBandList* pvalue, char* buffer, OSSIZE bufSize)
{
   ASN1T_SupportedSULFreqBandItem* pdata0;
   OSRTDListNode* pnode;
   char namebuf[512];
   char numbuf[32];

   rtxSizeToCharStr (pvalue->count, numbuf, sizeof(numbuf), 0);
   rtxStrJoin (namebuf, 512, name, ".count = ", numbuf, "\n", 0);
   if(rtPrintToString (namebuf, buffer, bufSize) < 0)
   {
      return -1;
   }

   {
   OSUINT32 xx1 = 0;

   for (pnode = pvalue->head; pnode != 0 && xx1 < pvalue->count; pnode = pnode->next) {
      pdata0 = ((ASN1T_SupportedSULFreqBandItem*)pnode->data);
      rtxUIntToCharStr (xx1, numbuf, sizeof(numbuf), 0);
      rtxStrJoin (namebuf, sizeof(namebuf), name, ".elem[", numbuf, "]", 0);
      if (asn1PrtToStr_SupportedSULFreqBandItem (namebuf, pdata0, buffer, bufSize) < 0)
      {
         return -1;
      }
      xx1++;
   }
   }
   return 0;
}

int asn1PrtToStr_NRFrequencyBandItem (const char* name, 
   ASN1T_NRFrequencyBandItem* pvalue, char* buffer, OSSIZE bufSize)
{
   char namebuf[512];

   rtxStrJoin (namebuf, 512, name, ".freqBandIndicatorNr", 0, 0, 0);
   if (rtPrintToStringUnsigned (namebuf, pvalue->freqBandIndicatorNr, buffer, bufSize) < 0)
   {
      return -1;
   }

   rtxStrJoin (namebuf, 512, name, ".supportedSULBandList", 0, 0, 0);
   if (asn1PrtToStr_SupportedSULBandList (namebuf, &pvalue->supportedSULBandList, buffer, bufSize) < 0)
   {
      return -1;
   }

   rtxStrJoin (namebuf, 512, name, ".extElem1", 0, 0, 0);
   if (rtPrintToStringOpenTypeExt (namebuf, &pvalue->extElem1, buffer, bufSize)  < 0)
   {
      return -1;
   }

   return 0;
}

int asn1PrtToStr_NRFrequencyBand_List (const char* name, 
   ASN1T_NRFrequencyBand_List* pvalue, char* buffer, OSSIZE bufSize)
{
   ASN1T_NRFrequencyBandItem* pdata0;
   OSRTDListNode* pnode;
   char namebuf[512];
   char numbuf[32];

   rtxSizeToCharStr (pvalue->count, numbuf, sizeof(numbuf), 0);
   rtxStrJoin (namebuf, 512, name, ".count = ", numbuf, "\n", 0);
   if(rtPrintToString (namebuf, buffer, bufSize) < 0)
   {
      return -1;
   }

   {
   OSUINT32 xx1 = 0;

   for (pnode = pvalue->head; pnode != 0 && xx1 < pvalue->count; pnode = pnode->next) {
      pdata0 = ((ASN1T_NRFrequencyBandItem*)pnode->data);
      rtxUIntToCharStr (xx1, numbuf, sizeof(numbuf), 0);
      rtxStrJoin (namebuf, sizeof(namebuf), name, ".elem[", numbuf, "]", 0);
      if (asn1PrtToStr_NRFrequencyBandItem (namebuf, pdata0, buffer, bufSize) < 0)
      {
         return -1;
      }
      xx1++;
   }
   }
   return 0;
}

int asn1PrtToStr_NRFrequencyInfo (const char* name, 
   ASN1T_NRFrequencyInfo* pvalue, char* buffer, OSSIZE bufSize)
{
   char namebuf[512];

   { char numbuf[32];
   rtxIntToCharStr ((int)pvalue->m.frequencyShift7p5khzPresent, numbuf, 32, 0);
   rtxStrJoin (namebuf, 512, name, ".m.frequencyShift7p5khzPresent = ", numbuf, "\n", 0);
   if (rtPrintToString (namebuf, buffer, bufSize) < 0) {
      return -1;
   }}
   rtxStrJoin (namebuf, 512, name, ".nrARFCN", 0, 0, 0);
   if (asn1PrtToStr_NR_ARFCN (namebuf, &pvalue->nrARFCN, buffer, bufSize) < 0)
   {
      return -1;
   }

   rtxStrJoin (namebuf, 512, name, ".frequencyBand_List", 0, 0, 0);
   if (asn1PrtToStr_NRFrequencyBand_List (namebuf, &pvalue->frequencyBand_List, buffer, bufSize) < 0)
   {
      return -1;
   }

   if (pvalue->m.frequencyShift7p5khzPresent) {
      rtxStrJoin (namebuf, 512, name, ".frequencyShift7p5khz", 0, 0, 0);
      if (asn1PrtToStr_NRFrequencyShift7p5khz (namebuf, &pvalue->frequencyShift7p5khz, buffer, bufSize) < 0)
      {
         return -1;
      }
   }

   rtxStrJoin (namebuf, 512, name, ".extElem1", 0, 0, 0);
   if (rtPrintToStringOpenTypeExt (namebuf, &pvalue->extElem1, buffer, bufSize)  < 0)
   {
      return -1;
   }

   return 0;
}

