/**
 * This file was generated by the Objective Systems ASN1C Compiler
 * (http://www.obj-sys.com).  Version: 7.8.2.5, Date: 12-Sep-2025.
 *
 * Command:  asn1c asn1files/E2SM-KPM-v05.00.asn asn1files/asn_flexric/e2sm_rc_v1_03_modified.asn asn1files/asn_flexric/e42ap_v2_03.asn -genTest -per -json -w32 -server -depends -events -genPrtToStr -list -reader -trace -c++ -print -prtfmt details -srcdir src -make Makefile -w32 -table-unions -stream -pdu all
 */
#include "E2SM-COMMON-IEs.h"
#include "rtxsrc/rtxCharStr.h"
#include "rtsrc/rtPrint.h"
#include "rtsrc/rtBCD.h"
#include "rtxsrc/rtxDiag.h"

void asn1Print_PLMNIdentity 
   (const char* name, const ASN1T_PLMNIdentity* pvalue)
{
   rtPrintOctStr (name, OSRTMIN(sizeof(pvalue->data), pvalue->numocts), pvalue->data, ".");
}

void ASN1C_PLMNIdentity::Print (const char* name)
{
   asn1Print_PLMNIdentity (name, &msgData);
}

void asn1Print_SST (const char* name, const ASN1T_SST* pvalue)
{
   rtPrintOctStr (name, OSRTMIN(sizeof(pvalue->data), pvalue->numocts), pvalue->data, ".");
}

void ASN1C_SST::Print (const char* name)
{
   asn1Print_SST (name, &msgData);
}

void asn1Print_SD (const char* name, const ASN1T_SD* pvalue)
{
   rtPrintOctStr (name, OSRTMIN(sizeof(pvalue->data), pvalue->numocts), pvalue->data, ".");
}

void ASN1C_SD::Print (const char* name)
{
   asn1Print_SD (name, &msgData);
}

void asn1Print_S_NSSAI (const char* name, const ASN1T_S_NSSAI* pvalue)
{
   char namebuf[512];

   printf ("%s.m.sDPresent = %d\n", name, (int)pvalue->m.sDPresent);
   rtxStrJoin (namebuf, 512, name, ".sST", 0, 0, 0);
   asn1Print_SST (namebuf, &pvalue->sST);

   if (pvalue->m.sDPresent) {
      rtxStrJoin (namebuf, 512, name, ".sD", 0, 0, 0);
      asn1Print_SD (namebuf, &pvalue->sD);
   }

   rtxStrJoin (namebuf, 512, name, ".extElem1", 0, 0, 0);
   rtPrintOpenTypeExt (namebuf, &pvalue->extElem1);

}

void ASN1C_S_NSSAI::Print (const char* name)
{
   asn1Print_S_NSSAI (name, &msgData);
}

void asn1Print_FiveQI (const char* name, const ASN1T_FiveQI* pvalue)
{
   rtxPrintUnsigned (name, *pvalue);
}

void ASN1C_FiveQI::Print (const char* name)
{
   asn1Print_FiveQI (name, &msgData);
}

void asn1Print_QosFlowIdentifier 
   (const char* name, const ASN1T_QosFlowIdentifier* pvalue)
{
   rtxPrintUnsigned (name, *pvalue);
}

void ASN1C_QosFlowIdentifier::Print (const char* name)
{
   asn1Print_QosFlowIdentifier (name, &msgData);
}

void asn1Print_QCI (const char* name, const ASN1T_QCI* pvalue)
{
   rtxPrintUnsigned (name, *pvalue);
}

void ASN1C_QCI::Print (const char* name)
{
   asn1Print_QCI (name, &msgData);
}

void asn1Print_NRCellIdentity 
   (const char* name, const ASN1T_NRCellIdentity* pvalue)
{
   rtPrintBitStr (name, OS_MIN(pvalue->numbits, 40), pvalue->data, ".");
}

void ASN1C_NRCellIdentity::Print (const char* name)
{
   asn1Print_NRCellIdentity (name, &msgData);
}

void asn1Print_NR_CGI (const char* name, const ASN1T_NR_CGI* pvalue)
{
   char namebuf[512];

   rtxStrJoin (namebuf, 512, name, ".pLMNIdentity", 0, 0, 0);
   asn1Print_PLMNIdentity (namebuf, &pvalue->pLMNIdentity);

   rtxStrJoin (namebuf, 512, name, ".nRCellIdentity", 0, 0, 0);
   asn1Print_NRCellIdentity (namebuf, &pvalue->nRCellIdentity);

   rtxStrJoin (namebuf, 512, name, ".extElem1", 0, 0, 0);
   rtPrintOpenTypeExt (namebuf, &pvalue->extElem1);

}

void ASN1C_NR_CGI::Print (const char* name)
{
   asn1Print_NR_CGI (name, &msgData);
}

void asn1Print_EUTRACellIdentity 
   (const char* name, const ASN1T_EUTRACellIdentity* pvalue)
{
   rtPrintBitStr (name, OS_MIN(pvalue->numbits, 32), pvalue->data, ".");
}

void ASN1C_EUTRACellIdentity::Print (const char* name)
{
   asn1Print_EUTRACellIdentity (name, &msgData);
}

void asn1Print_EUTRA_CGI (const char* name, const ASN1T_EUTRA_CGI* pvalue)
{
   char namebuf[512];

   rtxStrJoin (namebuf, 512, name, ".pLMNIdentity", 0, 0, 0);
   asn1Print_PLMNIdentity (namebuf, &pvalue->pLMNIdentity);

   rtxStrJoin (namebuf, 512, name, ".eUTRACellIdentity", 0, 0, 0);
   asn1Print_EUTRACellIdentity (namebuf, &pvalue->eUTRACellIdentity);

   rtxStrJoin (namebuf, 512, name, ".extElem1", 0, 0, 0);
   rtPrintOpenTypeExt (namebuf, &pvalue->extElem1);

}

void ASN1C_EUTRA_CGI::Print (const char* name)
{
   asn1Print_EUTRA_CGI (name, &msgData);
}

void asn1Print_CGI (const char* name, const ASN1T_CGI* pvalue)
{
   char namebuf[512];

   printf ("%s.t = %d\n", name, pvalue->t);
   switch (pvalue->t)
   {
      /* nR-CGI */
      case 1:
      {
         rtxStrJoin (namebuf, 512, name, ".u.nR_CGI", 0, 0, 0);
         asn1Print_NR_CGI (namebuf, pvalue->u.nR_CGI);
         break;
      }
      /* eUTRA-CGI */
      case 2:
      {
         rtxStrJoin (namebuf, 512, name, ".u.eUTRA_CGI", 0, 0, 0);
         asn1Print_EUTRA_CGI (namebuf, pvalue->u.eUTRA_CGI);
         break;
      }
      /* extElem1 */
      case 3:
      {
         rtxStrJoin (namebuf, 512, name, ".u.extElem1", 0, 0, 0);
         rtPrintOpenType (namebuf, pvalue->u.extElem1->numocts,
         pvalue->u.extElem1->data, ".");
         break;
      }
      default:;
   }
}

void ASN1C_CGI::Print (const char* name)
{
   asn1Print_CGI (name, &msgData);
}

void asn1Print_AMF_UE_NGAP_ID 
   (const char* name, const ASN1T_AMF_UE_NGAP_ID* pvalue)
{
   rtxPrintUInt64 (name, *pvalue);
}

void ASN1C_AMF_UE_NGAP_ID::Print (const char* name)
{
   asn1Print_AMF_UE_NGAP_ID (name, &msgData);
}

void asn1Print_AMFRegionID (const char* name, const ASN1T_AMFRegionID* pvalue)
{
   rtPrintBitStr (name, OS_MIN(pvalue->numbits, 8), pvalue->data, ".");
}

void ASN1C_AMFRegionID::Print (const char* name)
{
   asn1Print_AMFRegionID (name, &msgData);
}

void asn1Print_AMFSetID (const char* name, const ASN1T_AMFSetID* pvalue)
{
   rtPrintBitStr (name, OS_MIN(pvalue->numbits, 16), pvalue->data, ".");
}

void ASN1C_AMFSetID::Print (const char* name)
{
   asn1Print_AMFSetID (name, &msgData);
}

void asn1Print_AMFPointer (const char* name, const ASN1T_AMFPointer* pvalue)
{
   rtPrintBitStr (name, OS_MIN(pvalue->numbits, 8), pvalue->data, ".");
}

void ASN1C_AMFPointer::Print (const char* name)
{
   asn1Print_AMFPointer (name, &msgData);
}

void asn1Print_GUAMI (const char* name, const ASN1T_GUAMI* pvalue)
{
   char namebuf[512];

   rtxStrJoin (namebuf, 512, name, ".pLMNIdentity", 0, 0, 0);
   asn1Print_PLMNIdentity (namebuf, &pvalue->pLMNIdentity);

   rtxStrJoin (namebuf, 512, name, ".aMFRegionID", 0, 0, 0);
   asn1Print_AMFRegionID (namebuf, &pvalue->aMFRegionID);

   rtxStrJoin (namebuf, 512, name, ".aMFSetID", 0, 0, 0);
   asn1Print_AMFSetID (namebuf, &pvalue->aMFSetID);

   rtxStrJoin (namebuf, 512, name, ".aMFPointer", 0, 0, 0);
   asn1Print_AMFPointer (namebuf, &pvalue->aMFPointer);

   rtxStrJoin (namebuf, 512, name, ".extElem1", 0, 0, 0);
   rtPrintOpenTypeExt (namebuf, &pvalue->extElem1);

}

void ASN1C_GUAMI::Print (const char* name)
{
   asn1Print_GUAMI (name, &msgData);
}

void asn1Print_GNB_CU_UE_F1AP_ID 
   (const char* name, const ASN1T_GNB_CU_UE_F1AP_ID* pvalue)
{
   rtxPrintUnsigned (name, *pvalue);
}

void ASN1C_GNB_CU_UE_F1AP_ID::Print (const char* name)
{
   asn1Print_GNB_CU_UE_F1AP_ID (name, &msgData);
}

void asn1Print_UEID_GNB_CU_CP_F1AP_ID_Item 
   (const char* name, const ASN1T_UEID_GNB_CU_CP_F1AP_ID_Item* pvalue)
{
   char namebuf[512];

   rtxStrJoin (namebuf, 512, name, ".gNB_CU_UE_F1AP_ID", 0, 0, 0);
   asn1Print_GNB_CU_UE_F1AP_ID (namebuf, &pvalue->gNB_CU_UE_F1AP_ID);

   rtxStrJoin (namebuf, 512, name, ".extElem1", 0, 0, 0);
   rtPrintOpenTypeExt (namebuf, &pvalue->extElem1);

}

void ASN1C_UEID_GNB_CU_CP_F1AP_ID_Item::Print (const char* name)
{
   asn1Print_UEID_GNB_CU_CP_F1AP_ID_Item (name, &msgData);
}

void asn1Print_UEID_GNB_CU_F1AP_ID_List 
   (const char* name, const ASN1T_UEID_GNB_CU_F1AP_ID_List* pvalue)
{
   ASN1T_UEID_GNB_CU_CP_F1AP_ID_Item* pdata0;
   OSRTDListNode* pnode;
   char namebuf[512];
   char numbuf[32];

   printf ("%s.count = " OSSIZEFMT "\n", name, pvalue->count);
   {
   OSUINT32 xx1 = 0;

   for (pnode = pvalue->head; pnode != 0 && xx1 < pvalue->count; pnode = pnode->next) {
      pdata0 = ((ASN1T_UEID_GNB_CU_CP_F1AP_ID_Item*)pnode->data);
      rtxUIntToCharStr (xx1, numbuf, sizeof(numbuf), 0);
      rtxStrJoin (namebuf, sizeof(namebuf), name, ".elem[", numbuf, "]", 0);
      asn1Print_UEID_GNB_CU_CP_F1AP_ID_Item (namebuf, pdata0);
      xx1++;
   }
   }
}

void ASN1C_UEID_GNB_CU_F1AP_ID_List::Print (const char* name)
{
   asn1Print_UEID_GNB_CU_F1AP_ID_List (name, &msgData);
}

void asn1Print_GNB_CU_CP_UE_E1AP_ID 
   (const char* name, const ASN1T_GNB_CU_CP_UE_E1AP_ID* pvalue)
{
   rtxPrintUnsigned (name, *pvalue);
}

void ASN1C_GNB_CU_CP_UE_E1AP_ID::Print (const char* name)
{
   asn1Print_GNB_CU_CP_UE_E1AP_ID (name, &msgData);
}

void asn1Print_UEID_GNB_CU_CP_E1AP_ID_Item 
   (const char* name, const ASN1T_UEID_GNB_CU_CP_E1AP_ID_Item* pvalue)
{
   char namebuf[512];

   rtxStrJoin (namebuf, 512, name, ".gNB_CU_CP_UE_E1AP_ID", 0, 0, 0);
   asn1Print_GNB_CU_CP_UE_E1AP_ID (namebuf, &pvalue->gNB_CU_CP_UE_E1AP_ID);

   rtxStrJoin (namebuf, 512, name, ".extElem1", 0, 0, 0);
   rtPrintOpenTypeExt (namebuf, &pvalue->extElem1);

}

void ASN1C_UEID_GNB_CU_CP_E1AP_ID_Item::Print (const char* name)
{
   asn1Print_UEID_GNB_CU_CP_E1AP_ID_Item (name, &msgData);
}

void asn1Print_UEID_GNB_CU_CP_E1AP_ID_List 
   (const char* name, const ASN1T_UEID_GNB_CU_CP_E1AP_ID_List* pvalue)
{
   ASN1T_UEID_GNB_CU_CP_E1AP_ID_Item* pdata0;
   OSRTDListNode* pnode;
   char namebuf[512];
   char numbuf[32];

   printf ("%s.count = " OSSIZEFMT "\n", name, pvalue->count);
   {
   OSUINT32 xx1 = 0;

   for (pnode = pvalue->head; pnode != 0 && xx1 < pvalue->count; pnode = pnode->next) {
      pdata0 = ((ASN1T_UEID_GNB_CU_CP_E1AP_ID_Item*)pnode->data);
      rtxUIntToCharStr (xx1, numbuf, sizeof(numbuf), 0);
      rtxStrJoin (namebuf, sizeof(namebuf), name, ".elem[", numbuf, "]", 0);
      asn1Print_UEID_GNB_CU_CP_E1AP_ID_Item (namebuf, pdata0);
      xx1++;
   }
   }
}

void ASN1C_UEID_GNB_CU_CP_E1AP_ID_List::Print (const char* name)
{
   asn1Print_UEID_GNB_CU_CP_E1AP_ID_List (name, &msgData);
}

void asn1Print_RANUEID (const char* name, const ASN1T_RANUEID* pvalue)
{
   rtPrintOctStr (name, OSRTMIN(sizeof(pvalue->data), pvalue->numocts), pvalue->data, ".");
}

void ASN1C_RANUEID::Print (const char* name)
{
   asn1Print_RANUEID (name, &msgData);
}

void asn1Print_NG_RANnodeUEXnAPID 
   (const char* name, const ASN1T_NG_RANnodeUEXnAPID* pvalue)
{
   rtxPrintUnsigned (name, *pvalue);
}

void ASN1C_NG_RANnodeUEXnAPID::Print (const char* name)
{
   asn1Print_NG_RANnodeUEXnAPID (name, &msgData);
}

void asn1Print_GNB_ID (const char* name, const ASN1T_GNB_ID* pvalue)
{
   char namebuf[512];

   printf ("%s.t = %d\n", name, pvalue->t);
   switch (pvalue->t)
   {
      /* gNB-ID */
      case 1:
      {
         rtxStrJoin (namebuf, 512, name, ".u.gNB_ID", 0, 0, 0);
         rtPrintBitStr (namebuf, OS_MIN(pvalue->u.gNB_ID->numbits, 32), pvalue->u.gNB_ID->data, ".");
         break;
      }
      /* extElem1 */
      case 2:
      {
         rtxStrJoin (namebuf, 512, name, ".u.extElem1", 0, 0, 0);
         rtPrintOpenType (namebuf, pvalue->u.extElem1->numocts,
         pvalue->u.extElem1->data, ".");
         break;
      }
      default:;
   }
}

void ASN1C_GNB_ID::Print (const char* name)
{
   asn1Print_GNB_ID (name, &msgData);
}

void asn1Print_GlobalGNB_ID 
   (const char* name, const ASN1T_GlobalGNB_ID* pvalue)
{
   char namebuf[512];

   rtxStrJoin (namebuf, 512, name, ".pLMNIdentity", 0, 0, 0);
   asn1Print_PLMNIdentity (namebuf, &pvalue->pLMNIdentity);

   rtxStrJoin (namebuf, 512, name, ".gNB_ID", 0, 0, 0);
   asn1Print_GNB_ID (namebuf, &pvalue->gNB_ID);

   rtxStrJoin (namebuf, 512, name, ".extElem1", 0, 0, 0);
   rtPrintOpenTypeExt (namebuf, &pvalue->extElem1);

}

void ASN1C_GlobalGNB_ID::Print (const char* name)
{
   asn1Print_GlobalGNB_ID (name, &msgData);
}

void asn1Print_NgENB_ID (const char* name, const ASN1T_NgENB_ID* pvalue)
{
   char namebuf[512];

   printf ("%s.t = %d\n", name, pvalue->t);
   switch (pvalue->t)
   {
      /* macroNgENB-ID */
      case 1:
      {
         rtxStrJoin (namebuf, 512, name, ".u.macroNgENB_ID", 0, 0, 0);
         rtPrintBitStr (namebuf, OS_MIN(pvalue->u.macroNgENB_ID->numbits, 24), pvalue->u.macroNgENB_ID->data, ".");
         break;
      }
      /* shortMacroNgENB-ID */
      case 2:
      {
         rtxStrJoin (namebuf, 512, name, ".u.shortMacroNgENB_ID", 0, 0, 0);
         rtPrintBitStr (namebuf, OS_MIN(pvalue->u.shortMacroNgENB_ID->numbits, 24), pvalue->u.shortMacroNgENB_ID->data, ".");
         break;
      }
      /* longMacroNgENB-ID */
      case 3:
      {
         rtxStrJoin (namebuf, 512, name, ".u.longMacroNgENB_ID", 0, 0, 0);
         rtPrintBitStr (namebuf, OS_MIN(pvalue->u.longMacroNgENB_ID->numbits, 24), pvalue->u.longMacroNgENB_ID->data, ".");
         break;
      }
      /* extElem1 */
      case 4:
      {
         rtxStrJoin (namebuf, 512, name, ".u.extElem1", 0, 0, 0);
         rtPrintOpenType (namebuf, pvalue->u.extElem1->numocts,
         pvalue->u.extElem1->data, ".");
         break;
      }
      default:;
   }
}

void ASN1C_NgENB_ID::Print (const char* name)
{
   asn1Print_NgENB_ID (name, &msgData);
}

void asn1Print_GlobalNgENB_ID 
   (const char* name, const ASN1T_GlobalNgENB_ID* pvalue)
{
   char namebuf[512];

   rtxStrJoin (namebuf, 512, name, ".pLMNIdentity", 0, 0, 0);
   asn1Print_PLMNIdentity (namebuf, &pvalue->pLMNIdentity);

   rtxStrJoin (namebuf, 512, name, ".ngENB_ID", 0, 0, 0);
   asn1Print_NgENB_ID (namebuf, &pvalue->ngENB_ID);

   rtxStrJoin (namebuf, 512, name, ".extElem1", 0, 0, 0);
   rtPrintOpenTypeExt (namebuf, &pvalue->extElem1);

}

void ASN1C_GlobalNgENB_ID::Print (const char* name)
{
   asn1Print_GlobalNgENB_ID (name, &msgData);
}

void asn1Print_GlobalNGRANNodeID 
   (const char* name, const ASN1T_GlobalNGRANNodeID* pvalue)
{
   char namebuf[512];

   printf ("%s.t = %d\n", name, pvalue->t);
   switch (pvalue->t)
   {
      /* gNB */
      case 1:
      {
         rtxStrJoin (namebuf, 512, name, ".u.gNB", 0, 0, 0);
         asn1Print_GlobalGNB_ID (namebuf, pvalue->u.gNB);
         break;
      }
      /* ng-eNB */
      case 2:
      {
         rtxStrJoin (namebuf, 512, name, ".u.ng_eNB", 0, 0, 0);
         asn1Print_GlobalNgENB_ID (namebuf, pvalue->u.ng_eNB);
         break;
      }
      /* extElem1 */
      case 3:
      {
         rtxStrJoin (namebuf, 512, name, ".u.extElem1", 0, 0, 0);
         rtPrintOpenType (namebuf, pvalue->u.extElem1->numocts,
         pvalue->u.extElem1->data, ".");
         break;
      }
      default:;
   }
}

void ASN1C_GlobalNGRANNodeID::Print (const char* name)
{
   asn1Print_GlobalNGRANNodeID (name, &msgData);
}

void asn1Print_UEID_GNB (const char* name, const ASN1T_UEID_GNB* pvalue)
{
   char namebuf[512];

   printf ("%s.m.gNB_CU_UE_F1AP_ID_ListPresent = %d\n", name, (int)pvalue->m.gNB_CU_UE_F1AP_ID_ListPresent);
   printf ("%s.m.gNB_CU_CP_UE_E1AP_ID_ListPresent = %d\n", name, (int)pvalue->m.gNB_CU_CP_UE_E1AP_ID_ListPresent);
   printf ("%s.m.ran_UEIDPresent = %d\n", name, (int)pvalue->m.ran_UEIDPresent);
   printf ("%s.m.m_NG_RAN_UE_XnAP_IDPresent = %d\n", name, (int)pvalue->m.m_NG_RAN_UE_XnAP_IDPresent);
   printf ("%s.m.globalGNB_IDPresent = %d\n", name, (int)pvalue->m.globalGNB_IDPresent);
   printf ("%s.m.globalNG_RANNode_IDPresent = %d\n", name, (int)pvalue->m.globalNG_RANNode_IDPresent);
   rtxStrJoin (namebuf, 512, name, ".amf_UE_NGAP_ID", 0, 0, 0);
   asn1Print_AMF_UE_NGAP_ID (namebuf, &pvalue->amf_UE_NGAP_ID);

   rtxStrJoin (namebuf, 512, name, ".guami", 0, 0, 0);
   asn1Print_GUAMI (namebuf, &pvalue->guami);

   if (pvalue->m.gNB_CU_UE_F1AP_ID_ListPresent) {
      rtxStrJoin (namebuf, 512, name, ".gNB_CU_UE_F1AP_ID_List", 0, 0, 0);
      asn1Print_UEID_GNB_CU_F1AP_ID_List (namebuf, &pvalue->
         gNB_CU_UE_F1AP_ID_List);
   }

   if (pvalue->m.gNB_CU_CP_UE_E1AP_ID_ListPresent) {
      rtxStrJoin (namebuf, 512, name, ".gNB_CU_CP_UE_E1AP_ID_List", 0, 0, 0);
      asn1Print_UEID_GNB_CU_CP_E1AP_ID_List (namebuf, &pvalue->
         gNB_CU_CP_UE_E1AP_ID_List);
   }

   if (pvalue->m.ran_UEIDPresent) {
      rtxStrJoin (namebuf, 512, name, ".ran_UEID", 0, 0, 0);
      asn1Print_RANUEID (namebuf, &pvalue->ran_UEID);
   }

   if (pvalue->m.m_NG_RAN_UE_XnAP_IDPresent) {
      rtxStrJoin (namebuf, 512, name, ".m_NG_RAN_UE_XnAP_ID", 0, 0, 0);
      asn1Print_NG_RANnodeUEXnAPID (namebuf, &pvalue->m_NG_RAN_UE_XnAP_ID);
   }

   if (pvalue->m.globalGNB_IDPresent) {
      rtxStrJoin (namebuf, 512, name, ".globalGNB_ID", 0, 0, 0);
      asn1Print_GlobalGNB_ID (namebuf, &pvalue->globalGNB_ID);
   }

   if (pvalue->m.globalNG_RANNode_IDPresent) {
      rtxStrJoin (namebuf, 512, name, ".globalNG_RANNode_ID", 0, 0, 0);
      asn1Print_GlobalNGRANNodeID (namebuf, &pvalue->globalNG_RANNode_ID);
   }

   rtxStrJoin (namebuf, 512, name, ".extElem1", 0, 0, 0);
   rtPrintOpenTypeExt (namebuf, &pvalue->extElem1);

}

void ASN1C_UEID_GNB::Print (const char* name)
{
   asn1Print_UEID_GNB (name, &msgData);
}

void asn1Print_UEID_GNB_DU (const char* name, const ASN1T_UEID_GNB_DU* pvalue)
{
   char namebuf[512];

   printf ("%s.m.ran_UEIDPresent = %d\n", name, (int)pvalue->m.ran_UEIDPresent);
   rtxStrJoin (namebuf, 512, name, ".gNB_CU_UE_F1AP_ID", 0, 0, 0);
   asn1Print_GNB_CU_UE_F1AP_ID (namebuf, &pvalue->gNB_CU_UE_F1AP_ID);

   if (pvalue->m.ran_UEIDPresent) {
      rtxStrJoin (namebuf, 512, name, ".ran_UEID", 0, 0, 0);
      asn1Print_RANUEID (namebuf, &pvalue->ran_UEID);
   }

   rtxStrJoin (namebuf, 512, name, ".extElem1", 0, 0, 0);
   rtPrintOpenTypeExt (namebuf, &pvalue->extElem1);

}

void ASN1C_UEID_GNB_DU::Print (const char* name)
{
   asn1Print_UEID_GNB_DU (name, &msgData);
}

void asn1Print_UEID_GNB_CU_UP 
   (const char* name, const ASN1T_UEID_GNB_CU_UP* pvalue)
{
   char namebuf[512];

   printf ("%s.m.ran_UEIDPresent = %d\n", name, (int)pvalue->m.ran_UEIDPresent);
   rtxStrJoin (namebuf, 512, name, ".gNB_CU_CP_UE_E1AP_ID", 0, 0, 0);
   asn1Print_GNB_CU_CP_UE_E1AP_ID (namebuf, &pvalue->gNB_CU_CP_UE_E1AP_ID);

   if (pvalue->m.ran_UEIDPresent) {
      rtxStrJoin (namebuf, 512, name, ".ran_UEID", 0, 0, 0);
      asn1Print_RANUEID (namebuf, &pvalue->ran_UEID);
   }

   rtxStrJoin (namebuf, 512, name, ".extElem1", 0, 0, 0);
   rtPrintOpenTypeExt (namebuf, &pvalue->extElem1);

}

void ASN1C_UEID_GNB_CU_UP::Print (const char* name)
{
   asn1Print_UEID_GNB_CU_UP (name, &msgData);
}

void asn1Print_NGENB_CU_UE_W1AP_ID 
   (const char* name, const ASN1T_NGENB_CU_UE_W1AP_ID* pvalue)
{
   rtxPrintUnsigned (name, *pvalue);
}

void ASN1C_NGENB_CU_UE_W1AP_ID::Print (const char* name)
{
   asn1Print_NGENB_CU_UE_W1AP_ID (name, &msgData);
}

void asn1Print_UEID_NG_ENB (const char* name, const ASN1T_UEID_NG_ENB* pvalue)
{
   char namebuf[512];

   printf ("%s.m.ng_eNB_CU_UE_W1AP_IDPresent = %d\n", name, (int)pvalue->m.ng_eNB_CU_UE_W1AP_IDPresent);
   printf ("%s.m.m_NG_RAN_UE_XnAP_IDPresent = %d\n", name, (int)pvalue->m.m_NG_RAN_UE_XnAP_IDPresent);
   printf ("%s.m.globalNgENB_IDPresent = %d\n", name, (int)pvalue->m.globalNgENB_IDPresent);
   printf ("%s.m.globalNG_RANNode_IDPresent = %d\n", name, (int)pvalue->m.globalNG_RANNode_IDPresent);
   rtxStrJoin (namebuf, 512, name, ".amf_UE_NGAP_ID", 0, 0, 0);
   asn1Print_AMF_UE_NGAP_ID (namebuf, &pvalue->amf_UE_NGAP_ID);

   rtxStrJoin (namebuf, 512, name, ".guami", 0, 0, 0);
   asn1Print_GUAMI (namebuf, &pvalue->guami);

   if (pvalue->m.ng_eNB_CU_UE_W1AP_IDPresent) {
      rtxStrJoin (namebuf, 512, name, ".ng_eNB_CU_UE_W1AP_ID", 0, 0, 0);
      asn1Print_NGENB_CU_UE_W1AP_ID (namebuf, &pvalue->ng_eNB_CU_UE_W1AP_ID);
   }

   if (pvalue->m.m_NG_RAN_UE_XnAP_IDPresent) {
      rtxStrJoin (namebuf, 512, name, ".m_NG_RAN_UE_XnAP_ID", 0, 0, 0);
      asn1Print_NG_RANnodeUEXnAPID (namebuf, &pvalue->m_NG_RAN_UE_XnAP_ID);
   }

   if (pvalue->m.globalNgENB_IDPresent) {
      rtxStrJoin (namebuf, 512, name, ".globalNgENB_ID", 0, 0, 0);
      asn1Print_GlobalNgENB_ID (namebuf, &pvalue->globalNgENB_ID);
   }

   if (pvalue->m.globalNG_RANNode_IDPresent) {
      rtxStrJoin (namebuf, 512, name, ".globalNG_RANNode_ID", 0, 0, 0);
      asn1Print_GlobalNGRANNodeID (namebuf, &pvalue->globalNG_RANNode_ID);
   }

   rtxStrJoin (namebuf, 512, name, ".extElem1", 0, 0, 0);
   rtPrintOpenTypeExt (namebuf, &pvalue->extElem1);

}

void ASN1C_UEID_NG_ENB::Print (const char* name)
{
   asn1Print_UEID_NG_ENB (name, &msgData);
}

void asn1Print_UEID_NG_ENB_DU 
   (const char* name, const ASN1T_UEID_NG_ENB_DU* pvalue)
{
   char namebuf[512];

   rtxStrJoin (namebuf, 512, name, ".ng_eNB_CU_UE_W1AP_ID", 0, 0, 0);
   asn1Print_NGENB_CU_UE_W1AP_ID (namebuf, &pvalue->ng_eNB_CU_UE_W1AP_ID);

   rtxStrJoin (namebuf, 512, name, ".extElem1", 0, 0, 0);
   rtPrintOpenTypeExt (namebuf, &pvalue->extElem1);

}

void ASN1C_UEID_NG_ENB_DU::Print (const char* name)
{
   asn1Print_UEID_NG_ENB_DU (name, &msgData);
}

void asn1Print_ENB_UE_X2AP_ID 
   (const char* name, const ASN1T_ENB_UE_X2AP_ID* pvalue)
{
   rtxPrintUnsigned (name, *pvalue);
}

void ASN1C_ENB_UE_X2AP_ID::Print (const char* name)
{
   asn1Print_ENB_UE_X2AP_ID (name, &msgData);
}

void asn1Print_ENB_UE_X2AP_ID_Extension 
   (const char* name, const ASN1T_ENB_UE_X2AP_ID_Extension* pvalue)
{
   rtxPrintUnsigned (name, *pvalue);
}

void ASN1C_ENB_UE_X2AP_ID_Extension::Print (const char* name)
{
   asn1Print_ENB_UE_X2AP_ID_Extension (name, &msgData);
}

void asn1Print_ENB_ID (const char* name, const ASN1T_ENB_ID* pvalue)
{
   char namebuf[512];

   printf ("%s.t = %d\n", name, pvalue->t);
   switch (pvalue->t)
   {
      /* macro-eNB-ID */
      case 1:
      {
         rtxStrJoin (namebuf, 512, name, ".u.macro_eNB_ID", 0, 0, 0);
         rtPrintBitStr (namebuf, OS_MIN(pvalue->u.macro_eNB_ID->numbits, 24), pvalue->u.macro_eNB_ID->data, ".");
         break;
      }
      /* home-eNB-ID */
      case 2:
      {
         rtxStrJoin (namebuf, 512, name, ".u.home_eNB_ID", 0, 0, 0);
         rtPrintBitStr (namebuf, OS_MIN(pvalue->u.home_eNB_ID->numbits, 32), pvalue->u.home_eNB_ID->data, ".");
         break;
      }
      /* short-Macro-eNB-ID */
      case 3:
      {
         rtxStrJoin (namebuf, 512, name, ".u.short_Macro_eNB_ID", 0, 0, 0);
         rtPrintBitStr (namebuf, OS_MIN(pvalue->u.short_Macro_eNB_ID->numbits, 24), pvalue->u.short_Macro_eNB_ID->data, ".");
         break;
      }
      /* long-Macro-eNB-ID */
      case 4:
      {
         rtxStrJoin (namebuf, 512, name, ".u.long_Macro_eNB_ID", 0, 0, 0);
         rtPrintBitStr (namebuf, OS_MIN(pvalue->u.long_Macro_eNB_ID->numbits, 24), pvalue->u.long_Macro_eNB_ID->data, ".");
         break;
      }
      /* extElem1 */
      case 5:
      {
         rtxStrJoin (namebuf, 512, name, ".u.extElem1", 0, 0, 0);
         rtPrintOpenType (namebuf, pvalue->u.extElem1->numocts,
         pvalue->u.extElem1->data, ".");
         break;
      }
      default:;
   }
}

void ASN1C_ENB_ID::Print (const char* name)
{
   asn1Print_ENB_ID (name, &msgData);
}

void asn1Print_GlobalENB_ID 
   (const char* name, const ASN1T_GlobalENB_ID* pvalue)
{
   char namebuf[512];

   rtxStrJoin (namebuf, 512, name, ".pLMNIdentity", 0, 0, 0);
   asn1Print_PLMNIdentity (namebuf, &pvalue->pLMNIdentity);

   rtxStrJoin (namebuf, 512, name, ".eNB_ID", 0, 0, 0);
   asn1Print_ENB_ID (namebuf, &pvalue->eNB_ID);

   rtxStrJoin (namebuf, 512, name, ".extElem1", 0, 0, 0);
   rtPrintOpenTypeExt (namebuf, &pvalue->extElem1);

}

void ASN1C_GlobalENB_ID::Print (const char* name)
{
   asn1Print_GlobalENB_ID (name, &msgData);
}

void asn1Print_UEID_EN_GNB (const char* name, const ASN1T_UEID_EN_GNB* pvalue)
{
   char namebuf[512];

   printf ("%s.m.m_eNB_UE_X2AP_ID_ExtensionPresent = %d\n", name, (int)pvalue->m.m_eNB_UE_X2AP_ID_ExtensionPresent);
   printf ("%s.m.gNB_CU_UE_F1AP_IDPresent = %d\n", name, (int)pvalue->m.gNB_CU_UE_F1AP_IDPresent);
   printf ("%s.m.gNB_CU_CP_UE_E1AP_ID_ListPresent = %d\n", name, (int)pvalue->m.gNB_CU_CP_UE_E1AP_ID_ListPresent);
   printf ("%s.m.ran_UEIDPresent = %d\n", name, (int)pvalue->m.ran_UEIDPresent);
   rtxStrJoin (namebuf, 512, name, ".m_eNB_UE_X2AP_ID", 0, 0, 0);
   asn1Print_ENB_UE_X2AP_ID (namebuf, &pvalue->m_eNB_UE_X2AP_ID);

   if (pvalue->m.m_eNB_UE_X2AP_ID_ExtensionPresent) {
      rtxStrJoin (namebuf, 512, name, ".m_eNB_UE_X2AP_ID_Extension", 0, 0, 0);
      asn1Print_ENB_UE_X2AP_ID_Extension (namebuf, &pvalue->
         m_eNB_UE_X2AP_ID_Extension);
   }

   rtxStrJoin (namebuf, 512, name, ".globalENB_ID", 0, 0, 0);
   asn1Print_GlobalENB_ID (namebuf, &pvalue->globalENB_ID);

   if (pvalue->m.gNB_CU_UE_F1AP_IDPresent) {
      rtxStrJoin (namebuf, 512, name, ".gNB_CU_UE_F1AP_ID", 0, 0, 0);
      asn1Print_GNB_CU_UE_F1AP_ID (namebuf, &pvalue->gNB_CU_UE_F1AP_ID);
   }

   if (pvalue->m.gNB_CU_CP_UE_E1AP_ID_ListPresent) {
      rtxStrJoin (namebuf, 512, name, ".gNB_CU_CP_UE_E1AP_ID_List", 0, 0, 0);
      asn1Print_UEID_GNB_CU_CP_E1AP_ID_List (namebuf, &pvalue->
         gNB_CU_CP_UE_E1AP_ID_List);
   }

   if (pvalue->m.ran_UEIDPresent) {
      rtxStrJoin (namebuf, 512, name, ".ran_UEID", 0, 0, 0);
      asn1Print_RANUEID (namebuf, &pvalue->ran_UEID);
   }

   rtxStrJoin (namebuf, 512, name, ".extElem1", 0, 0, 0);
   rtPrintOpenTypeExt (namebuf, &pvalue->extElem1);

}

void ASN1C_UEID_EN_GNB::Print (const char* name)
{
   asn1Print_UEID_EN_GNB (name, &msgData);
}

void asn1Print_MME_UE_S1AP_ID 
   (const char* name, const ASN1T_MME_UE_S1AP_ID* pvalue)
{
   rtxPrintUnsigned (name, *pvalue);
}

void ASN1C_MME_UE_S1AP_ID::Print (const char* name)
{
   asn1Print_MME_UE_S1AP_ID (name, &msgData);
}

void asn1Print_MME_Group_ID 
   (const char* name, const ASN1T_MME_Group_ID* pvalue)
{
   rtPrintOctStr (name, OSRTMIN(sizeof(pvalue->data), pvalue->numocts), pvalue->data, ".");
}

void ASN1C_MME_Group_ID::Print (const char* name)
{
   asn1Print_MME_Group_ID (name, &msgData);
}

void asn1Print_MME_Code (const char* name, const ASN1T_MME_Code* pvalue)
{
   rtPrintOctStr (name, OSRTMIN(sizeof(pvalue->data), pvalue->numocts), pvalue->data, ".");
}

void ASN1C_MME_Code::Print (const char* name)
{
   asn1Print_MME_Code (name, &msgData);
}

void asn1Print_GUMMEI (const char* name, const ASN1T_GUMMEI* pvalue)
{
   char namebuf[512];

   rtxStrJoin (namebuf, 512, name, ".pLMN_Identity", 0, 0, 0);
   asn1Print_PLMNIdentity (namebuf, &pvalue->pLMN_Identity);

   rtxStrJoin (namebuf, 512, name, ".mME_Group_ID", 0, 0, 0);
   asn1Print_MME_Group_ID (namebuf, &pvalue->mME_Group_ID);

   rtxStrJoin (namebuf, 512, name, ".mME_Code", 0, 0, 0);
   asn1Print_MME_Code (namebuf, &pvalue->mME_Code);

   rtxStrJoin (namebuf, 512, name, ".extElem1", 0, 0, 0);
   rtPrintOpenTypeExt (namebuf, &pvalue->extElem1);

}

void ASN1C_GUMMEI::Print (const char* name)
{
   asn1Print_GUMMEI (name, &msgData);
}

void asn1Print_UEID_ENB (const char* name, const ASN1T_UEID_ENB* pvalue)
{
   char namebuf[512];

   printf ("%s.m.m_eNB_UE_X2AP_IDPresent = %d\n", name, (int)pvalue->m.m_eNB_UE_X2AP_IDPresent);
   printf ("%s.m.m_eNB_UE_X2AP_ID_ExtensionPresent = %d\n", name, (int)pvalue->m.m_eNB_UE_X2AP_ID_ExtensionPresent);
   printf ("%s.m.globalENB_IDPresent = %d\n", name, (int)pvalue->m.globalENB_IDPresent);
   rtxStrJoin (namebuf, 512, name, ".mME_UE_S1AP_ID", 0, 0, 0);
   asn1Print_MME_UE_S1AP_ID (namebuf, &pvalue->mME_UE_S1AP_ID);

   rtxStrJoin (namebuf, 512, name, ".gUMMEI", 0, 0, 0);
   asn1Print_GUMMEI (namebuf, &pvalue->gUMMEI);

   if (pvalue->m.m_eNB_UE_X2AP_IDPresent) {
      rtxStrJoin (namebuf, 512, name, ".m_eNB_UE_X2AP_ID", 0, 0, 0);
      asn1Print_ENB_UE_X2AP_ID (namebuf, &pvalue->m_eNB_UE_X2AP_ID);
   }

   if (pvalue->m.m_eNB_UE_X2AP_ID_ExtensionPresent) {
      rtxStrJoin (namebuf, 512, name, ".m_eNB_UE_X2AP_ID_Extension", 0, 0, 0);
      asn1Print_ENB_UE_X2AP_ID_Extension (namebuf, &pvalue->
         m_eNB_UE_X2AP_ID_Extension);
   }

   if (pvalue->m.globalENB_IDPresent) {
      rtxStrJoin (namebuf, 512, name, ".globalENB_ID", 0, 0, 0);
      asn1Print_GlobalENB_ID (namebuf, &pvalue->globalENB_ID);
   }

   rtxStrJoin (namebuf, 512, name, ".extElem1", 0, 0, 0);
   rtPrintOpenTypeExt (namebuf, &pvalue->extElem1);

}

void ASN1C_UEID_ENB::Print (const char* name)
{
   asn1Print_UEID_ENB (name, &msgData);
}

void asn1Print_UEID (const char* name, const ASN1T_UEID* pvalue)
{
   char namebuf[512];

   printf ("%s.t = %d\n", name, pvalue->t);
   switch (pvalue->t)
   {
      /* gNB-UEID */
      case 1:
      {
         rtxStrJoin (namebuf, 512, name, ".u.gNB_UEID", 0, 0, 0);
         asn1Print_UEID_GNB (namebuf, pvalue->u.gNB_UEID);
         break;
      }
      /* gNB-DU-UEID */
      case 2:
      {
         rtxStrJoin (namebuf, 512, name, ".u.gNB_DU_UEID", 0, 0, 0);
         asn1Print_UEID_GNB_DU (namebuf, pvalue->u.gNB_DU_UEID);
         break;
      }
      /* gNB-CU-UP-UEID */
      case 3:
      {
         rtxStrJoin (namebuf, 512, name, ".u.gNB_CU_UP_UEID", 0, 0, 0);
         asn1Print_UEID_GNB_CU_UP (namebuf, pvalue->u.gNB_CU_UP_UEID);
         break;
      }
      /* ng-eNB-UEID */
      case 4:
      {
         rtxStrJoin (namebuf, 512, name, ".u.ng_eNB_UEID", 0, 0, 0);
         asn1Print_UEID_NG_ENB (namebuf, pvalue->u.ng_eNB_UEID);
         break;
      }
      /* ng-eNB-DU-UEID */
      case 5:
      {
         rtxStrJoin (namebuf, 512, name, ".u.ng_eNB_DU_UEID", 0, 0, 0);
         asn1Print_UEID_NG_ENB_DU (namebuf, pvalue->u.ng_eNB_DU_UEID);
         break;
      }
      /* en-gNB-UEID */
      case 6:
      {
         rtxStrJoin (namebuf, 512, name, ".u.en_gNB_UEID", 0, 0, 0);
         asn1Print_UEID_EN_GNB (namebuf, pvalue->u.en_gNB_UEID);
         break;
      }
      /* eNB-UEID */
      case 7:
      {
         rtxStrJoin (namebuf, 512, name, ".u.eNB_UEID", 0, 0, 0);
         asn1Print_UEID_ENB (namebuf, pvalue->u.eNB_UEID);
         break;
      }
      /* extElem1 */
      case 8:
      {
         rtxStrJoin (namebuf, 512, name, ".u.extElem1", 0, 0, 0);
         rtPrintOpenType (namebuf, pvalue->u.extElem1->numocts,
         pvalue->u.extElem1->data, ".");
         break;
      }
      default:;
   }
}

void ASN1C_UEID::Print (const char* name)
{
   asn1Print_UEID (name, &msgData);
}

void asn1Print_RIC_Style_Type 
   (const char* name, const ASN1T_RIC_Style_Type* pvalue)
{
   rtxPrintInteger (name, *pvalue);
}

void ASN1C_RIC_Style_Type::Print (const char* name)
{
   asn1Print_RIC_Style_Type (name, &msgData);
}

void asn1Print_RANfunction_Name 
   (const char* name, const ASN1T_RANfunction_Name* pvalue)
{
   char namebuf[512];

   printf ("%s.m.ranFunction_InstancePresent = %d\n", name, (int)pvalue->m.ranFunction_InstancePresent);
   rtxStrJoin (namebuf, 512, name, ".ranFunction_ShortName", 0, 0, 0);
   rtxPrintCharStr (namebuf, pvalue->ranFunction_ShortName);

   rtxStrJoin (namebuf, 512, name, ".ranFunction_E2SM_OID", 0, 0, 0);
   rtxPrintCharStr (namebuf, pvalue->ranFunction_E2SM_OID);

   rtxStrJoin (namebuf, 512, name, ".ranFunction_Description", 0, 0, 0);
   rtxPrintCharStr (namebuf, pvalue->ranFunction_Description);

   if (pvalue->m.ranFunction_InstancePresent) {
      rtxStrJoin (namebuf, 512, name, ".ranFunction_Instance", 0, 0, 0);
      rtxPrintInteger (namebuf, pvalue->ranFunction_Instance);
   }

   rtxStrJoin (namebuf, 512, name, ".extElem1", 0, 0, 0);
   rtPrintOpenTypeExt (namebuf, &pvalue->extElem1);

}

void ASN1C_RANfunction_Name::Print (const char* name)
{
   asn1Print_RANfunction_Name (name, &msgData);
}

void asn1Print_RIC_Style_Name 
   (const char* name, const ASN1T_RIC_Style_Name pvalue)
{
   rtxPrintCharStr (name, pvalue);
}

void ASN1C_RIC_Style_Name::Print (const char* name)
{
   asn1Print_RIC_Style_Name (name, msgData);
}

void asn1Print_RIC_Format_Type 
   (const char* name, const ASN1T_RIC_Format_Type* pvalue)
{
   rtxPrintInteger (name, *pvalue);
}

void ASN1C_RIC_Format_Type::Print (const char* name)
{
   asn1Print_RIC_Format_Type (name, &msgData);
}

void asn1Print_InterfaceType 
   (const char* name, const ASN1T_InterfaceType* pvalue)
{
   printf ("%s = ", name);
   switch (*pvalue) {
      case 0: printf ("nG\n"); break;
      case 1: printf ("xn\n"); break;
      case 2: printf ("f1\n"); break;
      case 3: printf ("e1\n"); break;
      case 4: printf ("s1\n"); break;
      case 5: printf ("x2\n"); break;
      case 6: printf ("w1\n"); break;
      default: printf ("%u\n", *pvalue);
   }
}

void ASN1C_InterfaceType::Print (const char* name)
{
   asn1Print_InterfaceType (name, &msgData);
}

void asn1Print_RRCclass_LTE 
   (const char* name, const ASN1T_RRCclass_LTE* pvalue)
{
   printf ("%s = ", name);
   switch (*pvalue) {
      case 0: printf ("bCCH-BCH\n"); break;
      case 1: printf ("bCCH-BCH-MBMS\n"); break;
      case 2: printf ("bCCH-DL-SCH\n"); break;
      case 3: printf ("bCCH-DL-SCH-BR\n"); break;
      case 4: printf ("bCCH-DL-SCH-MBMS\n"); break;
      case 5: printf ("mCCH\n"); break;
      case 6: printf ("pCCH\n"); break;
      case 7: printf ("dL-CCCH\n"); break;
      case 8: printf ("dL-DCCH\n"); break;
      case 9: printf ("uL-CCCH\n"); break;
      case 10: printf ("uL-DCCH\n"); break;
      case 11: printf ("sC-MCCH\n"); break;
      default: printf ("%u\n", *pvalue);
   }
}

void ASN1C_RRCclass_LTE::Print (const char* name)
{
   asn1Print_RRCclass_LTE (name, &msgData);
}

void asn1Print_RRCclass_NR (const char* name, const ASN1T_RRCclass_NR* pvalue)
{
   printf ("%s = ", name);
   switch (*pvalue) {
      case 0: printf ("bCCH-BCH\n"); break;
      case 1: printf ("bCCH-DL-SCH\n"); break;
      case 2: printf ("dL-CCCH\n"); break;
      case 3: printf ("dL-DCCH\n"); break;
      case 4: printf ("pCCH\n"); break;
      case 5: printf ("uL-CCCH\n"); break;
      case 6: printf ("uL-CCCH1\n"); break;
      case 7: printf ("uL-DCCH\n"); break;
      default: printf ("%u\n", *pvalue);
   }
}

void ASN1C_RRCclass_NR::Print (const char* name)
{
   asn1Print_RRCclass_NR (name, &msgData);
}

void asn1Print_SubscriberProfileIDforRFP 
   (const char* name, const ASN1T_SubscriberProfileIDforRFP* pvalue)
{
   rtxPrintUnsigned (name, *pvalue);
}

void ASN1C_SubscriberProfileIDforRFP::Print (const char* name)
{
   asn1Print_SubscriberProfileIDforRFP (name, &msgData);
}

void asn1Print_E_UTRA_ARFCN 
   (const char* name, const ASN1T_E_UTRA_ARFCN* pvalue)
{
   rtxPrintUnsigned (name, *pvalue);
}

void ASN1C_E_UTRA_ARFCN::Print (const char* name)
{
   asn1Print_E_UTRA_ARFCN (name, &msgData);
}

void asn1Print_E_UTRA_PCI (const char* name, const ASN1T_E_UTRA_PCI* pvalue)
{
   rtxPrintUnsigned (name, *pvalue);
}

void ASN1C_E_UTRA_PCI::Print (const char* name)
{
   asn1Print_E_UTRA_PCI (name, &msgData);
}

void asn1Print_E_UTRA_TAC (const char* name, const ASN1T_E_UTRA_TAC* pvalue)
{
   rtPrintOctStr (name, OSRTMIN(sizeof(pvalue->data), pvalue->numocts), pvalue->data, ".");
}

void ASN1C_E_UTRA_TAC::Print (const char* name)
{
   asn1Print_E_UTRA_TAC (name, &msgData);
}

void asn1Print_NGENB_DU_ID (const char* name, const ASN1T_NGENB_DU_ID* pvalue)
{
   rtxPrintUInt64 (name, *pvalue);
}

void ASN1C_NGENB_DU_ID::Print (const char* name)
{
   asn1Print_NGENB_DU_ID (name, &msgData);
}

void asn1Print_IndexToRFSP (const char* name, const ASN1T_IndexToRFSP* pvalue)
{
   rtxPrintUnsigned (name, *pvalue);
}

void ASN1C_IndexToRFSP::Print (const char* name)
{
   asn1Print_IndexToRFSP (name, &msgData);
}

void asn1Print_GNB_CU_UP_ID 
   (const char* name, const ASN1T_GNB_CU_UP_ID* pvalue)
{
   rtxPrintUInt64 (name, *pvalue);
}

void ASN1C_GNB_CU_UP_ID::Print (const char* name)
{
   asn1Print_GNB_CU_UP_ID (name, &msgData);
}

void asn1Print_FiveGS_TAC (const char* name, const ASN1T_FiveGS_TAC* pvalue)
{
   rtPrintOctStr (name, OSRTMIN(sizeof(pvalue->data), pvalue->numocts), pvalue->data, ".");
}

void ASN1C_FiveGS_TAC::Print (const char* name)
{
   asn1Print_FiveGS_TAC (name, &msgData);
}

void asn1Print_GNB_DU_ID (const char* name, const ASN1T_GNB_DU_ID* pvalue)
{
   rtxPrintUInt64 (name, *pvalue);
}

void ASN1C_GNB_DU_ID::Print (const char* name)
{
   asn1Print_GNB_DU_ID (name, &msgData);
}

void asn1Print_NR_PCI (const char* name, const ASN1T_NR_PCI* pvalue)
{
   rtxPrintUnsigned (name, *pvalue);
}

void ASN1C_NR_PCI::Print (const char* name)
{
   asn1Print_NR_PCI (name, &msgData);
}

void asn1Print_NRFrequencyShift7p5khz 
   (const char* name, const ASN1T_NRFrequencyShift7p5khz* pvalue)
{
   printf ("%s = ", name);
   switch (*pvalue) {
      case 0: printf ("false\n"); break;
      case 1: printf ("true\n"); break;
      default: printf ("%u\n", *pvalue);
   }
}

void ASN1C_NRFrequencyShift7p5khz::Print (const char* name)
{
   asn1Print_NRFrequencyShift7p5khz (name, &msgData);
}

void asn1Print_Interface_MessageID_messageType 
   (const char* name, const ASN1T_Interface_MessageID_messageType* pvalue)
{
   printf ("%s = ", name);
   switch (*pvalue) {
      case 0: printf ("initiatingMessage\n"); break;
      case 1: printf ("successfulOutcome\n"); break;
      case 2: printf ("unsuccessfulOutcome\n"); break;
      default: printf ("%u\n", *pvalue);
   }
}

void ASN1C_Interface_MessageID_messageType::Print (const char* name)
{
   asn1Print_Interface_MessageID_messageType (name, &msgData);
}

void asn1Print_CoreCPID (const char* name, const ASN1T_CoreCPID* pvalue)
{
   char namebuf[512];

   printf ("%s.t = %d\n", name, pvalue->t);
   switch (pvalue->t)
   {
      /* fiveGC */
      case 1:
      {
         rtxStrJoin (namebuf, 512, name, ".u.fiveGC", 0, 0, 0);
         asn1Print_GUAMI (namebuf, pvalue->u.fiveGC);
         break;
      }
      /* ePC */
      case 2:
      {
         rtxStrJoin (namebuf, 512, name, ".u.ePC", 0, 0, 0);
         asn1Print_GUMMEI (namebuf, pvalue->u.ePC);
         break;
      }
      /* extElem1 */
      case 3:
      {
         rtxStrJoin (namebuf, 512, name, ".u.extElem1", 0, 0, 0);
         rtPrintOpenType (namebuf, pvalue->u.extElem1->numocts,
         pvalue->u.extElem1->data, ".");
         break;
      }
      default:;
   }
}

void ASN1C_CoreCPID::Print (const char* name)
{
   asn1Print_CoreCPID (name, &msgData);
}

void asn1Print_InterfaceID_NG 
   (const char* name, const ASN1T_InterfaceID_NG* pvalue)
{
   char namebuf[512];

   rtxStrJoin (namebuf, 512, name, ".guami", 0, 0, 0);
   asn1Print_GUAMI (namebuf, &pvalue->guami);

   rtxStrJoin (namebuf, 512, name, ".extElem1", 0, 0, 0);
   rtPrintOpenTypeExt (namebuf, &pvalue->extElem1);

}

void ASN1C_InterfaceID_NG::Print (const char* name)
{
   asn1Print_InterfaceID_NG (name, &msgData);
}

void asn1Print_InterfaceID_Xn 
   (const char* name, const ASN1T_InterfaceID_Xn* pvalue)
{
   char namebuf[512];

   rtxStrJoin (namebuf, 512, name, ".global_NG_RAN_ID", 0, 0, 0);
   asn1Print_GlobalNGRANNodeID (namebuf, &pvalue->global_NG_RAN_ID);

   rtxStrJoin (namebuf, 512, name, ".extElem1", 0, 0, 0);
   rtPrintOpenTypeExt (namebuf, &pvalue->extElem1);

}

void ASN1C_InterfaceID_Xn::Print (const char* name)
{
   asn1Print_InterfaceID_Xn (name, &msgData);
}

void asn1Print_InterfaceID_F1 
   (const char* name, const ASN1T_InterfaceID_F1* pvalue)
{
   char namebuf[512];

   rtxStrJoin (namebuf, 512, name, ".globalGNB_ID", 0, 0, 0);
   asn1Print_GlobalGNB_ID (namebuf, &pvalue->globalGNB_ID);

   rtxStrJoin (namebuf, 512, name, ".gNB_DU_ID", 0, 0, 0);
   asn1Print_GNB_DU_ID (namebuf, &pvalue->gNB_DU_ID);

   rtxStrJoin (namebuf, 512, name, ".extElem1", 0, 0, 0);
   rtPrintOpenTypeExt (namebuf, &pvalue->extElem1);

}

void ASN1C_InterfaceID_F1::Print (const char* name)
{
   asn1Print_InterfaceID_F1 (name, &msgData);
}

void asn1Print_InterfaceID_E1 
   (const char* name, const ASN1T_InterfaceID_E1* pvalue)
{
   char namebuf[512];

   rtxStrJoin (namebuf, 512, name, ".globalGNB_ID", 0, 0, 0);
   asn1Print_GlobalGNB_ID (namebuf, &pvalue->globalGNB_ID);

   rtxStrJoin (namebuf, 512, name, ".gNB_CU_UP_ID", 0, 0, 0);
   asn1Print_GNB_CU_UP_ID (namebuf, &pvalue->gNB_CU_UP_ID);

   rtxStrJoin (namebuf, 512, name, ".extElem1", 0, 0, 0);
   rtPrintOpenTypeExt (namebuf, &pvalue->extElem1);

}

void ASN1C_InterfaceID_E1::Print (const char* name)
{
   asn1Print_InterfaceID_E1 (name, &msgData);
}

void asn1Print_InterfaceID_S1 
   (const char* name, const ASN1T_InterfaceID_S1* pvalue)
{
   char namebuf[512];

   rtxStrJoin (namebuf, 512, name, ".gUMMEI", 0, 0, 0);
   asn1Print_GUMMEI (namebuf, &pvalue->gUMMEI);

   rtxStrJoin (namebuf, 512, name, ".extElem1", 0, 0, 0);
   rtPrintOpenTypeExt (namebuf, &pvalue->extElem1);

}

void ASN1C_InterfaceID_S1::Print (const char* name)
{
   asn1Print_InterfaceID_S1 (name, &msgData);
}

void asn1Print_EN_GNB_ID (const char* name, const ASN1T_EN_GNB_ID* pvalue)
{
   char namebuf[512];

   printf ("%s.t = %d\n", name, pvalue->t);
   switch (pvalue->t)
   {
      /* en-gNB-ID */
      case 1:
      {
         rtxStrJoin (namebuf, 512, name, ".u.en_gNB_ID", 0, 0, 0);
         rtPrintBitStr (namebuf, OS_MIN(pvalue->u.en_gNB_ID->numbits, 32), pvalue->u.en_gNB_ID->data, ".");
         break;
      }
      /* extElem1 */
      case 2:
      {
         rtxStrJoin (namebuf, 512, name, ".u.extElem1", 0, 0, 0);
         rtPrintOpenType (namebuf, pvalue->u.extElem1->numocts,
         pvalue->u.extElem1->data, ".");
         break;
      }
      default:;
   }
}

void ASN1C_EN_GNB_ID::Print (const char* name)
{
   asn1Print_EN_GNB_ID (name, &msgData);
}

void asn1Print_GlobalenGNB_ID 
   (const char* name, const ASN1T_GlobalenGNB_ID* pvalue)
{
   char namebuf[512];

   rtxStrJoin (namebuf, 512, name, ".pLMN_Identity", 0, 0, 0);
   asn1Print_PLMNIdentity (namebuf, &pvalue->pLMN_Identity);

   rtxStrJoin (namebuf, 512, name, ".en_gNB_ID", 0, 0, 0);
   asn1Print_EN_GNB_ID (namebuf, &pvalue->en_gNB_ID);

   rtxStrJoin (namebuf, 512, name, ".extElem1", 0, 0, 0);
   rtPrintOpenTypeExt (namebuf, &pvalue->extElem1);

}

void ASN1C_GlobalenGNB_ID::Print (const char* name)
{
   asn1Print_GlobalenGNB_ID (name, &msgData);
}

void asn1Print_InterfaceID_X2_nodeType 
   (const char* name, const ASN1T_InterfaceID_X2_nodeType* pvalue)
{
   char namebuf[512];

   printf ("%s.t = %d\n", name, pvalue->t);
   switch (pvalue->t)
   {
      /* global-eNB-ID */
      case 1:
      {
         rtxStrJoin (namebuf, 512, name, ".u.global_eNB_ID", 0, 0, 0);
         asn1Print_GlobalENB_ID (namebuf, pvalue->u.global_eNB_ID);
         break;
      }
      /* global-en-gNB-ID */
      case 2:
      {
         rtxStrJoin (namebuf, 512, name, ".u.global_en_gNB_ID", 0, 0, 0);
         asn1Print_GlobalenGNB_ID (namebuf, pvalue->u.global_en_gNB_ID);
         break;
      }
      /* extElem1 */
      case 3:
      {
         rtxStrJoin (namebuf, 512, name, ".u.extElem1", 0, 0, 0);
         rtPrintOpenType (namebuf, pvalue->u.extElem1->numocts,
         pvalue->u.extElem1->data, ".");
         break;
      }
      default:;
   }
}

void ASN1C_InterfaceID_X2_nodeType::Print (const char* name)
{
   asn1Print_InterfaceID_X2_nodeType (name, &msgData);
}

void asn1Print_InterfaceID_X2 
   (const char* name, const ASN1T_InterfaceID_X2* pvalue)
{
   char namebuf[512];

   rtxStrJoin (namebuf, 512, name, ".nodeType", 0, 0, 0);
   asn1Print_InterfaceID_X2_nodeType (namebuf, &pvalue->nodeType);

   rtxStrJoin (namebuf, 512, name, ".extElem1", 0, 0, 0);
   rtPrintOpenTypeExt (namebuf, &pvalue->extElem1);

}

void ASN1C_InterfaceID_X2::Print (const char* name)
{
   asn1Print_InterfaceID_X2 (name, &msgData);
}

void asn1Print_InterfaceID_W1 
   (const char* name, const ASN1T_InterfaceID_W1* pvalue)
{
   char namebuf[512];

   rtxStrJoin (namebuf, 512, name, ".global_ng_eNB_ID", 0, 0, 0);
   asn1Print_GlobalNgENB_ID (namebuf, &pvalue->global_ng_eNB_ID);

   rtxStrJoin (namebuf, 512, name, ".ng_eNB_DU_ID", 0, 0, 0);
   asn1Print_NGENB_DU_ID (namebuf, &pvalue->ng_eNB_DU_ID);

   rtxStrJoin (namebuf, 512, name, ".extElem1", 0, 0, 0);
   rtPrintOpenTypeExt (namebuf, &pvalue->extElem1);

}

void ASN1C_InterfaceID_W1::Print (const char* name)
{
   asn1Print_InterfaceID_W1 (name, &msgData);
}

void asn1Print_InterfaceIdentifier 
   (const char* name, const ASN1T_InterfaceIdentifier* pvalue)
{
   char namebuf[512];

   printf ("%s.t = %d\n", name, pvalue->t);
   switch (pvalue->t)
   {
      /* nG */
      case 1:
      {
         rtxStrJoin (namebuf, 512, name, ".u.nG", 0, 0, 0);
         asn1Print_InterfaceID_NG (namebuf, pvalue->u.nG);
         break;
      }
      /* xN */
      case 2:
      {
         rtxStrJoin (namebuf, 512, name, ".u.xN", 0, 0, 0);
         asn1Print_InterfaceID_Xn (namebuf, pvalue->u.xN);
         break;
      }
      /* f1 */
      case 3:
      {
         rtxStrJoin (namebuf, 512, name, ".u.f1", 0, 0, 0);
         asn1Print_InterfaceID_F1 (namebuf, pvalue->u.f1);
         break;
      }
      /* e1 */
      case 4:
      {
         rtxStrJoin (namebuf, 512, name, ".u.e1", 0, 0, 0);
         asn1Print_InterfaceID_E1 (namebuf, pvalue->u.e1);
         break;
      }
      /* s1 */
      case 5:
      {
         rtxStrJoin (namebuf, 512, name, ".u.s1", 0, 0, 0);
         asn1Print_InterfaceID_S1 (namebuf, pvalue->u.s1);
         break;
      }
      /* x2 */
      case 6:
      {
         rtxStrJoin (namebuf, 512, name, ".u.x2", 0, 0, 0);
         asn1Print_InterfaceID_X2 (namebuf, pvalue->u.x2);
         break;
      }
      /* w1 */
      case 7:
      {
         rtxStrJoin (namebuf, 512, name, ".u.w1", 0, 0, 0);
         asn1Print_InterfaceID_W1 (namebuf, pvalue->u.w1);
         break;
      }
      /* extElem1 */
      case 8:
      {
         rtxStrJoin (namebuf, 512, name, ".u.extElem1", 0, 0, 0);
         rtPrintOpenType (namebuf, pvalue->u.extElem1->numocts,
         pvalue->u.extElem1->data, ".");
         break;
      }
      default:;
   }
}

void ASN1C_InterfaceIdentifier::Print (const char* name)
{
   asn1Print_InterfaceIdentifier (name, &msgData);
}

void asn1Print_Interface_MessageID 
   (const char* name, const ASN1T_Interface_MessageID* pvalue)
{
   char namebuf[512];

   rtxStrJoin (namebuf, 512, name, ".interfaceProcedureID", 0, 0, 0);
   rtxPrintInteger (namebuf, pvalue->interfaceProcedureID);

   rtxStrJoin (namebuf, 512, name, ".messageType", 0, 0, 0);
   asn1Print_Interface_MessageID_messageType (namebuf, &pvalue->messageType);

   rtxStrJoin (namebuf, 512, name, ".extElem1", 0, 0, 0);
   rtPrintOpenTypeExt (namebuf, &pvalue->extElem1);

}

void ASN1C_Interface_MessageID::Print (const char* name)
{
   asn1Print_Interface_MessageID (name, &msgData);
}

void asn1Print_GroupID (const char* name, const ASN1T_GroupID* pvalue)
{
   char namebuf[512];

   printf ("%s.t = %d\n", name, pvalue->t);
   switch (pvalue->t)
   {
      /* fiveGC */
      case 1:
      {
         rtxStrJoin (namebuf, 512, name, ".u.fiveGC", 0, 0, 0);
         asn1Print_FiveQI (namebuf, &pvalue->u.fiveGC);
         break;
      }
      /* ePC */
      case 2:
      {
         rtxStrJoin (namebuf, 512, name, ".u.ePC", 0, 0, 0);
         asn1Print_QCI (namebuf, &pvalue->u.ePC);
         break;
      }
      /* extElem1 */
      case 3:
      {
         rtxStrJoin (namebuf, 512, name, ".u.extElem1", 0, 0, 0);
         rtPrintOpenType (namebuf, pvalue->u.extElem1->numocts,
         pvalue->u.extElem1->data, ".");
         break;
      }
      default:;
   }
}

void ASN1C_GroupID::Print (const char* name)
{
   asn1Print_GroupID (name, &msgData);
}

void asn1Print_QoSID (const char* name, const ASN1T_QoSID* pvalue)
{
   char namebuf[512];

   printf ("%s.t = %d\n", name, pvalue->t);
   switch (pvalue->t)
   {
      /* fiveGC */
      case 1:
      {
         rtxStrJoin (namebuf, 512, name, ".u.fiveGC", 0, 0, 0);
         asn1Print_FiveQI (namebuf, &pvalue->u.fiveGC);
         break;
      }
      /* ePC */
      case 2:
      {
         rtxStrJoin (namebuf, 512, name, ".u.ePC", 0, 0, 0);
         asn1Print_QCI (namebuf, &pvalue->u.ePC);
         break;
      }
      /* extElem1 */
      case 3:
      {
         rtxStrJoin (namebuf, 512, name, ".u.extElem1", 0, 0, 0);
         rtPrintOpenType (namebuf, pvalue->u.extElem1->numocts,
         pvalue->u.extElem1->data, ".");
         break;
      }
      default:;
   }
}

void ASN1C_QoSID::Print (const char* name)
{
   asn1Print_QoSID (name, &msgData);
}

void asn1Print_RRC_MessageID_rrcType 
   (const char* name, const ASN1T_RRC_MessageID_rrcType* pvalue)
{
   char namebuf[512];

   printf ("%s.t = %d\n", name, pvalue->t);
   switch (pvalue->t)
   {
      /* lTE */
      case 1:
      {
         rtxStrJoin (namebuf, 512, name, ".u.lTE", 0, 0, 0);
         asn1Print_RRCclass_LTE (namebuf, &pvalue->u.lTE);
         break;
      }
      /* nR */
      case 2:
      {
         rtxStrJoin (namebuf, 512, name, ".u.nR", 0, 0, 0);
         asn1Print_RRCclass_NR (namebuf, &pvalue->u.nR);
         break;
      }
      /* extElem1 */
      case 3:
      {
         rtxStrJoin (namebuf, 512, name, ".u.extElem1", 0, 0, 0);
         rtPrintOpenType (namebuf, pvalue->u.extElem1->numocts,
         pvalue->u.extElem1->data, ".");
         break;
      }
      default:;
   }
}

void ASN1C_RRC_MessageID_rrcType::Print (const char* name)
{
   asn1Print_RRC_MessageID_rrcType (name, &msgData);
}

void asn1Print_RRC_MessageID 
   (const char* name, const ASN1T_RRC_MessageID* pvalue)
{
   char namebuf[512];

   rtxStrJoin (namebuf, 512, name, ".rrcType", 0, 0, 0);
   asn1Print_RRC_MessageID_rrcType (namebuf, &pvalue->rrcType);

   rtxStrJoin (namebuf, 512, name, ".messageID", 0, 0, 0);
   rtxPrintInteger (namebuf, pvalue->messageID);

   rtxStrJoin (namebuf, 512, name, ".extElem1", 0, 0, 0);
   rtPrintOpenTypeExt (namebuf, &pvalue->extElem1);

}

void ASN1C_RRC_MessageID::Print (const char* name)
{
   asn1Print_RRC_MessageID (name, &msgData);
}

void asn1Print_NR_ARFCN (const char* name, const ASN1T_NR_ARFCN* pvalue)
{
   char namebuf[512];

   rtxStrJoin (namebuf, 512, name, ".nRARFCN", 0, 0, 0);
   rtxPrintUnsigned (namebuf, pvalue->nRARFCN);

   rtxStrJoin (namebuf, 512, name, ".extElem1", 0, 0, 0);
   rtPrintOpenTypeExt (namebuf, &pvalue->extElem1);

}

void ASN1C_NR_ARFCN::Print (const char* name)
{
   asn1Print_NR_ARFCN (name, &msgData);
}

void asn1Print_ServingCell_ARFCN 
   (const char* name, const ASN1T_ServingCell_ARFCN* pvalue)
{
   char namebuf[512];

   printf ("%s.t = %d\n", name, pvalue->t);
   switch (pvalue->t)
   {
      /* nR */
      case 1:
      {
         rtxStrJoin (namebuf, 512, name, ".u.nR", 0, 0, 0);
         asn1Print_NR_ARFCN (namebuf, pvalue->u.nR);
         break;
      }
      /* eUTRA */
      case 2:
      {
         rtxStrJoin (namebuf, 512, name, ".u.eUTRA", 0, 0, 0);
         asn1Print_E_UTRA_ARFCN (namebuf, &pvalue->u.eUTRA);
         break;
      }
      /* extElem1 */
      case 3:
      {
         rtxStrJoin (namebuf, 512, name, ".u.extElem1", 0, 0, 0);
         rtPrintOpenType (namebuf, pvalue->u.extElem1->numocts,
         pvalue->u.extElem1->data, ".");
         break;
      }
      default:;
   }
}

void ASN1C_ServingCell_ARFCN::Print (const char* name)
{
   asn1Print_ServingCell_ARFCN (name, &msgData);
}

void asn1Print_ServingCell_PCI 
   (const char* name, const ASN1T_ServingCell_PCI* pvalue)
{
   char namebuf[512];

   printf ("%s.t = %d\n", name, pvalue->t);
   switch (pvalue->t)
   {
      /* nR */
      case 1:
      {
         rtxStrJoin (namebuf, 512, name, ".u.nR", 0, 0, 0);
         asn1Print_NR_PCI (namebuf, &pvalue->u.nR);
         break;
      }
      /* eUTRA */
      case 2:
      {
         rtxStrJoin (namebuf, 512, name, ".u.eUTRA", 0, 0, 0);
         asn1Print_E_UTRA_PCI (namebuf, &pvalue->u.eUTRA);
         break;
      }
      /* extElem1 */
      case 3:
      {
         rtxStrJoin (namebuf, 512, name, ".u.extElem1", 0, 0, 0);
         rtPrintOpenType (namebuf, pvalue->u.extElem1->numocts,
         pvalue->u.extElem1->data, ".");
         break;
      }
      default:;
   }
}

void ASN1C_ServingCell_PCI::Print (const char* name)
{
   asn1Print_ServingCell_PCI (name, &msgData);
}

void asn1Print_FreqBandNrItem 
   (const char* name, const ASN1T_FreqBandNrItem* pvalue)
{
   char namebuf[512];

   rtxStrJoin (namebuf, 512, name, ".freqBandIndicatorNr", 0, 0, 0);
   rtxPrintUnsigned (namebuf, pvalue->freqBandIndicatorNr);

   rtxStrJoin (namebuf, 512, name, ".extElem1", 0, 0, 0);
   rtPrintOpenTypeExt (namebuf, &pvalue->extElem1);

}

void ASN1C_FreqBandNrItem::Print (const char* name)
{
   asn1Print_FreqBandNrItem (name, &msgData);
}

void asn1Print_SupportedSULFreqBandItem 
   (const char* name, const ASN1T_SupportedSULFreqBandItem* pvalue)
{
   char namebuf[512];

   rtxStrJoin (namebuf, 512, name, ".freqBandIndicatorNr", 0, 0, 0);
   rtxPrintUnsigned (namebuf, pvalue->freqBandIndicatorNr);

   rtxStrJoin (namebuf, 512, name, ".extElem1", 0, 0, 0);
   rtPrintOpenTypeExt (namebuf, &pvalue->extElem1);

}

void ASN1C_SupportedSULFreqBandItem::Print (const char* name)
{
   asn1Print_SupportedSULFreqBandItem (name, &msgData);
}

void asn1Print_SupportedSULBandList 
   (const char* name, const ASN1T_SupportedSULBandList* pvalue)
{
   ASN1T_SupportedSULFreqBandItem* pdata0;
   OSRTDListNode* pnode;
   char namebuf[512];
   char numbuf[32];

   printf ("%s.count = " OSSIZEFMT "\n", name, pvalue->count);
   {
   OSUINT32 xx1 = 0;

   for (pnode = pvalue->head; pnode != 0 && xx1 < pvalue->count; pnode = pnode->next) {
      pdata0 = ((ASN1T_SupportedSULFreqBandItem*)pnode->data);
      rtxUIntToCharStr (xx1, numbuf, sizeof(numbuf), 0);
      rtxStrJoin (namebuf, sizeof(namebuf), name, ".elem[", numbuf, "]", 0);
      asn1Print_SupportedSULFreqBandItem (namebuf, pdata0);
      xx1++;
   }
   }
}

void ASN1C_SupportedSULBandList::Print (const char* name)
{
   asn1Print_SupportedSULBandList (name, &msgData);
}

void asn1Print_NRFrequencyBandItem 
   (const char* name, const ASN1T_NRFrequencyBandItem* pvalue)
{
   char namebuf[512];

   rtxStrJoin (namebuf, 512, name, ".freqBandIndicatorNr", 0, 0, 0);
   rtxPrintUnsigned (namebuf, pvalue->freqBandIndicatorNr);

   rtxStrJoin (namebuf, 512, name, ".supportedSULBandList", 0, 0, 0);
   asn1Print_SupportedSULBandList (namebuf, &pvalue->supportedSULBandList);

   rtxStrJoin (namebuf, 512, name, ".extElem1", 0, 0, 0);
   rtPrintOpenTypeExt (namebuf, &pvalue->extElem1);

}

void ASN1C_NRFrequencyBandItem::Print (const char* name)
{
   asn1Print_NRFrequencyBandItem (name, &msgData);
}

void asn1Print_NRFrequencyBand_List 
   (const char* name, const ASN1T_NRFrequencyBand_List* pvalue)
{
   ASN1T_NRFrequencyBandItem* pdata0;
   OSRTDListNode* pnode;
   char namebuf[512];
   char numbuf[32];

   printf ("%s.count = " OSSIZEFMT "\n", name, pvalue->count);
   {
   OSUINT32 xx1 = 0;

   for (pnode = pvalue->head; pnode != 0 && xx1 < pvalue->count; pnode = pnode->next) {
      pdata0 = ((ASN1T_NRFrequencyBandItem*)pnode->data);
      rtxUIntToCharStr (xx1, numbuf, sizeof(numbuf), 0);
      rtxStrJoin (namebuf, sizeof(namebuf), name, ".elem[", numbuf, "]", 0);
      asn1Print_NRFrequencyBandItem (namebuf, pdata0);
      xx1++;
   }
   }
}

void ASN1C_NRFrequencyBand_List::Print (const char* name)
{
   asn1Print_NRFrequencyBand_List (name, &msgData);
}

void asn1Print_NRFrequencyInfo 
   (const char* name, const ASN1T_NRFrequencyInfo* pvalue)
{
   char namebuf[512];

   printf ("%s.m.frequencyShift7p5khzPresent = %d\n", name, (int)pvalue->m.frequencyShift7p5khzPresent);
   rtxStrJoin (namebuf, 512, name, ".nrARFCN", 0, 0, 0);
   asn1Print_NR_ARFCN (namebuf, &pvalue->nrARFCN);

   rtxStrJoin (namebuf, 512, name, ".frequencyBand_List", 0, 0, 0);
   asn1Print_NRFrequencyBand_List (namebuf, &pvalue->frequencyBand_List);

   if (pvalue->m.frequencyShift7p5khzPresent) {
      rtxStrJoin (namebuf, 512, name, ".frequencyShift7p5khz", 0, 0, 0);
      asn1Print_NRFrequencyShift7p5khz (namebuf, &pvalue->frequencyShift7p5khz
         );
   }

   rtxStrJoin (namebuf, 512, name, ".extElem1", 0, 0, 0);
   rtPrintOpenTypeExt (namebuf, &pvalue->extElem1);

}

void ASN1C_NRFrequencyInfo::Print (const char* name)
{
   asn1Print_NRFrequencyInfo (name, &msgData);
}

