/**
 * This file was generated by the Objective Systems ASN1C Compiler
 * (http://www.obj-sys.com).  Version: 7.8.2.5, Date: 27-Jun-2025.
 *
 * Command:  asn1c ./asn1files/E2SM-KPM-v05.00.asn ./asn1files/asn_flexric/e2sm_rc_v1_03_modified.asn ./asn1files/asn_flexric/e42ap_v2_03.asn -cpp -json -per -depends -events -oh ./src -i asn1files -i asn1files/asn_flexric -o ./src -genprint -printformat details -genprttostr -printformat details -stream -table-unions -gentest -trace
 */
#include "E2SM-KPM-IEs.h"
#include "E2SM-COMMON-IEs.h"
#include "rtxsrc/rtxCharStr.h"
#include "rtxsrc/rtxDiag.h"

/*
 * Randomly generated test file: seed = 1751031991
 */
ASN1T_E2SM_KPM_EventTriggerDefinition* ASN1C_E2SM_KPM_EventTriggerDefinition::genTestInstance(OSCTXT *pctxt, OSBOOL free)

{
   if (0 == pctxt) pctxt = getCtxtPtr();
   ASN1T_E2SM_KPM_EventTriggerDefinition* pvalue = (ASN1T_E2SM_KPM_EventTriggerDefinition*)&msgData;
   asn1Init_E2SM_KPM_EventTriggerDefinition (pvalue, free, pctxt);

   pvalue->eventDefinition_formats.t =  1;
   pvalue->eventDefinition_formats.u.eventDefinition_Format1 = rtxMemAllocTypeZ (pctxt, ASN1T_E2SM_KPM_EventTriggerDefinition_Format1);

   pvalue->eventDefinition_formats.u.eventDefinition_Format1->reportingPeriod = 725294643;
   return (pvalue);
}

ASN1T_E2SM_KPM_IndicationHeader* ASN1C_E2SM_KPM_IndicationHeader::genTestInstance(OSCTXT *pctxt, OSBOOL free)

{
   if (0 == pctxt) pctxt = getCtxtPtr();
   ASN1T_E2SM_KPM_IndicationHeader* pvalue = (ASN1T_E2SM_KPM_IndicationHeader*)&msgData;
   asn1Init_E2SM_KPM_IndicationHeader (pvalue, free, pctxt);

   pvalue->indicationHeader_formats.t =  1;
   pvalue->indicationHeader_formats.u.indicationHeader_Format1 = rtxMemAllocTypeZ (pctxt, ASN1T_E2SM_KPM_IndicationHeader_Format1);

   pvalue->indicationHeader_formats.u.indicationHeader_Format1->colletStartTime.numocts = 8;
   {
      static const OSOCTET testdata[] = {
      0xd4, 0x7c, 0x69, 0x23, 0x8e, 0xc1, 0x75, 0x8c };
      OSCRTLSAFEMEMCPY ((void*)pvalue->indicationHeader_formats.u.indicationHeader_Format1->colletStartTime.data, 8, testdata, 8);
   }

   pvalue->indicationHeader_formats.u.indicationHeader_Format1->m.fileFormatversionPresent = 1;
   pvalue->indicationHeader_formats.u.indicationHeader_Format1->fileFormatversion = ",je=CPY";

   pvalue->indicationHeader_formats.u.indicationHeader_Format1->m.senderNamePresent = 1;
   pvalue->indicationHeader_formats.u.indicationHeader_Format1->senderName = "VpYzdkRa7njXNVAbzKE Dp-";

   pvalue->indicationHeader_formats.u.indicationHeader_Format1->m.senderTypePresent = 1;
   pvalue->indicationHeader_formats.u.indicationHeader_Format1->senderType = "";

   pvalue->indicationHeader_formats.u.indicationHeader_Format1->m.vendorNamePresent = 1;
   pvalue->indicationHeader_formats.u.indicationHeader_Format1->vendorName = "k-bzeN?=.";
   return (pvalue);
}

ASN1T_E2SM_KPM_RANfunction_Description* ASN1C_E2SM_KPM_RANfunction_Description::genTestInstance(OSCTXT *pctxt, OSBOOL free)

{
   if (0 == pctxt) pctxt = getCtxtPtr();
   ASN1T_E2SM_KPM_RANfunction_Description* pvalue = (ASN1T_E2SM_KPM_RANfunction_Description*)&msgData;
   asn1Init_E2SM_KPM_RANfunction_Description (pvalue, free, pctxt);

   pvalue->ranFunction_Name.ranFunction_ShortName = "xWPCm(.0Q";

   pvalue->ranFunction_Name.ranFunction_E2SM_OID = "KrFq8-7.3(Ka0.Dn=YlGWNcml5osB+?hvaCrK9cW=m9.XWZsuKyRtaDeorBpaWB?wZqHrSd";

   pvalue->ranFunction_Name.ranFunction_Description = "+wxc9WU3(9HaWgE1CbzcxAxYvofQ-I-2+)nAD.4FDU'v'-,)h+fJ,che7M";

   pvalue->ranFunction_Name.m.ranFunction_InstancePresent = 1;
   pvalue->ranFunction_Name.ranFunction_Instance = 1582276675;

   pvalue->m.ric_EventTriggerStyle_ListPresent = 1;
   {
      ASN1C_E2SM_KPM_RANfunction_Description_ric_EventTriggerStyle_List llist2 (*this, pvalue->ric_EventTriggerStyle_List);
      llist2.init ();
      ASN1T_RIC_EventTriggerStyle_Item* pdata2;

      pdata2 = llist2.NewElement ();

      pdata2->ric_EventTriggerStyle_Type = 1883930873;

      pdata2->ric_EventTriggerStyle_Name = "B3Z+dZHkm";

      pdata2->ric_EventTriggerFormat_Type = 713802554;

      llist2.Append (pdata2);

   }

   pvalue->m.ric_ReportStyle_ListPresent = 1;
   {
      ASN1C_E2SM_KPM_RANfunction_Description_ric_ReportStyle_List llist2 (*this, pvalue->ric_ReportStyle_List);
      llist2.init ();
      ASN1T_RIC_ReportStyle_Item* pdata2;

      pdata2 = llist2.NewElement ();

      pdata2->ric_ReportStyle_Type = 188521203;

      pdata2->ric_ReportStyle_Name = "5i/=R2f?qoE9V,4) OY'Ex,)W3n0Ya7m/CkD4QYh+dzai3dME'Ney9L?Iy/gCCTKE)jRT/yYlxy:oFfsHsB,oi";

      pdata2->ric_ActionFormat_Type = 443935402;

      {
         ASN1C_MeasurementInfo_Action_List llist4 (*this, pdata2->measInfo_Action_List);
         llist4.init ();
         ASN1T_MeasurementInfo_Action_Item* pdata4;

         pdata4 = llist4.NewElement ();

         pdata4->measName = "L3yjO87S?djSlhqWJopx7=pBqqGeD2wkBZTQqN+";

         pdata4->m.measIDPresent = 1;
         pdata4->measID = 19807;

         pdata4->m.binRangeDefPresent = 1;

         {
            ASN1C_BinRangeList llist7 (*this, pdata4->binRangeDef.binRangeListX);
            llist7.init ();
            ASN1T_BinRangeItem* pdata7;

            pdata7 = llist7.NewElement ();

            pdata7->binIndex = 22960;

            pdata7->startValue.t =  1;
            pdata7->startValue.u.valueInt = 1895770288;

            pdata7->endValue.t =  1;
            pdata7->endValue.u.valueInt = 2032630097;

            llist7.Append (pdata7);

         }

         pdata4->binRangeDef.m.binRangeListYPresent = 1;
         {
            ASN1C_BinRangeList llist7 (*this, pdata4->binRangeDef.binRangeListY);
            llist7.init ();
            ASN1T_BinRangeItem* pdata7;

            pdata7 = llist7.NewElement ();

            pdata7->binIndex = 63335;

            pdata7->startValue.t =  2;
            pdata7->startValue.u.valueReal = 1.20459e+09;

            pdata7->endValue.t =  2;
            pdata7->endValue.u.valueReal = 1.3945e+09;

            llist7.Append (pdata7);

         }

         pdata4->binRangeDef.m.binRangeListZPresent = 1;
         {
            ASN1C_BinRangeList llist7 (*this, pdata4->binRangeDef.binRangeListZ);
            llist7.init ();
            ASN1T_BinRangeItem* pdata7;

            pdata7 = llist7.NewElement ();

            pdata7->binIndex = 772;

            pdata7->startValue.t =  2;
            pdata7->startValue.u.valueReal = 5.34791e+08;

            pdata7->endValue.t =  2;
            pdata7->endValue.u.valueReal = 1.8817e+09;

            llist7.Append (pdata7);

         }

         llist4.Append (pdata4);

      }

      pdata2->ric_IndicationHeaderFormat_Type = 720001677;

      pdata2->ric_IndicationMessageFormat_Type = 891179447;

      llist2.Append (pdata2);

   }

   pvalue->m.ric_IntegratedReportStyle_ListPresent = 1;
   {
      ASN1C_E2SM_KPM_RANfunction_Description_ric_IntegratedReportStyle_List llist2 (*this, pvalue->ric_IntegratedReportStyle_List);
      llist2.init ();
      ASN1T_RIC_IntegratedReportStyle_Item* pdata2;

      pdata2 = llist2.NewElement ();

      pdata2->ric_ReportStyle_Type = 1643088610;

      pdata2->ric_ReportStyle_Name = "o?iCBHsny,VRw0ZZ0YC82UBs.waPLOB O,Cl4uC2 tGwh(?UaXlls/Hzih578Puf?97M4SBr3dntf";

      pdata2->ric_ActionFormat_Type = 63333479;

      pdata2->ric_IndicationHeaderFormat_Type = 338721545;

      pdata2->ric_IndicationMessageFormat_Type = 799979521;

      pdata2->m.ric_FundamentalLevelReportStyle_ListPresent = 1;
      {
         ASN1C_RIC_IntegratedReportStyle_Item_ric_FundamentalLevelReportStyle_List llist4 (*this, pdata2->ric_FundamentalLevelReportStyle_List);
         llist4.init ();
         ASN1T_RIC_FundamentalLevelReportStyle_Item* pdata4;

         pdata4 = llist4.NewElement ();

         pdata4->ric_ReportStyle_Type = 1950668078;

         pdata4->m.jobSpecificActionDefinitionSupportPresent = 1;
         pdata4->jobSpecificActionDefinitionSupport = RIC_FundamentalLevelReportStyle_Item_jobSpecificActionDefinitionSupport::true_;

         pdata4->m.jobSpecificCellGlobalIDSupportPresent = 1;
         pdata4->jobSpecificCellGlobalIDSupport = RIC_FundamentalLevelReportStyle_Item_jobSpecificCellGlobalIDSupport::true_;

         pdata4->m.jobSpecificUEIDSupportPresent = 1;
         pdata4->jobSpecificUEIDSupport = RIC_FundamentalLevelReportStyle_Item_jobSpecificUEIDSupport::true_;

         pdata4->m.jobSpecificMatchingUEidListSupportPresent = 1;
         pdata4->jobSpecificMatchingUEidListSupport = RIC_FundamentalLevelReportStyle_Item_jobSpecificMatchingUEidListSupport::true_;

         llist4.Append (pdata4);

      }

      pdata2->m.ric_SingleReportingApproachSupportPresent = 1;
      pdata2->ric_SingleReportingApproachSupport = RIC_IntegratedReportStyle_Item_ric_SingleReportingApproachSupport::true_;

      pdata2->m.ric_MultipleReportingApproachSupportPresent = 1;
      pdata2->ric_MultipleReportingApproachSupport = RIC_IntegratedReportStyle_Item_ric_MultipleReportingApproachSupport::true_;

      pdata2->m.ric_CommonActionDefinitionSupportPresent = 1;
      pdata2->ric_CommonActionDefinitionSupport = RIC_IntegratedReportStyle_Item_ric_CommonActionDefinitionSupport::true_;

      llist2.Append (pdata2);

   }
   return (pvalue);
}

